"use client";
import Link from"next/link";
import{ArrowRight,MessageCircle,Share2}from"lucide-react";
type EventName="insight_cta_clicked"|"insight_to_tender"|"insight_to_signup"|"insight_to_buyer_signup"|"insight_to_supplier_signup"|"insight_to_post_tender"|"insight_to_alert";
const configs:Record<string,{kicker:string;title:string;body:string;primary:[string,string,EventName];secondary:[string,string,EventName]}>=
{browse_tenders:{kicker:"Put the guide into practice",title:"Find an opportunity worth pursuing.",body:"Browse current Ghana and eligible international opportunities, then save the ones that fit your capability.",primary:["Browse tenders","/tenders","insight_to_tender"],secondary:["Create tender alerts","/sign-in?mode=sign-up&account=supplier&next=/customer/alerts","insight_to_alert"]},supplier_profile:{kicker:"Build supplier readiness",title:"Keep your opportunity workflow in one place.",body:"Create a supplier account to save opportunities, prepare reusable information and manage tender alerts.",primary:["Create supplier account","/sign-in?mode=sign-up&account=supplier","insight_to_supplier_signup"],secondary:["Browse opportunities","/opportunities","insight_to_tender"]},buyer:{kicker:"Run procurement with confidence",title:"Create and manage a private tender on BidScope.",body:"Use the buyer workspace to define requirements, receive structured bids and document a consistent evaluation.",primary:["Post a tender","/post-tender","insight_to_post_tender"],secondary:["Create buyer account","/sign-in?mode=sign-up&account=buyer","insight_to_buyer_signup"]},alerts:{kicker:"Reduce missed deadlines",title:"Make BidScope watch the market for you.",body:"Create a supplier account, save a relevant search and choose the alerts included in your plan.",primary:["Create tender alerts","/sign-in?mode=sign-up&account=supplier&next=/customer/alerts","insight_to_alert"],secondary:["Explore current opportunities","/tenders","insight_to_tender"]}};
function track(eventName:EventName,slug:string,label:string){window.trackBidScopeSeoConversion?.(eventName,{metadata:{contentType:"insight",slug,label}});window.trackBidScopeSeoConversion?.("insight_cta_clicked" as EventName,{metadata:{contentType:"insight",slug,label,eventName}})}
export function InsightCta({type,slug}:{type:string;slug:string}){const config=configs[type]||configs.browse_tenders;return <aside className="rounded-[30px] bg-[#103f32] p-7 text-white shadow-[0_24px_60px_rgba(16,63,50,.18)] sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-[#8bd7b7]">{config.kicker}</p><h2 className="serif mt-3 text-3xl sm:text-4xl">{config.title}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-white/75">{config.body}</p><div className="mt-7 flex flex-wrap gap-3">{[config.primary,config.secondary].map(([label,href,event],index)=><Link key={href} href={href} onClick={()=>track(event,slug,label)} className={`inline-flex items-center gap-2 rounded-full px-6 py-3 font-black ${index?"border border-white/30 text-white":"bg-[#d0a44b] text-[#17362d]"}`}>{label}<ArrowRight size={17}/></Link>)}</div></aside>}
export function InsightShare({title,url}:{title:string;url:string}){const text=`New BidScope guide: ${title}. Practical procurement guidance for Ghanaian businesses.`;const encoded=encodeURIComponent(url),copy=encodeURIComponent(text);return <div className="flex flex-wrap items-center gap-2" aria-label="Share this insight"><span className="mr-2 inline-flex items-center gap-2 text-sm font-bold text-[#526b62]"><Share2 size={16}/>Share</span><a aria-label="Share on WhatsApp" href={`https://wa.me/?text=${copy}%20${encoded}`} target="_blank" rel="noreferrer" className="rounded-full border bg-white p-2.5 text-[#116149]"><MessageCircle size={18}/></a><a aria-label="Share on LinkedIn" href={`https://www.linkedin.com/sharing/share-offsite/?url=${encoded}`} target="_blank" rel="noreferrer" className="rounded-full border bg-white px-3 py-2 text-sm font-black text-[#116149]">in</a><a aria-label="Share on Facebook" href={`https://www.facebook.com/sharer/sharer.php?u=${encoded}`} target="_blank" rel="noreferrer" className="rounded-full border bg-white px-3 py-2 text-sm font-black text-[#116149]">f</a><a aria-label="Share on X" href={`https://twitter.com/intent/tweet?text=${copy}&url=${encoded}`} target="_blank" rel="noreferrer" className="rounded-full border bg-white px-3 py-2 text-sm font-black text-[#116149]">X</a></div>}
