import Link from "next/link";
import {ArrowRight,CalendarClock,MapPin} from "lucide-react";
import type {PublicTender} from "@/lib/server/seo-opportunities";
import {absoluteUrl,safeJsonLd} from "@/lib/seo/site";

export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJsonLd(data)}}/>;}

export function Breadcrumbs({items}:{items:Array<{name:string;href:string}>}){
  return <><nav aria-label="Breadcrumb" className="text-sm text-[#61736a]"><ol className="flex flex-wrap items-center gap-2">{items.map((item,index)=><li key={item.href} className="flex items-center gap-2">{index>0&&<span aria-hidden="true">›</span>}<Link href={item.href} className="hover:text-[#116149] hover:underline">{item.name}</Link></li>)}</ol></nav><JsonLd data={{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:absoluteUrl(item.href)}))}}/></>;
}

function date(value:string|null){return value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(new Date(value)):"Deadline not stated";}

export function TenderCards({items,empty="No open opportunities are available in this section today."}:{items:PublicTender[];empty?:string}){
  if(!items.length)return <div className="rounded-3xl border border-[#17362d]/10 bg-white p-8 text-[#61736a]"><p>{empty}</p><p className="mt-3">Browse all current opportunities or create an alert so BidScope can notify you when a relevant tender is published.</p><Link href="/opportunities" className="mt-5 inline-flex font-bold text-[#116149] underline">Browse all tenders</Link></div>;
  return <div className="grid gap-4">{items.map(item=><article key={item.slug} className="rounded-3xl border border-[#17362d]/10 bg-[#fffdf8] p-6 shadow-sm"><div className="flex flex-wrap gap-2 text-xs font-bold uppercase tracking-wider text-[#315b4e]"><span>{item.category}</span><span className="rounded-full bg-[#e8efe9] px-3 py-1">{item.status.replaceAll("_"," ")}</span></div><h2 className="mt-4 text-xl font-bold leading-7"><Link href={`/opportunities/${item.slug}`} className="hover:text-[#116149]">{item.title}</Link></h2><p className="mt-2 max-w-3xl leading-7 text-[#667970]">{item.summary}</p><div className="mt-5 flex flex-wrap gap-5 text-sm text-[#61736a]"><span className="inline-flex items-center gap-1"><MapPin size={15}/>{[item.region,item.country].filter(Boolean).join(", ")||"Location not stated"}</span><span className="inline-flex items-center gap-1"><CalendarClock size={15}/>{date(item.deadline_at)}</span><Link href={`/opportunities/${item.slug}`} className="ml-auto inline-flex items-center gap-2 font-bold text-[#116149]">View tender preview<ArrowRight size={16}/></Link></div></article>)}</div>;
}

export function SeoCta({buyer=false}:{buyer?:boolean}){return <aside className="rounded-[28px] bg-[#103f32] p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#8bd7b7]">{buyer?"Run procurement with confidence":"Never miss a relevant opportunity"}</p><h2 className="serif mt-3 text-3xl">{buyer?"Publish and manage your next tender on BidScope.":"Get tender alerts matched to your business."}</h2><p className="mt-4 max-w-2xl leading-7 text-white/75">{buyer?"Create a buyer account to receive bids, compare suppliers and manage the procurement process in one workspace.":"Create a supplier account to save opportunities, watch deadlines and receive matching alerts."}</p><Link href={buyer?"/sign-in?mode=sign-up&account=buyer":"/sign-in?mode=sign-up&account=supplier"} className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#d0a44b] px-6 py-3 font-bold text-[#17362d]">{buyer?"Post a tender":"Create supplier account"}<ArrowRight size={17}/></Link></aside>;}

export function Faqs({items}:{items:Array<{question:string;answer:string}>}){return <section><h2 className="serif text-3xl">Frequently asked questions</h2><div className="mt-5 divide-y divide-[#17362d]/10 rounded-3xl border border-[#17362d]/10 bg-white px-6">{items.map(item=><details key={item.question} className="group py-5"><summary className="cursor-pointer list-none font-bold">{item.question}</summary><p className="mt-3 max-w-3xl leading-7 text-[#61736a]">{item.answer}</p></details>)}</div><JsonLd data={{"@context":"https://schema.org","@type":"FAQPage",mainEntity:items.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}}/></section>;}
