"use client";

import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {CheckCircle2,KeyRound,LoaderCircle} from "lucide-react";
import {BrandLogo} from "@/components/brand/brand-logo";

export default function ResetPasswordPage(){
  const[token,setToken]=useState<string|null>(null);const[state,setState]=useState<"idle"|"busy"|"done"|"error">("idle");const[message,setMessage]=useState("");
  useEffect(()=>{const hash=new URLSearchParams(window.location.hash.slice(1));const access=hash.get("access_token");window.history.replaceState({},document.title,"/auth/reset-password");const update=window.setTimeout(()=>{setToken(access);if(!access){setState("error");setMessage("This password reset link is invalid or has expired.");}},0);return()=>window.clearTimeout(update);},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const values=new FormData(form);const password=String(values.get("password")||"");if(password!==String(values.get("confirmPassword")||"")){setState("error");setMessage("Your passwords do not match.");return;}setState("busy");setMessage("");try{const response=await fetch("/api/auth/recovery",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessToken:token,password})});const result=await response.json() as {message?:string;error?:string};if(!response.ok)throw new Error(result.error||"Your password could not be changed.");setState("done");setMessage(result.message||"Your password has been changed.");form.reset();}catch(error){setState("error");setMessage(error instanceof Error?error.message:"Please try again.");}}
  return <main className="relative grid min-h-svh place-items-center overflow-hidden bg-[#0b3c2f] px-5 py-10"><div className="absolute inset-0 bg-[url('/images/bidscope-hero.webp')] bg-cover bg-[65%_center] opacity-30"/><div className="absolute inset-0 bg-[linear-gradient(120deg,rgba(5,39,29,.96),rgba(5,39,29,.64))]"/><section className="relative w-full max-w-md rounded-[28px] border border-white/15 bg-[#fffdf8]/97 p-7 shadow-[0_30px_90px_rgba(0,0,0,.28)] sm:p-9"><BrandLogo className="h-auto w-40"/><span className="mt-8 grid size-11 place-items-center rounded-2xl bg-[#e1eee6] text-[#116149]"><KeyRound size={21}/></span><h1 className="serif mt-4 text-4xl text-[#17362d]">Choose a new password.</h1><p className="mt-3 text-sm leading-6 text-[#64776f]">Use at least eight characters and avoid reusing a password from another service.</p>{state==="done"?<div className="mt-6 rounded-2xl bg-[#e3f2e9] p-4 text-sm text-[#176347]"><CheckCircle2 className="mb-2" size={20}/>{message}<Link href="/sign-in" className="mt-4 flex h-11 items-center justify-center rounded-xl bg-[#116149] font-bold text-white">Continue to sign in</Link></div>:<form className="mt-6 grid gap-4" onSubmit={submit}><label className="grid gap-2 text-sm font-bold text-[#315b4e]">New password<input name="password" type="password" minLength={8} autoComplete="new-password" required className="h-12 rounded-xl border border-[#17362d]/15 bg-white px-4 outline-none focus:border-[#16805e]"/></label><label className="grid gap-2 text-sm font-bold text-[#315b4e]">Confirm password<input name="confirmPassword" type="password" minLength={8} autoComplete="new-password" required className="h-12 rounded-xl border border-[#17362d]/15 bg-white px-4 outline-none focus:border-[#16805e]"/></label>{message&&<p role="status" className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{message}</p>}<button disabled={!token||state==="busy"} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-[#116149] font-bold text-white disabled:opacity-60">{state==="busy"&&<LoaderCircle className="animate-spin" size={17}/>}Change password</button></form>}</section></main>;
}
