"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Building2, CalendarDays, Landmark, Search, Trophy, UsersRound, WalletCards } from "lucide-react";

type Supplier = { id:string; supplier_name:string; supplier_registration_number:string|null; country_code:string|null; awarded_value:number|null; is_joint_venture:boolean };
type Award = { id:string; title:string; reference_number:string; award_date:string|null; currency:string|null; award_value:number|null; procurement_method:string|null; source_url:string; buyer:{id:string;name:string;slug:string}|null; suppliers:Supplier[] };
type Result = { data:Award[]; pagination:{page:number;pageSize:number;total:number|null}; error?:string };
const date=(value:string|null)=>{if(!value)return "Not provided";const parsed=/^\d{2}-[A-Za-z]{3}-\d{4}$/.test(value)?new Date(value.replace(/-/g," ")):new Date(value);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat("en-GB",{dateStyle:"medium"}).format(parsed);};
const money=(currency:string|null,value:number|null)=>value==null?"Not disclosed":new Intl.NumberFormat("en-GB",{style:"currency",currency:currency||"USD",maximumFractionDigits:0}).format(value);

export function AwardedOpportunityFeed(){
  const [items,setItems]=useState<Award[]>([]);const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [page,setPage]=useState(1);const [total,setTotal]=useState<number|null>(null);
  async function load(nextPage:number,append=false){setLoading(true);setError("");try{const token=window.localStorage.getItem("bidscope_access_token");if(!token)throw new Error("Sign in is required.");const response=await fetch(`/api/awards?page=${nextPage}&pageSize=40`,{headers:{Authorization:`Bearer ${token}`}});const body=await response.json() as Result;if(!response.ok)throw new Error(body.error||"Awarded contracts could not be loaded.");setItems(current=>append?[...current,...body.data]:body.data);setTotal(body.pagination.total);setPage(nextPage);}catch(caught){setError(caught instanceof Error?caught.message:"Awarded contracts could not be loaded.");}finally{setLoading(false);}}
  useEffect(()=>{void Promise.resolve().then(()=>load(1));},[]);
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return term?items.filter(item=>[item.title,item.reference_number,item.buyer?.name,item.procurement_method,...item.suppliers.map(s=>s.supplier_name)].some(value=>value?.toLowerCase().includes(term))):items;},[items,query]);
  const more=total!=null&&items.length<total;
  return <>
    <section className="border-b border-[#123f32]/10 bg-[#103f32] text-white"><div className="mx-auto max-w-7xl px-5 py-9 sm:px-6 lg:px-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#d6af5d]/25 bg-[#d6af5d]/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-[#e5c77f]"><Trophy size={14}/>Award intelligence</span><h1 className="serif mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">Previous awards. Clearer decisions.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-white/68">Research awarded contracts, the public buyer, winning supplier and disclosed contract value.</p></div><label className="flex h-12 w-full items-center gap-3 rounded-xl border border-white/15 bg-white/10 px-4 lg:max-w-sm"><Search size={18} className="text-[#e5c77f]"/><input value={query} onChange={event=>setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/50" placeholder="Search awards, buyers or suppliers…"/></label></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold text-[#4f6b60]">{loading&&!items.length?"Loading award records…":`${visible.length} awarded opportunities shown`}</p><p className="text-xs font-medium text-[#718079]">Officially published records only</p></div>
      {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">{error}</div>}
      <div className="grid gap-5">{visible.map(item=>{const supplier=item.suppliers?.[0];return <article key={item.id} className="overflow-hidden rounded-[24px] border border-[#17362d]/10 bg-[#fffdf8] shadow-[0_12px_40px_rgba(19,62,49,.06)]"><div className="grid lg:grid-cols-[1fr_310px]"><div className="p-5 sm:p-6"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#f3e8c8] px-3 py-1.5 text-xs font-extrabold uppercase tracking-[.12em] text-[#805d1d]"><Trophy size={13}/>Awarded</span><span className="text-xs font-semibold text-[#72837c]">{item.reference_number||"Reference not provided"}</span></div><h2 className="mt-4 text-xl font-extrabold leading-7 text-[#17362d] sm:text-2xl">{item.title}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Detail icon={Building2} label="Government buyer" value={item.buyer?.name||"Not provided"}/><Detail icon={UsersRound} label="Winning supplier" value={supplier?.supplier_name||"Not disclosed"}/><Detail icon={CalendarDays} label="Award date" value={date(item.award_date)}/><Detail icon={Landmark} label="Procurement method" value={item.procurement_method||"Not provided"}/></div></div><aside className="flex flex-col justify-between border-t border-[#17362d]/8 bg-[#eef3ee] p-5 sm:p-6 lg:border-l lg:border-t-0"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#65776f]">Award value</p><p className="serif mt-2 text-3xl font-semibold text-[#17362d]">{money(item.currency,supplier?.awarded_value??item.award_value)}</p>{item.suppliers?.length>1&&<p className="mt-2 text-xs text-[#65776f]">{item.suppliers.length} suppliers listed</p>}{supplier?.is_joint_venture&&<p className="mt-2 text-xs font-semibold text-[#805d1d]">Joint venture award</p>}</div><a href={item.source_url} target="_blank" rel="noreferrer" className="mt-6 inline-flex h-10 items-center justify-center gap-2 rounded-full bg-[#116149] px-4 text-sm font-bold text-white">View official record <ArrowUpRight size={15}/></a></aside></div></article>})}
        {!loading&&!visible.length&&!error&&<div className="rounded-[24px] border border-dashed border-[#17362d]/20 bg-white/60 p-12 text-center"><WalletCards className="mx-auto text-[#16805e]"/><h2 className="mt-4 text-xl font-bold text-[#17362d]">No award records match</h2><p className="mt-2 text-sm text-[#65776f]">Try a broader search or check again after the next source update.</p></div>}{loading&&<div className="h-56 animate-pulse rounded-[24px] bg-white"/>}</div>
      {more&&<button onClick={()=>void load(page+1,true)} disabled={loading} className="mx-auto mt-7 flex h-11 items-center rounded-full border border-[#17362d]/15 bg-white px-6 text-sm font-bold text-[#17362d] disabled:opacity-50">{loading?"Loading…":"Load more awarded opportunities"}</button>}
    </section>
  </>;
}

function Detail({icon:Icon,label,value}:{icon:typeof Building2;label:string;value:string}){return <div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[#e5efe8] text-[#116149]"><Icon size={17}/></span><div><p className="text-[11px] font-bold uppercase tracking-[.1em] text-[#71817a]">{label}</p><p className="mt-1 text-sm font-semibold leading-5 text-[#294d41]">{value}</p></div></div>}
