import { ApiError,apiErrorResponse } from "@/lib/server/api-error";
import { requireSuperAdmin } from "@/lib/server/auth";
import { configuredProviders } from "@/lib/server/ai/providers";
import { supabaseRest } from "@/lib/server/supabase-rest";

const allowed=new Set(["enabled","role","priority","allow_sensitive_data","allow_customer_documents","rate_limit_per_minute","data_retention_notes"]);
export async function GET(request:Request){try{await requireSuperAdmin(request);const[{data:providers},{data:models},{data:routes}]=await Promise.all([supabaseRest<Array<Record<string,unknown>>>("ai_providers?select=*&order=priority.asc"),supabaseRest<Array<Record<string,unknown>>>("ai_models?select=*&order=provider.asc,priority.asc"),supabaseRest<Array<Record<string,unknown>>>("ai_feature_routes?select=*&order=task_type.asc")]);const adapters=new Map(configuredProviders().map(x=>[x.id,x]));return Response.json({data:{providers:providers.map(p=>({...p,configured:Boolean(adapters.get(String(p.id))?.configured)})),models,routes}});}catch(error){return apiErrorResponse(error);}}
export async function PATCH(request:Request){try{const{user}=await requireSuperAdmin(request);const body=await request.json() as Record<string,unknown>;const id=String(body.id||"");if(!id)throw new ApiError(400,"Provider is required.","invalid_provider");const changes=Object.fromEntries(Object.entries(body).filter(([key])=>allowed.has(key)));await supabaseRest(`ai_providers?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(changes)});await supabaseRest("audit_log",{method:"POST",body:JSON.stringify({actor_user_id:user.id,action:"ai.provider.updated",entity_type:"ai_provider",entity_id:id,metadata:{changed:Object.keys(changes)}})});return Response.json({data:{id,updated:Object.keys(changes)}});}catch(error){return apiErrorResponse(error);}}
export async function POST(request:Request){try{const{user}=await requireSuperAdmin(request);const body=await request.json() as{id?:string};const adapter=configuredProviders().find(x=>x.id===body.id);if(!adapter)throw new ApiError(404,"Provider adapter was not found.","provider_not_found");const health=await adapter.healthCheck();await Promise.all([supabaseRest(`ai_providers?id=eq.${encodeURIComponent(adapter.id)}`,{method:"PATCH",body:JSON.stringify({health_status:health.status,last_checked_at:new Date().toISOString()})}),supabaseRest("ai_provider_health",{method:"POST",body:JSON.stringify({provider:adapter.id,status:health.status,latency_ms:health.latencyMs,failure_reason:health.detail||null})}),supabaseRest("audit_log",{method:"POST",body:JSON.stringify({actor_user_id:user.id,action:"ai.provider.connection_tested",entity_type:"ai_provider",entity_id:adapter.id,metadata:{status:health.status,latency_ms:health.latencyMs}})})]);return Response.json({data:health});}catch(error){return apiErrorResponse(error);}}
