import { z } from "zod";
import { isBidscopeSuperAdmin, requireUser } from "@/lib/server/auth";
import { ApiError, apiErrorResponse } from "@/lib/server/api-error";
import { supabaseRest } from "@/lib/server/supabase-rest";
export const dynamic = "force-dynamic";
const idSchema = z.string().uuid();
const patchSchema = z.object({ action: z.enum(["save", "submit", "withdraw"]), fields: z.record(z.string(), z.unknown()).optional() });
type Row = Record<string, unknown>;
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; idSchema.parse(id); const { user } = await requireUser(request); const admin = await isBidscopeSuperAdmin(user); const query = new URLSearchParams({ select: "*", id: `eq.${id}`, limit: "1" }); if (!admin) query.set("submitted_by", `eq.${user.id}`); const { data } = await supabaseRest<Row[]>(`tender_submissions?${query}`, { serviceRole: true }); if (!data.length) throw new ApiError(404, "Tender submission not found."); return Response.json({ data: data[0] }); } catch (error) { return apiErrorResponse(error); } }
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; idSchema.parse(id); const input = patchSchema.parse(await request.json()); const { user } = await requireUser(request); const ownerQuery = `tender_submissions?select=id,status,submitted_by&id=eq.${id}&submitted_by=eq.${user.id}&limit=1`; const { data: owned } = await supabaseRest<Array<{ id: string; status: string; submitted_by: string }>>(ownerQuery, { serviceRole: true }); if (!owned.length) throw new ApiError(404, "Tender submission not found."); if (input.action === "withdraw") { if (!["DRAFT", "SUBMITTED", "NEEDS_CHANGES"].includes(owned[0].status)) throw new ApiError(409, "This submission can no longer be withdrawn."); const { data } = await supabaseRest<Row[]>(`tender_submissions?id=eq.${id}&submitted_by=eq.${user.id}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ status: "WITHDRAWN", updated_at: new Date().toISOString() }), serviceRole: true }); return Response.json({ data: data[0] }); } const nextStatus = input.action === "submit" ? "SUBMITTED" : "DRAFT"; const fields = { ...(input.fields || {}) }; delete fields.status; delete fields.submitted_by; const { data } = await supabaseRest<Row[]>(`tender_submissions?id=eq.${id}&submitted_by=eq.${user.id}&status=in.(DRAFT,NEEDS_CHANGES)`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ ...fields, status: nextStatus, submitted_at: input.action === "submit" ? new Date().toISOString() : null, updated_at: new Date().toISOString() }), serviceRole: true }); if (!data.length) throw new ApiError(409, "Only drafts or requested changes can be edited."); return Response.json({ data: data[0] }); } catch (error) { return apiErrorResponse(error); } }
