import { ApiError,apiErrorResponse } from "@/lib/server/api-error";
import { requireOrganizationMember,requireUser } from "@/lib/server/auth";
import { callConfiguredModel,dedupeCitations,groundedFallback,opportunityEvidenceChunk,retrieveRelevantChunks,type DocumentChunk,type OpportunityContext,type Passport } from "@/lib/server/procurement-ai";
import {chunkDocument,extractDocumentText} from "@/lib/server/documents";
import { procurementAiSchema } from "@/lib/server/schemas";
import { supabaseRest } from "@/lib/server/supabase-rest";
import {getUsageAllowance,primaryOrganization,recordSuccessfulUsage,requireEntitlement} from "@/lib/server/entitlements";
import {planFromBillingCode} from "@/lib/server/ai/orchestrator";

export const dynamic="force-dynamic";export const maxDuration=60;
const actionLabels:Record<string,string>={summary:"Summarise this tender",mandatory_documents:"What documents are mandatory?",disqualification_risks:"What could disqualify us?",key_dates:"What are the key dates?",passport_comparison:"Compare this with my Supplier Passport",missing_items:"What are we missing?",evaluation_criteria:"Explain the evaluation criteria",latest_amendment:"Summarise the latest amendment",eligibility:"Who is eligible to bid?",clarifications:"What needs clarification?",tender_report:"Create a structured tender intelligence report using only cited notice and document evidence. Cover executive summary, scope, deliverables, eligibility, mandatory requirements, documents, financial and experience requirements, certifications, bid security, dates, submission instructions, clarifications, risks, missing evidence, business match, readiness, recommendation, next actions and available buyer or award history. Use NOT FOUND, NOT STATED or UNKNOWN whenever evidence is absent."};

export async function POST(request:Request){try{const{user}=await requireUser(request);const input=procurementAiSchema.parse(await request.json());const membership=input.organizationId?{organization_id:input.organizationId}:await primaryOrganization(user.id);if(!membership)throw new ApiError(400,"Create a business profile before using BidScope AI.","profile_required");await requireOrganizationMember(user.id,membership.organization_id);const premiumActions=["mandatory_documents","disqualification_risks","passport_comparison","missing_items","evaluation_criteria","latest_amendment","clarifications","tender_report"];if(premiumActions.includes(input.action))await requireEntitlement(membership.organization_id,input.action==="tender_report"?"tender_intelligence_report":"ai_assistant",user);const allowance=await getUsageAllowance(membership.organization_id,"ai_analysis",user);if(allowance.used>=allowance.limit){await supabaseRest("ai_usage",{method:"POST",body:JSON.stringify({user_id:user.id,organization_id:membership.organization_id,provider:"bidscope",model:"usage-control",status:"limited"})});throw new ApiError(429,`Your AI allowance has been reached for this period.`,"ai_limit_reached");}
    const{data:opportunities}=await supabaseRest<OpportunityContext[]>(`procurement_opportunities?select=id,title,summary,description,buyer_name,external_reference,bidscope_reference,eligibility_text,procurement_method,contract_type,estimated_value,currency,published_at,deadline_at,opening_at,clarification_deadline_at,official_source_url,official_tender_url,documents_url,source_name,submission_method,submission_platform,submission_instructions,qualification_requirements,bid_security_requirement,participation_fee_amount,participation_fee_currency,procurement_codes,source_details&id=eq.${input.opportunityId}&published_at=not.is.null&status=neq.DRAFT&limit=1`);const opportunity=opportunities[0];if(!opportunity)throw new ApiError(404,"Opportunity not found.","not_found");
    const{data:documents}=await supabaseRest<Array<{id:string;title:string;url:string}>>(`opportunity_documents?select=id,title,url&opportunity_id=eq.${opportunity.id}&processing_status=eq.indexed`);const chunks:DocumentChunk[]=[opportunityEvidenceChunk(opportunity)];if(documents.length){const ids=documents.map(doc=>doc.id).join(",");const{data}=await supabaseRest<DocumentChunk[]>(`document_chunks?select=*&document_id=in.(${ids})&limit=1000`);const byId=new Map(documents.map(doc=>[doc.id,doc]));chunks.push(...data.map(chunk=>({...chunk,document:byId.get(chunk.document_id)})));}
    const liveUrls=[opportunity.official_tender_url,opportunity.official_source_url,opportunity.documents_url].filter((url,index,all):url is string=>!!url&&all.indexOf(url)===index).slice(0,2);const liveSources=await Promise.allSettled(liveUrls.map(async(url)=>({url,extracted:await extractDocumentText({url})})));for(const source of liveSources){if(source.status!=="fulfilled")continue;const liveChunks=chunkDocument(source.value.extracted.content.slice(0,50000));chunks.push(...liveChunks.map((chunk,index)=>({...chunk,id:`live-${opportunity.id}-${index}`,document_id:`live-${opportunity.id}`,section_label:chunk.section_label||"Live official source",document:{title:`Live ${opportunity.source_name} source`,url:source.value.url}})));}
    const{data:revisions}=await supabaseRest<Array<{changed_fields:unknown;verified_at:string}>>(`opportunity_revisions?select=changed_fields,verified_at&opportunity_id=eq.${opportunity.id}&order=verified_at.desc&limit=1`);if(revisions[0])chunks.push({id:`revision-${opportunity.id}`,document_id:opportunity.id,chunk_index:999999,page_number:null,section_label:"Latest verified amendment",content:JSON.stringify(revisions[0].changed_fields),document:{title:"BidScope amendment record",url:opportunity.official_source_url}});
    const prompt=input.question||actionLabels[input.action]||"Analyse this opportunity";const relevant=retrieveRelevantChunks(chunks,prompt,8);let passport:Passport|null=null;if(input.allowSupplierPassport){const[{data:orgs},{data:docs}]=await Promise.all([supabaseRest<Omit<Passport,"documents">[]>(`organizations?select=sectors,services,products,certifications,region,preferred_regions,preferred_minimum_value,preferred_maximum_value&id=eq.${membership.organization_id}&limit=1`),supabaseRest<Passport["documents"]>(`supplier_documents?select=document_type,title,expires_at,verification_status&organization_id=eq.${membership.organization_id}`)]);if(orgs[0])passport={...orgs[0],documents:docs};}
    let threadId=input.threadId;if(threadId){const{data}=await supabaseRest<Array<{id:string}>>(`ai_threads?select=id&id=eq.${threadId}&user_id=eq.${user.id}&limit=1`);if(!data[0])throw new ApiError(403,"You do not have access to this AI thread.","ai_thread_access_denied");}else{const{data}=await supabaseRest<Array<{id:string}>>("ai_threads",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({user_id:user.id,organization_id:membership.organization_id,opportunity_id:opportunity.id,title:`${opportunity.title.slice(0,90)} — analysis`})});threadId=data[0].id;}
    await supabaseRest("ai_messages",{method:"POST",body:JSON.stringify({thread_id:threadId,role:"user",content:prompt})});let providerResult:null|Awaited<ReturnType<typeof callConfiguredModel>>=null;let providerError="";try{providerResult=await callConfiguredModel({action:input.action,question:prompt,opportunity,chunks:relevant,passport,userId:user.id,organizationId:membership.organization_id,plan:planFromBillingCode(allowance.entitlement.plan.code,allowance.entitlement.adminOverride),requestedMode:input.analysisMode});}catch(error){providerError=error instanceof Error?error.message:"AI analysis is temporarily unavailable";}const fallback=groundedFallback(input.action,prompt,opportunity,relevant,passport);const result=providerResult?{content:providerResult.content,citations:dedupeCitations([...fallback.citations,...(providerResult.citations||[])]),groundingStatus:(fallback.groundingStatus==="verified"?"verified":relevant.length||providerResult.citations?.length?"mixed":"not_found") as "verified"|"mixed"|"not_found"}:fallback;
    const{data:messages}=await supabaseRest<Array<{id:string;created_at:string}>>("ai_messages",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({thread_id:threadId,role:"assistant",content:result.content,citation_metadata:result.citations,grounding_status:result.groundingStatus})});await Promise.all([supabaseRest("ai_usage",{method:"POST",body:JSON.stringify({user_id:user.id,organization_id:membership.organization_id,thread_id:threadId,provider:providerResult?.provider||"bidscope-grounded",model:providerResult?.model||"deterministic-v1",input_tokens:providerResult?.usage?.input_tokens||null,output_tokens:providerResult?.usage?.output_tokens||null,status:"succeeded"})}),recordSuccessfulUsage({organizationId:membership.organization_id,feature:"ai_analysis",periodStart:allowance.periodStart,periodEnd:allowance.periodEnd})]);return Response.json({data:{threadId,messageId:messages[0]?.id,content:result.content,citations:result.citations,groundingStatus:result.groundingStatus,provider:providerResult?"configured-model":"grounded-fallback",providerWarning:providerError||null,usage:{used:allowance.used+1,limit:allowance.limit,plan:allowance.entitlement.tier}}});
  }catch(error){return apiErrorResponse(error);}}
