import { ApiError,apiErrorResponse } from "@/lib/server/api-error";
import { requireOrganizationMember,requireUser } from "@/lib/server/auth";
import { callConfiguredModel,groundedFallback,retrieveRelevantChunks,type DocumentChunk,type OpportunityContext,type Passport } from "@/lib/server/procurement-ai";
import { procurementAiSchema } from "@/lib/server/schemas";
import { supabaseRest } from "@/lib/server/supabase-rest";

export const dynamic="force-dynamic";export const maxDuration=60;
const actionLabels:Record<string,string>={summary:"Summarise this tender",mandatory_documents:"What documents are mandatory?",disqualification_risks:"What could disqualify us?",key_dates:"What are the key dates?",passport_comparison:"Compare this with my Supplier Passport",missing_items:"What are we missing?",evaluation_criteria:"Explain the evaluation criteria",latest_amendment:"Summarise the latest amendment",eligibility:"Who is eligible to bid?",clarifications:"What needs clarification?"};

async function usageLimit(userId:string,organizationId?:string|null){let plan="free";if(organizationId){const{data}=await supabaseRest<Array<{plan_code:string;status:string}>>(`subscriptions?select=plan_code,status&organization_id=eq.${organizationId}&limit=1`);if(data[0]&&["active","trialing"].includes(data[0].status))plan=data[0].plan_code;}const limits:Record<string,number>={free:10,founding:25,pro:100,advisor:300};const since=new Date();since.setUTCHours(0,0,0,0);const{response}=await supabaseRest<unknown[]>(`ai_usage?select=id&user_id=eq.${userId}&created_at=gte.${since.toISOString()}&status=eq.succeeded`,{count:"exact"});return{plan,used:Number(response.headers.get("content-range")?.split("/")[1]||0),limit:limits[plan]||10};}

export async function POST(request:Request){try{const{user}=await requireUser(request);const input=procurementAiSchema.parse(await request.json());if(input.organizationId)await requireOrganizationMember(user.id,input.organizationId);const allowance=await usageLimit(user.id,input.organizationId);if(allowance.used>=allowance.limit){await supabaseRest("ai_usage",{method:"POST",body:JSON.stringify({user_id:user.id,organization_id:input.organizationId||null,provider:"bidscope",model:"usage-control",status:"limited"})});throw new ApiError(429,`Your ${allowance.plan} daily AI allowance has been reached.`,"ai_limit_reached");}
    const{data:opportunities}=await supabaseRest<OpportunityContext[]>(`procurement_opportunities?select=id,title,summary,description,buyer_name,external_reference,bidscope_reference,eligibility_text,procurement_method,contract_type,estimated_value,currency,published_at,deadline_at,official_source_url,official_tender_url,documents_url,source_name,submission_method,submission_platform&id=eq.${input.opportunityId}&published_at=not.is.null&status=neq.DRAFT&limit=1`);const opportunity=opportunities[0];if(!opportunity)throw new ApiError(404,"Opportunity not found.","not_found");
    const{data:documents}=await supabaseRest<Array<{id:string;title:string;url:string}>>(`opportunity_documents?select=id,title,url&opportunity_id=eq.${opportunity.id}&processing_status=eq.indexed`);let chunks:DocumentChunk[]=[];if(documents.length){const ids=documents.map(doc=>doc.id).join(",");const{data}=await supabaseRest<DocumentChunk[]>(`document_chunks?select=*&document_id=in.(${ids})&limit=1000`);const byId=new Map(documents.map(doc=>[doc.id,doc]));chunks=data.map(chunk=>({...chunk,document:byId.get(chunk.document_id)}));}
    const{data:revisions}=await supabaseRest<Array<{changed_fields:unknown;verified_at:string}>>(`opportunity_revisions?select=changed_fields,verified_at&opportunity_id=eq.${opportunity.id}&order=verified_at.desc&limit=1`);if(revisions[0])chunks.push({id:`revision-${opportunity.id}`,document_id:opportunity.id,chunk_index:999999,page_number:null,section_label:"Latest verified amendment",content:JSON.stringify(revisions[0].changed_fields),document:{title:"BidScope amendment record",url:opportunity.official_source_url}});
    const prompt=input.question||actionLabels[input.action]||"Analyse this opportunity";const relevant=retrieveRelevantChunks(chunks,prompt,8);let passport:Passport|null=null;if(input.allowSupplierPassport&&input.organizationId){const[{data:orgs},{data:docs}]=await Promise.all([supabaseRest<Omit<Passport,"documents">[]>(`organizations?select=sectors,services,products,certifications,region,preferred_regions,preferred_minimum_value,preferred_maximum_value&id=eq.${input.organizationId}&limit=1`),supabaseRest<Passport["documents"]>(`supplier_documents?select=document_type,title,expires_at,verification_status&organization_id=eq.${input.organizationId}`)]);if(orgs[0])passport={...orgs[0],documents:docs};}
    let threadId=input.threadId;if(threadId){const{data}=await supabaseRest<Array<{id:string}>>(`ai_threads?select=id&id=eq.${threadId}&user_id=eq.${user.id}&limit=1`);if(!data[0])throw new ApiError(403,"You do not have access to this AI thread.","ai_thread_access_denied");}else{const{data}=await supabaseRest<Array<{id:string}>>("ai_threads",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({user_id:user.id,organization_id:input.organizationId||null,opportunity_id:opportunity.id,title:`${opportunity.title.slice(0,90)} — analysis`})});threadId=data[0].id;}
    await supabaseRest("ai_messages",{method:"POST",body:JSON.stringify({thread_id:threadId,role:"user",content:prompt})});let providerResult:null|Awaited<ReturnType<typeof callConfiguredModel>>=null;let providerError="";try{providerResult=await callConfiguredModel({action:input.action,question:prompt,opportunity,chunks:relevant,passport});}catch(error){providerError=error instanceof Error?error.message:"AI provider failed";}const fallback=groundedFallback(input.action,prompt,opportunity,relevant,passport);const result=providerResult?{content:providerResult.content,citations:fallback.citations,groundingStatus:fallback.groundingStatus}:fallback;
    const{data:messages}=await supabaseRest<Array<{id:string;created_at:string}>>("ai_messages",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({thread_id:threadId,role:"assistant",content:result.content,citation_metadata:result.citations,grounding_status:result.groundingStatus})});await supabaseRest("ai_usage",{method:"POST",body:JSON.stringify({user_id:user.id,organization_id:input.organizationId||null,thread_id:threadId,provider:providerResult?.provider||"bidscope-grounded",model:providerResult?.model||"deterministic-v1",input_tokens:providerResult?.usage?.input_tokens||null,output_tokens:providerResult?.usage?.output_tokens||null,status:"succeeded"})});return Response.json({data:{threadId,messageId:messages[0]?.id,content:result.content,citations:result.citations,groundingStatus:result.groundingStatus,provider:providerResult?"configured-model":"grounded-fallback",providerWarning:providerError||null,usage:{used:allowance.used+1,limit:allowance.limit,plan:allowance.plan}}});
  }catch(error){return apiErrorResponse(error);}}
