import { isIP } from "node:net";
import { lookup } from "node:dns/promises";

const MAX_BYTES=20*1024*1024;
function privateAddress(address:string){if(isIP(address)===4){const [a,b]=address.split(".").map(Number);return a===10||a===127||a===0||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168);}return address==="::1"||address.startsWith("fc")||address.startsWith("fd")||address.startsWith("fe80");}
async function safeUrl(value:string){const url=new URL(value);if(!["https:","http:"].includes(url.protocol))throw new Error("Only HTTP(S) document URLs are supported.");const records=await lookup(url.hostname,{all:true});if(!records.length||records.some(record=>privateAddress(record.address)))throw new Error("Private or unresolved document hosts are not allowed.");return url;}
function stripHtml(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\s+/g," ").trim();}
async function download(urlValue:string){let url=await safeUrl(urlValue);for(let redirects=0;redirects<4;redirects++){const response=await fetch(url,{redirect:"manual",headers:{Accept:"application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,text/html;q=.8","User-Agent":"BidScopeGhana/1.0 document indexer"}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get("location");if(!location)throw new Error("Document redirect has no destination.");url=await safeUrl(new URL(location,url).toString());continue;}if(!response.ok)throw new Error(`Document source returned ${response.status}.`);const declared=Number(response.headers.get("content-length")||0);if(declared>MAX_BYTES)throw new Error("Document exceeds the 20 MB indexing limit.");const buffer=Buffer.from(await response.arrayBuffer());if(buffer.length>MAX_BYTES)throw new Error("Document exceeds the 20 MB indexing limit.");return{buffer,mimeType:(response.headers.get("content-type")||"").split(";")[0],finalUrl:url.toString()};}throw new Error("Document redirected too many times.");}

export async function extractDocumentText(input:{url:string;mimeType?:string|null;extractedText?:string|null}){if(input.extractedText?.trim())return{content:input.extractedText.trim(),mimeType:input.mimeType||"text/plain",source:"trusted-ingestion"};const downloaded=await download(input.url);const mime=input.mimeType||downloaded.mimeType;if(mime.startsWith("text/plain"))return{content:downloaded.buffer.toString("utf8"),mimeType:mime,source:"native"};if(mime.includes("html"))return{content:stripHtml(downloaded.buffer.toString("utf8")),mimeType:mime,source:"native"};const extractor=process.env.DOCUMENT_EXTRACTION_URL;if(!extractor)throw new Error(`A document extraction provider is required for ${mime||"this binary format"}.`);const response=await fetch(extractor,{method:"POST",headers:{"Content-Type":"application/json",...(process.env.DOCUMENT_EXTRACTION_API_KEY?{Authorization:`Bearer ${process.env.DOCUMENT_EXTRACTION_API_KEY}`}:{})},body:JSON.stringify({url:downloaded.finalUrl,mimeType:mime})});if(!response.ok)throw new Error(`Document extractor returned ${response.status}.`);const result=await response.json() as {text?:string};if(!result.text?.trim())throw new Error("Document extractor returned no text.");return{content:result.text.trim(),mimeType:mime,source:"configured-provider"};}

export function chunkDocument(content:string,size=4000,overlap=400){const pages=content.split(/\f/);const chunks:Array<{chunk_index:number;page_number:number|null;section_label:string|null;content:string;token_estimate:number}>=[];let index=0;for(let page=0;page<pages.length;page++){const text=pages[page].replace(/\r/g,"").trim();for(let start=0;start<text.length;start+=size-overlap){let end=Math.min(text.length,start+size);if(end<text.length){const boundary=text.lastIndexOf("\n",end);if(boundary>start+size/2)end=boundary;}const part=text.slice(start,end).trim();if(part)chunks.push({chunk_index:index++,page_number:pages.length>1?page+1:null,section_label:null,content:part,token_estimate:Math.ceil(part.length/4)});if(end===text.length)break;}}return chunks;}
