import "server-only";
import {encodeFilter,supabaseRest} from "./supabase-rest";

type Row=Record<string,unknown>;
const now=()=>new Date().toISOString();
const clean=(value:unknown)=>String(value||"").trim();
const domain=(value:unknown)=>{try{return new URL(clean(value)).hostname.replace(/^www\./,"").toLowerCase()}catch{return""}};

export async function getGrowthRelationships(){
 const[{data:organisations},{data:activities},{data:partnerships},{data:backlinks},{data:opportunities},{data:experiments},{data:referrals}]=await Promise.all([
  supabaseRest<Row[]>("seo_outreach_targets?select=*&order=priority.desc,relevance_score.desc,organisation.asc&limit=1000"),
  supabaseRest<Row[]>("seo_outreach_activities?select=*&order=due_at.asc.nullslast,created_at.desc&limit=1000"),
  supabaseRest<Row[]>("seo_partnerships?select=*&order=next_action_at.asc.nullslast,updated_at.desc&limit=500"),
  supabaseRest<Row[]>("seo_backlinks?select=*&order=updated_at.desc&limit=1000"),
  supabaseRest<Row[]>("seo_search_opportunities?select=*&order=priority_score.desc,last_detected_at.desc&limit=1000"),
  supabaseRest<Row[]>("seo_experiments?select=*&order=created_at.desc&limit=500"),
  supabaseRest<Row[]>("seo_referral_metrics?select=*&order=metric_date.desc,sessions.desc&limit=2000"),
 ]);
 const organisationsWithPerformance=organisations.map(row=>{const canonical=String(row.canonical_domain||"").replace(/^www\./,"").toLowerCase(),matched=referrals.filter(metric=>String(metric.referring_domain||"").replace(/^www\./,"").toLowerCase()===canonical),links=backlinks.filter(link=>link.outreach_target_id===row.id);return{...row,performance:{sessions:matched.reduce((sum,item)=>sum+Number(item.sessions||0),0),signups:matched.reduce((sum,item)=>sum+Number(item.signups||0),0),subscriptions:matched.reduce((sum,item)=>sum+Number(item.subscriptions||0),0),revenue_minor:matched.reduce((sum,item)=>sum+Number(item.revenue_minor||0),0),backlinks:links.length,verified_backlinks:links.filter(link=>link.verification_status==="verified").length}}});
 const metrics={organisations:organisations.length,verified:organisations.filter(row=>row.verification_status==="verified").length,highPriority:organisations.filter(row=>["critical","high"].includes(String(row.priority))).length,drafts:activities.filter(row=>row.activity_type==="draft_created"&&row.status==="draft").length,followUpsDue:activities.filter(row=>row.due_at&&new Date(String(row.due_at))<=new Date()&&row.status==="planned").length,activePartnerships:partnerships.filter(row=>["discussion","agreed","active"].includes(String(row.status))).length,liveBacklinks:backlinks.filter(row=>row.status==="live"&&row.verification_status==="verified").length,readyOpportunities:opportunities.filter(row=>row.state==="READY_TO_OPTIMISE").length};
 return{metrics,organisations:organisationsWithPerformance,activities,partnerships,backlinks,opportunities,experiments,referrals};
}

export async function createOrganisation(input:Row,userId:string){
 const organisation=clean(input.organisation),website=clean(input.website),canonicalDomain=domain(website),verificationUrl=clean(input.verificationSourceUrl);
 if(!organisation||!website||!verificationUrl)throw new Error("Organisation, website and verification source are required.");
 const{data:existing}=await supabaseRest<Row[]>(`seo_outreach_targets?or=(organisation.ilike.${encodeFilter(organisation)},canonical_domain.eq.${encodeFilter(canonicalDomain)})&select=id,organisation&limit=1`);if(existing.length)throw new Error("This organisation or domain is already tracked.");
 const score=Math.max(0,Math.min(100,Number(input.relevanceScore||0))),row={organisation,website,canonical_domain:canonicalDomain,organisation_type:clean(input.organisationType)||"ecosystem_partner",sector_tags:Array.isArray(input.sectorTags)?input.sectorTags:[],verification_status:"verified",verification_source_url:verificationUrl,verified_at:now(),last_verified_at:now(),verification_notes:clean(input.verificationNotes)||"Verified by an administrator from the linked source.",resource_match:clean(input.resourceMatch)||null,reason_to_approach:clean(input.outreachReason)||null,outreach_reason:clean(input.outreachReason)||null,relevance_score:score,priority:score>=90?"critical":score>=80?"high":score>=60?"medium":"low",score_breakdown:input.scoreBreakdown||{},status:"discovered",created_by:userId,notes:"No contact data is inferred; verify a public institutional contact route before outreach."};
 const{data}=await supabaseRest<Row[]>("seo_outreach_targets",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});return data[0];
}

export async function createOutreachDraft(targetId:string,userId:string){
 const{data:targets}=await supabaseRest<Row[]>(`seo_outreach_targets?id=eq.${encodeFilter(targetId)}&select=*&limit=1`),target=targets[0];if(!target)throw new Error("Organisation was not found.");if(target.verification_status!=="verified")throw new Error("Verify the organisation before drafting outreach.");
 const{data:existing}=await supabaseRest<Row[]>(`seo_outreach_activities?outreach_target_id=eq.${encodeFilter(targetId)}&activity_type=eq.draft_created&status=eq.draft&select=*&order=created_at.desc&limit=1`);if(existing[0])return existing[0];
 const name=clean(target.organisation),resource=clean(target.resource_match)||"https://www.bidscopeghana.com/insights",reason=clean(target.outreach_reason||target.reason_to_approach),subject=`Useful Ghana procurement resource for ${name}`;
 const body=`Hello ${name} team,\n\nBidScope publishes practical, source-linked procurement guidance for Ghanaian businesses. We identified ${resource} as potentially useful to your audience because ${reason.charAt(0).toLowerCase()}${reason.slice(1)}\n\nIf it is genuinely useful, we would be grateful if your team would consider sharing or linking to it in the most appropriate resource area. There is no obligation, paid link request or automated placement.\n\nKind regards,\nBidScope`;
 const{data}=await supabaseRest<Row[]>("seo_outreach_activities",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({outreach_target_id:targetId,activity_type:"draft_created",status:"draft",subject,body,created_by:userId,metadata:{manualReviewRequired:true,autoSend:false}})});await supabaseRest(`seo_outreach_targets?id=eq.${encodeFilter(targetId)}`,{method:"PATCH",body:JSON.stringify({status:"outreach_planned"})});return data[0];
}

export async function createPartnership(input:Row,userId:string){const targetId=clean(input.targetId),objective=clean(input.objective);if(!targetId||!objective)throw new Error("Organisation and partnership objective are required.");const row={outreach_target_id:targetId,partnership_type:clean(input.partnershipType)||"content",objective,proposed_value:clean(input.proposedValue)||null,status:"identified",next_action:clean(input.nextAction)||null,next_action_at:input.nextActionAt||null,owner_id:userId,created_by:userId};const{data}=await supabaseRest<Row[]>("seo_partnerships?on_conflict=outreach_target_id,partnership_type",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(row)});return data[0]}

export async function createLinkedBacklink(input:Row,userId:string){const sourceUrl=clean(input.sourceUrl),targetUrl=clean(input.targetUrl),targetId=clean(input.targetId);if(!sourceUrl||!targetUrl||!targetId)throw new Error("Organisation, source URL and BidScope target URL are required.");new URL(sourceUrl);new URL(targetUrl);const row={outreach_target_id:targetId,source_url:sourceUrl,target_url:targetUrl,source_domain:domain(sourceUrl),anchor_text:clean(input.anchorText)||null,status:"prospect",verification_status:"unverified",created_by:userId,notes:"Manual verification required before this record can be marked live."};const{data}=await supabaseRest<Row[]>("seo_backlinks?on_conflict=source_url,target_url",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(row)});return data[0]}

export async function updateGrowthRecord(kind:"organisation"|"activity"|"partnership"|"backlink"|"opportunity"|"experiment",id:string,input:Row,userId:string){
 const config={organisation:{table:"seo_outreach_targets",allowed:["status","priority","assigned_to","next_follow_up_at","contact_name","contact_email","contact_source_url","notes","verification_status","last_verified_at"]},activity:{table:"seo_outreach_activities",allowed:["status","due_at","occurred_at","outcome","subject","body"]},partnership:{table:"seo_partnerships",allowed:["status","next_action","next_action_at","outcome","notes","referral_sessions","attributed_signups","attributed_subscriptions","attributed_revenue_minor"]},backlink:{table:"seo_backlinks",allowed:["status","verification_status","verification_method","verification_evidence","anchor_text","rel_attributes","last_verified_at","notes"]},opportunity:{table:"seo_search_opportunities",allowed:["state","snoozed_until","implementation_notes"]},experiment:{table:"seo_experiments",allowed:["status","starts_at","ends_at","implemented_at","measurement_starts_at","measurement_ends_at","before_metrics","after_metrics","decision","result"]}}[kind];
 const changes=Object.fromEntries(Object.entries(input).filter(([field])=>config.allowed.includes(field)));const stamp=now();
 if(kind==="opportunity"){if(changes.state==="READY_TO_OPTIMISE")Object.assign(changes,{approved_at:stamp,approved_by:userId});if(changes.state==="NEEDS_REVIEW")Object.assign(changes,{dismissed_at:stamp,dismissed_by:userId});if(changes.state==="MEASURING_RESULT"){Object.assign(changes,{implemented_at:stamp,implemented_by:userId});const{data:items}=await supabaseRest<Row[]>(`seo_search_opportunities?id=eq.${encodeFilter(id)}&select=*&limit=1`),item=items[0];if(item)await supabaseRest("seo_experiments",{method:"POST",body:JSON.stringify({name:`Search optimisation: ${String(item.title||item.opportunity_type)}`,page_url:String(item.page_url||item.query||"search-console-opportunity"),hypothesis:String(item.recommended_action||"The approved optimisation will improve organic performance."),variant_a:{before:item.current_metrics||{}},variant_b:{implementationNotes:changes.implementation_notes||null},primary_metric:"organic_clicks_and_ctr",status:"running",starts_at:stamp,implemented_at:stamp,measurement_starts_at:stamp,measurement_ends_at:new Date(Date.now()+28*86400000).toISOString(),before_metrics:item.current_metrics||{},search_opportunity_id:id,created_by:userId})})}}
 if(kind==="backlink"&&changes.verification_status==="verified")Object.assign(changes,{last_verified_at:stamp,first_verified_at:stamp,status:"live"});
 await supabaseRest(`${config.table}?id=eq.${encodeFilter(id)}`,{method:"PATCH",body:JSON.stringify(changes)});return changes;
}
