import {createHash,randomUUID} from "node:crypto";
import {ApiError} from "./api-error.ts";
import {getEntitlement,listBillingPlans,recordConversionEvent} from "./entitlements.ts";
import {supabaseRest,supabaseRpc} from "./supabase-rest.ts";
import {createNotification,stableDedupe} from "./notifications.ts";
import {isValidPaystackSignature} from "./paystack-signature.ts";

const API="https://api.paystack.co";
type PaystackResponse<T>={status:boolean;message:string;data:T};
type Verification={id:number;status:string;reference:string;amount:number;currency:string;paid_at:string|null;channel:string;customer?:{customer_code?:string};subscription?:{subscription_code?:string};authorization?:{last4?:string;card_type?:string;bank?:string;brand?:string};metadata?:Record<string,unknown>};
type Checkout={authorization_url:string;access_code:string;reference:string};

function secret(){const key=process.env.PAYSTACK_SECRET_KEY;if(!key)throw new ApiError(503,"Paystack is not configured yet.","paystack_not_configured");return key;}
async function request<T>(path:string,init:RequestInit={}){const response=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${secret()}`,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});const body=await response.json() as PaystackResponse<T>;if(!response.ok||!body.status)throw new ApiError(502,body.message||"Paystack could not complete the request.","paystack_request_failed");return body.data;}
function safePayload(data:Verification){return{id:data.id,status:data.status,reference:data.reference,amount:data.amount,currency:data.currency,paid_at:data.paid_at,channel:data.channel,customer_code:data.customer?.customer_code||null,subscription_code:data.subscription?.subscription_code||null};}
async function notifyOrganization(organizationId:string,title:string,message:string,key:string,priority:"normal"|"high"="normal"){const{data:members}=await supabaseRest<Array<{user_id:string}>>(`organization_members?select=user_id&organization_id=eq.${organizationId}`);for(const member of members)await createNotification({userId:member.user_id,organizationId,type:"system",title,message,relatedEntityType:"subscription",relatedEntityId:organizationId,relatedUrl:"/customer/billing",priority,dedupeKey:stableDedupe(["billing",key,member.user_id])});}
export function paystackConfigurationStatus(){const key=process.env.PAYSTACK_SECRET_KEY;return{configured:Boolean(key),mode:key?.startsWith("sk_live_")?"LIVE":key?.startsWith("sk_test_")?"TEST":"NOT_CONFIGURED"};}

export async function initializePaystackCheckout(input:{userId:string;email:string;organizationId:string;billingPlanCode:string;triggerFeature?:string}){
 const plans=await listBillingPlans();const plan=plans.find(item=>item.code===input.billingPlanCode);
 if(!plan||plan.tier!=="PREMIUM")throw new ApiError(400,"Select a valid Premium plan.","invalid_billing_plan");
 if(!plan.enabled||plan.amount_minor==null||plan.activation_status==="PRICING_CONFIGURATION_REQUIRED")throw new ApiError(409,"Premium pricing must be configured in the Command Centre before checkout can open.","pricing_configuration_required");
 const configuration=paystackConfigurationStatus();if(!configuration.configured)throw new ApiError(503,"Paystack is not configured yet.","paystack_not_configured");
 if(plan.activation_status==="TEST_READY"&&configuration.mode!=="TEST")throw new ApiError(409,"This plan is configured for Paystack Test Mode only.","paystack_mode_mismatch");
 if(plan.activation_status==="LIVE"&&configuration.mode!=="LIVE")throw new ApiError(409,"This live plan requires Paystack Live Mode.","paystack_mode_mismatch");
 const reference=`bidscope_${randomUUID().replaceAll("-","")}`;const callback=`${(process.env.NEXT_PUBLIC_SITE_URL||"https://www.bidscopeghana.com").replace(/\/$/,"")}/api/payments/paystack/callback`;
 await supabaseRest("payment_transactions",{method:"POST",body:JSON.stringify({organization_id:input.organizationId,initiated_by:input.userId,reference,billing_plan_code:plan.code,amount_minor:plan.amount_minor,currency:plan.currency,payment_kind:plan.payment_kind,status:"PENDING"})});
 const payload:Record<string,unknown>={email:input.email,amount:String(plan.amount_minor),currency:plan.currency,reference,callback_url:callback,channels:plan.payment_kind==="RECURRING_CARD"?["card"]:["mobile_money"],metadata:{bidscope_organization_id:input.organizationId,bidscope_billing_plan:plan.code,bidscope_payment_kind:plan.payment_kind}};
 if(plan.payment_kind==="RECURRING_CARD"){if(!plan.provider_plan_code)throw new ApiError(409,"The Paystack recurring plan code is not configured.","paystack_plan_configuration_required");payload.plan=plan.provider_plan_code;}
 try{const checkout=await request<Checkout>("/transaction/initialize",{method:"POST",body:JSON.stringify(payload)});await supabaseRest(`payment_transactions?reference=eq.${reference}`,{method:"PATCH",body:JSON.stringify({authorization_url:checkout.authorization_url,access_code:checkout.access_code})});await recordConversionEvent({userId:input.userId,organizationId:input.organizationId,eventName:"PAYMENT_INITIALIZED",feature:input.triggerFeature,metadata:{billing_plan_code:plan.code,payment_kind:plan.payment_kind}});return checkout;}catch(error){await supabaseRest(`payment_transactions?reference=eq.${reference}`,{method:"PATCH",body:JSON.stringify({status:"FAILED",failure_reason:"Provider initialization failed"})});throw error;}
}

export async function verifyAndFulfil(reference:string){const data=await request<Verification>(`/transaction/verify/${encodeURIComponent(reference)}`);if(data.reference!==reference)throw new ApiError(409,"Paystack returned a different payment reference.","payment_reference_mismatch");if(data.status!=="success"){await supabaseRest(`payment_transactions?reference=eq.${encodeURIComponent(reference)}`,{method:"PATCH",body:JSON.stringify({status:data.status==="failed"?"FAILED":"UNVERIFIED",failure_reason:`Paystack status: ${data.status}`,verified_at:new Date().toISOString(),provider_payload:safePayload(data)})});throw new ApiError(409,"Payment has not been confirmed by Paystack.","payment_not_confirmed");}
 const paidAt=data.paid_at||new Date().toISOString();const method={channel:data.channel,last4:data.authorization?.last4||null,card_type:data.authorization?.card_type||null,bank:data.authorization?.bank||null,brand:data.authorization?.brand||null};
 const{data:result}=await supabaseRpc<{processed:boolean;idempotent:boolean;organization_id:string;period_end?:string}>("complete_paystack_payment",{p_reference:reference,p_provider_transaction_id:String(data.id),p_amount_minor:data.amount,p_currency:data.currency,p_paid_at:paidAt,p_channel:data.channel,p_customer_code:data.customer?.customer_code||null,p_subscription_code:data.subscription?.subscription_code||null,p_payment_method:method,p_provider_payload:safePayload(data)});
 if(result.processed){const{data:tx}=await supabaseRest<Array<{initiated_by:string|null;organization_id:string}>>(`payment_transactions?select=initiated_by,organization_id&reference=eq.${encodeURIComponent(reference)}&limit=1`);if(tx[0]){if(tx[0].initiated_by)await recordConversionEvent({userId:tx[0].initiated_by,organizationId:tx[0].organization_id,eventName:"PREMIUM_ACTIVATED",metadata:{reference}});await notifyOrganization(tx[0].organization_id,"BidScope Premium activated","Your verified payment has activated Premium intelligence for this business.",reference);}}
 return result;
}

function eventCode(data:Record<string,unknown>,key:string){const direct=data[key];if(typeof direct==="string")return direct;const nested=data.subscription;if(nested&&typeof nested==="object"&&typeof (nested as Record<string,unknown>)[key]==="string")return String((nested as Record<string,unknown>)[key]);return null;}
export function validPaystackSignature(raw:string,signature:string|null){return isValidPaystackSignature(raw,signature,secret());}
export async function processPaystackWebhook(raw:string,signature:string|null){if(!validPaystackSignature(raw,signature))throw new ApiError(401,"Invalid Paystack signature.","invalid_webhook_signature");const payload=JSON.parse(raw) as {event:string;data:Record<string,unknown>};const eventId=createHash("sha256").update(raw).digest("hex");await supabaseRest("webhook_events?on_conflict=provider,provider_event_id",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify({provider:"paystack",provider_event_id:eventId,event_type:payload.event,payload:{event:payload.event,reference:payload.data.reference||null},status:"received"})});const{data:stored}=await supabaseRest<Array<{status:string}>>(`webhook_events?select=status&provider=eq.paystack&provider_event_id=eq.${eventId}&limit=1`);if(stored[0]?.status==="processed")return{processed:false,idempotent:true};
 try{
  if(payload.event==="charge.success"&&typeof payload.data.reference==="string"){const reference=payload.data.reference;const{data:existing}=await supabaseRest<Array<{id:string}>>(`payment_transactions?select=id&reference=eq.${encodeURIComponent(reference)}&limit=1`);if(!existing[0]){const subscriptionCode=eventCode(payload.data,"subscription_code");if(!subscriptionCode)throw new ApiError(409,"A successful charge could not be mapped to a BidScope purchase.","unmapped_payment");const{data:subscriptions}=await supabaseRest<Array<{organization_id:string;amount_minor:number;currency:string;metadata:Record<string,unknown>}>>(`subscriptions?select=organization_id,amount_minor,currency,metadata&provider_subscription_code=eq.${encodeURIComponent(subscriptionCode)}&limit=1`);const subscription=subscriptions[0];if(!subscription)throw new ApiError(409,"The recurring Paystack subscription is not mapped to BidScope.","unmapped_subscription");await supabaseRest("payment_transactions",{method:"POST",body:JSON.stringify({organization_id:subscription.organization_id,provider:"paystack",reference,billing_plan_code:String(subscription.metadata.billing_plan_code||"premium_monthly"),amount_minor:subscription.amount_minor,currency:subscription.currency,payment_kind:"RECURRING_CARD",status:"PENDING",provider_subscription_code:subscriptionCode})});}await verifyAndFulfil(reference);}
  else{const subscriptionCode=eventCode(payload.data,"subscription_code");if(subscriptionCode){const{data:rows}=await supabaseRest<Array<{organization_id:string;metadata:Record<string,unknown>}>>(`subscriptions?select=organization_id,metadata&provider_subscription_code=eq.${encodeURIComponent(subscriptionCode)}&limit=1`);const row=rows[0];if(row){if(payload.event==="invoice.payment_failed"){const entitlement=await getEntitlement(row.organization_id);const days=Number(entitlement.plan.limits.grace_period_days||3);await supabaseRest(`subscriptions?organization_id=eq.${row.organization_id}`,{method:"PATCH",body:JSON.stringify({status:"PAST_DUE",grace_period_end:new Date(Date.now()+days*86400000).toISOString()})});await notifyOrganization(row.organization_id,"Premium payment failed",`Paystack could not renew Premium. Your data is safe and a ${days}-day grace period has started.`,eventId,"high");}if(payload.event==="subscription.not_renew"){await supabaseRest(`subscriptions?organization_id=eq.${row.organization_id}`,{method:"PATCH",body:JSON.stringify({status:"CANCEL_AT_PERIOD_END",cancel_at_period_end:true,cancelled_at:new Date().toISOString()})});await notifyOrganization(row.organization_id,"Automatic renewal cancelled","Premium remains active until the current paid period ends.",eventId);}if(payload.event==="subscription.disable"){await supabaseRest(`subscriptions?organization_id=eq.${row.organization_id}`,{method:"PATCH",body:JSON.stringify({status:"CANCELLED",cancel_at_period_end:true,cancelled_at:new Date().toISOString(),next_payment_at:null})});await notifyOrganization(row.organization_id,"Premium subscription ended","Your saved tenders, workspace and history remain preserved on BidScope Free.",eventId);}}}
  }
  await supabaseRest(`webhook_events?provider=eq.paystack&provider_event_id=eq.${eventId}`,{method:"PATCH",body:JSON.stringify({status:"processed",processed_at:new Date().toISOString()})});return{processed:true,idempotent:false};
 }catch(error){await supabaseRest(`webhook_events?provider=eq.paystack&provider_event_id=eq.${eventId}`,{method:"PATCH",body:JSON.stringify({status:"failed",error_message:(error instanceof Error?error.message:"Webhook failed").slice(0,500)})});throw error;}
}

export async function cancelPaystackSubscription(organizationId:string){const entitlement=await getEntitlement(organizationId);const code=entitlement.subscription?.provider_subscription_code;if(!code)throw new ApiError(409,"No recurring Paystack subscription is attached to this business.","subscription_not_recurring");const detail=await request<{email_token?:string}>(`/subscription/${encodeURIComponent(code)}`);if(!detail.email_token)throw new ApiError(502,"Paystack did not return a cancellation token.","paystack_cancellation_unavailable");await request("/subscription/disable",{method:"POST",body:JSON.stringify({code,token:detail.email_token})});await supabaseRest(`subscriptions?organization_id=eq.${organizationId}`,{method:"PATCH",body:JSON.stringify({status:"CANCEL_AT_PERIOD_END",cancel_at_period_end:true,cancelled_at:new Date().toISOString()})});return getEntitlement(organizationId);}
export async function reconcilePendingPaystack(limit=25){const{data}=await supabaseRest<Array<{reference:string}>>(`payment_transactions?select=reference&provider=eq.paystack&status=in.(PENDING,UNVERIFIED)&order=created_at.asc&limit=${Math.min(50,Math.max(1,limit))}`);let verified=0,failed=0;for(const item of data){try{await verifyAndFulfil(item.reference);verified++;}catch{failed++;}}return{checked:data.length,verified,failed};}
export async function expireEndedSubscriptions(){const now=new Date().toISOString();const{data}=await supabaseRest<Array<{organization_id:string}>>(`subscriptions?select=organization_id&status=in.(ACTIVE,CANCEL_AT_PERIOD_END,PAST_DUE,GRACE_PERIOD)&or=(current_period_ends_at.lt.${now},grace_period_end.lt.${now})`);for(const row of data)await supabaseRest(`subscriptions?organization_id=eq.${row.organization_id}`,{method:"PATCH",body:JSON.stringify({status:"EXPIRED",next_payment_at:null})});return{expired:data.length};}
