export type OpportunityContext={id:string;title:string;summary:string;description:string;buyer_name:string;external_reference:string|null;bidscope_reference:string;eligibility_text:string|null;procurement_method:string|null;contract_type:string|null;estimated_value:number|null;currency:string|null;published_at:string|null;deadline_at:string|null;official_source_url:string;official_tender_url:string|null;documents_url:string|null;source_name:string;submission_method:string|null;submission_platform:string|null};
export type DocumentChunk={id:string;document_id:string;chunk_index:number;page_number:number|null;section_label:string|null;content:string;document?:{title:string;url:string}};
export type Citation={label:string;documentId?:string;page?:number|null;section?:string|null;url?:string|null};
export type Passport={sectors:string[];services:string[];products:string[];certifications:string[];region:string|null;preferred_regions:string[];preferred_minimum_value:number|null;preferred_maximum_value:number|null;documents:Array<{document_type:string;title:string;expires_at:string|null;verification_status:string}>};

const terms=(value:string)=>[...new Set(value.toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(word=>word.length>2))];
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-GB",{dateStyle:"long",timeStyle:"short",timeZone:"Africa/Accra"}).format(new Date(value)):"Not stated in the available source documents.";

export function retrieveRelevantChunks(chunks:DocumentChunk[],question:string,limit=8){const needles=terms(question);return chunks.map(chunk=>({chunk,score:needles.reduce((sum,word)=>sum+(chunk.content.toLowerCase().includes(word)?1:0),0)})).filter(item=>item.score>0||chunks.length<=limit).sort((a,b)=>b.score-a.score||a.chunk.chunk_index-b.chunk.chunk_index).slice(0,limit).map(item=>item.chunk);}

function sourceCitation(opportunity:OpportunityContext):Citation{return{label:`${opportunity.source_name} opportunity record`,url:opportunity.official_tender_url||opportunity.official_source_url};}
function chunkCitations(chunks:DocumentChunk[]):Citation[]{return chunks.map(chunk=>({label:chunk.document?.title||`Tender document section ${chunk.chunk_index+1}`,documentId:chunk.document_id,page:chunk.page_number,section:chunk.section_label,url:chunk.document?.url}));}
function mentions(text:string,patterns:RegExp[]){return patterns.filter(pattern=>pattern.test(text)).map(pattern=>pattern.source.replace(/\\b|\(\?:|\)|\\s\+|\[.*?\]|\+|\?/g," ").replace(/\|/g," / ").trim());}

export function groundedFallback(action:string,question:string,opportunity:OpportunityContext,chunks:DocumentChunk[],passport?:Passport|null){const combined=[opportunity.summary,opportunity.description,opportunity.eligibility_text||"",...chunks.map(chunk=>chunk.content)].join("\n");const citations=[sourceCitation(opportunity),...chunkCitations(chunks)];const unavailable="Not stated in the available source documents.";
  if(action==="summary")return{content:[`## Opportunity\n${opportunity.title}`,`**Buyer:** ${opportunity.buyer_name||unavailable}`,`**Reference:** ${opportunity.external_reference||opportunity.bidscope_reference||unavailable}`,`**Scope:** ${opportunity.summary||opportunity.description||unavailable}`,`**Eligibility:** ${opportunity.eligibility_text||unavailable}`,`**Procurement method:** ${opportunity.procurement_method||unavailable}`,`**Contract value:** ${opportunity.estimated_value!=null?`${opportunity.currency||""} ${opportunity.estimated_value.toLocaleString()}`:unavailable}`,`**Key dates:** Published ${date(opportunity.published_at)}; closing ${date(opportunity.deadline_at)}`,`**Submission method:** ${opportunity.submission_method||opportunity.submission_platform||unavailable}`,`**Official source:** ${opportunity.official_tender_url||opportunity.official_source_url}`,`\nBidScope AI helps interpret procurement information. Always review the official tender documents before submitting a bid.`].join("\n\n"),citations,groundingStatus:"verified" as const};
  const mandatory=mentions(combined,[/tax\s+clearance/i,/ssnit\s+clearance/i,/vat\s+(?:certificate|registration)/i,/business\s+registration/i,/audited\s+(?:accounts|financial statements)/i,/bid\s+security/i,/manufacturer(?:'s)?\s+authori[sz]ation/i,/insurance/i,/professional\s+licen[cs]e/i]);
  if(action==="mandatory_documents")return{content:mandatory.length?`## Requirements found\n${mandatory.map(item=>`- ${item}`).join("\n")}\n\nThese terms appear in the available source text. Confirm whether each is explicitly mandatory in the official document.`:`## Mandatory documents\n${unavailable}`,citations,groundingStatus:mandatory.length?"mixed" as const:"not_found" as const};
  if(action==="key_dates")return{content:`## Key dates\n- Publication: ${date(opportunity.published_at)}\n- Submission deadline: ${date(opportunity.deadline_at)}\n- Clarification deadline: ${unavailable}`,citations,groundingStatus:"verified" as const};
  if(action==="eligibility")return{content:`## Eligibility\n${opportunity.eligibility_text||unavailable}`,citations,groundingStatus:opportunity.eligibility_text?"verified" as const:"not_found" as const};
  if(action==="passport_comparison"||action==="missing_items"){
    if(!passport)return{content:"Supplier Passport access was not granted. Enable passport comparison for this request.",citations,groundingStatus:"not_found" as const};
    const ready=mandatory.filter(requirement=>passport.certifications.some(value=>requirement.toLowerCase().includes(value.toLowerCase()))||passport.documents.some(doc=>doc.verification_status==="verified"&&(requirement.toLowerCase().includes(doc.document_type.toLowerCase())||doc.title.toLowerCase().includes(requirement.toLowerCase()))));
    const missing=mandatory.filter(requirement=>!ready.includes(requirement));const closing=opportunity.deadline_at?new Date(opportunity.deadline_at):null;const expiring=passport.documents.filter(doc=>doc.expires_at&&closing&&new Date(doc.expires_at)<closing);
    return{content:`## Tender readiness\n${mandatory.length} requirements identified\n\n- ${ready.length} Ready\n- ${missing.length} Missing\n- ${expiring.length} Expiring before deadline\n- ${mandatory.length?0:1} Needs Review\n\n### Missing\n${missing.length?missing.map(item=>`- ${item}`).join("\n"):mandatory.length?"None identified from available evidence.":unavailable}\n\n### Expiring\n${expiring.length?expiring.map(item=>`- ${item.title} expires ${date(item.expires_at)}`).join("\n"):"None identified from verified Supplier Passport records."}`,citations,groundingStatus:mandatory.length?"mixed" as const:"not_found" as const};
  }
  if(action==="latest_amendment")return{content:`## Latest amendment\n${unavailable}`,citations,groundingStatus:"not_found" as const};
  if(action==="evaluation_criteria")return{content:`## Evaluation criteria\n${/evaluation/i.test(combined)?"Evaluation language exists in the available document text. Open the cited source sections for the authoritative criteria.":unavailable}`,citations,groundingStatus:/evaluation/i.test(combined)?"mixed" as const:"not_found" as const};
  if(action==="disqualification_risks")return{content:`## Possible disqualification risks\n${mandatory.length?mandatory.map(item=>`- Confirm compliance with: ${item}`).join("\n"):unavailable}\n\nThese are preparation flags, not a legal conclusion. Only the official tender states whether a requirement is disqualifying.`,citations,groundingStatus:mandatory.length?"mixed" as const:"not_found" as const};
  if(action==="clarifications")return{content:`## Items that may need clarification\n${question?`Your question: ${question}\n\n`:""}${unavailable}`,citations,groundingStatus:"not_found" as const};
  return{content:`## Procurement analysis\nI could not find a sufficiently supported answer to “${question||"this question"}” in the available source record or indexed tender sections.\n\n${unavailable}\n\nBidScope AI helps interpret procurement information. Always review the official tender documents before submitting a bid.`,citations,groundingStatus:"not_found" as const};
}

export async function callConfiguredModel(input:{action:string;question:string;opportunity:OpportunityContext;chunks:DocumentChunk[];passport?:Passport|null}){
  const key=process.env.OPENAI_API_KEY;const model=process.env.BIDSCOPE_AI_MODEL;if(!key||!model)return null;
  const context={opportunity:input.opportunity,retrievedSections:input.chunks.map((chunk,index)=>({citation:index+1,page:chunk.page_number,section:chunk.section_label,text:chunk.content})),supplierPassport:input.passport||undefined};
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"developer",content:"You are BidScope's procurement analyst. Use only the supplied JSON context. Never infer a tender requirement without labelling it Inferred by BidScope. Use 'Not found in source' when evidence is absent. Never promise an award, claim insider knowledge, or imply a bid was submitted. Cite retrieved sections as [1], [2]. End by reminding the user to review official tender documents."},{role:"user",content:JSON.stringify({action:input.action,question:input.question,context})}],max_output_tokens:1400})});
  if(!response.ok)throw new Error(`AI provider returned ${response.status}`);const body=await response.json() as {output_text?:string;usage?:{input_tokens?:number;output_tokens?:number}};if(!body.output_text)return null;return{content:body.output_text,usage:body.usage,provider:"openai",model};
}
