import { ai } from "./ai/orchestrator.ts";
import type { AIPlan } from "./ai/types.ts";

export type OpportunityContext={id:string;title:string;summary:string;description:string;buyer_name:string;external_reference:string|null;bidscope_reference:string;eligibility_text:string|null;procurement_method:string|null;contract_type:string|null;estimated_value:number|null;currency:string|null;published_at:string|null;deadline_at:string|null;opening_at?:string|null;clarification_deadline_at?:string|null;official_source_url:string;official_tender_url:string|null;documents_url:string|null;source_name:string;submission_method:string|null;submission_platform:string|null;submission_instructions?:string|null;qualification_requirements?:string|null;bid_security_requirement?:string|null;participation_fee_amount?:number|null;participation_fee_currency?:string|null;procurement_codes?:string[];source_details?:Record<string,unknown>};
export type DocumentChunk={id:string;document_id:string;chunk_index:number;page_number:number|null;section_label:string|null;content:string;document?:{title:string;url:string}};
export type Citation={label:string;documentId?:string;page?:number|null;section?:string|null;url?:string|null};
export type Passport={sectors:string[];services:string[];products:string[];certifications:string[];region:string|null;preferred_regions:string[];preferred_minimum_value:number|null;preferred_maximum_value:number|null;documents:Array<{document_type:string;title:string;expires_at:string|null;verification_status:string}>};

const terms=(value:string)=>[...new Set(value.toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(word=>word.length>2))];
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-GB",{dateStyle:"long",timeStyle:"short",timeZone:"Africa/Accra"}).format(new Date(value)):"Not stated in the available source documents.";

export function retrieveRelevantChunks(chunks:DocumentChunk[],question:string,limit=8){const needles=terms(question);return chunks.map(chunk=>({chunk,score:needles.reduce((sum,word)=>sum+(chunk.content.toLowerCase().includes(word)?1:0),0)})).filter(item=>item.score>0||chunks.length<=limit).sort((a,b)=>b.score-a.score||a.chunk.chunk_index-b.chunk.chunk_index).slice(0,limit).map(item=>item.chunk);}

function sourceCitation(opportunity:OpportunityContext):Citation{return{label:`${opportunity.source_name} opportunity record`,url:opportunity.official_tender_url||opportunity.official_source_url};}
export function dedupeCitations(citations:Citation[]):Citation[]{const seen=new Set<string>();return citations.filter(citation=>{const key=citation.url?`url:${citation.url}`:[citation.documentId||"",citation.page??"",citation.section||"",citation.label].join("|");if(seen.has(key))return false;seen.add(key);return true;});}
function chunkCitations(chunks:DocumentChunk[]):Citation[]{return chunks.map(chunk=>({label:chunk.document?.title||`Tender document section ${chunk.chunk_index+1}`,documentId:chunk.document_id,page:chunk.page_number,section:chunk.section_label,url:chunk.document?.url}));}
export function opportunityEvidenceChunk(opportunity:OpportunityContext):DocumentChunk{const details=Object.entries(opportunity.source_details||{}).filter(([,value])=>value!==null&&value!==undefined&&String(value).trim()).map(([label,value])=>`${label}: ${typeof value==="object"?JSON.stringify(value):String(value)}`);const evidence=[`Tender title: ${opportunity.title}`,`Buyer: ${opportunity.buyer_name}`,`Reference: ${opportunity.external_reference||opportunity.bidscope_reference}`,`Summary: ${opportunity.summary||"Not stated"}`,`Description: ${opportunity.description||"Not stated"}`,`Procurement method: ${opportunity.procurement_method||"Not stated"}`,`Contract type: ${opportunity.contract_type||"Not stated"}`,`Published: ${opportunity.published_at||"Not stated"}`,`Submission deadline: ${opportunity.deadline_at||"Not stated"}`,`Clarification deadline: ${opportunity.clarification_deadline_at||"Not stated"}`,`Bid opening: ${opportunity.opening_at||"Not stated"}`,`Eligibility: ${opportunity.eligibility_text||"Not stated"}`,`Qualification requirements: ${opportunity.qualification_requirements||"Not stated"}`,`Bid security: ${opportunity.bid_security_requirement||"Not stated"}`,`Participation fee: ${opportunity.participation_fee_amount!=null?`${opportunity.participation_fee_currency||""} ${opportunity.participation_fee_amount}`:"Not stated"}`,`Submission: ${opportunity.submission_instructions||opportunity.submission_method||opportunity.submission_platform||"Not stated"}`,`Procurement codes: ${opportunity.procurement_codes?.join(", ")||"Not stated"}`,...details].join("\n");return{id:`opportunity-${opportunity.id}`,document_id:opportunity.id,chunk_index:-1,page_number:null,section_label:"Official opportunity metadata",content:evidence.slice(0,30000),document:{title:`${opportunity.source_name} opportunity record`,url:opportunity.official_tender_url||opportunity.official_source_url}};}
function sourceDetail(opportunity:OpportunityContext,...names:string[]){const canonical=(value:string)=>value.toLowerCase().replace(/\\s\*/g,"").replace(/[^a-z0-9]/g,"");const entries=Object.entries(opportunity.source_details||{});for(const name of names){const normalized=canonical(name);const match=entries.find(([key])=>canonical(key)===normalized);if(match?.[1]!==null&&match?.[1]!==undefined&&String(match[1]).trim())return String(match[1]);}return null;}
function mentions(text:string,patterns:RegExp[]){return patterns.filter(pattern=>pattern.test(text)).map(pattern=>pattern.source.replace(/\\b|\(\?:|\)|\\s\+|\[.*?\]|\+|\?/g," ").replace(/\|/g," / ").trim());}

export function groundedFallback(action:string,question:string,opportunity:OpportunityContext,chunks:DocumentChunk[],passport?:Passport|null){const combined=[opportunity.summary,opportunity.description,opportunity.eligibility_text||"",...chunks.map(chunk=>chunk.content)].join("\n");const citations=dedupeCitations([sourceCitation(opportunity),...chunkCitations(chunks)]);const unavailable="Not stated in the available source documents.";
  if(action==="summary")return{content:[`## Opportunity\n${opportunity.title}`,`**Buyer:** ${opportunity.buyer_name||unavailable}`,`**Reference:** ${opportunity.external_reference||opportunity.bidscope_reference||unavailable}`,`**Scope:** ${opportunity.summary||opportunity.description||unavailable}`,`**Eligibility:** ${opportunity.eligibility_text||unavailable}`,`**Procurement method:** ${opportunity.procurement_method||unavailable}`,`**Contract value:** ${opportunity.estimated_value!=null?`${opportunity.currency||""} ${opportunity.estimated_value.toLocaleString()}`:unavailable}`,`**Key dates:** Published ${date(opportunity.published_at)}; closing ${date(opportunity.deadline_at)}`,`**Submission method:** ${opportunity.submission_method||opportunity.submission_platform||unavailable}`,`**Official source:** ${opportunity.official_tender_url||opportunity.official_source_url}`,`\nBidScope AI helps interpret procurement information. Always review the official tender documents before submitting a bid.`].join("\n\n"),citations,groundingStatus:"verified" as const};
  const mandatory=mentions(combined,[/tax\s+clearance/i,/ssnit\s+clearance/i,/vat\s+(?:certificate|registration)/i,/business\s+registration/i,/audited\s+(?:accounts|financial statements)/i,/bid\s+security/i,/manufacturer(?:'s)?\s+authori[sz]ation/i,/insurance/i,/professional\s+licen[cs]e/i]);
  if(action==="mandatory_documents")return{content:mandatory.length?`## Requirements found\n${mandatory.map(item=>`- ${item}`).join("\n")}\n\nThese terms appear in the available source text. Confirm whether each is explicitly mandatory in the official document.`:`## Mandatory documents\n${unavailable}`,citations,groundingStatus:mandatory.length?"mixed" as const:"not_found" as const};
  if(action==="key_dates")return{content:`## Key dates\n- Publication: ${date(opportunity.published_at)}\n- Submission deadline: ${date(opportunity.deadline_at)}\n- Clarification deadline: ${unavailable}`,citations,groundingStatus:"verified" as const};
  if(action==="eligibility")return{content:`## Eligibility\n${opportunity.eligibility_text||unavailable}`,citations,groundingStatus:opportunity.eligibility_text?"verified" as const:"not_found" as const};
  if(action==="passport_comparison"||action==="missing_items"){
    if(!passport)return{content:"Supplier Passport access was not granted. Enable passport comparison for this request.",citations,groundingStatus:"not_found" as const};
    const ready=mandatory.filter(requirement=>passport.certifications.some(value=>requirement.toLowerCase().includes(value.toLowerCase()))||passport.documents.some(doc=>doc.verification_status==="verified"&&(requirement.toLowerCase().includes(doc.document_type.toLowerCase())||doc.title.toLowerCase().includes(requirement.toLowerCase()))));
    const missing=mandatory.filter(requirement=>!ready.includes(requirement));const closing=opportunity.deadline_at?new Date(opportunity.deadline_at):null;const expiring=passport.documents.filter(doc=>doc.expires_at&&closing&&new Date(doc.expires_at)<closing);
    return{content:`## Tender readiness\n${mandatory.length} requirements identified\n\n- ${ready.length} Ready\n- ${missing.length} Missing\n- ${expiring.length} Expiring before deadline\n- ${mandatory.length?0:1} Needs Review\n\n### Missing\n${missing.length?missing.map(item=>`- ${item}`).join("\n"):mandatory.length?"None identified from available evidence.":unavailable}\n\n### Expiring\n${expiring.length?expiring.map(item=>`- ${item.title} expires ${date(item.expires_at)}`).join("\n"):"None identified from verified Supplier Passport records."}`,citations,groundingStatus:mandatory.length?"mixed" as const:"not_found" as const};
  }
  if(action==="latest_amendment")return{content:`## Latest amendment\n${unavailable}`,citations,groundingStatus:"not_found" as const};
  if(action==="evaluation_criteria")return{content:`## Evaluation criteria\n${/evaluation/i.test(combined)?"Evaluation language exists in the available document text. Open the cited source sections for the authoritative criteria.":unavailable}`,citations,groundingStatus:/evaluation/i.test(combined)?"mixed" as const:"not_found" as const};
  if(action==="disqualification_risks")return{content:`## Possible disqualification risks\n${mandatory.length?mandatory.map(item=>`- Confirm compliance with: ${item}`).join("\n"):unavailable}\n\nThese are preparation flags, not a legal conclusion. Only the official tender states whether a requirement is disqualifying.`,citations,groundingStatus:mandatory.length?"mixed" as const:"not_found" as const};
  if(action==="clarifications")return{content:`## Items that may need clarification\n${question?`Your question: ${question}\n\n`:""}${unavailable}`,citations,groundingStatus:"not_found" as const};
  const hasEvidence=combined.replace(/Not stated/gi,"").trim().length>120;
  if(hasEvidence&&/(explain|summary|summari[sz]e|key requirements?|what is this tender)/i.test(question)){const fee=opportunity.participation_fee_amount!=null?`${opportunity.participation_fee_currency||""} ${opportunity.participation_fee_amount}`:sourceDetail(opportunity,"Payment Amount GHS","Tender Participation Fees");const securityAmount=sourceDetail(opportunity,"Bid Security Amount GHS","Bid Security Amount");const security=[opportunity.bid_security_requirement,securityAmount?`${securityAmount}${sourceDetail(opportunity,"Bid Security Amount Type")==="Percentage"?"%":""}`:null].filter(Boolean).join(" · ");return{content:[`## Tender explained`,`**Opportunity:** ${opportunity.title}`,`**Buyer:** ${opportunity.buyer_name||unavailable}`,`**Reference:** ${opportunity.external_reference||opportunity.bidscope_reference||unavailable}`,`**What is being procured:** ${opportunity.summary||opportunity.description||unavailable}`,`**Procedure:** ${[opportunity.procurement_method,opportunity.contract_type].filter(Boolean).join(" · ")||unavailable}`,`**Evaluation:** ${sourceDetail(opportunity,"Evaluation Mechanism")||unavailable}`,`**Qualifications:** ${opportunity.qualification_requirements||opportunity.eligibility_text||unavailable}`,`**Bid security:** ${security||unavailable}`,`**Participation fee:** ${fee||unavailable}`,`**Closing:** ${date(opportunity.deadline_at)}`,`**Clarification deadline:** ${date(opportunity.clarification_deadline_at||null)}`,`**Bid opening:** ${date(opportunity.opening_at||null)}`,`**How to proceed:** ${opportunity.submission_instructions||opportunity.submission_method||opportunity.submission_platform||unavailable}`,`\nOnly requirements explicitly present in the cited official record are reported here. Obtain and review the full tender pack before deciding to bid.`].join("\n\n"),citations,groundingStatus:"verified" as const};}
  return{content:`## Procurement analysis\nI could not find a sufficiently supported answer to “${question||"this question"}” in the available source record or indexed tender sections.\n\n${unavailable}\n\nBidScope AI helps interpret procurement information. Always review the official tender documents before submitting a bid.`,citations,groundingStatus:"not_found" as const};
}

type ModelInput={action:string;question:string;opportunity:OpportunityContext;chunks:DocumentChunk[];passport?:Passport|null;userId?:string;organizationId?:string;plan?:AIPlan;requestedMode?:"standard"|"deep"};
const analystRules="You are BidScope AI, a careful procurement analyst for Ghanaian businesses. Treat the supplied official opportunity record and tender documents as primary evidence. You may use URL context and Google Search to locate public official buyer, funder, procurement-regulator, tender-document or amendment pages beyond BidScope. Clearly label third-party web material as supplementary and never turn it into a tender requirement unless an official tender source confirms it. Never invent a requirement. Do not infer sole-source, single-source, non-competitive, set-aside, mandatory registration, submission or document requirements from a notice type, procurement label or generic portal guidance. In particular, 'Special Notice' is only a published notice type unless official evidence explicitly states a sole-source or non-competitive procedure. Do not claim that tender documents can be downloaded unless a cited document link is present. Do not expose or describe internal database identifiers. Label interpretations as 'Inferred by BidScope'. Use 'Not found in the reviewed sources' when evidence is absent. Never promise an award, claim insider knowledge, or imply a bid was submitted. Explain the tender in practical language, separate confirmed facts from inferences, cite sources, and end by reminding the user to review the complete official tender pack.";
export function modelContext(input:ModelInput){const{id:_internalId,...opportunity}=input.opportunity;void _internalId;return{opportunity,retrievedSections:input.chunks.map((chunk,index)=>({citation:index+1,page:chunk.page_number,section:chunk.section_label,text:chunk.content})),supplierPassport:input.passport||undefined};}

export function providerAnalysisHasUnsupportedCompetitionClaim(content:string,opportunity:OpportunityContext){
  const evidence=[opportunity.summary,opportunity.description,opportunity.eligibility_text||"",JSON.stringify(opportunity.source_details||{})].join("\n");
  const claim=/sole[-\s]?source|single[-\s]?source|non[-\s]?competitive|without (?:a )?competitive|only one (?:responsible )?vendor|chosen to award without/i.test(content);
  const supported=/sole[-\s]?source|single[-\s]?source|intent to award|non[-\s]?competitive|without competition|only one responsible source/i.test(evidence);
  return claim&&!supported;
}

export async function callConfiguredModel(input:ModelInput){
  const taskType=input.action==="tender_report"?"deep_tender_analysis":input.action==="summary"||input.action==="key_dates"?"tender_summary":"tender_extraction";
  const result=await ai.execute({taskType,userId:input.userId,organizationId:input.organizationId,plan:input.plan||"FREE",requestedMode:input.requestedMode,documentCount:input.chunks.length,estimatedInputTokens:Math.ceil(JSON.stringify(modelContext(input)).length/4),requiresLongContext:input.chunks.length>8,containsCustomerDocuments:false,cacheTtlSeconds:86400,metadata:{feature:"procurement_assistant",action:input.action,supplierPassportMetadata:Boolean(input.passport)},messages:[{role:"system",content:analystRules},{role:"user",content:JSON.stringify({action:input.action,question:input.question,context:modelContext(input)})}]});
  return{content:result.text,citations:result.citations,usage:{input_tokens:result.usage.inputTokens,output_tokens:result.usage.outputTokens},provider:result.provider,model:result.model,orchestration:{source:result.source,complexity:result.complexity,premiumReasoning:result.premiumReasoning,fallbackCount:result.fallbackCount}};
}
