import "server-only";
import {createSign} from "node:crypto";
import {ApiError} from "./api-error";
import {buildSearchOpportunities,type SearchMetric} from "./seo-search-opportunity-engine";
import {supabaseRest} from "./supabase-rest";

const encode=(value:string|Buffer)=>Buffer.from(value).toString("base64url");
const iso=(date:Date)=>date.toISOString().slice(0,10);
const addDays=(date:Date,days:number)=>new Date(date.getTime()+days*86400000);
async function accessToken(){
 const email=process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL,raw=process.env.GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY;
 if(!email||!raw)throw new ApiError(503,"Search Console credentials require owner configuration.","search_console_owner_action_required");
 const now=Math.floor(Date.now()/1000),header=encode(JSON.stringify({alg:"RS256",typ:"JWT"})),claims=encode(JSON.stringify({iss:email,scope:"https://www.googleapis.com/auth/webmasters.readonly",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})),unsigned=`${header}.${claims}`,signer=createSign("RSA-SHA256");signer.update(unsigned);const assertion=`${unsigned}.${signer.sign(raw.replace(/\\n/g,"\n"),"base64url")}`;
 const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}),cache:"no-store"});
 const data=await response.json() as{access_token?:string;error_description?:string};if(!response.ok||!data.access_token)throw new ApiError(503,data.error_description||"Search Console authentication failed.","search_console_auth_failed");return data.access_token;
}
type SearchRow={keys:string[];clicks:number;impressions:number;ctr:number;position:number};
async function query(token:string,site:string,dimensions:string[],startDate:string,endDate:string){const response=await fetch(`https://searchconsole.googleapis.com/webmasters/v3/sites/${encodeURIComponent(site)}/searchAnalytics/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({startDate,endDate,dimensions,rowLimit:25000,dataState:"final"}),cache:"no-store"});const data=await response.json() as{rows?:SearchRow[];error?:{message?:string}};if(!response.ok)throw new ApiError(503,data.error?.message||"Search Console data could not be read.","search_console_sync_failed");return data.rows||[]}
const metric=(type:SearchMetric["dimensionType"],row:SearchRow):SearchMetric=>({dimensionType:type,value:row.keys[0]||"unknown",secondaryValue:row.keys[1]||"",clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,position:row.position});
async function queryWindow(token:string,site:string,startDate:string,endDate:string){const[pages,queries,queryPages]=await Promise.all([query(token,site,["page"],startDate,endDate),query(token,site,["query"],startDate,endDate),query(token,site,["query","page"],startDate,endDate)]);return[...pages.map(row=>metric("page",row)),...queries.map(row=>metric("query",row)),...queryPages.map(row=>metric("query_page",row))]}

export async function syncSearchConsole(userId:string|null){
 const{data:settings}=await supabaseRest<Array<{search_console_property:string;search_opportunity_min_impressions?:number}>>("seo_settings?singleton_key=eq.default&select=search_console_property,search_opportunity_min_impressions&limit=1");
 const site=settings[0]?.search_console_property||"sc-domain:bidscopeghana.com",minimum=Math.max(25,Number(settings[0]?.search_opportunity_min_impressions||100)),token=await accessToken(),end=new Date(Date.now()-86400000),currentStart=addDays(end,-27),previousEnd=addDays(currentStart,-1),previousStart=addDays(previousEnd,-27),baselineStart=addDays(end,-89);
 const windows={current:{startDate:iso(currentStart),endDate:iso(end),days:28,role:"current"},previous:{startDate:iso(previousStart),endDate:iso(previousEnd),days:28,role:"previous"},baseline:{startDate:iso(baselineStart),endDate:iso(end),days:90,role:"baseline"}} as const;
 const{data:run}=await supabaseRest<Array<{id:string}>>("seo_sync_runs",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({source:"search_console",status:"running",metadata:{site,windows,minimumImpressions:minimum}})}),runId=run[0]?.id;
 try{
  const[current,previous,ninetyDay,countries,devices,appearances]=await Promise.all([
    queryWindow(token,site,windows.current.startDate,windows.current.endDate),queryWindow(token,site,windows.previous.startDate,windows.previous.endDate),queryWindow(token,site,windows.baseline.startDate,windows.baseline.endDate),
    query(token,site,["country"],windows.current.startDate,windows.current.endDate),query(token,site,["device"],windows.current.startDate,windows.current.endDate),query(token,site,["searchAppearance"],windows.current.startDate,windows.current.endDate),
  ]);
  const windowPairs:[[typeof windows.current,SearchMetric[]],[typeof windows.previous,SearchMetric[]],[typeof windows.baseline,SearchMetric[]]]=[[windows.current,current],[windows.previous,previous],[windows.baseline,ninetyDay]];
  const windowRows=windowPairs.flatMap(([window,rows])=>rows.map(row=>({period_start:window.startDate,period_end:window.endDate,window_days:window.days,window_role:window.role,dimension_type:row.dimensionType,dimension_value:row.value,secondary_value:row.secondaryValue||"",clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,average_position:row.position,synced_at:new Date().toISOString()})));
  if(windowRows.length)await supabaseRest("seo_search_performance_windows?on_conflict=period_start,period_end,window_role,dimension_type,dimension_value,secondary_value",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify(windowRows)});
  const currentPages=current.filter(row=>row.dimensionType==="page"),currentQueries=current.filter(row=>row.dimensionType==="query");
  if(currentPages.length)await supabaseRest("seo_page_metrics?on_conflict=page_url,metric_date,source",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify(currentPages.map(row=>({page_url:row.value,metric_date:windows.current.endDate,page_type:row.value.includes("/tenders/")?"tender_listing":row.value.includes("/opportunities/")?"tender_detail":row.value.includes("/resources/")?"resource":"other",clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,average_position:row.position,source:"search_console"})))});
  for(const row of currentQueries){const keyword=row.value.trim();if(!keyword)continue;await supabaseRest("seo_keywords?on_conflict=normalized_keyword,country_code",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({keyword,country_code:"GH",cluster:"Search Console discoveries",status:"tracking",current_position:row.position,impressions:row.impressions,clicks:row.clicks,ctr:row.ctr,opportunity_score:Math.round(Math.min(100,row.impressions*Math.max(0,1-row.ctr)*.02)),last_checked_at:new Date().toISOString(),created_by:userId})})}
  const dimensionRows=[...countries.map(row=>({type:"country",row})),...devices.map(row=>({type:"device",row})),...appearances.map(row=>({type:"search_appearance",row}))].map(({type,row})=>({metric_date:windows.current.endDate,dimension_type:type,dimension_value:row.keys[0]||"unknown",secondary_value:row.keys[1]||"",clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,average_position:row.position}));
  if(dimensionRows.length)await supabaseRest("seo_search_dimensions?on_conflict=metric_date,dimension_type,dimension_value,secondary_value",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify(dimensionRows)});
  const{data:conversionEvents}=await supabaseRest<Array<{page_path:string|null}>>(`seo_conversion_events?created_at=gte.${windows.current.startDate}T00:00:00Z&event_name=in.(sign_up,buyer_signup,supplier_signup,subscription_started,subscription_completed,subscription_paid,tender_watch,alert_created,bid_started,bid_submitted)&select=page_path&limit=10000`),pageConversions:Record<string,number>={};
  for(const event of conversionEvents){const path=String(event.page_path||"");if(!path)continue;pageConversions[path]=(pageConversions[path]||0)+1;try{const absolute=new URL(path,site.startsWith("http")?site:"https://www.bidscopeghana.com").toString();pageConversions[absolute]=(pageConversions[absolute]||0)+1}catch{}}
  const opportunities=buildSearchOpportunities({current,previous,ninetyDay,minimumImpressions:minimum,pageConversions});
  const{data:existing}=await supabaseRest<Array<{opportunity_key:string;state:string;snoozed_until:string|null}>>("seo_search_opportunities?select=opportunity_key,state,snoozed_until&limit=10000"),existingMap=new Map(existing.map(item=>[item.opportunity_key,item]));
  const manualStates=new Set(["READY_TO_OPTIMISE","OPTIMISATION_IN_PROGRESS","MEASURING_RESULT","STABLE"]),detectedAt=new Date().toISOString();
  if(opportunities.length)await supabaseRest("seo_search_opportunities?on_conflict=opportunity_key",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify(opportunities.map(item=>{const prior=existingMap.get(item.opportunityKey),snoozed=prior?.snoozed_until&&new Date(prior.snoozed_until)>new Date();return{opportunity_key:item.opportunityKey,opportunity_type:item.opportunityType,state:manualStates.has(prior?.state||"")?prior?.state:snoozed?"WATCH":item.state,query:item.query,page_url:item.pageUrl,title:item.title,explanation:item.explanation,recommended_action:item.recommendedAction,priority_score:item.priorityScore,current_metrics:item.currentMetrics||{},previous_metrics:item.previousMetrics||{},ninety_day_metrics:item.ninetyDayMetrics||{},evidence:item.evidence,last_detected_at:detectedAt,snoozed_until:prior?.snoozed_until||null}}))});
  const currentMap=new Map(current.map(row=>[`${row.dimensionType}|${row.value}|${row.secondaryValue||""}`.toLowerCase(),row])),{data:dueExperiments}=await supabaseRest<Array<{id:string;search_opportunity_id:string;page_url:string}>>(`seo_experiments?status=eq.running&measurement_ends_at=lte.${new Date().toISOString()}&search_opportunity_id=not.is.null&select=id,search_opportunity_id,page_url&limit=500`);
  for(const experiment of dueExperiments){const{data:items}=await supabaseRest<Array<{query:string|null;page_url:string|null;opportunity_type:string}>>(`seo_search_opportunities?id=eq.${experiment.search_opportunity_id}&select=query,page_url,opportunity_type&limit=1`),item=items[0];if(!item)continue;const after=[...currentMap.values()].find(row=>row.value===item.query||row.value===item.page_url||row.secondaryValue===item.page_url);await supabaseRest(`seo_experiments?id=eq.${experiment.id}`,{method:"PATCH",body:JSON.stringify({status:"completed",ends_at:new Date().toISOString(),after_metrics:after||{},result:{measurementWindowDays:28,source:"search_console",reviewRequired:true},decision:"inconclusive"})});await supabaseRest(`seo_search_opportunities?id=eq.${experiment.search_opportunity_id}`,{method:"PATCH",body:JSON.stringify({state:"NEEDS_REVIEW"})})}
  const processed=windowRows.length+dimensionRows.length+opportunities.length,completedAt=new Date().toISOString();
  await supabaseRest("seo_settings?singleton_key=eq.default",{method:"PATCH",body:JSON.stringify({search_console_connected:true,search_console_last_synced_at:completedAt,updated_by:userId,updated_at:completedAt})});if(runId)await supabaseRest(`seo_sync_runs?id=eq.${runId}`,{method:"PATCH",body:JSON.stringify({status:"succeeded",completed_at:completedAt,rows_processed:processed,metadata:{site,windows,minimumImpressions:minimum,opportunities:opportunities.length}})});
  return{pages:currentPages.length,queries:currentQueries.length,searchOpportunities:opportunities.length,countries:countries.length,devices:devices.length,searchAppearances:appearances.length,startDate:windows.current.startDate,endDate:windows.current.endDate,windows};
 }catch(error){if(runId)await supabaseRest(`seo_sync_runs?id=eq.${runId}`,{method:"PATCH",body:JSON.stringify({status:"failed",completed_at:new Date().toISOString(),error_summary:error instanceof Error?error.message:"Search Console sync failed"})});throw error}
}
