import { createSign } from "node:crypto";
import { ApiError } from "./api-error";
import { supabaseRest } from "./supabase-rest";
const encode=(value:string|Buffer)=>Buffer.from(value).toString("base64url");
async function accessToken(){
 const email=process.env.GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL,raw=process.env.GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY;
 if(!email||!raw)throw new ApiError(503,"Search Console credentials require owner configuration.","search_console_owner_action_required");
 const now=Math.floor(Date.now()/1000),header=encode(JSON.stringify({alg:"RS256",typ:"JWT"})),claims=encode(JSON.stringify({iss:email,scope:"https://www.googleapis.com/auth/webmasters.readonly",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600})),unsigned=`${header}.${claims}`,signer=createSign("RSA-SHA256");signer.update(unsigned);const assertion=`${unsigned}.${signer.sign(raw.replace(/\\n/g,"\n"),"base64url")}`;
 const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}),cache:"no-store"});
 const data=await response.json() as{access_token?:string;error_description?:string};if(!response.ok||!data.access_token)throw new ApiError(503,data.error_description||"Search Console authentication failed.","search_console_auth_failed");return data.access_token;
}
type SearchRow={keys:string[];clicks:number;impressions:number;ctr:number;position:number};
async function query(token:string,site:string,dimensions:string[],startDate:string,endDate:string){const response=await fetch(`https://searchconsole.googleapis.com/webmasters/v3/sites/${encodeURIComponent(site)}/searchAnalytics/query`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({startDate,endDate,dimensions,rowLimit:25000,dataState:"final"}),cache:"no-store"});const data=await response.json() as{rows?:SearchRow[];error?:{message?:string}};if(!response.ok)throw new ApiError(503,data.error?.message||"Search Console data could not be read.","search_console_sync_failed");return data.rows||[]}
export async function syncSearchConsole(userId:string|null){
 const{data:settings}=await supabaseRest<Array<{search_console_property:string}>>("seo_settings?singleton_key=eq.default&select=search_console_property&limit=1");const site=settings[0]?.search_console_property||"sc-domain:bidscopeghana.com",token=await accessToken(),end=new Date(Date.now()-86400000),start=new Date(end.getTime()-89*86400000),startDate=start.toISOString().slice(0,10),endDate=end.toISOString().slice(0,10);
 const{data:run}=await supabaseRest<Array<{id:string}>>("seo_sync_runs",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({source:"search_console",status:"running",metadata:{site,startDate,endDate}})}),runId=run[0]?.id;
 try{
  const[pages,queries,countries,devices,appearances,queryPages]=await Promise.all([
    query(token,site,["page"],startDate,endDate),query(token,site,["query"],startDate,endDate),
    query(token,site,["country"],startDate,endDate),query(token,site,["device"],startDate,endDate),
    query(token,site,["searchAppearance"],startDate,endDate),query(token,site,["query","page"],startDate,endDate),
  ]);
  if(pages.length)await supabaseRest("seo_page_metrics?on_conflict=page_url,metric_date,source",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify(pages.map(row=>({page_url:row.keys[0],metric_date:endDate,page_type:row.keys[0].includes("/tenders/")?"tender_listing":row.keys[0].includes("/opportunities/")?"tender_detail":row.keys[0].includes("/resources/")?"resource":"other",clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,average_position:row.position,source:"search_console"})))});
  for(const row of queries){const keyword=row.keys[0]?.trim();if(!keyword)continue;await supabaseRest("seo_keywords?on_conflict=normalized_keyword,country_code",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({keyword,country_code:"GH",cluster:"Search Console discoveries",status:"tracking",current_position:row.position,impressions:row.impressions,clicks:row.clicks,ctr:row.ctr,opportunity_score:Math.round(Math.min(100,row.impressions*Math.max(0,1-row.ctr)*.02)),last_checked_at:new Date().toISOString(),created_by:userId})})}
  const dimensionRows=[...countries.map(row=>({type:"country",row})),...devices.map(row=>({type:"device",row})),...appearances.map(row=>({type:"search_appearance",row})),...queryPages.map(row=>({type:"query_page",row}))].map(({type,row})=>({metric_date:endDate,dimension_type:type,dimension_value:row.keys[0]||"unknown",secondary_value:row.keys[1]||"",clicks:row.clicks,impressions:row.impressions,ctr:row.ctr,average_position:row.position}));
  if(dimensionRows.length)await supabaseRest("seo_search_dimensions?on_conflict=metric_date,dimension_type,dimension_value,secondary_value",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify(dimensionRows)});
  const processed=pages.length+queries.length+dimensionRows.length,completedAt=new Date().toISOString();
  await supabaseRest("seo_settings?singleton_key=eq.default",{method:"PATCH",body:JSON.stringify({search_console_connected:true,search_console_last_synced_at:completedAt,updated_by:userId,updated_at:completedAt})});if(runId)await supabaseRest(`seo_sync_runs?id=eq.${runId}`,{method:"PATCH",body:JSON.stringify({status:"succeeded",completed_at:completedAt,rows_processed:processed})});return{pages:pages.length,queries:queries.length,countries:countries.length,devices:devices.length,searchAppearances:appearances.length,queryPages:queryPages.length,startDate,endDate};
 }catch(error){if(runId)await supabaseRest(`seo_sync_runs?id=eq.${runId}`,{method:"PATCH",body:JSON.stringify({status:"failed",completed_at:new Date().toISOString(),error_summary:error instanceof Error?error.message:"Search Console sync failed"})});throw error}
}
