import"server-only";
import{cache}from"react";
import{editorialArticles}from"@/lib/content/editorial-articles";
import{supabaseRest}from"./supabase-rest";
export type PublishedSeoContent={id:string;title:string;slug:string;excerpt:string|null;body:string|null;seo_title:string|null;meta_description:string|null;canonical_url:string|null;featured_image_url:string|null;author_name:string|null;author_role:string|null;author_bio:string|null;cluster:string;primary_keyword:string|null;search_intent:string;target_audience:string;tags:string[];related_tender_categories:string[];cta_type:string;published_at:string|null;updated_at:string;recommended_internal_links:string[]};
const fields="id,title,slug,excerpt,body,seo_title,meta_description,canonical_url,featured_image_url,author_name,author_role,author_bio,cluster,primary_keyword,search_intent,target_audience,tags,related_tender_categories,cta_type,published_at,updated_at,recommended_internal_links";
export const getPublishedSeoContent=cache(async(slug:string)=>{try{const{data}=await supabaseRest<PublishedSeoContent[]>(`seo_content_items?slug=eq.${encodeURIComponent(slug.slice(0,140))}&status=in.(published,refresh_due)&indexable=eq.true&select=${fields}&limit=1`);if(data[0])return data[0]}catch{}return editorialArticles.find(item=>item.slug===slug)||null});
export const listPublishedSeoContent=cache(async(limit=1000)=>{let managed:PublishedSeoContent[]=[];try{const{data}=await supabaseRest<PublishedSeoContent[]>(`seo_content_items?status=in.(published,refresh_due)&indexable=eq.true&select=${fields}&order=published_at.desc.nullslast&limit=${Math.min(limit,1000)}`);managed=data}catch{}const merged=new Map(editorialArticles.map(item=>[item.slug,item]));managed.forEach(item=>merged.set(item.slug,item));return[...merged.values()].sort((a,b)=>new Date(b.published_at||b.updated_at).getTime()-new Date(a.published_at||a.updated_at).getTime()).slice(0,Math.min(limit,1000))});
export async function listRelatedSeoContent(item:PublishedSeoContent,limit=3){const items=await listPublishedSeoContent(100);return items.filter(candidate=>candidate.slug!==item.slug).map(candidate=>({candidate,score:(candidate.cluster===item.cluster?5:0)+candidate.tags.filter(tag=>item.tags.includes(tag)).length*2+(candidate.target_audience===item.target_audience?1:0)})).sort((a,b)=>b.score-a.score||a.candidate.title.localeCompare(b.candidate.title)).slice(0,limit).map(result=>result.candidate)}
