export const SEARCH_OPPORTUNITY_TYPES=["LOW_CTR","NEAR_PAGE_ONE","DECLINING_TRAFFIC","RISING_QUERY","CONTENT_GAP","QUERY_MISMATCH","CANNIBALISATION","HIGH_IMPRESSIONS_LOW_CONVERSIONS","STRONG_PAGE_EXPANSION","INTERNAL_LINK_OPPORTUNITY"] as const;
export const SEARCH_OPPORTUNITY_STATES=["NEW","DATA_COLLECTING","WATCH","READY_TO_OPTIMISE","OPTIMISATION_IN_PROGRESS","MEASURING_RESULT","STABLE","NEEDS_REVIEW"] as const;
export type SearchOpportunityType=typeof SEARCH_OPPORTUNITY_TYPES[number];
export type SearchOpportunityState=typeof SEARCH_OPPORTUNITY_STATES[number];
export type SearchMetric={dimensionType:"page"|"query"|"query_page";value:string;secondaryValue?:string;clicks:number;impressions:number;ctr:number;position:number};
export type SearchOpportunity={opportunityKey:string;opportunityType:SearchOpportunityType;state:SearchOpportunityState;query:string|null;pageUrl:string|null;title:string;explanation:string;recommendedAction:string;priorityScore:number;currentMetrics:SearchMetric|null;previousMetrics:SearchMetric|null;ninetyDayMetrics:SearchMetric|null;evidence:Record<string,unknown>};

const key=(row:SearchMetric)=>`${row.dimensionType}|${row.value}|${row.secondaryValue||""}`;
const stableKey=(type:SearchOpportunityType,row:SearchMetric)=>`${type}|${key(row)}`.toLowerCase();
const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value)));
const mapRows=(rows:SearchMetric[])=>new Map(rows.map(row=>[key(row),row]));
const detail=(row:SearchMetric)=>row.dimensionType==="query_page"?{query:row.value,pageUrl:row.secondaryValue||null}:row.dimensionType==="query"?{query:row.value,pageUrl:null}:{query:null,pageUrl:row.value};

function opportunity(type:SearchOpportunityType,row:SearchMetric,previous:SearchMetric|null,ninety:SearchMetric|null,title:string,explanation:string,recommendedAction:string,score:number,evidence:Record<string,unknown>={}):SearchOpportunity{
  const identity=detail(row);
  return{opportunityKey:stableKey(type,row),opportunityType:type,state:"NEW",...identity,title,explanation,recommendedAction,priorityScore:clamp(score),currentMetrics:row,previousMetrics:previous,ninetyDayMetrics:ninety,evidence:{minimumEvidence:"28-day current, preceding 28-day and 90-day windows",...evidence}};
}

export function buildSearchOpportunities(input:{current:SearchMetric[];previous:SearchMetric[];ninetyDay:SearchMetric[];minimumImpressions?:number;pageConversions?:Record<string,number>}){
  const minimum=Math.max(25,input.minimumImpressions||100),previous=mapRows(input.previous),ninety=mapRows(input.ninetyDay),results:SearchOpportunity[]=[];
  const currentQueries=new Map<string,SearchMetric[]>();
  for(const row of input.current){
    const before=previous.get(key(row))||null,baseline=ninety.get(key(row))||null;
    if(row.dimensionType==="query_page"){const rows=currentQueries.get(row.value)||[];rows.push(row);currentQueries.set(row.value,rows)}
    if(row.impressions<minimum)continue;
    if(row.ctr<0.02&&row.position<=20)results.push(opportunity("LOW_CTR",row,before,baseline,"High visibility, low click-through rate",`${row.impressions} impressions generated a ${(row.ctr*100).toFixed(1)}% CTR at average position ${row.position.toFixed(1)}.`,`Review the title and description against the search intent, then approve a measured metadata experiment.`,50+Math.min(30,row.impressions/minimum*6)+(row.position<=10?12:0),{threshold:minimum,ctrThreshold:0.02}));
    if(row.position>=8&&row.position<=15)results.push(opportunity("NEAR_PAGE_ONE",row,before,baseline,"Ranking close to page one",`Average position ${row.position.toFixed(1)} is within the page-one opportunity band.`,`Strengthen the page section that answers this query and add relevant internal links after human review.`,72+Math.min(20,row.impressions/minimum*4),{positionBand:[8,15]}));
    if(before&&before.impressions>=minimum&&row.clicks<before.clicks*.7)results.push(opportunity("DECLINING_TRAFFIC",row,before,baseline,"Organic clicks declined",`Clicks fell from ${before.clicks} to ${row.clicks} compared with the preceding 28 days.`,`Check ranking, SERP and content changes before deciding whether to refresh or leave the page unchanged.`,75+Math.min(20,(before.clicks-row.clicks)*2),{declineRatio:before.clicks?row.clicks/before.clicks:0}));
    if(row.dimensionType!=="page"&&before&&row.impressions>before.impressions*1.3&&row.clicks>=before.clicks)results.push(opportunity("RISING_QUERY",row,before,baseline,"Search demand is rising",`Impressions increased from ${before.impressions} to ${row.impressions} while clicks did not decline.`,`Confirm that the landing page fully answers the emerging query and consider a reviewed content expansion.`,68+Math.min(25,(row.impressions/Math.max(1,before.impressions)-1)*30),{growthRatio:row.impressions/Math.max(1,before.impressions)}));
    if(row.dimensionType==="query_page"&&row.position>15&&row.ctr<0.01)results.push(opportunity("QUERY_MISMATCH",row,before,baseline,"Query and landing page may be misaligned",`The query reaches ${row.secondaryValue} but averages position ${row.position.toFixed(1)} with low engagement.`,`Compare the query intent with the landing page. Re-map it or create a focused reviewed section only if evidence supports the change.`,58+Math.min(25,row.impressions/minimum*5),{ctrThreshold:0.01,positionThreshold:15}));
    if(row.dimensionType==="page"&&row.position<=10&&before&&row.clicks>before.clicks*1.2)results.push(opportunity("STRONG_PAGE_EXPANSION",row,before,baseline,"Strong page has expansion potential",`This page ranks at ${row.position.toFixed(1)} and clicks grew from ${before.clicks} to ${row.clicks}.`,`Review related queries and add source-grounded supporting sections without weakening the page's current intent.`,75+Math.min(20,row.clicks-before.clicks),{growthRatio:row.clicks/Math.max(1,before.clicks)}));
    if(row.dimensionType==="page"&&row.position>=8&&row.position<=20)results.push(opportunity("INTERNAL_LINK_OPPORTUNITY",row,before,baseline,"Internal links may support this page",`The page has proven impressions and sits at average position ${row.position.toFixed(1)}.`,`Identify relevant high-authority BidScope pages and propose contextual internal links for approval.`,62+Math.min(25,row.impressions/minimum*4),{positionBand:[8,20]}));
    if(row.dimensionType==="page"&&row.impressions>=minimum*5&&Number(input.pageConversions?.[row.value]||0)===0)results.push(opportunity("HIGH_IMPRESSIONS_LOW_CONVERSIONS",row,before,baseline,"High organic visibility without recorded conversions",`${row.impressions} impressions produced no consented conversion event for this landing page in the current window.`,`Review intent, access boundaries and calls to action before proposing a measured conversion experiment.`,70+Math.min(25,row.impressions/(minimum*2)),{conversionCount:0,conversionEvidence:"consented BidScope conversion events"}));
  }
  const queryPages=new Set(input.current.filter(row=>row.dimensionType==="query_page").map(row=>row.value));for(const row of input.current.filter(row=>row.dimensionType==="query"&&row.impressions>=minimum&&!queryPages.has(row.value)))results.push(opportunity("CONTENT_GAP",row,previous.get(key(row))||null,ninety.get(key(row))||null,"Search demand lacks a stable mapped page",`The query produced ${row.impressions} impressions but no query-page row survived the current evidence set.`,`Inspect Search Console directly, confirm the intent and map or plan content only after human review.`,65+Math.min(25,row.impressions/minimum*4),{threshold:minimum}));
  for(const [query,rows] of currentQueries){const qualified=rows.filter(row=>row.impressions>=minimum).sort((a,b)=>b.impressions-a.impressions);if(qualified.length>1){const total=qualified.reduce((sum,row)=>sum+row.impressions,0),leader=qualified[0];results.push(opportunity("CANNIBALISATION",leader,previous.get(key(leader))||null,ninety.get(key(leader))||null,"Multiple pages compete for one query",`${qualified.length} pages received at least ${minimum} impressions for “${query}”.`,`Review intent and consolidate, differentiate or re-link pages only after confirming the pages genuinely compete.`,80+Math.min(15,qualified.length*3),{competingPages:qualified.map(row=>({page:row.secondaryValue,impressions:row.impressions,position:row.position})),totalImpressions:total}))}}
  const deduped=new Map<string,SearchOpportunity>();for(const item of results){const existing=deduped.get(item.opportunityKey);if(!existing||item.priorityScore>existing.priorityScore)deduped.set(item.opportunityKey,item)}
  return[...deduped.values()].sort((a,b)=>b.priorityScore-a.priorityScore);
}
