"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Building2, CalendarDays, CircleCheck, FileText, Landmark, MapPin, Search, WalletCards } from "lucide-react";

type Opportunity = {
  id:string; slug:string; bidscope_reference:string; title:string; summary:string; description:string; buyer_name:string; buyer_type:string|null; country:string; region:string|null; sector:string|null; category:string; subcategory:string|null; procurement_method:string|null; contract_type:string|null; currency:string|null; estimated_value:number|null; minimum_value:number|null; maximum_value:number|null; published_at:string|null; deadline_at:string|null; status:string; source_name:string; external_reference:string|null; official_source_url:string; official_tender_url:string|null; official_submission_url:string|null; submission_platform:string|null; submission_method:string|null; requires_registration:boolean; registration_url:string|null; funding_source:string; funding_agency:string|null; eligibility_text:string|null; eligibility_country:string|null; documents_url:string|null; contact_name:string|null; contact_email:string|null; contact_phone:string|null; last_verified_at:string|null; data_confidence:string; verification_status:string;
};
type Result = { data:Opportunity[]; pagination:{page:number;pageSize:number;total:number|null} };

const date = (value:string|null) => value ? new Intl.DateTimeFormat("en-GB", {dateStyle:"medium"}).format(new Date(value)) : "Not provided";
const money = (item:Opportunity) => item.estimated_value != null ? `${item.currency || ""} ${item.estimated_value.toLocaleString()}`.trim() : item.minimum_value != null || item.maximum_value != null ? `${item.currency || ""} ${item.minimum_value?.toLocaleString() || "—"} – ${item.maximum_value?.toLocaleString() || "—"}`.trim() : "Not disclosed";

export function LiveOpportunityFeed() {
  const [items,setItems]=useState<Opportunity[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [page,setPage]=useState(1); const [total,setTotal]=useState<number|null>(null);
  async function load(nextPage:number, append=false){setLoading(true);setError("");try{const token=window.localStorage.getItem("bidscope_access_token");if(!token)throw new Error("Sign in is required.");const response=await fetch(`/api/opportunities?view=live&page=${nextPage}&pageSize=50&sort=newest`,{headers:{Authorization:`Bearer ${token}`}});const body=await response.json() as Result & {error?:string};if(!response.ok)throw new Error(body.error||"Live opportunities could not be loaded.");const open=body.data.filter(item=>["OPEN","CLOSING_SOON"].includes(item.status.toUpperCase()));setItems(current=>append?[...current,...open]:open);setTotal(body.pagination.total);setPage(nextPage);}catch(caught){setError(caught instanceof Error?caught.message:"Live opportunities could not be loaded.");}finally{setLoading(false);}}
  useEffect(()=>{void Promise.resolve().then(()=>load(1));},[]);
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return term?items.filter(item=>[item.title,item.buyer_name,item.source_name,item.sector,item.category,item.external_reference].some(value=>value?.toLowerCase().includes(term))):items;},[items,query]);
  const more=total!=null && items.length<total;
  return <>
    <section className="border-b border-[#123f32]/10 bg-[#103f32] text-white"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-6 lg:px-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full border border-[#69ddb0]/25 bg-[#69ddb0]/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[.14em] text-[#8ce0bd]"><span className="size-2 animate-pulse rounded-full bg-[#69ddb0]"/>Live procurement feed</span><h1 className="serif mt-4 text-4xl font-medium tracking-[-.04em] sm:text-5xl">Open opportunities, in one place.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-white/68">Every record below is currently marked open and links back to its official source.</p></div><label className="flex h-12 w-full items-center gap-3 rounded-xl border border-white/15 bg-white/10 px-4 lg:max-w-sm"><Search size={18} className="text-[#8ce0bd]"/><input value={query} onChange={event=>setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-white/50" placeholder="Search live opportunities…"/></label></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="mb-5 flex items-center justify-between"><p className="text-sm font-semibold text-[#4f6b60]">{loading && !items.length ? "Loading live records…" : `${visible.length} live opportunities shown`}</p><a href="/profile" className="text-sm font-bold text-[#116149] hover:underline">Improve matches in Profile</a></div>
      {error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{error}</div>}
      <div className="grid gap-5">{visible.map(item=><article key={item.id} className="overflow-hidden rounded-[24px] border border-[#17362d]/10 bg-[#fffdf8] shadow-[0_12px_40px_rgba(19,62,49,.06)]"><div className="border-b border-[#17362d]/8 px-5 py-5 sm:px-6"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-[#dcf7e9] px-3 py-1.5 text-xs font-extrabold uppercase tracking-[.12em] text-[#087449]"><span className="size-2 animate-pulse rounded-full bg-[#0aa76d]"/>Live</span><span className="rounded-full bg-[#eef1ec] px-3 py-1.5 text-xs font-bold text-[#49675c]">{item.source_name}</span><span className="text-xs font-semibold text-[#72837c]">Verified {date(item.last_verified_at)}</span></div><h2 className="mt-4 text-xl font-extrabold leading-7 text-[#17362d] sm:text-2xl">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[#60756c] sm:text-base">{item.summary||item.description||"Open the official record for the full procurement notice."}</p></div>
        <div className="grid gap-px bg-[#17362d]/8 sm:grid-cols-2 lg:grid-cols-4">{[[Building2,"Buyer",item.buyer_name||"Not provided"],[CalendarDays,"Deadline",date(item.deadline_at)],[WalletCards,"Estimated value",money(item)],[MapPin,"Location",[item.region,item.country].filter(Boolean).join(", ")||"Ghana"],[Landmark,"Funding",item.funding_agency||item.funding_source||"Not provided"],[FileText,"Procurement method",item.procurement_method||"Not provided"],[CircleCheck,"Eligibility",item.eligibility_text||item.eligibility_country||"See official notice"],[FileText,"Reference",item.external_reference||item.bidscope_reference]].map(([Icon,label,value])=><div key={String(label)} className="bg-[#fffdf8] p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#71817a]"><Icon size={14} className="text-[#16805e]"/>{label as string}</div><p className="mt-2 break-words text-sm font-semibold leading-5 text-[#294d41]">{value as string}</p></div>)}</div>
        <div className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex flex-wrap gap-x-5 gap-y-1 text-xs text-[#6c7d75]"><span>{item.category}{item.subcategory?` · ${item.subcategory}`:""}</span><span>{item.contract_type||"Contract type not provided"}</span><span>Published {date(item.published_at)}</span>{item.requires_registration&&<span>Registration required</span>}</div><div className="flex flex-wrap gap-2"><a href={`/opportunities/${item.slug}`} className="inline-flex h-10 items-center rounded-full border border-[#17362d]/15 px-4 text-sm font-bold text-[#315b4e]">Full details</a><a href={item.official_tender_url||item.official_source_url} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 rounded-full bg-[#116149] px-4 text-sm font-bold text-white">Official notice<ArrowUpRight size={15}/></a></div></div></article>)}
        {!loading&&!visible.length&&!error&&<div className="rounded-[24px] border border-dashed border-[#17362d]/20 bg-white/60 p-12 text-center"><CircleCheck className="mx-auto text-[#16805e]"/><h2 className="mt-4 text-xl font-bold text-[#17362d]">No open opportunities match</h2><p className="mt-2 text-sm text-[#65776f]">Try a broader search. Closed records are never shown here.</p></div>}
        {loading&&<div className="h-48 animate-pulse rounded-[24px] bg-white"/>}</div>{more&&<button onClick={()=>void load(page+1,true)} disabled={loading} className="mx-auto mt-7 flex h-11 items-center rounded-full border border-[#17362d]/15 bg-white px-6 text-sm font-bold text-[#17362d] disabled:opacity-50">{loading?"Loading…":"Load more live opportunities"}</button>}
    </section>
  </>;
}
