/* eslint-disable react-hooks/exhaustive-deps */
"use client";
import Link from "next/link";
import { Bell, CheckCheck, Trash2 } from "lucide-react";
import { useEffect,useState } from "react";
type Notice={id:string;type:string;title:string;message:string;related_url:string|null;priority:string;match_score:number|null;match_reasons:string[];read_at:string|null;created_at:string};
const filters=[["all","All"],["opportunity_match","Matches"],["deadline","Deadlines"],["buyer_activity","Buyers"],["award","Awards"],["document_expiry","Documents"],["system","System"]];
export function NotificationCentre(){const[items,setItems]=useState<Notice[]>([]);const[filter,setFilter]=useState("all");const[message,setMessage]=useState("Loading notifications…");
  async function load(){const token=localStorage.getItem("bidscope_access_token");if(!token){setMessage("Sign in to view your notification centre.");return;}const response=await fetch(`/api/notifications?type=${filter}`,{headers:{Authorization:`Bearer ${token}`}});const body=await response.json() as {data?:Notice[];error?:string};if(!response.ok){setMessage(body.error||"Notifications could not be loaded.");return;}setItems(body.data||[]);setMessage("");}
  useEffect(()=>{void Promise.resolve().then(load);},[filter]);async function update(id:string,body:Record<string,boolean>){const token=localStorage.getItem("bidscope_access_token");if(!token)return;await fetch(`/api/notifications/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});void load();}
  async function markAll(){const token=localStorage.getItem("bidscope_access_token");if(!token)return;await fetch("/api/notifications",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({markAllRead:true})});void load();}
  return <section className="mx-auto max-w-5xl px-5 py-10 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#16805e]">Alert centre</p><h1 className="serif mt-2 text-4xl text-[#17362d] sm:text-5xl">Procurement signals that matter.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#64766e]">Matches, changes and deadlines are linked to their underlying BidScope record.</p></div><button onClick={markAll} className="inline-flex h-10 items-center justify-center gap-2 rounded-full border bg-white px-4 text-xs font-bold text-[#116149]"><CheckCheck size={15}/>Mark all read</button></div><div className="mt-7 flex gap-2 overflow-x-auto pb-2">{filters.map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold ${filter===value?"bg-[#116149] text-white":"border bg-white text-[#526a61]"}`}>{label}</button>)}</div>{message&&<div className="mt-8 rounded-2xl border border-dashed bg-white/60 p-10 text-center text-sm text-[#64766e]"><Bell className="mx-auto mb-3"/>{message}</div>}<div className="mt-5 grid gap-3">{items.map(item=><article key={item.id} className={`rounded-[22px] border p-5 ${item.read_at?"bg-[#fffdf8]":"border-[#85bba6] bg-[#edf6f0]"}`}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#16805e]">{item.type.replaceAll("_"," ")}</span>{item.match_score!=null&&<span className="rounded-full bg-[#17362d] px-2 py-1 text-[9px] font-bold text-white">{item.match_score}% match</span>}</div><h2 className="mt-2 text-lg font-bold text-[#17362d]">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[#5f7169]">{item.message}</p>{item.match_reasons?.length>0&&<ul className="mt-3 grid gap-1 text-xs text-[#526a61]">{item.match_reasons.map(reason=><li key={reason}>• {reason}</li>)}</ul>}<div className="mt-4 flex gap-3">{item.related_url&&<Link href={item.related_url} onClick={()=>void update(item.id,{read:true})} className="text-xs font-bold text-[#116149]">Open related item →</Link>}{!item.read_at&&<button onClick={()=>update(item.id,{read:true})} className="text-xs font-bold text-[#63756d]">Mark read</button>}</div></div><button onClick={()=>update(item.id,{dismissed:true})} aria-label="Dismiss notification" className="text-[#819087] hover:text-[#b4513d]"><Trash2 size={16}/></button></div></article>)}</div></section>}
