"use client";
import Link from "next/link";
import { ArrowLeft, CalendarDays, FileText, ShieldCheck, Users, Video } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { api } from "@/components/customer/data";

type JoinData={provider:"daily"|"google_meet";url:string;token:string|null;meeting?:{id:string;title:string;agenda:string;startsAt:string;endsAt:string}};

export function MeetingRoom({meetingId,guestToken}:{meetingId?:string;guestToken?:string}){
  const host=useRef<HTMLDivElement>(null),call=useRef<{destroy:()=>Promise<void>|void}|null>(null),[join,setJoin]=useState<JoinData|null>(null),[state,setState]=useState("Checking your secure access…"),[error,setError]=useState("");
  useEffect(()=>{let active=true;async function load(){try{const response=guestToken?await fetch(`/api/meetings/guest/${encodeURIComponent(guestToken)}/join`,{method:"POST"}).then(async(r)=>{const body=await r.json() as {data?:JoinData;error?:string};if(!r.ok||!body.data)throw new Error(body.error||"Meeting access could not be created.");return {data:body.data};}):await api<{data:JoinData}>(`/api/meetings/${meetingId}/join`,{});if(active)setJoin(response.data);}catch(reason){if(active){setError((reason as Error).message);setState("");}}}void load();return()=>{active=false;void call.current?.destroy();};},[meetingId,guestToken]);
  useEffect(()=>{if(!join||join.provider!=="daily"||!host.current)return;const access=join;let cancelled=false;async function mount(){setState("Preparing your BidScope Meet room…");const dailySdk=await import("@daily-co/daily-js");if(cancelled||!host.current)return;const frame=dailySdk.default.createFrame(host.current,{showLeaveButton:true,showFullscreenButton:true,iframeStyle:{width:"100%",height:"100%",border:"0",borderRadius:"18px"}});call.current=frame;frame.on("joined-meeting",()=>setState("Connected securely")).on("left-meeting",()=>setState("You left the meeting.")).on("error",()=>setError("The meeting connection encountered a problem. Please rejoin."));await frame.join({url:access.url,token:access.token||undefined});}void mount();return()=>{cancelled=true;void call.current?.destroy();call.current=null;};},[join]);
  const isGoogle=join?.provider==="google_meet";
  return <main className="meet-room-shell"><header><Link href={guestToken?"/":"/customer/meetings"}><ArrowLeft size={17}/> Back to meetings</Link><div><ShieldCheck size={16}/> Secure BidScope meeting</div></header><div className="meet-room-grid"><section className="meet-video-panel"><div className="meet-video-title"><span><Video size={17}/></span><div><strong>{join?.meeting?.title||"BidScope Meet"}</strong><small>{state}</small></div></div>{error?<div className="meet-room-message"><ShieldCheck size={34}/><h1>Meeting access needs attention</h1><p>{error}</p></div>:isGoogle?<div className="meet-room-message"><Video size={36}/><h1>Your Google Meet is ready</h1><p>Google Meet opens separately while the agenda, notes and actions remain in BidScope.</p><a href={join.url} target="_blank" rel="noreferrer">Open Google Meet</a></div>:<div ref={host} className="meet-video-host"/>}</section><aside><p className="meet-eyebrow">MEETING CONTEXT</p><h1>{join?.meeting?.title||"BidScope Meet"}</h1><div className="meet-context-item"><CalendarDays/><span><strong>Schedule</strong><small>{join?.meeting?.startsAt?new Date(join.meeting.startsAt).toLocaleString("en-GB"):"Secure access window"}</small></span></div><div className="meet-context-item"><Users/><span><strong>Attendance</strong><small>Recorded from actual join activity</small></span></div><div className="meet-context-item"><FileText/><span><strong>Agenda</strong><small>{join?.meeting?.agenda||"Open the BidScope meeting record for full context."}</small></span></div>{!guestToken&&<Link className="meet-record-link" href={`/customer/meetings/${meetingId}`}>Open notes and actions</Link>}</aside></div></main>;
}
