import { apiErrorResponse } from "@/lib/server/api-error";
import { requireCronOrInternalSecret } from "@/lib/server/auth";
import { createNotification,processPendingDeliveries,stableDedupe } from "@/lib/server/notifications";
import { generateDailyEngagementAlerts } from "@/lib/server/daily-engagement-alerts";
import { getEntitlement,getPlanLimit } from "@/lib/server/entitlements";
import { calculateOpportunityMatch,type MatchOpportunity,type MatchProfile } from "@/lib/server/procurement/matching";
import { refreshAllOrganizationRetention } from "@/lib/server/procurement/retention";
import {expireEndedSubscriptions,reconcilePendingPaystack} from "@/lib/server/paystack";
import { supabaseRest } from "@/lib/server/supabase-rest";
import {runSeoMaintenance} from "@/lib/server/seo-maintenance";
import {processSupplierVerificationExpiry} from "@/lib/server/supplier-verification";
import {documentValidity,documentReminderDays} from "@/lib/document-passport";
import {amendmentFingerprint,meaningfulAmendmentChanges} from "@/lib/server/procurement/amendments";
export const dynamic="force-dynamic";export const maxDuration=300;
type Event={id:string;event_type:string;entity_id:string;payload:Record<string,unknown>};type Opportunity=MatchOpportunity&{id:string;slug:string;buyer_name:string;buyer_normalized_id:string|null;deadline_at:string|null;status:string;source_name:string;official_source_url:string};type Organisation=MatchProfile&{id:string;members:Array<{user_id:string}>};
async function usersForEntity(entityType:string,entityId?:string|null,entityName?:string|null){const filters=[`entity_type=eq.${entityType}`];if(entityId)filters.push(`entity_id=eq.${entityId}`);else if(entityName)filters.push(`entity_name=ilike.${encodeURIComponent(entityName)}`);else return[];const{data}=await supabaseRest<Array<{user_id:string;organization_id:string|null;relevant_only?:boolean}>>(`watched_entities?select=user_id,organization_id,relevant_only&${filters.join("&")}`);return data;}
async function usersInterestedInOpportunity(opportunityId:string){const all=await usersForEntity("opportunity",opportunityId);const[{data:saved},{data:tracked},{data:analysed}]=await Promise.all([supabaseRest<Array<{organization_id:string}>>(`saved_opportunities?select=organization_id&opportunity_id=eq.${opportunityId}`),supabaseRest<Array<{user_id:string;organization_id:string|null}>>(`user_bid_tracking?select=user_id,organization_id&opportunity_id=eq.${opportunityId}`),supabaseRest<Array<{user_id:string;organization_id:string|null}>>(`ai_threads?select=user_id,organization_id&opportunity_id=eq.${opportunityId}`)]);all.push(...tracked,...analysed);for(const item of saved){const{data:members}=await supabaseRest<Array<{user_id:string}>>(`organization_members?select=user_id&organization_id=eq.${item.organization_id}`);all.push(...members.map(member=>({user_id:member.user_id,organization_id:item.organization_id})));}return[...new Map(all.map(item=>[item.user_id,item])).values()];}
async function notifyOpportunity(event:Event,opportunity:Opportunity){const{data:organisations}=await supabaseRest<Organisation[]>("organizations?select=id,sectors,services,products,certifications,region,preferred_regions,preferred_minimum_value,preferred_maximum_value,members:organization_members(user_id)&limit=500");let created=0;const dayStart=`${new Date().toISOString().slice(0,10)}T00:00:00.000Z`;for(const org of organisations){const entitlement=await getEntitlement(org.id);const dailyLimit=getPlanLimit(entitlement,"daily_tender_alerts"),threshold=getPlanLimit(entitlement,"alert_match_threshold")||101;if(!entitlement.features.smart_alerts||dailyLimit<1)continue;const match=calculateOpportunityMatch(org,opportunity);if(match.percentage==null||match.percentage<threshold)continue;for(const member of org.members||[]){const{response}=await supabaseRest<Array<{id:string}>>(`notifications?select=id&user_id=eq.${member.user_id}&type=eq.matching_tender&created_at=gte.${dayStart}`,{count:"exact"});if(Number(response.headers.get("content-range")?.split("/")[1]||0)>=dailyLimit)continue;const result=await createNotification({userId:member.user_id,organizationId:org.id,type:"matching_tender",title:opportunity.title,message:`${opportunity.buyer_name} published an opportunity that matches your ${entitlement.plan.name} profile. Closing ${opportunity.deadline_at?new Date(opportunity.deadline_at).toLocaleDateString("en-GB"):"date not stated"}.`,relatedEntityType:"opportunity",relatedEntityId:opportunity.id,relatedUrl:`/customer/opportunity/${opportunity.slug}`,matchScore:match.percentage,matchReasons:match.reasons,metadata:{planCode:entitlement.plan.code,planName:entitlement.plan.name},dedupeKey:stableDedupe(["match",opportunity.id,org.id,member.user_id])});if(result)created++;}}
  if(opportunity.buyer_normalized_id){for(const watcher of await usersForEntity("buyer",opportunity.buyer_normalized_id)){if(watcher.relevant_only&&watcher.organization_id){const org=organisations.find(item=>item.id===watcher.organization_id);if(!org||(calculateOpportunityMatch(org,opportunity).percentage||0)<50)continue;}const result=await createNotification({userId:watcher.user_id,organizationId:watcher.organization_id,type:"buyer_activity",title:"Buyer you follow",message:`${opportunity.buyer_name} published a new procurement opportunity relevant to your follow settings.`,relatedEntityType:"opportunity",relatedEntityId:opportunity.id,relatedUrl:`/customer/opportunity/${opportunity.slug}`,dedupeKey:stableDedupe(["buyer-activity",opportunity.id,watcher.user_id])});if(result)created++;}}
  return created;
}
async function processEvent(event:Event){if(["OPPORTUNITY_CREATED","OPPORTUNITY_AMENDED"].includes(event.event_type)){const{data}=await supabaseRest<Opportunity[]>(`procurement_opportunities?select=id,slug,title,summary,buyer_name,buyer_normalized_id,deadline_at,status,source_name,official_source_url,sector,category,region,estimated_value,eligibility_text&id=eq.${event.entity_id}&limit=1`);const opportunity=data[0];if(!opportunity)return 0;if(event.event_type==="OPPORTUNITY_CREATED"){const expired=opportunity.deadline_at&&new Date(opportunity.deadline_at)<=new Date();if(expired||!["OPEN","CLOSING_SOON"].includes(opportunity.status))return 0;return notifyOpportunity(event,opportunity);}const changes=meaningfulAmendmentChanges(Array.isArray(event.payload.changes)?event.payload.changes as Array<{field:string;previous:unknown;current:unknown}>:[]);if(!changes.length)return 0;const watchers=await usersInterestedInOpportunity(opportunity.id);let count=0;for(const watcher of watchers){const first=changes[0];const severity=typeof event.payload.severity==="string"?event.payload.severity:"IMPORTANT";const result=await createNotification({userId:watcher.user_id,organizationId:watcher.organization_id,type:"tender_amendment",title:first?.field==="deadline_at"?"Tender deadline changed":"Tender notice amended",message:first?`${first.field.replaceAll("_"," ")}: ${String(first.previous??"not stated")} → ${String(first.current??"not stated")}`:"The verified source record changed.",relatedEntityType:"opportunity",relatedEntityId:opportunity.id,relatedUrl:`/customer/opportunity/${opportunity.slug}`,priority:severity==="CRITICAL"?"urgent":severity==="IMPORTANT"?"high":"normal",metadata:{changes,severity,changeTypes:changes.map(change=>change.field)},dedupeKey:stableDedupe(["amendment",opportunity.id,amendmentFingerprint(changes),watcher.user_id])});if(result)count++;}return count;}
  if(event.event_type==="AWARD_CREATED"){const{data}=await supabaseRest<Array<{id:string;title:string;buyer_id:string|null;opportunity_id:string|null;award_value:number|null;currency:string|null;award_date:string|null;source_url:string;suppliers:Array<{supplier_name:string}>}>>(`awards?select=id,title,buyer_id,opportunity_id,award_value,currency,award_date,source_url,suppliers:award_suppliers(supplier_name)&id=eq.${event.entity_id}&limit=1`);const award=data[0];if(!award)return 0;const watchers=[...(award.buyer_id?await usersForEntity("buyer",award.buyer_id):[]),...(award.opportunity_id?await usersForEntity("opportunity",award.opportunity_id):[])];for(const supplier of award.suppliers||[])watchers.push(...await usersForEntity("supplier",null,supplier.supplier_name));let count=0;for(const watcher of new Map(watchers.map(item=>[item.user_id,item])).values()){const winners=award.suppliers.map(item=>item.supplier_name).join(", ")||"Winner not stated";const result=await createNotification({userId:watcher.user_id,organizationId:watcher.organization_id,type:"award",title:"Contract award published",message:`${award.title}. Winner: ${winners}.${award.award_value!=null?` Value: ${award.currency||""} ${Number(award.award_value).toLocaleString()}.`:""}`,relatedEntityType:"award",relatedEntityId:award.id,relatedUrl:"/awarded-opportunities",metadata:{sourceUrl:award.source_url,awardDate:award.award_date},dedupeKey:stableDedupe(["award",award.id,watcher.user_id])});if(result)count++;}return count;}return 0;}
async function deadlineNotifications(){const now=new Date();const maximum=new Date(now.getTime()+8*86400000).toISOString();const{data}=await supabaseRest<Array<{user_id:string;organization_id:string|null;status:string;opportunity:Opportunity}>>(`user_bid_tracking?select=user_id,organization_id,status,opportunity:procurement_opportunities(id,slug,title,buyer_name,deadline_at,status,source_name,official_source_url,summary,buyer_normalized_id,sector,category,region,estimated_value,eligibility_text)&status=not.in.(WITHDRAWN,UNSUCCESSFUL,AWARDED)&opportunity.deadline_at=gt.${now.toISOString()}&opportunity.deadline_at=lte.${maximum}&opportunity.status=eq.OPEN`);let count=0;for(const row of data){if(!row.opportunity?.deadline_at)continue;const days=Math.ceil((new Date(row.opportunity.deadline_at).getTime()-now.getTime())/86400000);const{data:prefs}=await supabaseRest<Array<{reminder_days:number[]}>>(`alert_preferences?select=reminder_days&user_id=eq.${row.user_id}&alert_type=eq.deadline&limit=1`);if(!(prefs[0]?.reminder_days||[7,3,1]).includes(days))continue;const result=await createNotification({userId:row.user_id,organizationId:row.organization_id,type:"deadline",title:`${days} DAY${days===1?"":"S"} LEFT`,message:`${row.opportunity.title} closes ${new Date(row.opportunity.deadline_at).toLocaleString("en-GB")}. Review remaining preparation tasks in your workspace.`,relatedEntityType:"opportunity",relatedEntityId:row.opportunity.id,relatedUrl:`/opportunities/${row.opportunity.slug}`,priority:days<=1?"urgent":"high",dedupeKey:stableDedupe(["deadline",row.opportunity.id,row.user_id,days])});if(result)count++;}return count;}
async function documentExpiryNotifications(){
  const now=new Date();
  const maximum=new Date(now.getTime()+365*86400000).toISOString().slice(0,10);
  let count=0,offset=0;
  // Page through every organisation's documents; PostgREST's row cap must not
  // silently exclude later suppliers from their configured reminders.
  for(;;){
    const{data:docs}=await supabaseRest<Array<{id:string;organization_id:string;title:string;expires_at:string}>>(`supplier_documents?select=id,organization_id,title,expires_at&expires_at=gte.${now.toISOString().slice(0,10)}&expires_at=lte.${maximum}&order=id.asc&limit=500&offset=${offset}`);
    for(const doc of docs){
      const days=documentValidity(doc,now).daysRemaining;
      if(days===null)continue;
      const{data:members}=await supabaseRest<Array<{user_id:string}>>(`organization_members?select=user_id&organization_id=eq.${doc.organization_id}`);
      for(const member of members){
        const{data:prefs}=await supabaseRest<Array<{reminder_days:number[]}>>(`alert_preferences?select=reminder_days&user_id=eq.${member.user_id}&alert_type=eq.document_expiry&limit=1`);
        if(!documentReminderDays(prefs[0]?.reminder_days).includes(days))continue;
        const result=await createNotification({userId:member.user_id,organizationId:doc.organization_id,type:"document_expiry",title:"Compliance document expiring",message:`${doc.title} expires in ${days} day${days===1?"":"s"}.`,relatedEntityType:"supplier_document",relatedEntityId:doc.id,relatedUrl:"/customer/documents",priority:days<=7?"urgent":"high",dedupeKey:stableDedupe(["document-expiry",doc.id,doc.expires_at,member.user_id,days])});
        if(result)count++;
      }
    }
    if(docs.length<500)break;
    offset+=docs.length;
  }
  return count;
}
export async function runNotificationProcessing(){const{data:events}=await supabaseRest<Event[]>("procurement_events?select=*&processed_at=is.null&order=occurred_at.asc&limit=500");let generated=0;for(const event of events){try{generated+=await processEvent(event);await supabaseRest(`procurement_events?id=eq.${event.id}`,{method:"PATCH",body:JSON.stringify({processed_at:new Date().toISOString(),processing_error:null})});}catch(error){await supabaseRest(`procurement_events?id=eq.${event.id}`,{method:"PATCH",body:JSON.stringify({processing_error:(error instanceof Error?error.message:"Processing failed").slice(0,1000),retry_count:1})});}}generated+=await processCustomerSearchAlerts();generated+=await deadlineNotifications();generated+=await documentExpiryNotifications();const verification=await processSupplierVerificationExpiry();generated+=verification.reminders+verification.expired;const engagement=await generateDailyEngagementAlerts();generated+=engagement.generated;const retention=await refreshAllOrganizationRetention(10);const billing=process.env.PAYSTACK_SECRET_KEY?await Promise.all([reconcilePendingPaystack(10),expireEndedSubscriptions()]):[{checked:0,verified:0,failed:0},{expired:0}];const deliveries=await processPendingDeliveries(100);return{events:events.length,notificationsGenerated:generated,verification,engagement,retention,billing:{reconciliation:billing[0],expiry:billing[1]},deliveries};}
export async function POST(request:Request){try{requireCronOrInternalSecret(request);const notifications=await runNotificationProcessing();let seoMaintenance:Record<string,unknown>;try{seoMaintenance=await runSeoMaintenance()}catch(error){seoMaintenance={status:"failed",message:error instanceof Error?error.message:"SEO maintenance failed"}}return Response.json({...notifications,seoMaintenance});}catch(error){return apiErrorResponse(error);}}
export async function GET(request:Request){return POST(request);}
import {processCustomerSearchAlerts} from "@/lib/server/customer-search-alerts";
