import Link from "next/link";
import {ProcurementHeader,ProcurementFooter} from "@/components/procurement/site-shell";
const templates=[
 {name:"Company profile",items:["Registered business name and verified registration details","Products, services and geographical coverage","Relevant completed projects: client, date, scope and evidence","Actual staff, equipment and delivery capacity","Contact details and supporting certificates"]},
 {name:"Tender-specific staff CV",items:["Name and proposed role, with permission to share","Relevant qualifications and current professional memberships","Employment dates and responsibilities","Comparable project experience with accurate dates","Availability and any declarations required by the tender"]},
 {name:"Technical proposal outline",items:["Understanding of the published scope and deliverables","Methodology linked to each evaluation criterion","Work plan, milestones and responsible personnel","Quality assurance, risks and mitigation","Evidence of capacity and an explicit list of assumptions"]},
 {name:"Bid / no-bid worksheet",items:["Are all mandatory eligibility conditions evidenced?","Can the business meet the scope, location and timetable?","Are required staff, finances and securities available?","Which published evaluation criteria can be supported?","Record a decision, unresolved questions and the next review date"]},
 {name:"Submission checklist",items:["Confirm the latest notice, amendments and deadline timezone","Verify each mandatory document, signature and validity date","Check the financial schedule, currency and arithmetic","Follow the required packaging, naming and submission method","Keep the official submission receipt and reference"]},
];
export default function Resources(){return <main className="min-h-screen bg-[#f7f4eb] text-[#17362d]"><ProcurementHeader/><section className="mx-auto max-w-6xl px-5 py-12"><p className="text-sm font-bold uppercase tracking-widest text-[#116149]">Practical preparation resources</p><h1 className="serif mt-4 text-4xl sm:text-5xl">Start with a clear structure.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#61736a]">Use these free outlines as a starting point. They are not official tender forms or a statement that your business qualifies. The issuing authority’s current instructions always take priority.</p><div className="mt-8 grid gap-5 md:grid-cols-2">{templates.map(template=><article key={template.name} className="rounded-3xl border bg-white p-6"><h2 className="text-2xl font-bold">{template.name}</h2><ol className="mt-5 list-inside list-decimal space-y-4 leading-7">{template.items.map(item=><li key={item}>{item}</li>)}</ol></article>)}</div><p className="mt-8 rounded-2xl bg-[#e8efe9] p-6 leading-7">Never invent certifications, project experience, staff or financial figures. Need a tailored deliverable? <Link href="/services" className="font-bold underline">Request a separately priced service.</Link></p></section><ProcurementFooter/></main>;}
