"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useSearchParams} from "next/navigation";
import {ArrowLeft,ExternalLink,FileText,Sparkles} from "lucide-react";
import {api,date,eligibility,money,officialUrl,useData,type Opportunity,type RetentionAssessment} from "./data";
import {Skeleton,useAccount} from "./shell";
import {OpportunityActions} from "./opportunities";
const tabs=["Overview","Bid Decision","Requirements","Eligibility","Documents","Dates","Buyer","Amendments","AI Analysis","Activity"];
export function Detail({slug}:{slug:string}){
 const response=useData<{data:Opportunity}>(`/api/opportunities/${encodeURIComponent(slug)}`);const [tab,setTab]=useState("Overview");const params=useSearchParams();
 const o=response.data?.data;const revisions=useData<{data:{id:string;changed_fields:unknown;change_types:string[];severity:string;verified_at:string}[]}>(o?`/api/customer?resource=amendments&id=${o.id}`:null);
 useEffect(()=>{if(o)void api("/api/customer",{resource:"recent",opportunityId:o.id}).catch(()=>{});},[o]);
 const back=params.get("returnTo");const href=back?.startsWith("/customer/")?back:"/customer/discover";
 if(response.loading)return <Skeleton/>;if(response.error||!o)return <p role="alert" className="cc-error">{response.error||"Opportunity not found."}</p>;
 return <><Link className="cc-back" href={href}><ArrowLeft size={15}/>Back to results</Link><div className="cc-detail-heading"><p className="cc-eyebrow">{o.source_name} · {o.external_reference||"Official procurement notice"}</p><h1>{o.title}</h1><p>{o.buyer_name} · {o.country}</p><div className="cc-detail-facts"><span><small>Status</small>{o.status}</span><span><small>Deadline</small>{date(o.deadline_at)}</span><span><small>Estimated value</small>{money(o)}</span><span><small>Eligibility</small>{eligibility(o)}</span></div><div className="cc-detail-actions"><OpportunityActions o={o}/>{officialUrl(o.official_tender_url||o.official_source_url)&&<a className="cc-button primary" href={officialUrl(o.official_tender_url||o.official_source_url)} target="_blank" rel="noreferrer">View official notice<ExternalLink size={14}/></a>}</div></div><div className="cc-tabs" role="tablist" aria-label="Opportunity information">{tabs.map(t=><button role="tab" aria-selected={tab===t} id={`tab-${t.replaceAll(" ","-")}`} aria-controls="detail-panel" key={t} tabIndex={tab===t?0:-1} onKeyDown={e=>{const index=tabs.indexOf(t);const next=e.key==="ArrowRight"?(index+1)%tabs.length:e.key==="ArrowLeft"?(index+tabs.length-1)%tabs.length:e.key==="Home"?0:e.key==="End"?tabs.length-1:null;if(next!==null){e.preventDefault();setTab(tabs[next]);document.getElementById(`tab-${tabs[next].replaceAll(" ","-")}`)?.focus();}}} onClick={()=>setTab(t)}>{t}</button>)}</div><section id="detail-panel" role="tabpanel" aria-labelledby={`tab-${tab.replaceAll(" ","-")}`} className="cc-detail-panel">
 {tab==="Overview"&&<><p className="cc-eyebrow">OFFICIAL SOURCE INFORMATION{o.quality_score?` · ${o.quality_score}% DATA COMPLETENESS`:""}</p><h2>Scope & contract information</h2><p className="cc-prose">{o.summary||"Summary not published in the indexed notice."}</p><p className="cc-prose">{o.description}</p><dl><dt>Category</dt><dd>{o.category}</dd><dt>Procurement method</dt><dd>{o.procurement_method||"Not published"}</dd><dt>Contract type</dt><dd>{o.contract_type||"Not published"}</dd><dt>Reference</dt><dd>{o.external_reference||"Not published"}</dd><dt>Submission method</dt><dd>{o.submission_method||"See official notice"}</dd><dt>Registration</dt><dd>{o.requires_registration?"Required":"Not separately stated"}</dd>{o.procurement_codes?.length?<><dt>Procurement codes</dt><dd>{o.procurement_codes.join(", ")}</dd></>:null}</dl>{o.submission_instructions&&<><h3>How to submit</h3><p className="cc-prose">{o.submission_instructions}</p></>}</>}
 {tab==="Bid Decision"&&<BidDecision opportunity={o}/>}
 {tab==="Requirements"&&<><h2>Requirements & qualifications</h2><p className="cc-prose">{o.qualification_requirements||o.eligibility_text||"Structured requirements have not been provided in the indexed notice. Review the official documents for experience, financial capacity, technical certifications and bid security."}</p><dl><dt>Bid security</dt><dd>{o.bid_security_requirement||"Not separately published"}</dd><dt>Bid validity</dt><dd>{o.bid_validity_days?`${o.bid_validity_days} days`:"Not separately published"}</dd><dt>Participation fee</dt><dd>{o.participation_fee_amount!=null?`${o.participation_fee_currency||""} ${o.participation_fee_amount.toLocaleString()}`:"Not separately published"}</dd><dt>Lots</dt><dd>{o.lots?.length?`${o.lots.length} indexed lot(s)`:"No separate lots indexed"}</dd></dl><Link className="cc-button" href={`/customer/ai?opportunity=${slug}`}>Review requirements with AI<Sparkles size={14}/></Link></>}
 {tab==="Eligibility"&&<><p className="cc-eyebrow">SOURCE EVIDENCE & BIDSCOPE CLASSIFICATION</p><h2>{eligibility(o)}</h2><p className="cc-prose">{o.eligibility_text||"No tender-specific eligibility evidence is available."}</p><p className="cc-quiet">Ghanaian business eligibility, foreign registration, local partners and joint ventures must be checked against the official conditions. Location alone does not confirm eligibility.</p></>}
 {tab==="Documents"&&<><h2>Official tender documents</h2>{o.documents?.map(d=><a className="cc-document-row" key={d.id} href={officialUrl(d.url)} target="_blank" rel="noreferrer"><FileText size={18}/>{d.title}<ExternalLink size={14}/></a>)}{officialUrl(o.documents_url)&&<a className="cc-document-row" href={officialUrl(o.documents_url)} target="_blank" rel="noreferrer"><FileText size={18}/>Source document portal<ExternalLink size={14}/></a>}{!o.documents?.length&&!o.documents_url&&<p className="cc-quiet">No direct document links have been indexed. Use the official notice to obtain the tender pack.</p>}</>}
 {tab==="Dates"&&<><h2>Procurement timetable</h2><dl><dt>Publication</dt><dd>{date(o.published_at)}</dd><dt>Submission deadline</dt><dd>{o.deadline_at?new Date(o.deadline_at).toLocaleString("en-GB",{timeZoneName:"short"}):"Not published"}</dd><dt>Clarification deadline</dt><dd>{o.clarification_deadline_at?new Date(o.clarification_deadline_at).toLocaleString("en-GB",{timeZoneName:"short"}):"Not separately published"}</dd><dt>Bid opening</dt><dd>{o.opening_at?new Date(o.opening_at).toLocaleString("en-GB",{timeZoneName:"short"}):"Not separately published"}</dd></dl></>}
 {tab==="Buyer"&&<><h2>{o.buyer_name}</h2><p>Research the buyer&apos;s currently indexed procurement activity and historic awards.</p>{(o.contact_name||o.contact_email||o.contact_phone||o.contact_address)&&<dl><dt>Contact</dt><dd>{o.contact_name||"Procurement contact"}</dd><dt>Email</dt><dd>{o.contact_email||"Not published"}</dd><dt>Phone</dt><dd>{o.contact_phone||"Not published"}</dd><dt>Address</dt><dd>{o.contact_address||"Not published"}</dd></dl>}<div className="cc-inline-actions"><Link className="cc-button" href={`/customer/discover?buyer=${encodeURIComponent(o.buyer_name)}`}>View buyer opportunities</Link><Link className="cc-button" href="/customer/awards">Research awards</Link></div></>}
 {tab==="Amendments"&&(revisions.loading?<Skeleton/>:revisions.error?<p className="cc-error">{revisions.error}</p>:revisions.data?.data.length?revisions.data.data.map(r=><article className="cc-revision" key={r.id}><p className="cc-eyebrow">{r.severity.toUpperCase()} CHANGE · VERIFIED {date(r.verified_at)}</p><AmendmentChanges changes={r.changed_fields}/></article>):<p className="cc-quiet">No recorded amendments. Check the official notice for changes before submitting.</p>)}
 {tab==="AI Analysis"&&<AIAnalysis opportunity={o}/>}
 {tab==="Activity"&&<><h2>Opportunity activity</h2><p>Viewed just now. Your recent opportunities are saved to your account.</p><Link href="/customer/recent" className="cc-text-link">View recently opened opportunities</Link></>}
 </section></>;
}
function BidDecision({opportunity}:{opportunity:Opportunity}){
 const response=useData<{data:RetentionAssessment}>(`/api/retention?resource=decision&opportunityId=${opportunity.id}`);if(response.loading)return <Skeleton/>;if(response.error)return <p className="cc-error">{response.error}</p>;const d=response.data?.data;if(!d)return null;
 const labels:Record<string,string>={businessMatch:"Business match",eligibility:"Eligibility",capability:"Capability",financialFit:"Financial fit",experienceFit:"Experience fit",documentReadiness:"Document readiness",deadlineFeasibility:"Deadline feasibility"};
 return <div className="cc-decision"><p className="cc-eyebrow">EXPLAINABLE BID / NO-BID ADVISOR</p><div className="cc-decision-summary"><div><strong>{d.overallScore===null?"—":`${d.overallScore}%`}</strong><span>overall evidence score</span></div><span className={`cc-decision-label ${d.decision.toLowerCase().replaceAll("_","-")}`}>{d.decision.replaceAll("_"," ")}</span></div><p className="cc-quiet">This is decision support based on indexed notice data and your saved business evidence. It is not a guarantee of eligibility or award.</p><div className="cc-score-grid">{Object.entries(d.components).map(([key,value])=><div key={key}><span>{labels[key]||key}</span><strong>{value===null?"Unknown":`${value}%`}</strong><progress max={100} value={value||0}/></div>)}</div><div className="cc-decision-columns"><section><h3>Why it may fit</h3>{d.reasons.length?d.reasons.map(r=><p key={r}><CheckIcon/>{r}</p>):<p>Not enough positive evidence has been recorded.</p>}</section><section><h3>Concerns to resolve</h3>{d.concerns.map(c=><p key={c}>{c}</p>)}</section></div><a className="cc-button primary" href={officialUrl(opportunity.official_tender_url||opportunity.official_source_url)} target="_blank" rel="noreferrer">Verify in official notice<ExternalLink size={14}/></a></div>;
}
function CheckIcon(){return <span aria-hidden="true">✓</span>;}
type Answer={content:string;provider:string;providerWarning?:string|null;citations:{label:string;url?:string;page?:number}[];threadId:string};
export function AIAnalysis({opportunity}:{opportunity:Opportunity}){
 const {organization,profile}=useAccount();const [question,setQuestion]=useState(""),[answer,setAnswer]=useState<Answer>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function ask(text:string){setBusy(true);setError("");try{const r=await api<{data:Answer}>("/api/ai/assistant",{opportunityId:opportunity.id,organizationId:organization?.id,action:"question",question:text,allowSupplierPassport:!!organization,threadId:answer?.threadId});setAnswer(r.data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="cc-ai"><p className="cc-eyebrow">BIDSCOPE AI · SOURCE-GROUNDED INTERPRETATION</p><h2>Understand before you commit.</h2><p>Analysing: <strong>{opportunity.title}</strong></p><div className="cc-ai-prompts">{["Explain this tender and its key requirements.","Can my company qualify? Identify missing evidence.","What documents are required?","What are the risks and next actions?"].map(q=><button disabled={busy} className="cc-button" key={q} onClick={()=>void ask(q)}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();void ask(question);}}><label>Your question<textarea required maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about a requirement, deadline or bid decision…"/></label><button disabled={busy} className="cc-button primary"><Sparkles size={15}/>{busy?"Reviewing source evidence…":"Ask BidScope AI"}</button></form>{error&&<p role="alert" className="cc-error">{error}</p>}{busy&&<Skeleton/>}{answer&&<article className="cc-ai-answer"><p className="cc-eyebrow">{answer.provider==="grounded-fallback"?"BIDSCOPE SOURCE SUMMARY":"AI INTERPRETATION"}</p>{answer.providerWarning&&profile?.email?.trim().toLowerCase()==="basintaleuk@gmail.com"?<details className="cc-error"><summary>Administrator: deep-research provider diagnostic</summary><p>{answer.providerWarning}</p></details>:null}<div className="cc-prose">{answer.content}</div><h3>Sources</h3>{answer.citations.map((c,i)=><p key={i}><a href={officialUrl(c.url)} target="_blank" rel="noreferrer">[{i+1}] {c.label}{c.page?` · page ${c.page}`:""}</a></p>)}</article>}<p className="cc-quiet">{organization?"This analysis includes your business profile. ":""}Confirm interpretations against official tender documents. BidScope never submits a bid on your behalf.</p></div>;
}
function AmendmentChanges({changes}:{changes:unknown}){
 if(!changes||typeof changes!=="object")return <p className="cc-quiet">The source was updated. Review the official notice for the full amendment.</p>;
 const display=(value:unknown):string=>value==null?"Not published":typeof value==="object"?JSON.stringify(value):String(value);
 return <dl>{Object.entries(changes).map(([field,value])=>{const change=value&&typeof value==="object"?value as Record<string,unknown>:null;return <div key={field}><dt>{field.replaceAll("_"," ")}</dt><dd>{change&&("old" in change||"previous" in change)?<><del>{display(change.old??change.previous)}</del><br/><ins>{display(change.new??change.current)}</ins></>:display(value)}</dd></div>;})}</dl>;
}
