"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect} from "react";
import {ArrowRight,ArrowUpRight,CalendarDays,Check,SlidersHorizontal,Sparkles} from "lucide-react";
import {api,date,days,invalidate,stages,useData,type Bid,type Notice,type Opportunity,type Pulse,type RetentionOverview} from "./data";
import {Empty,Skeleton,useAccount} from "./shell";
import {OpportunityActions,OpportunityRow} from "./opportunities";
export function PanelTitle({title,href,label="View all"}:{title:string;href?:string;label?:string}){return <div className="cc-panel-heading"><h2>{title}</h2>{href&&<Link href={href}>{label}<ArrowUpRight size={13}/></Link>}</div>;}
export function HomePage(){
 const {profile,organization,preferences,toast}=useAccount();
 const pulse=useData<{data:Pulse}>("/api/customer?resource=pulse");
 const retention=useData<{data:RetentionOverview}>("/api/retention?resource=overview");
 const matches=useData<{data:Opportunity[]}>("/api/customer?resource=discover&collection=recommended&pageSize=5&sort=match");
 const upcoming=useData<{data:Opportunity[]}>("/api/customer?resource=discover&stage=upcoming&scope=ghana&pageSize=3");
 const africa=useData<{data:Opportunity[]}>("/api/customer?resource=discover&scope=africa&pageSize=50&sort=newest");
 const bids=useData<{data:Bid[]}>("/api/bids");const notices=useData<{data:Notice[]}>("/api/notifications");
 const watches=useData<{data:{id:string;name:string;alerts_enabled:boolean;frequency:string;last_notified_at:string|null;filters:Record<string,string>}[]}>("/api/customer?resource=searches");
 const p=pulse.data?.data; const africaBeyondGhana=africa.data?.data.filter(o=>o.country_code!=="GH").slice(0,3) || [];
 const attention=notices.data?.data.filter(n=>["urgent","high"].includes(n.priority)&&!n.read_at).slice(0,4)||[];
 const deadlines=bids.data?.data.filter(b=>b.opportunity?.deadline_at&&!["SUBMITTED","AWARDED","UNSUCCESSFUL","WITHDRAWN"].includes(b.status)).sort((a,b)=>Date.parse(a.opportunity.deadline_at!)-Date.parse(b.opportunity.deadline_at!)).slice(0,4)||[];
 const best=retention.data?.data.bestMatch;const readiness=retention.data?.data.readiness;const radar=retention.data?.data.radar||[];
 const hour=new Date().getHours();
 useEffect(()=>{void api("/api/retention",{resource:"feed_view"}).catch(()=>{});},[]);
 return <><div className="cc-page-heading"><div><p className="cc-eyebrow">TODAY · {date(new Date().toISOString())}</p><h1>Good {hour<12?"morning":hour<18?"afternoon":"evening"}{profile?.full_name?`, ${profile.full_name.split(" ")[0]}`:""}.</h1><p>Here&apos;s what has changed in your opportunity pipeline.</p></div><div className="cc-page-heading-actions"><Link href="/customer/settings" className="cc-button"><SlidersHorizontal size={14}/>Customise home</Link><div className="cc-page-heading-image" aria-hidden="true"><Image src="/images/ghana-supplier.webp" alt="" fill sizes="(max-width: 768px) 96px, 180px"/></div></div></div>
 <div className="cc-pulse-label">PROCUREMENT PULSE <span>Current indexed opportunities</span></div><div className="cc-pulse">{([["Open Opportunities","open","/customer/discover"],["Matched to You","matched","/customer/recommended"],["Strong Matches","strong","/customer/recommended?match=80"],["Closing in 7 Days","closing","/customer/discover?days=7"],["Saved","saved","/customer/saved"],["Active Bids","bids","/customer/bids"],["International Matches","international","/customer/recommended?scope=international"]] as const).map(([label,key,href])=><Link href={href} key={key}><span>{label}</span><strong>{p?p[key].toLocaleString():pulse.error?"—":<span className="cc-skeleton cc-number-skeleton"/>}</strong><ArrowUpRight size={13}/></Link>)}</div>{pulse.error&&<p role="alert" className="cc-error">Briefing data is unavailable: {pulse.error}</p>}
 <div className={`cc-home-grid ${preferences.deadlinesFirst?"cc-deadlines-first":""}`}><div className="cc-home-primary">
 <section className="cc-brief"><div className="cc-brief-icon"><Sparkles size={18}/></div><div><p className="cc-eyebrow">TODAY&apos;S BRIEF <span>· BidScope data summary</span></p>{p?<p>{p.matched?`${p.matched} opportunities match your business profile. ${p.strong} score at least 80%.` :"Start with your business profile to find opportunities aligned with your capabilities."} {deadlines.length?`Your next tracked deadline is ${date(deadlines[0].opportunity.deadline_at)}.`:"Track an opportunity to bring its deadlines into your briefing."}</p>:<Skeleton/>}<div><Link href="/customer/recommended">View recommended <ArrowRight size={13}/></Link><Link href="/customer/ai">Explore with AI</Link></div></div></section>
 <section className="cc-best-match"><div><p className="cc-eyebrow">YOUR BEST MATCH · VERIFIED OPEN OPPORTUNITIES</p><h2>{best?.opportunity.title||"Your Best Match will appear here"}</h2><p>{best?`${best.opportunity.buyer_name} · ${best.opportunity.country} · ${date(best.opportunity.deadline_at)}`:"Complete your business profile so BidScope can compare your evidence with current opportunities."}</p>{best&&<><div className="cc-best-reasons">{best.reasons.slice(0,2).map(reason=><span key={reason}><Check size={13}/>{reason}</span>)}</div><OpportunityActions o={best.opportunity}/></>}</div>{best?<div className="cc-best-score"><strong>{best.overallScore}%</strong><span>{best.decision.replaceAll("_"," ")}</span><Link href={`/customer/opportunity/${best.opportunity.slug}`}>Review decision <ArrowRight size={13}/></Link></div>:<Link className="cc-button" href="/customer/profile">Complete profile</Link>}</section>
 <section className={`cc-home-matches ${preferences.compact?"cc-compact":""}`}><PanelTitle title="Top opportunities for you" href="/customer/recommended" label="All recommendations"/><p className="cc-section-subtitle">Ranked using your business profile and published opportunity data.</p>{matches.loading?<Skeleton/>:matches.error?<p className="cc-error">{matches.error}</p>:matches.data?.data.length?matches.data.data.map(o=><OpportunityRow key={o.id} o={o}/>):<Empty title="Build your first shortlist" description="Tell us your sectors, services and operating regions. BidScope will rank the opportunities that fit." href="/customer/profile" action="Complete business profile"/>}</section>
 <section className="cc-attention"><PanelTitle title="Attention required" href="/customer/notifications"/>{notices.loading?<Skeleton/>:notices.error?<p className="cc-error">{notices.error}</p>:attention.length?attention.map(n=><Link className="cc-attention-item" key={n.id} href={n.related_url||"/customer/notifications"}><span className={n.priority==="urgent"?"cc-urgent-dot":"cc-caution-dot"}/><span><strong>{n.title}</strong><small>{n.message}</small></span><ChevronRightIcon/></Link>):<p className="cc-quiet"><Check size={16}/> No high-priority unread alerts. Your next actions will appear here.</p>}</section>
 <section className="cc-new"><PanelTitle title="New since your last visit"/>{p?.since?<div className="cc-new-counts"><Link href={`/customer/discover?scope=ghana&publishedAfter=${encodeURIComponent(p.since)}`}><strong>{p.newGhana}</strong>Ghana opportunities<ArrowUpRight size={13}/></Link><Link href={`/customer/discover?scope=international&publishedAfter=${encodeURIComponent(p.since)}`}><strong>{p.newInternational}</strong>International opportunities<ArrowUpRight size={13}/></Link><Link href="/customer/recommended?match=80"><strong>{p.newMatches}</strong>New strong matches<ArrowUpRight size={13}/></Link></div>:<p className="cc-quiet">Your first visit sets a starting point. New opportunities will be highlighted when you return.</p>}</section>
 <section><PanelTitle title="Prepare early" href="/customer/discover?stage=upcoming" label="All procurement plans"/><p className="cc-section-subtitle">Ghana procurement plans, not open tenders. Get ready before procurement begins.</p>{upcoming.loading?<Skeleton/>:upcoming.error?<p className="cc-error">{upcoming.error}</p>:upcoming.data?.data.length?upcoming.data.data.map(o=><div className="cc-plan-row" key={o.id}><CalendarDays size={17}/><div><Link href={`/customer/opportunity/${o.slug}`}>{o.title}</Link><p>{o.buyer_name}</p></div><button className="cc-button" onClick={async()=>{try{await api("/api/watched-entities",{organizationId:organization?.id,entityType:"opportunity",entityId:o.id,entityName:o.title});toast("Procurement followed.");invalidate();}catch(e){toast((e as Error).message);}}}>Follow</button></div>):<p className="cc-quiet">No published Ghana procurement plans are currently indexed. Browse all plans to research other markets.</p>}</section>
 {!preferences.hideInternational&&<section><PanelTitle title="African opportunities beyond Ghana" href="/customer/discover?scope=africa"/><p className="cc-section-subtitle">Open African and regional notices. Eligibility is labelled from published evidence and must be confirmed in the official notice.</p>{africa.loading?<Skeleton/>:africa.error?<p className="cc-error">{africa.error}</p>:africaBeyondGhana.length?africaBeyondGhana.map(o=><OpportunityRow key={o.id} o={o}/>):<p className="cc-quiet">No current cross-border African notices are indexed yet. BidScope will show them here as official sources publish them.</p>}</section>}
 </div><aside className="cc-home-secondary"><section className="cc-deadline-panel"><PanelTitle title="Upcoming deadlines" href="/customer/deadlines" label="Calendar"/>{bids.loading?<Skeleton/>:bids.error?<p className="cc-error">{bids.error}</p>:deadlines.length?deadlines.map(b=><Link className="cc-timeline-item" key={b.id} href={`/customer/bids?opportunity=${b.opportunity.id}`}><span className={(days(b.opportunity.deadline_at)??99)<=1?"urgent":""}>{date(b.opportunity.deadline_at)}</span><strong>{b.opportunity.title}</strong><small>Submission · {new Date(b.opportunity.deadline_at!).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZoneName:"short"})}</small></Link>):<p className="cc-quiet">No tracked deadlines yet. Add a bid to keep its submission date in view.</p>}</section>
 <section><PanelTitle title="Your bid pipeline" href="/customer/pipeline"/>{p?<div className="cc-pipeline-summary">{stages.filter(([s])=>s!=="WITHDRAWN").map(([stage,label])=><Link key={stage} href={`/customer/bids?status=${stage}`}><span>{label}</span><span className="cc-pipeline-bar"><i style={{width:`${Math.min(100,(p.pipeline[stage]||0)/Math.max(1,...Object.values(p.pipeline))*100)}%`}}/></span><strong>{p.pipeline[stage]||0}</strong></Link>)}</div>:<Skeleton/>}</section>
 {readiness&&<section className="cc-readiness"><PanelTitle title="Bid readiness"/><strong>{readiness.overallScore}% <span>{readiness.confidence} evidence confidence</span></strong><progress max={100} value={readiness.overallScore}/><p>{readiness.recommendations[0]?.label||"Your recorded readiness evidence is complete."}</p><Link href="/customer/profile">Improve readiness <ArrowRight size={13}/></Link></section>}
 <section><PanelTitle title="Tender Watch activity" href="/customer/alerts" label="Manage watches"/>{watches.loading?<Skeleton/>:watches.error?<p className="cc-error">{watches.error}</p>:watches.data?.data.length?watches.data.data.slice(0,4).map(w=><Link className="cc-activity" key={w.id} href={`/customer/discover?${new URLSearchParams(w.filters)}`}><small>{w.alerts_enabled?`${w.frequency.toUpperCase()} ALERTS ON`:"ALERTS OFF"}</small><p>{w.name}</p></Link>):<p className="cc-quiet">Save a filtered search to make BidScope watch the market for you.</p>}</section>
 <section><PanelTitle title="Followed buyer activity" href="/customer/following"/>{notices.data?.data.filter(n=>n.type==="buyer_activity").slice(0,3).map(n=><Link className="cc-activity" href={n.related_url||"/customer/notifications"} key={n.id}><small>{date(n.created_at)}</small><p>{n.title}</p><span>{n.message}</span></Link>)}{!notices.loading&&!notices.data?.data.some(n=>n.type==="buyer_activity")&&<p className="cc-quiet">New relevant activity from followed buyers will appear here.</p>}</section>
 <section><PanelTitle title="Procurement radar" href="/customer/discover?stage=upcoming" label="View official plans"/><p className="cc-section-subtitle">Evidence-backed early signals. Official plans are clearly labelled.</p>{retention.loading?<Skeleton/>:retention.error?<p className="cc-error">{retention.error}</p>:radar.length?radar.slice(0,3).map(item=><Link className="cc-radar-row" key={item.opportunity_id} href={`/customer/opportunity/${item.slug}`}><span>OFFICIAL PLAN</span><strong>{item.title}</strong><small>{item.buyer_name} · {date(item.expected_at)}</small></Link>):<p className="cc-quiet">No matching official upcoming plans are currently indexed. Unverified predictions are not shown.</p>}</section>
 <section><PanelTitle title="Buyers to watch" href="/customer/buyers"/>{p?.buyers.length?p.buyers.map(b=><div className="cc-watch-row" key={b.buyer_name}><Link href={`/customer/discover?buyer=${encodeURIComponent(b.buyer_name)}`}><strong>{b.buyer_name}</strong><small>{b.total} current profile matches</small></Link><button title={`Follow ${b.buyer_name}`} onClick={async()=>{try{await api("/api/watched-entities",{organizationId:organization?.id,entityType:"buyer",entityName:b.buyer_name,relevantOnly:true});toast("Buyer followed. Relevant activity alerts are on by default.");invalidate();}catch(e){toast((e as Error).message);}}}>Follow</button></div>):<p className="cc-quiet">Relevant buyers appear as your profile finds matches.</p>}</section>
 {!preferences.hideMarket&&<section><PanelTitle title="Market snapshot" href="/customer/intelligence"/><p className="cc-section-subtitle">Published sector classifications · current index</p>{p?.sectors.map(s=><div className="cc-market-row" key={s.sector}><span>{s.sector}</span><strong>{s.total}</strong></div>)}</section>}
 <section><PanelTitle title="Recent activity" href="/customer/notifications"/>{notices.data?.data.slice(0,3).map(n=><Link className="cc-activity" href={n.related_url||"/customer/notifications"} key={n.id}><small>{date(n.created_at)}</small><p>{n.title}</p></Link>)}{!notices.loading&&!notices.data?.data.length&&<p className="cc-quiet">Procurement events will appear here as you save and follow opportunities.</p>}</section></aside></div></>;
}
function ChevronRightIcon(){return <ArrowRight size={14}/>;}
