"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {ArrowUpRight,Bookmark,BriefcaseBusiness,ChevronDown,ChevronLeft,ChevronRight,Globe2,SlidersHorizontal,Sparkles,X,Search,Columns3,List,Check,ExternalLink,EyeOff} from "lucide-react";
import {api,date,days,eligibility,invalidate,money,officialUrl,useData,type Opportunity,type OpportunityAccess} from "./data";
import {Empty,Skeleton,useAccount} from "./shell";

export function OpportunityActions({o}:{o:Opportunity}){
 const {organization,toast}=useAccount();const [busy,setBusy]=useState(false);const [feedbackOpen,setFeedbackOpen]=useState(false);const router=useRouter();
 async function act(kind:"save"|"track") {setBusy(true);try{if(kind==="save"){if(!organization){router.push("/customer/profile");toast("Add your business profile to save opportunities.");return;}await api("/api/saved-opportunities",{organizationId:organization.id,opportunityId:o.id,pipelineStage:"watching"});window.trackBidScopeSeoConversion?.("tender_watch",{metadata:{opportunity:o.slug}});toast("Opportunity saved to your shortlist.");}else{await api("/api/bids",{opportunityId:o.id,organizationId:organization?.id,status:"REVIEWING"});window.trackBidScopeSeoConversion?.("bid_started",{metadata:{opportunity:o.slug}});toast("Added to your bid workspace.");router.push(`/customer/bids?opportunity=${o.id}`);}invalidate();}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 async function feedback(reasonCode:string){if(!organization){toast("Add your business profile before personalising your feed.");return;}setBusy(true);try{await api("/api/retention",{resource:"feedback",organizationId:organization.id,opportunityId:o.id,action:"not_relevant",reasonCode});toast("Thanks. This opportunity was removed and your feedback was saved.");setFeedbackOpen(false);invalidate();}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 return <div className="cc-row-actions"><button disabled={busy} onClick={()=>void act("save")} aria-label={`Save ${o.title}`}><Bookmark size={14}/>{o.saved?"Saved":"Save"}</button><Link href={`/customer/ai?opportunity=${o.slug}`}><Sparkles size={14}/>Analyse</Link>{o.status!=="UPCOMING"&&<button disabled={busy} onClick={()=>void act("track")}><BriefcaseBusiness size={14}/>Track Bid</button>}<span className="cc-feedback"><button disabled={busy} onClick={()=>setFeedbackOpen(!feedbackOpen)} aria-expanded={feedbackOpen} title="Remove this opportunity and improve future recommendations"><EyeOff size={14}/>Not relevant</button>{feedbackOpen&&<span className="cc-feedback-menu"><strong>Why is this not relevant?</strong>{([['WRONG_SECTOR','Wrong sector'],['TOO_SMALL','Value too small'],['TOO_LARGE','Value too large'],['WRONG_COUNTRY','Wrong country'],['NOT_ELIGIBLE','Not eligible'],['WRONG_SERVICE','Wrong service'],['DEADLINE_TOO_CLOSE','Deadline too close'],['OTHER','Other']] as const).map(([code,label])=><button key={code} onClick={()=>void feedback(code)}>{label}</button>)}</span>}</span></div>;
}
export function OpportunityRow({o,preview,returnTo}:{o:Opportunity&OpportunityAccess;preview?:(o:Opportunity&OpportunityAccess)=>void;returnTo?:string}){
 const remaining=days(o.deadline_at);const [reason,setReason]=useState(false);
 const locked=Boolean(o.locked?.length);
 const href=`/customer/opportunity/${o.slug}${returnTo?`?returnTo=${encodeURIComponent(returnTo)}`:""}`;
 return <article className="cc-opportunity cc-external-opportunity"><div className="cc-op-main"><div className="cc-op-meta"><span className="cc-badge external"><Globe2 size={10}/>EXTERNAL TENDER</span><span className={`cc-badge ${o.status==="UPCOMING"?"neutral":"positive"}`}>{o.status==="UPCOMING"?"PLANNED":o.status==="OPEN"||o.status==="CLOSING_SOON"?"OPEN":o.status.replaceAll("_"," ")}</span><span>{o.category?.replaceAll("_"," ")}</span>{!locked&&<span>{o.source_name}</span>}{o.country_code!=="GH"&&<span><Globe2 size={12}/> International</span>}</div><h3>{preview?<button onClick={()=>preview(o)}>{o.title}</button>:<Link href={href}>{o.title}</Link>}</h3><p className="cc-buyer-line">{locked?(o.buyer_type||"Public-sector organisation"):o.buyer_name} <span>· {o.country||"Location not published"}{o.region?` / ${o.region}`:""}</span></p><div className="cc-op-facts"><span>Apply on the issuing authority&apos;s portal</span><span>{money(o)}</span>{locked?<span>Requirements available with subscription</span>:<span title={o.eligibility_text||"No tender-specific eligibility evidence is available"}>{eligibility(o)}</span>}{!locked&&["OFFICIAL","VERIFIED"].includes(o.verification_status)&&<span><Check size={12}/>Official source</span>}</div>{locked?<Link className="cc-text-link" href="/plans">Unlock tender details <ArrowUpRight size={13}/></Link>:<OpportunityActions o={o}/>}</div><div className="cc-op-right">{o.match?.percentage!=null?<button className="cc-match" onClick={()=>setReason(!reason)} aria-expanded={reason}><strong>{o.match.percentage}%</strong><span>business match <ChevronDown size={12}/></span></button>:<span className="cc-muted">Match not assessed</span>}<div className={`cc-deadline ${remaining!==null&&remaining<=3?"urgent":""}`}><strong>{date(o.deadline_at)}</strong><span>{remaining===null?"Deadline not published":remaining<0?"Closed":remaining===0?"Closes today":remaining===1?"1 day remaining":`${remaining} days remaining`}</span></div><Link href={href} className="cc-text-link">View external tender <ArrowUpRight size={13}/></Link></div>{reason&&<div className="cc-reasons"><strong>Why this matches you</strong><span className="cc-eyebrow">BIDSCOPE RULE-BASED ANALYSIS</span>{o.match?.reasons.map(r=><p key={r}><Check size={13}/>{r}</p>)}<p>Potential concerns: confirm bid security, experience and mandatory documents in the official notice. A profile match is not an eligibility decision.</p></div>}</article>;
}
const fields=[['country','Country'],['region','Region'],['sector','Sector'],['category','Procurement category'],['buyer','Buyer'],['source','Source'],['contractType','Opportunity type'],['procurementMethod','Procurement method'],['funding','Funding organisation'],['currency','Currency'],['minimumValue','Minimum value'],['maximumValue','Maximum value'],['days','Days remaining'],['match','Minimum match %'],['publishedAfter','Published after'],['deadlineBefore','Deadline before']] as const;
export function Discovery({collection}:{collection?:string}){
 const params=useSearchParams(),router=useRouter(),{preferences,setPreferences,toast}=useAccount();
 const [filtersOpen,setFiltersOpen]=useState(false),[input,setInput]=useState(params.get("q")||"");
 const [saveOpen,setSaveOpen]=useState(false);
 const searchTimer=useRef<ReturnType<typeof setTimeout>|null>(null),trackedSearch=useRef("");
 useEffect(()=>{if(searchTimer.current)clearTimeout(searchTimer.current);void Promise.resolve().then(()=>setInput(params.get("q")||""));},[params]);
 useEffect(()=>()=>{if(searchTimer.current)clearTimeout(searchTimer.current);},[]);
 const query=new URLSearchParams(params.toString());query.delete("selected");query.delete("preview");query.delete("returnTo");if(collection)query.set("collection",collection);
 const response=useData<{data:Array<Opportunity&OpportunityAccess>;pagination:{total:number;page:number;pageSize:number}}>(`/api/customer?resource=discover&${query}`);
 useEffect(()=>{const term=params.get("q")?.trim()||"";if(response.data&&term&&trackedSearch.current!==`${term}:${response.data.pagination.total}`){trackedSearch.current=`${term}:${response.data.pagination.total}`;window.trackBidScopeInternalSearch?.(term,response.data.pagination.total)}},[params,response.data]);
 const selected=response.data?.data.find(o=>o.slug===params.get("selected"));
 const advanced=params.get("preview")==="1";
 const path=collection?`/customer/${collection==="recent"?"recent":collection}`:"/customer/discover";
 const selectedHref=selected?.locked?.length?"/plans":selected?`/customer/opportunity/${selected.slug}?returnTo=${encodeURIComponent(`${path}?${params}`)}`:"/customer/discover";
 function update(key:string,value:string){const q=new URLSearchParams(params);if(value)q.set(key,value);else q.delete(key);if(!["page","selected","preview"].includes(key))q.delete("page");router.push(`${path}?${q}`,{scroll:false});}
 function search(value:string){setInput(value);if(searchTimer.current)clearTimeout(searchTimer.current);searchTimer.current=setTimeout(()=>{const p=new URLSearchParams(params);if(value)p.set("q",value);else p.delete("q");p.delete("page");router.replace(`${path}?${p}`,{scroll:false});},350);}
 const title=collection==="saved"?"Saved opportunities":collection==="recommended"?"Recommended for you":collection==="recent"?"Recently viewed":params.get("stage")==="upcoming"?"Upcoming procurement":params.get("scope")==="international"?"International opportunities":params.get("scope")==="ghana"?"Ghana opportunities":"Discover opportunities";
 return <><div className="cc-page-heading"><div><p className="cc-eyebrow">{collection?"MY OPPORTUNITIES":"EXTERNAL TENDER DISCOVERY"}</p><h1>{title}</h1><p>{params.get("stage")==="upcoming"?"Official procurement plans. These procurements have not opened yet.":"Opportunities indexed from external authorities. Applications remain on the official source portal."}</p></div><div className="cc-page-heading-actions"><button className="cc-button" onClick={()=>setSaveOpen(!saveOpen)}><Bookmark size={15}/>Save search</button><div className="cc-page-heading-image" aria-hidden="true"><Image src="/images/bidscope-hero.webp" alt="" fill sizes="(max-width: 768px) 96px, 180px"/></div></div></div>
 {!collection&&<div className="cc-tabs cc-tender-source-tabs"><Link aria-current="page" href="/customer/discover"><Globe2 size={14}/>External Tenders</Link><Link href="/customer/bidscope-tenders"><BriefcaseBusiness size={14}/>BidScope-Managed Tenders</Link></div>}
 {saveOpen&&<form className="cc-inline-form" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{await api("/api/customer",{resource:"searches",name:form.get("name"),frequency:form.get("frequency"),filters:Object.fromEntries(query)});toast("Tender Watch saved. Turn alerts on in your Alert Centre.");setSaveOpen(false);invalidate();}catch(e){toast((e as Error).message);}}}><label>Watch name<input name="name" required maxLength={160} placeholder="e.g. Electrical contracts in Ghana"/></label><label>Alert frequency<select name="frequency" defaultValue="daily"><option value="instant">Immediate</option><option value="daily">Daily digest</option><option value="weekly">Weekly digest</option></select></label><button className="cc-button primary">Save Tender Watch</button><button type="button" onClick={()=>setSaveOpen(false)} aria-label="Cancel"><X size={16}/></button></form>}
 <div className="cc-discovery-search"><Search size={18}/><input aria-label="Search opportunities" placeholder="Title, buyer, sector, keyword or reference…" value={input} onChange={e=>search(e.target.value)}/><button className="cc-button cc-filter-toggle" onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={16}/>Filters</button></div>
 <div className={`cc-discovery ${advanced?"cc-three-panel":""}`}><aside className={`cc-filters ${filtersOpen?"open":""}`}><div className="cc-panel-heading"><h2>Refine results</h2><button className="cc-text-link" onClick={()=>{setInput("");router.push(path);}}>Reset</button><button className="cc-filter-toggle" onClick={()=>setFiltersOpen(false)} aria-label="Close filters"><X size={17}/></button></div><label>Geography<select value={params.get("scope")||"all"} onChange={e=>update("scope",e.target.value)}><option value="all">All locations</option><option value="ghana">Ghana</option><option value="africa">Africa</option><option value="international">International</option></select></label><label>Eligibility evidence<select value={params.get("eligibility")||""} onChange={e=>update("eligibility",e.target.value)}><option value="">Any / unconfirmed</option><option value="INTERNATIONAL_ELIGIBLE">International bidding indicated</option><option value="RESTRICTED">Restrictions identified</option><option value="UNCLEAR">Unclear</option></select></label>{fields.map(([key,label],i)=><label key={key} className={i>4?"cc-advanced-filter":""}>{label}<input type={key.includes("Value")||["days","match"].includes(key)?"number":key.includes("After")||key.includes("Before")?"date":"text"} min="0" defaultValue={params.get(key)||""} key={params.get(key)||key} onBlur={e=>{if(e.target.value!==(params.get(key)||""))update(key,e.target.value);}} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}} placeholder="Any"/></label>)}<p className="cc-muted">Classification codes and partner requirements are shown when supplied by the official notice; they are not inferred.</p><button className="cc-button cc-filter-toggle" onClick={()=>setFiltersOpen(false)}>Show results</button></aside>
 <section className={`cc-results ${preferences.compact?"cc-compact":""}`}><div className="cc-results-toolbar"><span>{response.loading?"Searching…":response.data?`${response.data.pagination.total.toLocaleString()} opportunities`:"Results"}</span><div><select aria-label="Sort results" value={params.get("sort")|| (collection==="recommended"?"match":"deadline")} onChange={e=>update("sort",e.target.value)}><option value="deadline">Deadline first</option><option value="newest">Newest first</option><option value="match">Best match</option></select><button title={preferences.compact?"Comfortable view":"Compact view"} aria-label="Toggle compact view" aria-pressed={!!preferences.compact} onClick={()=>setPreferences({compact:!preferences.compact})}><List size={18}/></button><button className="cc-preview-toggle" title="Three-panel preview" aria-label="Toggle preview panel" aria-pressed={advanced} onClick={()=>update("preview",advanced?"":"1")}><Columns3 size={18}/></button></div></div>
 {response.loading?<Skeleton/>:response.error?<div role="alert" className="cc-error">{response.error}<button onClick={invalidate}>Retry</button></div>:!response.data?.data.length?<Empty title="No opportunities in this view" description={collection==="recommended"?"Complete your business profile or broaden your preferences.":collection==="saved"?"Saved results are listed here.":"Try fewer filters or a different keyword."} href={collection==="recommended"?"/customer/profile":"/customer/discover"} action={collection==="recommended"?"Complete business profile":"Browse all opportunities"}/>:response.data.data.map(o=><OpportunityRow key={o.id||o.slug} o={o} preview={advanced?o=>update("selected",o.slug):undefined} returnTo={`${path}?${params}`}/>)}
 {response.data&&<div className="cc-pagination"><span>Page {response.data.pagination.page} of {Math.max(1,Math.ceil(response.data.pagination.total/response.data.pagination.pageSize))}</span><div><button className="cc-button" disabled={response.data.pagination.page<=1} onClick={()=>update("page",String(response.data!.pagination.page-1))}><ChevronLeft size={14}/>Previous</button><button className="cc-button" disabled={response.data.pagination.page*response.data.pagination.pageSize>=response.data.pagination.total} onClick={()=>update("page",String(response.data!.pagination.page+1))}>Next<ChevronRight size={14}/></button></div></div>}</section>
 {advanced&&<aside className="cc-preview">{selected?<><p className="cc-eyebrow">OPPORTUNITY PREVIEW</p><h2>{selected.title}</h2><p>{selected.locked?.length?(selected.buyer_type||"Public-sector organisation"):selected.buyer_name}</p><dl><dt>Submission deadline</dt><dd>{date(selected.deadline_at)}</dd><dt>Estimated value</dt><dd>{money(selected)}</dd><dt>Eligibility</dt><dd>{selected.locked?.length?"Available with subscription":eligibility(selected)}</dd></dl><p>{selected.summary||"Read the tender summary."}</p>{selected.locked?.length?<p>Subscribe to unlock the buyer, requirements, source documents and application route.</p>:<p>{selected.eligibility_text||"Requirements have not been published in the indexed record."}</p>}{!selected.locked?.length&&<OpportunityActions o={selected}/>}<Link className="cc-button primary" href={selectedHref}>{selected.locked?.length?"View plans":"Open full opportunity"}<ArrowUpRight size={14}/></Link>{!selected.locked?.length&&officialUrl(selected.documents_url)&&<a href={officialUrl(selected.documents_url)} target="_blank" rel="noreferrer">Official documents <ExternalLink size={13}/></a>}</>:<Empty title="Inspect without losing your place" description="Select an opportunity title to preview its scope, deadline and eligibility here." action="Close preview" href={`${path}?${query}`}/>}</aside>}</div></>;
}
