"use client";
import { useState } from "react";
import { BadgeCheck, FileCheck2, ShieldCheck, UploadCloud } from "lucide-react";
import { api, downloadAuthenticatedFile, invalidate, uploadAuthenticatedFile, useData } from "./data";
import { useAccount } from "./shell";

type Application={id:string;requested_level:"verified"|"enhanced_verified";status:string;payment_status:string;amount_minor:number;created_at:string;decision_reason:string|null};
type Check={id:string;request_id:string;check_type:string;status:string};
type Doc={id:string;request_id:string;document_type:string;original_filename:string;risk_level:string;integrity_flags:string[]};
type State={level:"basic"|"verified"|"enhanced_verified";verifiedAt:string|null;expiresAt:string|null;basicChecks:Record<string,boolean>;requests:Application[];checks:Check[];documents:Doc[];settings:{enhanced_price_minor:number;currency:string;validity_months:number}|null};
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export function SupplierVerification(){
 const {organization,toast}=useAccount();
 const response=useData<{data:State}>(organization?.id?`/api/supplier-verification?organizationId=${organization.id}`:null);
 const [busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[documentType,setDocumentType]=useState("Business registration"),[file,setFile]=useState<File|null>(null);
 const state=response.data?.data;
 const current=state?.requests.find(item=>item.id===selected)||state?.requests[0];
 async function run(action:Record<string,string>){setBusy(true);try{const result=await api<{data:{id?:string;authorization_url?:string}}>("/api/supplier-verification",action);if(result.data?.id)setSelected(result.data.id);if(result.data?.authorization_url){window.location.assign(result.data.authorization_url);return;}invalidate();toast("Verification application updated.");}catch(error){toast((error as Error).message);}finally{setBusy(false);}}
 async function upload(){if(!current||!file)return;setBusy(true);try{const form=new FormData();form.set("requestId",current.id);form.set("documentType",documentType);form.set("file",file);await uploadAuthenticatedFile("/api/supplier-verification/documents",form);setFile(null);invalidate();toast("Document stored privately for review.");}catch(error){toast((error as Error).message);}finally{setBusy(false);}}
 if(!organization)return <section className="cc-editor"><h1>Supplier verification</h1><p>Create your business profile before applying.</p></section>;
 return <div className="space-y-6">
  <header className="rounded-3xl bg-gradient-to-br from-[#07372c] via-[#116149] to-[#1a8060] p-7 text-white shadow-lg"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e5c769]">BidScope trust centre</p><h1 className="mt-2 text-3xl font-bold">Supplier verification</h1><p className="mt-3 max-w-2xl text-white/80">Build a transparent, evidence-backed company profile. Verification is separate from your subscription and never guarantees a contract.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm font-semibold"><ShieldCheck size={17}/>{label(state?.level||"basic")} Supplier</div>{state?.expiresAt&&<p className="mt-2 text-sm text-white/70">Valid until {new Date(state.expiresAt).toLocaleDateString("en-GB")}</p>}</header>
  {response.error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{response.error}</p>}
  <section className="rounded-2xl border border-[#143e32]/15 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Basic supplier profile readiness</h2><p className="mt-1 text-sm text-[#64766e]">These are profile completeness signals, not official registration verification. Phone verification is recommended where supported.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(state?.basicChecks||{}).map(([check,complete])=><p key={check} className={`rounded-xl px-3 py-2 text-sm ${complete?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-900"}`}>{complete?"✓":"○"} {label(check)}</p>)}</div></section>
  <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[#143e32]/15 bg-white p-6 shadow-sm"><BadgeCheck className="text-[#116149]"/><h2 className="mt-3 text-xl font-bold">Verified Supplier</h2><p className="mt-2 text-sm leading-6 text-[#566962]">Company registration, name and number, document integrity and manual official-source review. No enhanced-service fee.</p><button className="mt-5 rounded-full bg-[#116149] px-5 py-3 text-sm font-bold text-white disabled:opacity-50" disabled={busy||!state||!organization.can_bid} onClick={()=>void run({action:"apply",organizationId:organization.id,level:"verified"})}>Get verified</button></article>
  <article className="rounded-2xl border border-[#b98b28]/40 bg-gradient-to-br from-[#fffbeb] to-[#f6edce] p-6 shadow-sm"><FileCheck2 className="text-[#9c6d18]"/><h2 className="mt-3 text-xl font-bold">Enhanced Verified Supplier</h2><p className="mt-1 text-2xl font-bold text-[#72501a]">GH₵{((state?.settings?.enhanced_price_minor||50000)/100).toLocaleString("en-GH")}</p><p className="mt-2 text-sm leading-6">Additional applicable tax, licence, ownership, address and compliance checks with manual BidScope review.</p><p className="mt-3 rounded-xl bg-white/80 p-3 text-sm font-semibold">The Enhanced Verification Fee covers additional verification and compliance checks. Payment does not guarantee Enhanced Verified status.</p><button className="mt-5 rounded-full bg-[#8a621a] px-5 py-3 text-sm font-bold text-white disabled:opacity-50" disabled={busy||!state||!organization.can_bid} onClick={()=>void run({action:"apply",organizationId:organization.id,level:"enhanced_verified"})}>Apply for enhanced review</button></article></section>
  {current&&<section className="rounded-2xl border border-[#143e32]/15 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-[#638176]">Current application</p><h2 className="mt-1 text-xl font-bold">{label(current.requested_level)} · {label(current.status)}</h2><p className="text-sm text-[#64766e]">Payment: {label(current.payment_status)} · Submitted {new Date(current.created_at).toLocaleDateString("en-GB")}</p></div>{current.requested_level==="enhanced_verified"&&current.status==="awaiting_payment"&&<button disabled={busy} className="rounded-full bg-[#8a621a] px-5 py-3 text-sm font-bold text-white" onClick={()=>void run({action:"checkout",requestId:current.id})}>Continue to secure Paystack checkout</button>}</div>{current.decision_reason&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">Review note: {current.decision_reason}</p>}
   <div className="mt-5 grid gap-4 md:grid-cols-2"><div><h3 className="font-bold">Review checklist</h3><ul className="mt-2 space-y-2 text-sm">{state?.checks.filter(check=>check.request_id===current.id).map(check=><li key={check.id} className="flex justify-between gap-4 border-b py-2"><span>{label(check.check_type)}</span><span className="font-semibold">{label(check.status)}</span></li>)}</ul></div><div><h3 className="font-bold">Supporting documents</h3><ul className="mt-2 space-y-2 text-sm">{state?.documents.filter(doc=>doc.request_id===current.id).map(doc=><li key={doc.id} className="flex justify-between gap-3 border-b py-2"><span>{doc.document_type} · {doc.original_filename}<small className="block text-[#64766e]">Integrity screen: {label(doc.risk_level)} risk; official authenticity not yet established</small></span><button className="underline" onClick={()=>void downloadAuthenticatedFile(`/api/supplier-verification/documents?id=${doc.id}`,doc.original_filename)}>Download</button></li>)}</ul></div></div>
   {["draft","awaiting_payment","paid","information_required"].includes(current.status)&&<div className="mt-6 rounded-xl bg-[#f4f8f5] p-4"><h3 className="font-bold">Add evidence</h3><p className="mb-3 text-sm text-[#596d63]">Upload registration, tax or applicable licences. Files stay private. Automated flags are for human review, not proof of authenticity.</p><div className="flex flex-wrap items-center gap-3"><input aria-label="Document type" className="rounded-lg border p-2" value={documentType} onChange={event=>setDocumentType(event.target.value)}/><input aria-label="Document file" type="file" accept="application/pdf,image/png,image/jpeg" onChange={event=>setFile(event.target.files?.[0]||null)}/><button disabled={busy||!file} onClick={()=>void upload()} className="inline-flex items-center gap-2 rounded-full bg-[#116149] px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><UploadCloud size={16}/> Upload privately</button></div>{["draft","paid","information_required"].includes(current.status)&&<button disabled={busy} onClick={()=>void run({action:"submit",requestId:current.id})} className="mt-4 rounded-full border border-[#116149] px-5 py-2 text-sm font-bold text-[#116149]">Submit for review</button>}</div>}</section>}
  {!!state?.requests.length&&<section className="rounded-2xl bg-white p-6"><h2 className="font-bold">Application history</h2><div className="mt-3 flex flex-wrap gap-2">{state.requests.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={`rounded-full border px-3 py-2 text-sm ${current?.id===item.id?"bg-[#116149] text-white":"bg-white"}`}>{label(item.requested_level)} · {label(item.status)}</button>)}</div></section>}
  <p className="text-sm text-[#64766e]">BidScope verification is not a government endorsement, a guarantee of buyer trust, or a promise of a tender award. Applicable checks depend on the supplier’s sector. Payment and refund eligibility are reviewed under the applicable service terms.</p>
 </div>;
}
