import {apiErrorResponse} from "@/lib/server/api-error";
import {requireUser} from "@/lib/server/auth";
import {primaryOrganization,requireEntitlement} from "@/lib/server/entitlements";
import {supabaseRpc} from "@/lib/server/supabase-rest";

export const dynamic="force-dynamic";
const allowed=new Set(["q","scope","stage","collection","sort","country","sector","buyer","source","region","category","contractType","procurementMethod","funding","currency","eligibility","minimumValue","maximumValue","match","days","deadlineBefore","publishedAfter"]);
function safeCell(value:unknown){let text=value==null?"":Array.isArray(value)?value.join("; "):String(value);if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`;}

export async function GET(request:Request){try{const{user}=await requireUser(request);const membership=await primaryOrganization(user.id);if(!membership)throw new Error("Create a business profile before exporting opportunities.");await requireEntitlement(membership.organization_id,"csv_exports",user);const params=new URL(request.url).searchParams;const filters=Object.fromEntries([...params].filter(([key,value])=>allowed.has(key)&&value!==""));const rows:Array<Record<string,unknown>>=[];for(let page=1;page<=10;page++){const{data}=await supabaseRpc<{data:Array<Record<string,unknown>>;pagination:{total:number}}>("customer_discover",{p_user:user.id,filters,page_number:page,page_size:100});rows.push(...data.data);if(rows.length>=data.pagination.total||data.data.length<100)break;}const columns:[[string,string],...Array<[string,string]>]=[["title","Opportunity"],["buyer_name","Buyer"],["country","Country"],["sector","Sector"],["category","Category"],["estimated_value","Estimated value"],["currency","Currency"],["published_at","Published"],["deadline_at","Deadline"],["eligibility_status","Eligibility"],["source_name","Source"],["external_reference","Reference"],["official_tender_url","Official tender URL"],["official_source_url","Official source URL"]];const csv="\uFEFF"+[columns.map(([,label])=>safeCell(label)).join(","),...rows.map(row=>columns.map(([key])=>safeCell(row[key])).join(","))].join("\r\n");return new Response(csv,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":'attachment; filename="bidscope-opportunities.csv"',"Cache-Control":"private, no-store"}});}catch(error){return apiErrorResponse(error);}}
