"use client";
import { FormEvent,useEffect,useState } from "react";
import { FileCheck2,Plus,ShieldAlert } from "lucide-react";
type Doc={id:string;document_type:string;title:string;source_url:string|null;issued_at:string|null;expires_at:string|null;verification_status:string};
export function SupplierReadiness(){const[organizationId,setOrganizationId]=useState<string|null>(null);const[docs,setDocs]=useState<Doc[]>([]);const[message,setMessage]=useState("Loading Supplier Passport…");const[adding,setAdding]=useState(false);
  async function load(id:string){const token=localStorage.getItem("bidscope_access_token");if(!token)return;const response=await fetch(`/api/supplier-documents?organizationId=${id}`,{headers:{Authorization:`Bearer ${token}`}});const body=await response.json() as {data?:Doc[]};setDocs(body.data||[]);setMessage("");}
  useEffect(()=>{const token=localStorage.getItem("bidscope_access_token");if(!token){void Promise.resolve().then(()=>setMessage("Sign in to manage your Supplier Passport."));return;}void fetch("/api/organizations",{headers:{Authorization:`Bearer ${token}`}}).then(async r=>await r.json() as {data?:Array<{organization:{id:string}}>}).then(body=>{const id=body.data?.[0]?.organization.id||null;setOrganizationId(id);if(id)void load(id);else setMessage("Create a business profile before adding compliance documents.");});},[]);
  async function add(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!organizationId)return;const form=new FormData(event.currentTarget);const token=localStorage.getItem("bidscope_access_token");if(!token)return;const response=await fetch("/api/supplier-documents",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({organizationId,documentType:form.get("documentType"),title:form.get("title"),sourceUrl:form.get("sourceUrl")||null,expiresAt:form.get("expiresAt")||null})});if(response.ok){setAdding(false);void load(organizationId);}else setMessage("The document record could not be saved.");}
  // The timestamp is a display-only snapshot for expiry styling.
  // eslint-disable-next-line react-hooks/purity
  const today=Date.now();return <section className="mx-auto max-w-5xl px-5 py-10 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#16805e]">Supplier Passport</p><h1 className="serif mt-2 text-4xl text-[#17362d] sm:text-5xl">Compliance readiness</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#61736a]">Track the evidence BidScope may compare against verified tender requirements. Records stay marked Needs Review until there is enough evidence to verify them.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setAdding(!adding)} className="inline-flex h-11 items-center gap-2 rounded-full bg-[#116149] px-5 text-sm font-bold text-white"><Plus size={16}/>Add document record</button><a href="/settings/alerts" className="inline-flex h-11 items-center rounded-full border bg-white px-5 text-sm font-bold text-[#315b4e]">Expiry alert settings</a></div>{adding&&<form onSubmit={add} className="mt-5 grid gap-4 rounded-[24px] border bg-[#fffdf8] p-5 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Document type<input required name="documentType" placeholder="Tax Clearance" className="h-11 rounded-xl border px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold">Title<input required name="title" placeholder="2026 Tax Clearance Certificate" className="h-11 rounded-xl border px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold">Secure source URL (optional)<input name="sourceUrl" type="url" className="h-11 rounded-xl border px-3 font-normal"/></label><label className="grid gap-1 text-xs font-bold">Expiry date<input name="expiresAt" type="date" className="h-11 rounded-xl border px-3 font-normal"/></label><button className="h-11 rounded-full bg-[#17362d] px-5 text-sm font-bold text-white sm:col-span-2 sm:w-fit">Save for review</button></form>}{message&&<p className="mt-8 rounded-2xl border border-dashed bg-white/60 p-8 text-center text-sm text-[#61736a]">{message}</p>}<div className="mt-7 grid gap-3">{docs.map(doc=>{const expiring=doc.expires_at&&new Date(doc.expires_at).getTime()-today<30*86400000;return <article key={doc.id} className="flex flex-col justify-between gap-4 rounded-[22px] border bg-[#fffdf8] p-5 sm:flex-row sm:items-center"><div className="flex gap-3">{expiring?<ShieldAlert className="shrink-0 text-[#c45b40]"/>:<FileCheck2 className="shrink-0 text-[#16805e]"/>}<div><h2 className="font-bold text-[#17362d]">{doc.title}</h2><p className="mt-1 text-xs text-[#64766e]">{doc.document_type} · {doc.expires_at?`Expires ${new Date(doc.expires_at).toLocaleDateString("en-GB")}`:"No expiry recorded"}</p></div></div><span className={`w-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase ${doc.verification_status==="verified"?"bg-[#dff1e7] text-[#146044]":"bg-[#f2e8cb] text-[#765618]"}`}>{doc.verification_status.replace("_"," ")}</span></article>})}</div></section>}
