import {z} from "zod";
import {requireOrganizationMember,requireUser} from "@/lib/server/auth";
import {ApiError,apiErrorResponse} from "@/lib/server/api-error";
import {supabaseRest} from "@/lib/server/supabase-rest";
import {assessOpportunityForUser,refreshOrganizationRetention} from "@/lib/server/procurement/retention";
import {getEntitlement,primaryOrganization,requireEntitlement} from "@/lib/server/entitlements";

export const dynamic="force-dynamic";
const uuid=z.string().uuid();
function freeOverview(data:Awaited<ReturnType<typeof refreshOrganizationRetention>>){return{...data,bestMatch:null,radar:[],matches:data.matches.slice(0,3).map(item=>({...item,assessment:{...item.assessment,decision:"UNKNOWN",components:{...item.assessment.components,eligibility:null,capability:null,financialFit:null,experienceFit:null,documentReadiness:null,deadlineFeasibility:null},reasons:item.assessment.reasons.slice(0,1),concerns:[],evidence:{basicRecommendation:true}}})),readiness:data.readiness?{...data.readiness,categoryScores:{},recommendations:[],evidence:{basicScore:true}}:null};}
export async function GET(request:Request){try{const{user}=await requireUser(request);const params=new URL(request.url).searchParams;const resource=params.get("resource")||"overview";const membership=await primaryOrganization(user.id);
 if(resource==="overview"){const data=await refreshOrganizationRetention(user.id);if(!membership)return Response.json({data:{...data,entitlement:{tier:"FREE",status:"FREE"}}});const entitlement=await getEntitlement(membership.organization_id);return Response.json({data:{...(entitlement.tier==="PREMIUM"?data:freeOverview(data)),entitlement:{tier:entitlement.tier,status:entitlement.status}}});}
 if(resource==="decision"){if(!membership)throw new ApiError(404,"Add a business profile before requesting a bid decision.","profile_required");await requireEntitlement(membership.organization_id,"bid_advisor");const data=await assessOpportunityForUser(user.id,uuid.parse(params.get("opportunityId")),true);if(!data)throw new ApiError(404,"Add a business profile before requesting a bid decision.","profile_required");return Response.json({data});}
 throw new ApiError(400,"Unknown retention resource.","invalid_resource");
}catch(error){return apiErrorResponse(error);}}

export async function POST(request:Request){try{const{user}=await requireUser(request);const body=z.object({resource:z.enum(["feedback","recalculate","feed_view"]),organizationId:uuid.optional(),opportunityId:uuid.optional(),action:z.enum(["hidden","not_relevant"]).optional(),reasonCode:z.enum(["WRONG_SECTOR","TOO_SMALL","TOO_LARGE","WRONG_COUNTRY","NOT_ELIGIBLE","WRONG_SERVICE","DEADLINE_TOO_CLOSE","OTHER"]).optional(),reason:z.string().trim().max(500).optional()}).parse(await request.json());
 if(body.resource==="feedback"){if(!body.organizationId||!body.opportunityId||!body.action)throw new ApiError(400,"Business, opportunity and feedback action are required.","invalid_feedback");await requireOrganizationMember(user.id,body.organizationId);await supabaseRest("opportunity_feedback?on_conflict=user_id,opportunity_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({user_id:user.id,organization_id:body.organizationId,opportunity_id:body.opportunityId,action:body.action,reason_code:body.reasonCode||null,reason:body.reason||null,updated_at:new Date().toISOString()})});const data=await refreshOrganizationRetention(user.id);return Response.json({data:{saved:true,bestMatch:data.bestMatch}});}
 if(body.resource==="feed_view"){await supabaseRest("customer_preferences?on_conflict=user_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({user_id:user.id,last_feed_view_at:new Date().toISOString(),updated_at:new Date().toISOString()})});return Response.json({data:{recorded:true}});}
 const data=await refreshOrganizationRetention(user.id);const membership=await primaryOrganization(user.id);if(!membership)return Response.json({data});const entitlement=await getEntitlement(membership.organization_id);return Response.json({data:entitlement.tier==="PREMIUM"?data:freeOverview(data)});
}catch(error){return apiErrorResponse(error);}}
