/* eslint-disable @next/next/no-html-link-for-pages */
"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, Clipboard, Clock3, ExternalLink, FileCheck2, ShieldCheck, X } from "lucide-react";
import { SourceBadge } from "@/components/procurement/source-badge";

type Opportunity = { id:string; bidscope_reference:string; title:string; summary:string; description:string; buyer_name:string; buyer_type:string|null; region:string|null; sector:string|null; category:string; procurement_method:string|null; contract_type:string|null; currency:string|null; estimated_value:number|null; published_at:string|null; deadline_at:string|null; status:string; source_name:string; external_reference:string|null; official_source_url:string; official_tender_url:string|null; official_submission_url:string|null; submission_platform:string|null; requires_registration:boolean; registration_url:string|null; funding_source:string; funding_agency:string|null; eligibility_text:string|null; documents_url:string|null; last_verified_at:string|null; data_confidence:string; project:{external_project_id:string;name:string;country:string|null;sector:string|null;status:string|null;financing_institution:string;official_url:string}|null; submission:{destination:string;label:string}; intelligence:Record<string,string> };

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "long", timeStyle: "short" }).format(new Date(value)) : "Not provided by source"; }

export function OpportunityDetail({ slug }: { slug: string }) {
  const [item, setItem] = useState<Opportunity | null>(null); const [error, setError] = useState("");
  const [ready, setReady] = useState(false); const [returned, setReturned] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { fetch(`/api/opportunities/${encodeURIComponent(slug)}`).then(async (response) => { const body = await response.json() as { data?: Opportunity; error?: string }; if (!response.ok || !body.data) throw new Error(body.error || "Opportunity could not be loaded."); setItem(body.data); }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : "Opportunity could not be loaded.")); }, [slug]);
  async function copyReference() { if (!item) return; await navigator.clipboard.writeText(item.external_reference || item.bidscope_reference); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  async function continueOfficial() {
    if (!item) return; let destination = item.submission.destination;
    const token = window.localStorage.getItem("bidscope_access_token");
    if (token) { const response = await fetch(`/api/opportunities/${item.id}/submission`, { method: "POST", headers: { Authorization: `Bearer ${token}` } }); if (response.ok) destination = ((await response.json()) as { data:{destination:string} }).data.destination; }
    window.open(destination, "_blank", "noopener,noreferrer"); setReady(false); setReturned(true);
  }
  async function updateStatus(status: "SUBMITTED" | "PREPARING") {
    if (!item) return; const token = window.localStorage.getItem("bidscope_access_token");
    if (!token) { setError("Sign in is required to save bid progress. Your official portal remains open."); return; }
    const response = await fetch("/api/bids", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ opportunityId: item.id, status, notes: "" }) });
    if (!response.ok) setError("Your bid status could not be saved. Please try again."); else setReturned(false);
  }

  if (error && !item) return <div className="mx-auto max-w-4xl px-5 py-20"><a href="/opportunities" className="text-sm font-semibold text-[#116149]">← Back to opportunities</a><p className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{error}</p></div>;
  if (!item) return <div className="mx-auto max-w-5xl px-5 py-16"><div className="h-96 animate-pulse rounded-[28px] bg-white"/></div>;
  const facts = [["Buyer",item.buyer_name || "Not yet normalised"],["Tender reference",item.external_reference || item.bidscope_reference],["Deadline",formatDate(item.deadline_at)],["Procurement method",item.procurement_method || "Not provided"],["Notice type",item.contract_type || "Not provided"],["Project",item.project ? `${item.project.name} (${item.project.external_project_id})` : "Not provided by source"],["Project status",item.project?.status || "Not provided by source"],["Funding",item.project?.financing_institution || item.funding_agency || item.funding_source]];
  return <><section className="border-b border-[#17362d]/10 bg-[#fffdf8]"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-6 lg:px-8"><a href="/opportunities" className="inline-flex items-center gap-2 text-sm font-semibold text-[#547067]"><ArrowLeft size={16}/>All opportunities</a><div className="mt-7 flex flex-wrap gap-2"><SourceBadge source={item.source_name}/><span className="rounded-full bg-[#e7efe9] px-2.5 py-1 text-[10px] font-bold text-[#285547]">{item.status}</span><span className="rounded-full border border-[#17362d]/10 px-2.5 py-1 text-[10px] font-semibold text-[#61736a]">{item.data_confidence.replaceAll("_", " ")}</span></div><h1 className="serif mt-5 max-w-4xl text-4xl font-medium leading-[1.04] tracking-[-.04em] text-[#17362d] sm:text-6xl">{item.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-[#65776f] sm:text-lg">{item.summary}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button onClick={() => setReady(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-[#116149] px-6 text-sm font-bold text-white hover:-translate-y-0.5">{item.submission.label}<ArrowUpRight size={17}/></button><a href={item.official_source_url} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-2 rounded-full border border-[#17362d]/15 bg-white px-6 text-sm font-bold text-[#17362d]">View Official Source<ExternalLink size={16}/></a></div></div></section>
  <section className="mx-auto grid max-w-6xl gap-6 px-5 py-8 sm:px-6 lg:grid-cols-[1fr_320px] lg:px-8"><div className="space-y-5"><article className="rounded-[24px] border border-[#17362d]/10 bg-[#fffdf8] p-6"><h2 className="serif text-2xl text-[#17362d]">Opportunity overview</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-[#5e7168]">{item.description || "The source did not provide a verified detailed description."}</p></article>{["Why This May Suit You","Buyer Intelligence","Previous Contracts","Past Winners","Historical Award Values","Procurement Frequency","Procurement Seasonality","Competition Insights"].map((title) => <article key={title} className="rounded-[20px] border border-[#17362d]/10 bg-[#fffdf8] p-5"><h2 className="font-bold text-[#17362d]">{title}</h2><p className="mt-2 text-sm text-[#6a7972]">Not enough verified data available.</p></article>)}<article className="rounded-[24px] border border-[#17362d]/10 bg-[#fffdf8] p-6"><h2 className="serif text-2xl text-[#17362d]">Eligibility & documents</h2><p className="mt-4 text-sm leading-7 text-[#5e7168]">{item.eligibility_text || "Not enough verified data available."}</p>{item.documents_url && <a href={item.documents_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#116149]">Open official documents <ExternalLink size={15}/></a>}</article></div><aside className="space-y-4"><div className="rounded-[24px] bg-[#103f32] p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#89d8b8]">Tender facts</p><dl className="mt-4 space-y-4">{facts.map(([label,value]) => <div key={label} className="border-b border-white/10 pb-3 last:border-0"><dt className="text-[10px] uppercase tracking-wider text-white/45">{label}</dt><dd className="mt-1 text-sm font-semibold leading-5">{value}</dd></div>)}</dl><button onClick={copyReference} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#d8c07d]"><Clipboard size={14}/>{copied ? "Copied" : "Copy reference"}</button></div><div className="rounded-[20px] border border-[#17362d]/10 bg-[#e8efe9] p-5 text-xs leading-6 text-[#466359]"><ShieldCheck size={20}/><p className="mt-2 font-bold text-[#17362d]">Source traceability</p><p>Published by {item.source_name}. Last checked {formatDate(item.last_verified_at)}.</p></div></aside></section>
  {ready && <div className="fixed inset-0 z-50 grid place-items-center bg-[#0a2d24]/70 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="max-h-[92vh] w-full max-w-xl overflow-auto rounded-[26px] bg-[#fffdf8] p-6 shadow-2xl sm:p-8"><button onClick={() => setReady(false)} className="float-right rounded-full p-2 hover:bg-[#edf1eb]" aria-label="Close"><X size={18}/></button><p className="text-xs font-bold uppercase tracking-[.16em] text-[#116149]">Ready to submit</p><h2 className="serif mt-3 pr-8 text-3xl text-[#17362d]">{item.title}</h2><div className="mt-5 grid gap-2 text-sm text-[#5f7169]"><p><strong>Buyer:</strong> {item.buyer_name}</p><p><strong>Reference:</strong> {item.external_reference || item.bidscope_reference}</p><p><strong>Deadline:</strong> {formatDate(item.deadline_at)}</p><p><strong>Source:</strong> {item.source_name}</p></div><div className="mt-6 rounded-2xl border border-[#17362d]/10 bg-[#f5f1e7] p-4"><p className="text-xs font-bold uppercase tracking-wider">Preparation checklist</p>{["Business Registration","Tax Clearance","SSNIT","Tender Documents","Technical Documents","Financial Proposal"].map((label) => <label key={label} className="mt-3 flex items-center gap-3 text-sm"><input type="checkbox" className="size-4 accent-[#116149]"/>{label}</label>)}</div><p className="mt-5 text-sm leading-6 text-[#667970]">Official submission takes place through {item.submission_platform || item.source_name}. BidScope does not receive the formal bid.</p><button onClick={continueOfficial} className="mt-5 inline-flex h-12 w-full items-center justify-center gap-2 rounded-full bg-[#116149] text-sm font-bold text-white">Continue to Official Submission <ArrowUpRight size={16}/></button></div></div>}
  {returned && <div className="fixed bottom-4 left-4 right-4 z-40 mx-auto max-w-2xl rounded-[22px] border border-[#17362d]/15 bg-[#fffdf8] p-5 shadow-2xl"><div className="flex gap-3"><Clock3 className="shrink-0 text-[#116149]"/><div><p className="font-bold text-[#17362d]">Official procurement portal opened in another tab.</p><p className="mt-1 text-sm text-[#687970]">Return here when you have completed your submission.</p></div></div>{error && <p className="mt-3 text-xs text-amber-800">{error}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => updateStatus("SUBMITTED")} className="rounded-full bg-[#116149] px-4 py-2 text-xs font-bold text-white"><Check className="mr-1 inline" size={14}/>I&apos;ve Submitted</button><button onClick={() => updateStatus("PREPARING")} className="rounded-full border px-4 py-2 text-xs font-bold">I&apos;m Still Preparing</button><button onClick={copyReference} className="rounded-full border px-4 py-2 text-xs font-bold"><Clipboard className="mr-1 inline" size={14}/>Copy Tender Reference</button><a href={item.submission.destination} target="_blank" rel="noreferrer" className="rounded-full border px-4 py-2 text-xs font-bold"><FileCheck2 className="mr-1 inline" size={14}/>Reopen Official Tender</a></div></div>}</>;
}
