import {apiErrorResponse} from "@/lib/server/api-error";
import {requireCronOrInternalSecret} from "@/lib/server/auth";
import {supabaseRest} from "@/lib/server/supabase-rest";
import {createNotification} from "@/lib/server/notifications";

export const dynamic="force-dynamic";export const maxDuration=60;

export async function GET(request:Request){try{requireCronOrInternalSecret(request);const now=new Date(),soon=new Date(now.getTime()+7*86400000);const{data:tenders}=await supabaseRest<Array<{id:string;organization_id:string;title:string;status:string;issue_date:string|null;submission_deadline:string}>>(`procurement_tenders?select=id,organization_id,title,status,issue_date,submission_deadline&status=in.(scheduled,live,closing_soon)&limit=1000`);let changed=0;for(const tender of tenders){let next=tender.status;if(tender.status==="scheduled"&&(!tender.issue_date||Date.parse(tender.issue_date)<=now.getTime()))next="live";if(["live","closing_soon"].includes(next)&&Date.parse(tender.submission_deadline)<=now.getTime())next="closed";else if(next==="live"&&Date.parse(tender.submission_deadline)<=soon.getTime())next="closing_soon";if(next===tender.status)continue;await supabaseRest(`procurement_tenders?id=eq.${tender.id}`,{method:"PATCH",body:JSON.stringify({status:next})});await supabaseRest("procurement_audit_logs",{method:"POST",body:JSON.stringify({organization_id:tender.organization_id,tender_id:tender.id,action:`tender_${next}`,entity_type:"procurement_tender",entity_id:tender.id,before_data:{status:tender.status},after_data:{status:next},metadata:{automated:true}})});if(next==="closing_soon"||next==="closed"){const{data:bidders}=await supabaseRest<Array<{created_by:string;supplier_organization_id:string}>>(`supplier_bids?select=created_by,supplier_organization_id&tender_id=eq.${tender.id}&status=neq.withdrawn`);await Promise.all(bidders.map(b=>createNotification({userId:b.created_by,organizationId:b.supplier_organization_id,type:"system",title:next==="closed"?"Tender closed":"Tender closing soon",message:`${tender.title} ${next==="closed"?"is now closed for submissions.":"closes within seven days."}`,relatedEntityType:"procurement_tender",relatedEntityId:tender.id,relatedUrl:`/customer/bidscope-tenders/${tender.id}`,priority:next==="closed"?"normal":"high",frequencyOverride:"instant",dedupeKey:`procurement-${next}-${tender.id}-${b.created_by}`})));}changed++;}return Response.json({ok:true,checked:tenders.length,changed});}catch(error){return apiErrorResponse(error);}}
export async function POST(request:Request){return GET(request)}
