"use client";
import { useState } from "react";
import { ShieldAlert, ShieldCheck } from "lucide-react";
import { api, downloadAuthenticatedFile, invalidate, useData } from "@/components/customer/data";

type Application={id:string;organization_id:string;requested_level:string;status:string;payment_status:string;amount_minor:number;currency:string;created_at:string;expiry_date:string|null;decision_reason:string|null;risk_level:string;eligible_for_refund:boolean|null;refund_status:string;assigned_to:string|null};
type Check={id:string;request_id:string;check_type:string;status:string;source:string|null;evidence_reference:string|null;notes:string|null};
type Doc={id:string;request_id:string;document_type:string;original_filename:string;risk_level:string;integrity_flags:string[];sha256:string};
type Data={requests:Application[];organizations:Array<{id:string;name:string;registration_number:string|null;region:string|null;sectors:string[]}>;checks:Check[];documents:Doc[];statuses:Array<{organization_id:string;level:string;effective_level:string;expires_at:string|null}>;settings:{enhanced_price_minor:number;currency:string;validity_months:number};analytics:{applications:number;paidApplications:number;approvals:number;rejections:number;pendingReviews:number;informationRequired:number;expiringSoon:number;confirmedRevenueMinor:number;refundReviewCount:number}};
const show=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function SupplierVerificationsAdmin(){
 const [filter,setFilter]=useState("all"),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const result=useData<{data:Data}>(`/api/admin/supplier-verifications?status=${filter}`);
 const data=result.data?.data,application=data?.requests.find(item=>item.id===selected)||data?.requests[0];
 async function post(body:Record<string,unknown>){setBusy(true);try{await api("/api/admin/supplier-verifications",body);invalidate();setMessage("Review action saved to the audit trail.");}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 function decide(decision:"approve"|"reject"|"request_information"|"start_review"){
  if(!application)return;
  const reason=window.prompt(decision==="approve"?"Record approval evidence and rationale":"Record the review reason","");
  if(reason===null||decision!=="start_review"&&!reason.trim())return;
  void post({action:"decision",requestId:application.id,decision,reason:reason.trim()});
 }
 const counts={basic:0,verified:0,enhanced_verified:0};for(const item of data?.statuses||[]){const level=item.effective_level;if(level in counts)counts[level as keyof typeof counts]++;}
 const expiring=data?.analytics.expiringSoon||0;
 return <main className="mx-auto max-w-7xl space-y-6 p-5 text-[#17362d] sm:p-8"><header className="rounded-3xl bg-gradient-to-r from-[#092f26] to-[#157152] p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-[#dec36a]">BidScope trust operations</p><h1 className="mt-2 text-3xl font-bold">Supplier Verification</h1><p className="mt-2 text-white/75">Official-source evidence, document review, payment reconciliation and human decisions.</p></header>
 {message&&<p role="status" className="rounded-xl bg-white p-3">{message}</p>}{result.error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{result.error}</p>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Basic suppliers",counts.basic],["Verified",counts.verified],["Enhanced verified",counts.enhanced_verified],["Pending review",data?.analytics.pendingReviews||0],["Information required",data?.analytics.informationRequired||0],["Expiring within 60 days",expiring],["Enhanced applications paid",data?.analytics.paidApplications||0],["Confirmed service fees",`GH₵${((data?.analytics.confirmedRevenueMinor||0)/100).toLocaleString("en-GH")}`]].map(([title,value])=><div key={title} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-[#657870]">{title}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</section>
 <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">Future application settings</h2><p className="text-sm text-[#657870]">Changing these values does not change historical charges.</p><form className="mt-3 flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void post({action:"settings",enhancedPriceMinor:Math.round(Number(form.get("price"))*100),validityMonths:Number(form.get("months"))});}}><label className="text-sm">Enhanced fee (GHS)<input name="price" type="number" min="0" step="0.01" defaultValue={(data?.settings.enhanced_price_minor||50000)/100} className="mt-1 block rounded-lg border p-2"/></label><label className="text-sm">Validity (months)<input name="months" type="number" min="1" max="60" defaultValue={data?.settings.validity_months||12} className="mt-1 block rounded-lg border p-2"/></label><button disabled={busy} className="rounded-full bg-[#116149] px-5 py-2 text-sm font-bold text-white">Save settings</button></form></section>
 <div className="grid gap-5 xl:grid-cols-[330px_1fr]"><section className="rounded-2xl bg-white p-4 shadow-sm"><label className="text-sm font-bold">Review queue<select value={filter} onChange={event=>{setFilter(event.target.value);setSelected(null);}} className="mt-2 block w-full rounded-lg border p-2">{["all","submitted","under_review","information_required","approved","rejected","expired"].map(value=><option key={value} value={value}>{show(value)}</option>)}</select></label><div className="mt-4 space-y-2">{data?.requests.map(item=>{const org=data.organizations.find(org=>org.id===item.organization_id);return <button key={item.id} onClick={()=>setSelected(item.id)} className={`w-full rounded-xl border p-3 text-left text-sm ${item.id===application?.id?"border-[#116149] bg-emerald-50":"border-[#e1e9e3]"}`}><strong className="block">{org?.name||"Supplier"}</strong><span className="text-[#5b7166]">{show(item.requested_level)} · {show(item.status)}</span></button>;})}{!data?.requests.length&&<p className="text-sm text-[#657870]">No applications in this queue.</p>}</div></section>
 <section className="space-y-5">{application?(()=>{const org=data?.organizations.find(item=>item.id===application.organization_id);return <><article className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-[#116149]">{show(application.requested_level)}</p><h2 className="mt-1 text-2xl font-bold">{org?.name||"Supplier"}</h2><p className="text-sm text-[#657870]">Registration: {org?.registration_number||"Not supplied"} · {org?.region||"Region not supplied"} · {org?.sectors.join(", ")||"Sectors not supplied"}</p></div><span className="self-start rounded-full bg-[#e9f5ee] px-3 py-2 text-sm font-bold">{show(application.status)}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><p className="rounded-xl bg-[#f6f8f5] p-3 text-sm"><strong>Payment</strong><br/>{show(application.payment_status)} · {application.currency} {(application.amount_minor/100).toLocaleString()}</p><p className="rounded-xl bg-[#f6f8f5] p-3 text-sm"><strong>Integrity risk</strong><br/>{show(application.risk_level)}</p><p className="rounded-xl bg-[#f6f8f5] p-3 text-sm"><strong>Valid until</strong><br/>{application.expiry_date?new Date(application.expiry_date).toLocaleDateString("en-GB"):"Not approved"}</p></div>{application.decision_reason&&<p className="mt-4 text-sm">Decision note: {application.decision_reason}</p>}</article>
 <article className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="flex items-center gap-2 text-lg font-bold"><FileIcon/> Private evidence</h3><button disabled={busy} onClick={()=>void post({action:"rerun_screening",requestId:application.id})} className="rounded-full border px-4 py-2 text-sm font-bold">Re-run file screening</button></div><p className="mt-2 text-sm text-[#657870]">Screening detects signatures, duplicate hashes and storage changes; it cannot prove authenticity.</p><div className="mt-3 space-y-3">{data?.documents.filter(item=>item.request_id===application.id).map(doc=><div key={doc.id} className="rounded-xl border p-3 text-sm"><div className="flex justify-between gap-2"><strong>{doc.document_type}: {doc.original_filename}</strong><button className="underline" onClick={()=>void downloadAuthenticatedFile(`/api/supplier-verification/documents?id=${doc.id}`,doc.original_filename)}>Download privately</button></div><p className="mt-1 text-[#657870]">Risk: {show(doc.risk_level)} · Flags: {doc.integrity_flags.join(", ")||"No obvious file-signature or duplicate issue"}</p><p className="break-all text-xs text-[#657870]">SHA-256: {doc.sha256}</p></div>)}</div></article>
 <article className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="flex items-center gap-2 text-lg font-bold"><ShieldCheck size={18}/> Verification checklist</h3><p className="mt-1 text-sm text-[#657870]">Record official source, lookup reference and notes for each manual check. AI screening cannot declare a document genuine.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{data?.checks.filter(check=>check.request_id===application.id).map(check=><CheckEditor key={check.id} check={check} busy={busy} onSave={values=>void post({action:"check",requestId:application.id,checkType:check.check_type,...values})}/>)}</div></article>
 <article className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="text-lg font-bold">Human decision</h3><p className="mt-1 text-sm text-[#657870]">Payment alone never grants a badge. Approval requires all core checks passed and all contextual checks passed or documented as not applicable.</p><p className="mt-2 text-sm">Reviewer: {application.assigned_to?"Assigned":"Unassigned"}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void post({action:"assign_to_me",requestId:application.id})} className="rounded-full border px-4 py-2 text-sm font-bold">Assign to me</button><button disabled={busy} onClick={()=>decide("start_review")} className="rounded-full border px-4 py-2 text-sm font-bold">Start review</button><button disabled={busy} onClick={()=>decide("request_information")} className="rounded-full border px-4 py-2 text-sm font-bold">Request information</button><button disabled={busy} onClick={()=>decide("reject")} className="rounded-full bg-red-100 px-4 py-2 text-sm font-bold text-red-800">Reject</button><button disabled={busy} onClick={()=>decide("approve")} className="rounded-full bg-[#116149] px-4 py-2 text-sm font-bold text-white">Approve</button></div></article>
 <article className="rounded-2xl bg-white p-6 shadow-sm"><h3 className="text-lg font-bold">Refund eligibility review</h3><p className="mt-1 text-sm text-[#657870]">This records a policy review only. It does not issue a Paystack refund or promise eligibility.</p><p className="mt-2 text-sm">Current: {show(application.refund_status)} · Eligible: {application.eligible_for_refund===null?"Undetermined":application.eligible_for_refund?"Yes":"No"}</p><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void post({action:"refund_review",requestId:application.id,eligible:form.get("eligible")==="yes",status:String(form.get("status")),reason:String(form.get("reason"))});}}><label className="text-sm">Eligibility<select name="eligible" className="mt-1 block rounded-lg border p-2"><option value="no">Not eligible</option><option value="yes">Eligible for review</option></select></label><label className="text-sm">Review status<select name="status" className="mt-1 block rounded-lg border p-2"><option value="under_review">Under review</option><option value="approved">Approved for refund processing</option><option value="denied">Denied</option></select></label><label className="min-w-56 flex-1 text-sm">Reason<input name="reason" required maxLength={5000} className="mt-1 block w-full rounded-lg border p-2"/></label><button disabled={busy} className="rounded-full border px-4 py-2 text-sm font-bold">Record review</button></form></article>
 </>})():<div className="rounded-2xl bg-white p-7 text-[#657870]">Select an application to review.</div>}</section></div></main>;
}
function FileIcon(){return <ShieldAlert size={18}/>;}
function CheckEditor({check,busy,onSave}:{check:Check;busy:boolean;onSave:(values:Record<string,string>)=>void}){const [status,setStatus]=useState(check.status),[source,setSource]=useState(check.source||""),[evidenceReference,setEvidence]=useState(check.evidence_reference||""),[notes,setNotes]=useState(check.notes||"");return <div className="rounded-xl border p-3 text-sm"><strong>{show(check.check_type)}</strong><select aria-label={`${check.check_type} status`} value={status} onChange={event=>setStatus(event.target.value)} className="mt-2 block w-full rounded-lg border p-2">{["pending","passed","failed","needs_review","not_applicable"].map(value=><option key={value} value={value}>{show(value)}</option>)}</select><input aria-label="Official verification source" placeholder="Official source / authority" value={source} onChange={event=>setSource(event.target.value)} className="mt-2 w-full rounded-lg border p-2"/><input aria-label="Lookup reference" placeholder="Lookup or evidence reference" value={evidenceReference} onChange={event=>setEvidence(event.target.value)} className="mt-2 w-full rounded-lg border p-2"/><textarea aria-label="Review notes" placeholder="Review notes" value={notes} onChange={event=>setNotes(event.target.value)} className="mt-2 w-full rounded-lg border p-2"/><button disabled={busy||status==="pending"} className="mt-2 rounded-full bg-[#116149] px-4 py-2 font-bold text-white disabled:opacity-50" onClick={()=>onSave({status,source,evidenceReference,notes})}>Save check</button></div>}
