export type Guide={slug:string;title:string;description:string;updated:string;readingTime:string;sections:Array<{heading:string;paragraphs:string[];bullets?:string[]}>};
export const guides:Guide[]=[
 {slug:"how-to-find-tenders-in-ghana",title:"How to Find Tenders in Ghana",description:"A practical guide to finding public and private procurement opportunities, checking official requirements and setting focused tender alerts in Ghana.",updated:"2026-09-20",readingTime:"7 min read",sections:[
  {heading:"Start with the type of work your business can prove",paragraphs:["The best tender search starts with evidence, not ambition. List the goods, works or services your business can deliver and the locations, contract sizes and delivery times it can support."],bullets:["Products and services you currently deliver","Regions you can serve without unrealistic costs","Completed projects you can evidence","Licences and certifications that are still valid"]},
  {heading:"Use more than one discovery channel",paragraphs:["Public opportunities may appear on government procurement systems, institutional websites and development-finance portals. Private buyers may publish through their own procurement channels or managed platforms such as BidScope."],bullets:["Search by sector and procurement category","Watch repeat buyers and programmes","Set alerts for a small number of relevant keywords","Keep the official notice as the final authority"]},
  {heading:"Qualify before you invest time",paragraphs:["Read the eligibility, mandatory documents, submission method, location and deadline before preparing a response. If a condition is unclear, use the official clarification process rather than making an assumption."],bullets:["Confirm registration and tax requirements","Check experience and turnover thresholds","Identify bid security or tender-fee requirements","Allow time for signatures, uploads and physical delivery"]},
 ]},
 {slug:"how-to-bid-for-contracts-in-ghana",title:"How to Bid for Contracts in Ghana",description:"Understand the evidence, planning and compliance steps involved in preparing a competitive tender response in Ghana.",updated:"2026-09-20",readingTime:"9 min read",sections:[
  {heading:"Read the current tender documents",paragraphs:["Use the latest official notice, amendments and clarification responses. A summary can help you navigate the opportunity, but the issuing authority's documents determine what must be submitted."]},
  {heading:"Build a compliance matrix",paragraphs:["Turn every mandatory instruction and evaluation criterion into a checklist with an owner, evidence source and completion status."],bullets:["Eligibility and statutory documents","Technical response and methodology","Staff and experience evidence","Pricing schedule and currency","Submission format, naming and deadline"]},
  {heading:"Write to the published evaluation criteria",paragraphs:["Evaluators can only score the evidence in the response. Use specific examples, dates and outcomes, and connect each section directly to the stated requirement."],bullets:["Do not invent projects, staff or certifications","Explain assumptions and dependencies","Check arithmetic and pricing consistency","Complete an independent final review before submission"]},
 ]},
 {slug:"rfq-vs-rfp-vs-tender",title:"RFQ vs RFP vs Tender: What Is the Difference?",description:"A clear explanation of requests for quotations, requests for proposals and tenders for suppliers and procurement teams.",updated:"2026-09-20",readingTime:"6 min read",sections:[
  {heading:"Request for quotation (RFQ)",paragraphs:["An RFQ is commonly used when the buyer can define the required goods or services clearly and price is an important comparison factor. Suppliers still need to meet every stated specification and commercial condition."]},
  {heading:"Request for proposal (RFP)",paragraphs:["An RFP asks suppliers to propose an approach to a problem or outcome. The evaluation normally considers methodology, team, experience, delivery plan and price rather than price alone."]},
  {heading:"Invitation to tender",paragraphs:["A tender is a formal competitive process with defined instructions, eligibility conditions and evaluation rules. The exact terminology varies by buyer, so respond to the published documents rather than relying only on the label."]},
 ]},
 {slug:"how-to-prepare-a-tender-response",title:"How to Prepare a Tender Response",description:"A step-by-step framework for planning, writing, checking and submitting a compliant tender response.",updated:"2026-09-20",readingTime:"8 min read",sections:[
  {heading:"Make a bid or no-bid decision",paragraphs:["Confirm that the opportunity fits your capacity, evidence, location, timetable and commercial priorities. A disciplined no-bid decision protects time for stronger opportunities."]},
  {heading:"Plan the response backwards from the deadline",paragraphs:["Set internal deadlines for questions, evidence collection, pricing, approvals and final submission. Leave a practical buffer for portal or connectivity problems."],bullets:["Assign one accountable response lead","Record every required attachment","Freeze pricing before the final review","Submit early enough to obtain a receipt"]},
  {heading:"Run a final compliance review",paragraphs:["A reviewer who did not write the response should verify that every requirement is answered, attachments are current, signatures are present and the submission package follows the buyer's instructions."]},
 ]},
];
export function guideBySlug(slug:string){return guides.find(item=>item.slug===slug);}

