import {apiErrorResponse} from "@/lib/server/api-error";
import {requireSuperAdmin} from "@/lib/server/auth";
import {WHATSAPP_ENABLED} from "@/lib/server/notifications";
import {supabaseRest} from "@/lib/server/supabase-rest";
export const dynamic="force-dynamic";
async function count(path:string){const{response}=await supabaseRest<unknown[]>(path,{count:"exact"});return Number(response.headers.get("content-range")?.split("/")[1]||0);}
export async function GET(request:Request){try{await requireSuperAdmin(request);const since=new Date(Date.now()-24*86400000).toISOString();const [alerts,delivered,failed,email,whatsapp,ai,documentFailures,pendingEvents,tenderWatches,activeWatches,followedBuyers,assessments,bidDecisions,feedback,radarSignals,organizationsWithBestMatch,matchOpens]=await Promise.all([
 count(`notifications?select=id&created_at=gte.${since}`),count(`notification_deliveries?select=id&status=eq.sent&created_at=gte.${since}`),count(`notification_deliveries?select=id&status=eq.failed&created_at=gte.${since}`),count(`notification_deliveries?select=id&channel=eq.email&created_at=gte.${since}`),count(`notification_deliveries?select=id&channel=eq.whatsapp&created_at=gte.${since}`),count(`ai_usage?select=id&created_at=gte.${since}`),count("opportunity_documents?select=id&processing_status=eq.failed"),count("procurement_events?select=id&processed_at=is.null"),count("customer_saved_searches?select=id"),count("customer_saved_searches?select=id&alerts_enabled=eq.true"),count("watched_entities?select=id&entity_type=eq.buyer"),count("organization_opportunity_matches?select=id"),count("bid_decisions?select=id"),count("opportunity_feedback?select=id"),count("procurement_radar_items?select=id&status=eq.active"),count("organizations?select=id&best_match_opportunity_id=not.is.null"),count(`analytics_events?select=id&event_name=eq.MATCH_OPENED&created_at=gte.${since}`)
 ]);return Response.json({data:{window:"24 hours",alerts,delivered,failed,email,whatsapp,ai,documentFailures,pendingEvents,retention:{tenderWatches,activeWatches,followedBuyers,assessments,bidDecisions,feedback,radarSignals,organizationsWithBestMatch,matchOpens,matchClickThroughRate:assessments?Math.round(matchOpens/assessments*1000)/10:0},whatsappProvider:WHATSAPP_ENABLED?process.env.WHATSAPP_PROVIDER:"Not connected",aiProvider:process.env.OPENAI_API_KEY&&process.env.BIDSCOPE_AI_MODEL?"Configured model + grounded fallback":"Grounded fallback only",emailProvider:process.env.RESEND_API_KEY?"Resend":"Not configured"}});}catch(error){return apiErrorResponse(error);}}
