/* eslint-disable @next/next/no-html-link-for-pages */
"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, Bookmark, BriefcaseBusiness, Building2, Check, ChevronDown, ChevronRight, CircleCheck, Clock3, FileCheck2, FileSearch2, Globe2, HardHat, Landmark, Leaf, Mail, MapPin, Menu, Search, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { BrandLogo } from "@/components/brand/brand-logo";
import { AuthNav } from "@/components/procurement/auth-nav";

type Opportunity = { id: string; title: string; buyer: string; category: "Goods" | "Works" | "Services"; region: string; deadline: string; days: number; fit: number; procedure: string };
type Intelligence = { active: number; closingThisWeek: number; addedRecently: number; sources: number };

const opportunities: Opportunity[] = [
  { id: "GH-2026-01942", title: "Supply of office equipment and consumables", buyer: "Illustrative public institution", category: "Goods", region: "Greater Accra", deadline: "18 Oct 2026", days: 36, fit: 94, procedure: "National competitive tender" },
  { id: "GH-2026-01887", title: "Routine maintenance of feeder roads", buyer: "Illustrative district assembly", category: "Works", region: "Ashanti", deadline: "11 Oct 2026", days: 29, fit: 88, procedure: "Request for tenders" },
  { id: "GH-2026-01830", title: "Digital records consultancy services", buyer: "Illustrative government agency", category: "Services", region: "Greater Accra", deadline: "03 Oct 2026", days: 21, fit: 81, procedure: "Expression of interest" },
  { id: "GH-2026-01799", title: "Supply and installation of solar streetlights", buyer: "Illustrative municipal assembly", category: "Works", region: "Northern", deadline: "28 Sep 2026", days: 16, fit: 76, procedure: "National competitive tender" },
];

const sectors = [[HardHat, "Construction"], [Globe2, "ICT"], [Leaf, "Agriculture"], [BriefcaseBusiness, "Consulting"], [Building2, "Supplies"], [Landmark, "Finance"]] as const;
const steps = [[Mail, "Tell us what fits", "Choose your sectors, regions and preferred work."], [Target, "See the signal", "Get a focused shortlist with deadlines and matching reasons."], [FileCheck2, "Verify, then move", "Open the original notice and prepare your response."]] as const;
const promises = [[ShieldCheck, "Source-linked", "Every listing points back to the original public notice."], [CircleCheck, "Clearly labelled", "Demonstration, corrected and expired records are unmistakable."], [Bookmark, "No influence sold", "We organise information; we never promise awards or access."]] as const;

declare global { interface Document { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } } }

export function OpportunityDashboard() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All categories");
  const [trialOpen, setTrialOpen] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [showExplorer, setShowExplorer] = useState(false);
  const [infoTab, setInfoTab] = useState<"how" | "promise">("how");
  const [selected, setSelected] = useState<Opportunity | null>(null);
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [message, setMessage] = useState("");
  const [intelligence, setIntelligence] = useState<Intelligence | null | undefined>(undefined);

  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return opportunities.filter((item) => (category === "All categories" || item.category === category) && (!needle || `${item.title} ${item.buyer} ${item.region}`.toLowerCase().includes(needle))); }, [query, category]);

  async function submitFoundingMember(payload: Record<string, unknown>) {
    const response = await fetch("/api/founding-members", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const result = (await response.json()) as { message?: string; error?: string };
    if (!response.ok) throw new Error(result.error || "We could not save your registration.");
    return result;
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("sending"); setMessage(""); const form = event.currentTarget;
    try { const result = await submitFoundingMember(Object.fromEntries(new FormData(form).entries())); setStatus("success"); setMessage(result.message || "Registration received."); form.reset(); }
    catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Please try again."); }
  }

  useEffect(() => {
    const context = document.modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController();
    try { void Promise.resolve(context.registerTool({ name: "register_founding_business", title: "Register founding business", description: "Register a Ghanaian business for the BidScope Ghana one-month founding-member trial.", inputSchema: { type: "object", properties: { businessName: { type: "string" }, contactName: { type: "string" }, email: { type: "string" }, phone: { type: "string" }, sector: { type: "string" }, consent: { type: "boolean" } }, required: ["businessName", "contactName", "email", "sector", "consent"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: (input: unknown) => submitFoundingMember(input as Record<string, unknown>) }, { signal: lifecycle.signal })).catch(() => undefined); } catch { /* optional browser capability */ }
    return () => lifecycle.abort();
  }, []);

  useEffect(() => {
    void fetch("/api/homepage-intelligence")
      .then(async (response) => (await response.json()) as { data: Intelligence | null })
      .then((body) => setIntelligence(body.data))
      .catch(() => setIntelligence(null));
  }, []);

  const infoItems = infoTab === "how" ? steps : promises;

  return <main className="paper-noise min-h-screen bg-[var(--bidscope-cream)] text-[var(--bidscope-charcoal)]">
    <header className="sticky top-0 z-40 border-b border-[#084D33]/10 bg-[color:rgba(253,251,244,.92)] backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center px-5 lg:px-8"><Brand />
      <nav className="ml-auto hidden items-center gap-2 md:flex"><Button asChild variant="ghost" className="rounded-full text-[#35554a]"><a href="/opportunities">Opportunities</a></Button><Button asChild variant="ghost" className="rounded-full text-[#35554a]"><a href="#why">Why BidScope</a></Button><AuthNav/><Button onClick={() => setTrialOpen(true)} className="ml-2 h-11 rounded-full bg-[#116149] px-5 shadow-[0_8px_24px_rgba(17,97,73,.2)] hover:-translate-y-0.5 hover:bg-[#0c523d]">Get 1 month free <ArrowRight /></Button></nav>
      <div className="ml-auto flex items-center gap-1 md:hidden"><AuthNav/><Button variant="ghost" size="icon" onClick={() => setMobileMenu((value) => !value)} aria-label="Open navigation">{mobileMenu ? <X /> : <Menu />}</Button></div></div>
      {mobileMenu && <nav className="border-t border-[#17362d]/10 bg-[#fbf7ed] px-4 py-2 md:hidden"><div className="grid grid-cols-2 gap-1.5"><a href="/opportunities" onClick={() => setMobileMenu(false)} className="rounded-lg px-2 py-2 text-center text-xs font-medium hover:bg-[#eee8d9]">Opportunities</a><a href="#why" onClick={() => setMobileMenu(false)} className="rounded-lg px-2 py-2 text-center text-xs font-medium hover:bg-[#eee8d9]">Why BidScope</a><Button onClick={() => { setTrialOpen(true); setMobileMenu(false); }} className="col-span-2 h-9 rounded-full text-xs">Get 1 month free</Button></div></nav>}
    </header>

    <section className="mx-auto max-w-[1440px] px-0 sm:px-5 sm:pt-5 lg:px-8"><div className="relative min-h-[630px] overflow-hidden bg-[#103f32] sm:rounded-[36px] lg:min-h-[680px]">
      <Image src="/images/bidscope-hero.webp" alt="Ghanaian business owners reviewing an opportunity together" fill priority sizes="100vw" className="object-cover object-[67%_center]" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(8,40,32,.97)_0%,rgba(8,40,32,.9)_100%)] sm:bg-[linear-gradient(90deg,rgba(10,48,38,.99)_0%,rgba(10,48,38,.91)_38%,rgba(10,48,38,.25)_73%,rgba(10,48,38,.1)_100%)]"/><div className="absolute -left-24 bottom-[-130px] size-[340px] rounded-full bg-[#a97d2f]/30 blur-3xl"/>
      <div className="relative z-10 flex min-h-[720px] max-w-3xl flex-col justify-center px-5 py-16 text-white sm:min-h-[700px] sm:px-12 lg:min-h-[680px] lg:px-20"><Badge className="h-auto w-fit max-w-full whitespace-normal rounded-full border border-[#c89a43]/35 bg-[#c89a43]/15 px-3 py-1.5 text-left text-[10px] leading-4 tracking-[.08em] text-[#dfc17e] hover:bg-[#c89a43]/15 sm:text-xs"><Sparkles className="shrink-0" /> PROCUREMENT INTELLIGENCE FOR GHANA &amp; BEYOND</Badge><h1 className="serif mt-6 max-w-[720px] text-[clamp(2.65rem,5.2vw,4.9rem)] font-medium leading-[.94] tracking-[-.052em]"><span className="block">Find the right opportunities.</span><span className="mt-1 block">Know which ones are worth pursuing.</span></h1><p className="serif mt-5 max-w-2xl text-[clamp(1.25rem,2.1vw,1.7rem)] font-medium leading-[1.15] tracking-[-.02em] text-[#d2aa58]">From opportunity to decision, BidScope gives you the intelligence to move.</p><p className="mt-5 max-w-xl text-base leading-7 text-white/75 sm:text-lg">Discover public-sector and development-funded opportunities, research buyers and past awards, track competitors, prepare your business and manage your bidding journey — all in one place.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-14 rounded-full bg-[#c79a42] px-7 text-base font-bold text-[#17362d] shadow-[0_14px_40px_rgba(154,111,35,.25)] hover:-translate-y-1 hover:bg-[#d5ad5b]"><a href="/opportunities">Explore Opportunities <ArrowRight /></a></Button><Button asChild variant="outline" size="lg" className="h-14 rounded-full border-white/30 bg-white/10 px-7 text-base text-white backdrop-blur hover:bg-white/20 hover:text-white"><a href="#explore">See How BidScope Works <ChevronDown /></a></Button></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-xs font-medium text-white/70"><TrustPoint>Official sources linked</TrustPoint><TrustPoint>Buyer &amp; award intelligence</TrustPoint><TrustPoint>Ghana + global opportunities</TrustPoint></div></div>
      <div aria-live="polite" className="absolute bottom-6 right-6 hidden min-w-64 rounded-2xl border border-white/15 bg-[#102f27]/82 px-5 py-4 text-white shadow-2xl backdrop-blur-xl md:block"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#8ce0bd]">Live opportunity intelligence</p>{intelligence === undefined ? <div className="mt-3 space-y-2" aria-label="Loading live opportunity intelligence"><div className="h-3 w-44 animate-pulse rounded bg-white/15"/><div className="h-3 w-36 animate-pulse rounded bg-white/15"/><div className="h-3 w-40 animate-pulse rounded bg-white/15"/></div> : intelligence ? <div className="mt-2 space-y-1 text-sm font-semibold"><p>{intelligence.active.toLocaleString()} active opportunities</p><p>{intelligence.addedRecently.toLocaleString()} added recently</p><p>{intelligence.closingThisWeek.toLocaleString()} closing this week</p><p>{intelligence.sources.toLocaleString()} official sources monitored</p></div> : <div className="mt-2 space-y-1 text-sm font-semibold"><p>New opportunities added regularly</p><p>Official procurement sources monitored</p></div>}</div>
    </div></section>

    <section className="border-b border-[#17362d]/10 bg-[#e4ece6]"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-[#17362d]/15 px-5 sm:grid-cols-4 lg:px-8">{intelligence ? [[intelligence.active.toLocaleString(), "active"], [intelligence.closingThisWeek.toLocaleString(), "closing this week"], [intelligence.addedRecently.toLocaleString(), "added recently"], [intelligence.sources.toLocaleString(), "sources monitored"]].map(([number, label]) => <div key={label} className="px-3 py-5 text-center"><strong className="serif block text-3xl">{number}</strong><span className="mt-1 block text-[10px] font-bold uppercase tracking-[.13em] text-[#17362d]/65">{label}</span></div>) : <div className="col-span-2 px-3 py-5 text-center text-xs font-semibold text-[#17362d]/70 sm:col-span-4">Procurement intelligence from trusted public and official sources.</div>}</div></section>

    <section id="explore" className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><div className="grid items-center gap-8 lg:grid-cols-[.82fr_1.18fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d26a45]">Opportunity preview</p><h2 className="serif mt-4 max-w-xl text-5xl font-medium leading-[.98] tracking-[-.04em] sm:text-6xl">Only what looks worth your time.</h2><p className="mt-5 max-w-lg leading-7 text-[#65776f]">Filter a short sample by sector, deadline and fit. Full notices appear only when you choose to explore.</p><div className="mt-7 flex flex-wrap gap-2">{sectors.slice(0, 5).map(([Icon, label]) => <button key={label} onClick={() => { setShowExplorer(true); setQuery(label === "Supplies" ? "supply" : label === "Construction" ? "roads" : label === "Consulting" ? "consultancy" : ""); }} className="flex items-center gap-2 rounded-full border border-[#17362d]/12 bg-white px-4 py-2.5 text-sm font-semibold shadow-sm hover:-translate-y-0.5 hover:border-[#116149]/30 hover:text-[#116149]"><Icon size={16}/>{label}</button>)}</div></div>
      {!showExplorer ? <button onClick={() => setShowExplorer(true)} className="group relative min-h-[330px] overflow-hidden rounded-[30px] bg-[#163f34] p-7 text-left text-white shadow-[0_24px_70px_rgba(23,54,45,.18)] sm:p-9"><div className="absolute -right-20 -top-20 size-64 rounded-full bg-[#a97d2f]/25 blur-2xl"/><div className="relative"><span className="grid size-14 place-items-center rounded-2xl bg-[#c79a42] text-[#17362d]"><Search size={25}/></span><p className="mt-14 text-xs font-bold uppercase tracking-[.17em] text-[#84d6b5]">Interactive sample</p><h3 className="serif mt-3 max-w-md text-4xl font-medium leading-tight">Open the opportunity finder</h3><p className="mt-4 max-w-md text-sm leading-6 text-white/58">Search, filter and inspect example notices without turning this page into a dashboard.</p><span className="mt-7 inline-flex items-center gap-2 font-bold text-[#d2aa58]">Explore sample opportunities <ArrowRight className="transition group-hover:translate-x-1" size={18}/></span></div></button> : <OpportunityFinder filtered={filtered} query={query} setQuery={setQuery} category={category} setCategory={setCategory} onSelect={setSelected} onClose={() => { setShowExplorer(false); setQuery(""); setCategory("All categories"); }} />}
    </div></section>

    <section id="why" className="bg-[#153f33] px-5 py-16 text-white lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[32px] bg-[#f4ead8] text-[#17362d] shadow-[0_30px_90px_rgba(0,0,0,.18)] lg:grid-cols-[.82fr_1.18fr]"><div className="relative min-h-[390px] lg:min-h-[520px]"><Image src="/images/ghana-supplier.webp" alt="Ghanaian supplier reviewing an opportunity on a tablet" fill sizes="(max-width: 1024px) 100vw, 42vw" className="object-cover object-center"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#112e27]/90 to-transparent p-7 pt-24 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d8b66c]">Built for growing businesses</p><p className="serif mt-2 text-3xl">Less hunting. More preparing.</p></div></div><div className="p-7 sm:p-10 lg:p-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d26a45]">Why BidScope</p><h2 className="serif mt-4 text-4xl font-medium leading-tight tracking-[-.035em] sm:text-5xl">Clear enough to act on.<br/><em className="font-light text-[#13805e]">Honest enough to trust.</em></h2><div className="mt-8 inline-flex rounded-full border border-[#17362d]/10 bg-white/55 p-1"><button onClick={() => setInfoTab("how")} className={`rounded-full px-5 py-2.5 text-sm font-bold ${infoTab === "how" ? "bg-[#116149] text-white shadow" : "text-[#5d7167]"}`}>How it works</button><button onClick={() => setInfoTab("promise")} className={`rounded-full px-5 py-2.5 text-sm font-bold ${infoTab === "promise" ? "bg-[#116149] text-white shadow" : "text-[#5d7167]"}`}>Our promise</button></div><div className="mt-7 grid gap-3">{infoItems.map(([Icon, title, copy], index) => <article key={title} className="flex gap-4 rounded-2xl border border-[#17362d]/10 bg-white/65 p-4"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${index === 1 ? "bg-[#ead9ae] text-[#8d641a]" : "bg-[#e3f2e9] text-[#116149]"}`}><Icon size={19}/></span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-[#697a72]">{copy}</p></div></article>)}</div></div></div></section>

    <section className="px-5 py-14 lg:px-8 lg:py-16"><div className="relative mx-auto min-h-[420px] max-w-7xl overflow-hidden rounded-[32px] bg-[#17362d]"><Image src="/images/contract-win.webp" alt="A young Ghanaian entrepreneur celebrating a contract win" fill sizes="100vw" className="object-cover object-[70%_center]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(19,62,50,.98)_0%,rgba(19,62,50,.88)_42%,rgba(19,62,50,.14)_76%)]"/><div className="relative flex min-h-[420px] max-w-2xl flex-col justify-center p-8 text-white sm:p-12 lg:p-16"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d2aa58]">Be ready when your moment comes</p><h2 className="serif mt-4 text-5xl font-medium leading-[1] tracking-[-.04em]">Preparation turns opportunity into progress.</h2><p className="mt-5 max-w-lg leading-7 text-white/65">BidScope helps you see relevant opportunities sooner. Awards always depend on the official procurement process.</p><Button onClick={() => setTrialOpen(true)} size="lg" className="mt-8 h-14 w-fit rounded-full bg-[#ef7650] px-7 text-base font-bold text-white shadow-xl hover:-translate-y-1 hover:bg-[#ff8761]">Reserve your free access <ArrowRight/></Button></div></div></section>

    <footer className="border-t border-white/10 bg-[var(--bidscope-green)]"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-10 text-sm text-white/70 xl:flex-row xl:items-center xl:justify-between lg:px-8"><div><Brand reversed/><p className="mt-3 text-xs tracking-[.08em] text-white/55">Where Opportunity Finds You.</p></div><p className="max-w-2xl leading-6">An independent information service—not affiliated with Ghana&apos;s Public Procurement Authority or GHANEPS. <a href="https://www.ghaneps.gov.gh/" target="_blank" rel="noreferrer" className="font-bold text-[#F1D77E] hover:underline">Visit the official portal ↗</a></p><span className="shrink-0 text-xs">© 2026 BidScope Ghana</span></div></footer>

    <OpportunityDialog selected={selected} onClose={() => setSelected(null)} />
    <TrialDialog open={trialOpen} setOpen={setTrialOpen} status={status} setStatus={setStatus} message={message} onSubmit={handleSubmit} />
  </main>;
}

function OpportunityFinder({ filtered, query, setQuery, category, setCategory, onSelect, onClose }: { filtered: Opportunity[]; query: string; setQuery: (value: string) => void; category: string; setCategory: (value: string) => void; onSelect: (item: Opportunity) => void; onClose: () => void }) {
  return <div className="overflow-hidden rounded-[30px] border border-[#17362d]/10 bg-[#fffdf8] shadow-[0_20px_65px_rgba(40,58,48,.12)]"><div className="flex items-center justify-between bg-[#153f33] px-5 py-4 text-white"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#84d6b5]">Opportunity finder</p><p className="mt-1 text-sm font-semibold">Illustrative records</p></div><Button variant="ghost" size="icon" onClick={onClose} className="rounded-full text-white hover:bg-white/10 hover:text-white" aria-label="Close opportunity finder"><X size={18}/></Button></div><div className="grid gap-3 border-b p-4 sm:grid-cols-[1fr_160px]"><label className="flex h-11 items-center gap-3 rounded-xl border border-[#17362d]/15 bg-white px-4"><Search size={17} className="text-[#809087]"/><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-auto border-0 bg-transparent p-0 text-sm shadow-none focus-visible:ring-0" placeholder="Try ‘solar’ or ‘roads’" /></label><NativeSelect value={category} onChange={(event) => setCategory(event.target.value)} className="h-11 w-full rounded-xl"><NativeSelectOption>All categories</NativeSelectOption><NativeSelectOption>Goods</NativeSelectOption><NativeSelectOption>Works</NativeSelectOption><NativeSelectOption>Services</NativeSelectOption></NativeSelect></div><div className="divide-y divide-[#17362d]/10">{filtered.slice(0, 3).map((item) => <button key={item.id} onClick={() => onSelect(item)} className="group grid w-full grid-cols-[1fr_auto] items-center gap-4 p-5 text-left hover:bg-[#f8f4e9]"><span className="min-w-0"><span className="mb-2 flex items-center gap-2"><Category category={item.category}/><span className="truncate text-[9px] font-semibold uppercase tracking-wider text-[#819087]">{item.procedure}</span></span><strong className="block text-sm leading-5 sm:text-base">{item.title}</strong><span className="mt-2 flex flex-wrap gap-3 text-[11px] text-[#6a7b73]"><span className="flex items-center gap-1"><MapPin size={12}/>{item.region}</span><span className="flex items-center gap-1"><Clock3 size={12}/>{item.days} days</span></span></span><span className="text-right"><span className="serif text-3xl font-semibold text-[#116149]">{item.fit}</span><span className="text-[10px] text-[#116149]">% fit</span><ChevronRight className="ml-auto mt-1 text-[#8b9892] transition group-hover:translate-x-1" size={16}/></span></button>)}{filtered.length === 0 && <div className="p-10 text-center"><FileSearch2 className="mx-auto text-[#9aa59f]"/><p className="mt-3 text-sm font-semibold">No sample matches that search.</p><Button variant="ghost" onClick={() => { setQuery(""); setCategory("All categories"); }} className="mt-1 text-[#116149]">Clear search</Button></div>}</div><div className="flex items-center gap-2 border-t bg-[#f4efe3] px-5 py-3 text-[10px] text-[#687970]"><ShieldCheck size={14}/> Demonstration only. Launch records will link to their original source.</div></div>;
}

function OpportunityDialog({ selected, onClose }: { selected: Opportunity | null; onClose: () => void }) {
  return <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && onClose()}><DialogContent className="max-w-2xl overflow-hidden rounded-[24px] p-0"><DialogHeader className="bg-[#f4efe3] p-6 pr-12"><div className="mb-2 flex items-center gap-2">{selected && <Category category={selected.category}/>}<span className="text-[10px] font-bold uppercase tracking-wider text-[#74847b]">Illustrative record</span></div><DialogTitle className="serif text-3xl font-medium leading-tight">{selected?.title}</DialogTitle><DialogDescription>{selected?.buyer}</DialogDescription></DialogHeader>{selected && <div className="p-6"><div className="grid grid-cols-2 gap-4 rounded-2xl border bg-[#fbfaf5] p-4 sm:grid-cols-4"><Detail label="Region" value={selected.region}/><Detail label="Deadline" value={selected.deadline}/><Detail label="Time left" value={`${selected.days} days`}/><Detail label="Profile fit" value={`${selected.fit}%`}/></div><h3 className="mt-7 text-sm font-bold">Why this could fit</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{["Sector matches your profile", "Region is within coverage", "Procedure matches preferences", "Preparation time remains"].map((item) => <p key={item} className="flex items-center gap-2 text-sm text-[#61736a]"><span className="grid size-5 place-items-center rounded-full bg-[#e1f1e8] text-[#116149]"><Check size={12}/></span>{item}</p>)}</div><div className="mt-7 flex flex-col gap-3 border-t pt-5 sm:flex-row sm:justify-between"><Button variant="outline"><Bookmark/>Save for later</Button><Button asChild><a href="https://www.ghaneps.gov.gh/" target="_blank" rel="noreferrer">Verify at official source <ArrowRight/></a></Button></div></div>}</DialogContent></Dialog>;
}

function TrialDialog({ open, setOpen, status, setStatus, message, onSubmit }: { open: boolean; setOpen: (value: boolean) => void; status: "idle" | "sending" | "success" | "error"; setStatus: (value: "idle" | "sending" | "success" | "error") => void; message: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <Dialog open={open} onOpenChange={(value) => { setOpen(value); if (!value) setStatus("idle"); }}><DialogContent className="max-w-xl rounded-[24px]"><DialogHeader><Badge className="mb-2 w-fit rounded-full border border-[#c89435]/20 bg-[#fff1cf] text-[#8a601b] hover:bg-[#fff1cf]">Founding-business access</Badge><DialogTitle className="serif text-3xl font-medium">Reserve your free month</DialogTitle><DialogDescription>No card. No automatic paid renewal. We will contact you before launch.</DialogDescription></DialogHeader>{status === "success" ? <div className="rounded-2xl bg-[#e4f2e9] p-7 text-center"><CircleCheck className="mx-auto text-[#116149]" size={38}/><h3 className="serif mt-4 text-2xl font-medium">Your place is reserved</h3><p className="mt-2 text-sm text-[#557067]">{message}</p><Button onClick={() => setOpen(false)} className="mt-5 rounded-full">Done</Button></div> : <form onSubmit={onSubmit} className="grid gap-4 pt-2"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Business name" name="businessName" required/><FormField label="Your name" name="contactName" required/></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Work email" name="email" type="email" required/><FormField label="Phone / WhatsApp" name="phone"/></div><label className="grid gap-1.5 text-xs font-bold">Main sector<NativeSelect name="sector" required className="w-full"><NativeSelectOption value="">Select a sector</NativeSelectOption><NativeSelectOption>Goods and supplies</NativeSelectOption><NativeSelectOption>Construction and works</NativeSelectOption><NativeSelectOption>Professional services</NativeSelectOption><NativeSelectOption>ICT and technology</NativeSelectOption><NativeSelectOption>Other</NativeSelectOption></NativeSelect></label><label className="flex items-start gap-2.5 text-xs leading-5 text-[#6c7d75]"><input type="checkbox" name="consent" value="yes" required className="mt-1 accent-[#116149]"/>I agree to be contacted about the trial and understand that BidScope does not guarantee government contracts.</label>{status === "error" && <p className="rounded-xl bg-red-50 p-3 text-xs font-medium text-red-700">{message}</p>}<Button disabled={status === "sending"} size="lg" className="mt-1 h-12 rounded-full">{status === "sending" ? "Saving your place…" : "Join the founding circle"}</Button></form>}</DialogContent></Dialog>;
}

function Brand({ reversed = false }: { reversed?: boolean }) { return <a href="#" className="flex shrink-0 items-center" aria-label="BidScope Ghana home"><BrandLogo reversed={reversed} priority={!reversed} className="h-auto w-[170px] sm:w-[190px]" /></a>; }
function TrustPoint({ children }: { children: React.ReactNode }) { return <span className="flex shrink-0 items-center gap-2"><CircleCheck size={15} className="text-[#77d5ae]" />{children}</span>; }
function Category({ category }: { category: Opportunity["category"] }) { const classes = category === "Works" ? "border-[#e0bd70] bg-[#fff4d9] text-[#8e641e]" : category === "Services" ? "border-[#abc7c8] bg-[#e7f2f1] text-[#315f61]" : "border-[#9fcdb9] bg-[#e5f3eb] text-[#176448]"; return <Badge variant="outline" className={`rounded-full ${classes}`}>{category}</Badge>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] font-bold uppercase tracking-wider text-[#7d8b84]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function FormField({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <label className="grid gap-1.5 text-xs font-bold">{label}<Input name={name} type={type} required={required} className="h-11 rounded-xl bg-white"/></label>; }
