"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  ArrowRight, BellRing, Bookmark, BriefcaseBusiness, Building2, CalendarDays, Check,
  ChevronDown, ChevronRight, CircleCheck, Clock3, FileCheck2, FileSearch2, Globe2,
  HardHat, Landmark, Leaf, Mail, MapPin, Menu, Search, ShieldCheck, Sparkles, Target, X,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";

type Opportunity = {
  id: string; title: string; buyer: string; category: "Goods" | "Works" | "Services";
  region: string; deadline: string; days: number; fit: number; procedure: string;
};

const opportunities: Opportunity[] = [
  { id: "GH-2026-01942", title: "Supply of office equipment and consumables", buyer: "Illustrative public institution", category: "Goods", region: "Greater Accra", deadline: "18 Oct 2026", days: 36, fit: 94, procedure: "National competitive tender" },
  { id: "GH-2026-01887", title: "Routine maintenance of feeder roads", buyer: "Illustrative district assembly", category: "Works", region: "Ashanti", deadline: "11 Oct 2026", days: 29, fit: 88, procedure: "Request for tenders" },
  { id: "GH-2026-01830", title: "Digital records consultancy services", buyer: "Illustrative government agency", category: "Services", region: "Greater Accra", deadline: "03 Oct 2026", days: 21, fit: 81, procedure: "Expression of interest" },
  { id: "GH-2026-01799", title: "Supply and installation of solar streetlights", buyer: "Illustrative municipal assembly", category: "Works", region: "Northern", deadline: "28 Sep 2026", days: 16, fit: 76, procedure: "National competitive tender" },
];

const sectors = [[HardHat, "Construction"], [Globe2, "ICT"], [Leaf, "Agriculture"], [BriefcaseBusiness, "Consulting"], [Building2, "Supplies"], [Landmark, "Financial services"]] as const;
const marquee = ["Suppliers", "Contractors", "Consultants", "Growing businesses", "Professional firms", "Local manufacturers"];

declare global { interface Document { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } } }

export function OpportunityDashboard() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All categories");
  const [trialOpen, setTrialOpen] = useState(false);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [selected, setSelected] = useState<Opportunity | null>(null);
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [message, setMessage] = useState("");

  const filtered = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return opportunities.filter((item) => (category === "All categories" || item.category === category) && (!needle || `${item.title} ${item.buyer} ${item.region}`.toLowerCase().includes(needle)));
  }, [query, category]);

  async function submitFoundingMember(payload: Record<string, unknown>) {
    const response = await fetch("/api/founding-members", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const result = (await response.json()) as { message?: string; error?: string };
    if (!response.ok) throw new Error(result.error || "We could not save your registration.");
    return result;
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("sending"); setMessage("");
    const formElement = event.currentTarget;
    try { const result = await submitFoundingMember(Object.fromEntries(new FormData(formElement).entries())); setStatus("success"); setMessage(result.message || "Registration received."); formElement.reset(); }
    catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Please try again."); }
  }

  useEffect(() => {
    const context = document.modelContext; if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try { void Promise.resolve(context.registerTool({
      name: "register_founding_business", title: "Register founding business",
      description: "Register a Ghanaian business for the BidScope Ghana three-month founding-member trial.",
      inputSchema: { type: "object", properties: { businessName: { type: "string" }, contactName: { type: "string" }, email: { type: "string" }, phone: { type: "string" }, sector: { type: "string" }, consent: { type: "boolean" } }, required: ["businessName", "contactName", "email", "sector", "consent"], additionalProperties: false },
      annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: (input: unknown) => submitFoundingMember(input as Record<string, unknown>),
    }, { signal: lifecycle.signal })).catch(() => undefined); } catch { /* optional browser capability */ }
    return () => lifecycle.abort();
  }, []);

  return <main className="paper-noise min-h-screen bg-[#f8f4e9] text-[#17362d]">
    <header className="sticky top-0 z-40 border-b border-[#17362d]/10 bg-[#f8f4e9]/90 backdrop-blur-xl">
      <div className="mx-auto flex h-[76px] max-w-7xl items-center px-5 lg:px-8"><Brand />
        <nav className="mx-auto hidden items-center gap-8 text-sm font-medium text-[#52675f] md:flex"><a href="#discover" className="hover:text-[#116149]">Discover</a><a href="#how" className="hover:text-[#116149]">How it works</a><a href="#principles" className="hover:text-[#116149]">Our promise</a><a href="#founding" className="hover:text-[#116149]">Founding access</a></nav>
        <div className="ml-auto hidden items-center gap-3 md:flex"><Button variant="ghost" className="text-[#35554a]">Sign in</Button><Button onClick={() => setTrialOpen(true)} className="h-11 rounded-full bg-[#116149] px-5 shadow-[0_8px_24px_rgba(17,97,73,.18)] hover:-translate-y-0.5 hover:bg-[#0c523d]">Get 3 months free <ArrowRight /></Button></div>
        <Button variant="ghost" size="icon" className="ml-auto md:hidden" onClick={() => setMobileMenu((value) => !value)} aria-label="Open navigation">{mobileMenu ? <X /> : <Menu />}</Button>
      </div>
      {mobileMenu && <nav className="border-t border-[#17362d]/10 bg-[#f8f4e9] px-5 py-5 md:hidden"><div className="grid gap-1">{[["Discover","#discover"],["How it works","#how"],["Our promise","#principles"],["Founding access","#founding"]].map(([label,href]) => <a key={href} href={href} onClick={() => setMobileMenu(false)} className="rounded-xl px-3 py-3 font-medium hover:bg-[#eee8d9]">{label}</a>)}<Button onClick={() => { setTrialOpen(true); setMobileMenu(false) }} className="mt-3 rounded-full">Get 3 months free</Button></div></nav>}
    </header>

    <section className="relative overflow-hidden">
      <div className="pointer-events-none absolute -left-24 top-32 size-72 rounded-full bg-[#d7aa4b]/10 blur-3xl" /><div className="pointer-events-none absolute -right-28 top-8 size-[460px] rounded-full bg-[#8bbda7]/20 blur-3xl" />
      <div className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-20 pt-14 lg:grid-cols-[.92fr_1.08fr] lg:px-8 lg:pb-28 lg:pt-24">
        <div className="relative z-10 min-w-0"><Badge variant="outline" className="rounded-full border-[#bf9140]/30 bg-[#fff9eb] px-3 py-1.5 text-[#8c651f]"><Sparkles /> Founding-business programme now open</Badge>
          <h1 className="serif mt-7 max-w-2xl text-[clamp(3.5rem,7vw,6.25rem)] font-medium leading-[.9] tracking-[-.055em]">Opportunity,<br/><em className="font-light text-[#15805f]">made visible.</em></h1>
          <p className="mt-7 max-w-lg text-lg leading-8 text-[#5f736a]">A thoughtful way for Ghanaian businesses to discover public opportunities, understand what fits, and move before the deadline.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={() => setTrialOpen(true)} size="lg" className="h-14 rounded-full bg-[#116149] px-7 text-base shadow-[0_14px_30px_rgba(17,97,73,.2)] hover:-translate-y-1 hover:bg-[#0b523d]">Join the founding circle <ArrowRight /></Button><Button asChild variant="outline" size="lg" className="h-14 rounded-full border-[#17362d]/20 bg-white/50 px-7 text-base"><a href="#discover">See how it feels <ChevronDown /></a></Button></div>
          <div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-xs font-medium text-[#6d7e76]"><span className="flex shrink-0 items-center gap-2"><CircleCheck size={15} className="text-[#15805f]" /> No card required</span><span className="flex shrink-0 items-center gap-2"><CircleCheck size={15} className="text-[#15805f]" /> No automatic renewal</span><span className="flex shrink-0 items-center gap-2"><CircleCheck size={15} className="text-[#15805f]" /> Always links to source</span></div>
        </div>

        <div className="relative mx-auto min-w-0 w-full max-w-[650px] py-8 lg:py-0"><div className="absolute -right-4 top-0 hidden rotate-6 rounded-2xl bg-[#d7aa4b] px-5 py-3 text-xs font-bold text-[#2f2716] shadow-lg sm:block">NEW MATCH · 94%</div>
          <div className="relative overflow-hidden rounded-[34px] border border-[#17362d]/10 bg-[#fbf8ef] p-4 shadow-[0_30px_90px_rgba(38,61,50,.18)] sm:p-6">
            <div className="rounded-[24px] bg-[#123f32] p-5 text-white sm:p-7"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#87cdb2]">Your opportunity brief</p><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[10px] text-white/60">Updated today</span></div><h2 className="serif mt-8 max-w-md text-3xl font-medium leading-tight sm:text-[40px]">The right notices,<br/><em className="font-light text-[#e5bd65]">without the noise.</em></h2><div className="mt-8 grid grid-cols-3 border-t border-white/10 pt-5"><MiniStat number="24" label="matched" /><MiniStat number="7" label="closing soon" /><MiniStat number="4" label="new today" /></div></div>
            <div className="mt-4 space-y-3">{opportunities.slice(0,3).map((item,index) => <button key={item.id} onClick={() => setSelected(item)} className={`group flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 hover:shadow-md ${index === 0 ? "border-[#88bca6]/50 bg-[#edf5ef]" : "border-[#17362d]/10 bg-white/65"}`}><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${index === 0 ? "bg-[#116149] text-white" : "bg-[#eeeadd] text-[#5c6e66]"}`}>{index === 1 ? <HardHat size={18}/> : index === 2 ? <BriefcaseBusiness size={18}/> : <FileCheck2 size={18}/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{item.title}</span><span className="mt-1 flex items-center gap-2 text-[11px] text-[#6c7d75]"><span>{item.region}</span><span>·</span><span>{item.days} days left</span></span></span><span className="font-mono text-sm font-bold text-[#137657]">{item.fit}%</span><ChevronRight size={16} className="text-[#8c9993] transition group-hover:translate-x-1" /></button>)}</div>
            <p className="mt-4 px-1 text-[10px] leading-4 text-[#7e8c85]">Illustrative preview—not live notices. Every launch record will open the original public source.</p>
          </div>
          <div className="float-soft absolute -bottom-1 -left-3 hidden max-w-[220px] rounded-2xl border border-[#17362d]/10 bg-white p-4 shadow-xl sm:flex sm:items-center sm:gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#fff2d3] text-[#9c6e1f]"><BellRing size={18}/></span><span><strong className="block text-xs">Deadline protected</strong><span className="mt-1 block text-[10px] text-[#718078]">Reminder set for 7 days before close</span></span></div>
        </div>
      </div>
    </section>

    <section className="overflow-hidden border-y border-[#17362d]/10 bg-[#f0eadb] py-4"><div className="marquee-track flex w-max items-center">{[...marquee,...marquee].map((item,index) => <span key={`${item}-${index}`} className="flex items-center"><span className="px-8 text-xs font-semibold uppercase tracking-[.14em] text-[#556a60]">{item}</span><span className="text-[#c59943]">✦</span></span>)}</div></section>

    <section id="discover" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#b07c27]">Discover with confidence</p><h2 className="serif mt-4 text-5xl font-medium leading-[1.02] tracking-[-.035em] sm:text-6xl">A clearer view of what is worth your time.</h2><p className="mt-6 max-w-md leading-7 text-[#65776f]">Search by what your business actually does. See the deadline, location and why an opportunity could fit—then verify everything at the official source.</p><div className="mt-9 grid grid-cols-2 gap-3">{sectors.map(([Icon,label]) => <button key={label} onClick={() => setQuery(label === "Supplies" ? "supply" : label === "Construction" ? "roads" : label === "Consulting" ? "consultancy" : "")} className="flex items-center gap-3 rounded-2xl border border-[#17362d]/10 bg-white/50 p-4 text-left text-sm font-semibold hover:border-[#116149]/30 hover:bg-white"><span className="grid size-9 place-items-center rounded-full bg-[#e8efe8] text-[#116149]"><Icon size={17}/></span>{label}</button>)}</div></div>
        <div className="overflow-hidden rounded-[30px] border border-[#17362d]/10 bg-[#fffdf8] shadow-[0_20px_65px_rgba(40,58,48,.11)]"><div className="flex flex-col gap-3 border-b border-[#17362d]/10 p-4 sm:flex-row"><label className="flex h-12 flex-1 items-center gap-3 rounded-xl border border-[#17362d]/15 bg-white px-4"><Search size={18} className="text-[#809087]"/><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-auto border-0 bg-transparent p-0 text-sm shadow-none focus-visible:ring-0" placeholder="Try ‘solar’, ‘roads’ or ‘consultancy’" /></label><NativeSelect value={category} onChange={(event) => setCategory(event.target.value)} className="h-12 w-full rounded-xl sm:w-[170px]"><NativeSelectOption>All categories</NativeSelectOption><NativeSelectOption>Goods</NativeSelectOption><NativeSelectOption>Works</NativeSelectOption><NativeSelectOption>Services</NativeSelectOption></NativeSelect></div>
          <div className="divide-y divide-[#17362d]/10">{filtered.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="group grid w-full gap-4 p-5 text-left hover:bg-[#f8f4e9]/70 sm:grid-cols-[1fr_auto] sm:items-center sm:p-6"><span><span className="mb-2 flex flex-wrap items-center gap-2"><Category category={item.category}/><span className="text-[10px] font-semibold uppercase tracking-wider text-[#819087]">{item.procedure}</span></span><strong className="block text-base leading-6 sm:text-lg">{item.title}</strong><span className="mt-2 flex flex-wrap gap-4 text-xs text-[#6a7b73]"><span className="flex items-center gap-1.5"><MapPin size={13}/>{item.region}</span><span className="flex items-center gap-1.5"><CalendarDays size={13}/>{item.deadline}</span><span className="flex items-center gap-1.5"><Clock3 size={13}/>{item.days} days</span></span></span><span className="flex items-center justify-between gap-4 sm:block sm:text-right"><span><span className="serif text-3xl font-semibold text-[#116149]">{item.fit}</span><span className="text-xs text-[#116149]">% fit</span></span><ChevronRight className="ml-auto mt-2 text-[#8b9892] transition group-hover:translate-x-1" size={18}/></span></button>)}{filtered.length === 0 && <div className="p-12 text-center"><FileSearch2 className="mx-auto text-[#9aa59f]"/><p className="mt-3 font-semibold">Nothing in this demonstration matches yet.</p><Button variant="ghost" onClick={() => {setQuery("");setCategory("All categories")}} className="mt-2 text-[#116149]">Clear search</Button></div>}</div>
          <div className="flex flex-col items-start justify-between gap-3 border-t bg-[#f4efe3] px-5 py-4 text-xs text-[#687970] sm:flex-row sm:items-center"><span className="flex items-center gap-2"><ShieldCheck size={15}/> Source-linked and independently presented</span><a href="https://www.ghaneps.gov.gh/" target="_blank" rel="noreferrer" className="font-semibold text-[#116149] hover:underline">Visit the official portal ↗</a></div>
        </div></div></section>

    <section id="how" className="ghana-weave bg-[#123f32] text-[#f8f4e9]"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#e0b75f]">How it works</p><h2 className="serif mt-4 text-5xl font-medium leading-[1.02] tracking-[-.035em] sm:text-6xl">Less hunting.<br/><em className="font-light text-[#83ceb0]">More preparing.</em></h2></div><div className="grid gap-4 sm:grid-cols-3">{[["01",Mail,"Tell us what fits","Share your sectors, regions and the kind of work your business can deliver."],["02",Target,"See the signal","Receive a focused shortlist with deadlines and clear matching reasons."],["03",FileCheck2,"Verify, then move","Open the original notice, check every requirement and prepare your response."]].map(([number,Icon,title,copy]) => { const C = Icon as typeof Mail; return <article key={String(number)} className="rounded-[24px] border border-white/10 bg-white/[.055] p-6"><span className="text-xs font-bold text-[#e0b75f]">{String(number)}</span><C className="mt-10 text-[#83ceb0]" size={25}/><h3 className="serif mt-5 text-2xl font-medium">{String(title)}</h3><p className="mt-3 text-sm leading-6 text-white/55">{String(copy)}</p></article>})}</div></div></div></section>

    <section id="principles" className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="rounded-[34px] border border-[#17362d]/10 bg-[#efe9da] p-7 sm:p-12 lg:p-16"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div><Badge variant="outline" className="rounded-full border-[#17362d]/15 bg-white/40 px-3 py-1.5">Our promise</Badge><h2 className="serif mt-6 text-5xl font-medium leading-[1.02] tracking-[-.035em]">Information you can trust.<br/><em className="font-light text-[#116149]">Decisions that stay yours.</em></h2><p className="mt-6 max-w-lg leading-7 text-[#64766d]">BidScope is designed to help legitimate businesses see public information more clearly—not to sell access, influence awards or promise outcomes.</p></div><div className="grid gap-3">{["Every opportunity opens its original public source.","Illustrative, corrected and expired records are clearly labelled.","No success fees and no payment for an award.","Your profile is used to deliver the service you request."].map((item,index) => <div key={item} className="flex items-center gap-4 rounded-2xl border border-[#17362d]/10 bg-[#fffdf8]/70 p-4 sm:p-5"><span className="serif grid size-9 shrink-0 place-items-center rounded-full bg-[#116149] text-sm text-white">{index+1}</span><p className="text-sm font-medium sm:text-base">{item}</p></div>)}</div></div></div></section>

    <section id="founding" className="px-5 pb-24 lg:px-8 lg:pb-32"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[36px] bg-[#d7aa4b] p-8 text-[#293023] sm:p-12 lg:p-16"><div className="absolute -right-24 -top-24 size-80 rounded-full border-[60px] border-white/10"/><div className="relative grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em]">The founding circle</p><h2 className="serif mt-5 max-w-4xl text-5xl font-medium leading-[.98] tracking-[-.04em] sm:text-6xl">Three months to see if it earns a place in your business.</h2><p className="mt-5 max-w-2xl leading-7 text-[#514421]">Use every core feature free. We will show you the paid price before the trial ends, and nothing renews unless you choose it.</p></div><Button onClick={() => setTrialOpen(true)} size="lg" className="h-14 rounded-full bg-[#17362d] px-7 text-base text-white shadow-xl hover:-translate-y-1 hover:bg-[#0e2a22]">Reserve your place <ArrowRight/></Button></div></div></section>

    <footer className="border-t border-[#17362d]/10 bg-[#f0eadb]"><div className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="flex flex-col justify-between gap-8 md:flex-row"><Brand/><div className="max-w-xl text-sm leading-6 text-[#6d7c75]">BidScope Ghana is a working brand pending clearance. It is an independent information service and is not affiliated with Ghana&apos;s Public Procurement Authority or GHANEPS.</div></div><div className="mt-10 flex flex-col justify-between gap-3 border-t border-[#17362d]/10 pt-5 text-xs text-[#7a8881] sm:flex-row"><span>© 2026 BidScope Ghana concept</span><span>Privacy · Terms · Data requests</span></div></div></footer>

    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-2xl overflow-hidden rounded-[24px] p-0"><DialogHeader className="bg-[#f4efe3] p-6 pr-12"><div className="mb-2 flex items-center gap-2">{selected && <Category category={selected.category}/>}<span className="text-[10px] font-bold uppercase tracking-wider text-[#74847b]">Illustrative record</span></div><DialogTitle className="serif text-3xl font-medium leading-tight">{selected?.title}</DialogTitle><DialogDescription>{selected?.buyer}</DialogDescription></DialogHeader>{selected && <div className="p-6"><div className="grid grid-cols-2 gap-4 rounded-2xl border bg-[#fbfaf5] p-4 sm:grid-cols-4"><Detail label="Region" value={selected.region}/><Detail label="Deadline" value={selected.deadline}/><Detail label="Time left" value={`${selected.days} days`}/><Detail label="Profile fit" value={`${selected.fit}%`}/></div><h3 className="mt-7 text-sm font-bold">Why this could fit</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{["Sector matches your profile","Region is within coverage","Procedure matches preferences","Preparation time remains"].map((item) => <p key={item} className="flex items-center gap-2 text-sm text-[#61736a]"><span className="grid size-5 place-items-center rounded-full bg-[#e1f1e8] text-[#116149]"><Check size={12}/></span>{item}</p>)}</div><div className="mt-7 flex flex-col gap-3 border-t pt-5 sm:flex-row sm:justify-between"><Button variant="outline"><Bookmark/>Save for later</Button><Button asChild><a href="https://www.ghaneps.gov.gh/" target="_blank" rel="noreferrer">Verify at official source <ArrowRight/></a></Button></div></div>}</DialogContent></Dialog>

    <Dialog open={trialOpen} onOpenChange={(open) => { setTrialOpen(open); if (!open) setStatus("idle") }}><DialogContent className="max-w-xl rounded-[24px]"><DialogHeader><Badge className="mb-2 w-fit rounded-full border border-[#c89435]/20 bg-[#fff1cf] text-[#8a601b] hover:bg-[#fff1cf]">Founding-business access</Badge><DialogTitle className="serif text-3xl font-medium">Reserve your three free months</DialogTitle><DialogDescription>No card. No automatic paid renewal. We will contact you before launch.</DialogDescription></DialogHeader>{status === "success" ? <div className="rounded-2xl bg-[#e4f2e9] p-7 text-center"><CircleCheck className="mx-auto text-[#116149]" size={38}/><h3 className="serif mt-4 text-2xl font-medium">Your place is reserved</h3><p className="mt-2 text-sm text-[#557067]">{message}</p><Button onClick={() => setTrialOpen(false)} className="mt-5 rounded-full">Done</Button></div> : <form onSubmit={handleSubmit} className="grid gap-4 pt-2"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Business name" name="businessName" required/><FormField label="Your name" name="contactName" required/></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Work email" name="email" type="email" required/><FormField label="Phone / WhatsApp" name="phone"/></div><label className="grid gap-1.5 text-xs font-bold">Main sector<NativeSelect name="sector" required className="w-full"><NativeSelectOption value="">Select a sector</NativeSelectOption><NativeSelectOption>Goods and supplies</NativeSelectOption><NativeSelectOption>Construction and works</NativeSelectOption><NativeSelectOption>Professional services</NativeSelectOption><NativeSelectOption>ICT and technology</NativeSelectOption><NativeSelectOption>Other</NativeSelectOption></NativeSelect></label><label className="flex items-start gap-2.5 text-xs leading-5 text-[#6c7d75]"><input type="checkbox" name="consent" value="yes" required className="mt-1 accent-[#116149]"/>I agree to be contacted about the trial and understand that BidScope does not guarantee government contracts.</label>{status === "error" && <p className="rounded-xl bg-red-50 p-3 text-xs font-medium text-red-700">{message}</p>}<Button disabled={status === "sending"} size="lg" className="mt-1 h-12 rounded-full">{status === "sending" ? "Saving your place…" : "Join the founding circle"}</Button></form>}</DialogContent></Dialog>
  </main>;
}

function Brand() { return <a href="#" className="flex shrink-0 items-center gap-3" aria-label="BidScope Ghana home"><span className="relative grid size-10 place-items-center rounded-full bg-[#116149] text-white"><Target size={19}/><span className="absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full border-2 border-[#f8f4e9] bg-[#d7aa4b]"/></span><span><strong className="serif block text-xl leading-none tracking-[-.03em]">BidScope</strong><span className="mt-1 block text-[8px] font-bold uppercase tracking-[.22em] text-[#b17c26]">Ghana</span></span></a> }
function MiniStat({number,label}:{number:string;label:string}) { return <div><strong className="serif block text-2xl font-semibold sm:text-3xl">{number}</strong><span className="mt-1 block text-[10px] uppercase tracking-wider text-white/45">{label}</span></div> }
function Category({category}:{category:Opportunity["category"]}) { const classes = category === "Works" ? "border-[#e0bd70] bg-[#fff4d9] text-[#8e641e]" : category === "Services" ? "border-[#abc7c8] bg-[#e7f2f1] text-[#315f61]" : "border-[#9fcdb9] bg-[#e5f3eb] text-[#176448]"; return <Badge variant="outline" className={`rounded-full ${classes}`}>{category}</Badge> }
function Detail({label,value}:{label:string;value:string}) { return <div><p className="text-[9px] font-bold uppercase tracking-wider text-[#7d8b84]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div> }
function FormField({label,name,type="text",required=false}:{label:string;name:string;type?:string;required?:boolean}) { return <label className="grid gap-1.5 text-xs font-bold">{label}<Input name={name} type={type} required={required} className="h-11 rounded-xl bg-white"/></label> }
