"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2, FileUp, Info, Send, ShieldCheck } from "lucide-react";
import { api } from "@/components/customer/data";
const fields = [
  ["title", "Tender title", "e.g. Supply and installation of solar equipment"], ["buyerName", "Procuring organisation", "Ministry, agency, company or development partner"], ["country", "Country", "Ghana"], ["region", "Region / state", "Greater Accra"], ["city", "City", "Accra"], ["category", "Category", "Works, goods, consulting or services"], ["industry", "Industry", "Construction, ICT, health…"], ["referenceNumber", "Reference number", "Optional official reference"], ["procurementMethod", "Procurement method", "Open tender, RFQ, RFP…"], ["submissionDeadline", "Submission deadline", ""], ["tenderUrl", "Official tender URL", "https://…"], ["submissionUrl", "Submission portal URL", "https://…"]] as const;
const longFields = [["description", "Tender description", "Describe the scope, deliverables and location."], ["eligibility", "Eligibility requirements", "Registration, nationality, licences and minimum criteria."], ["certifications", "Certifications / registrations", "Required certificates, tax or professional registrations."], ["financialRequirements", "Financial requirements", "Turnover, statements, bid security or financial capacity."], ["experienceRequirements", "Experience requirements", "Similar contracts, references and years of experience."], ["technicalRequirements", "Technical requirements", "Specifications, methodology, staffing and equipment."], ["submissionInstructions", "How to submit", "Summarise the submission steps and required documents."], ["additionalInformation", "Additional information", "Clarifications, contact details, site visit or other notes."]] as const;
export function PostTenderForm() { const [values, setValues] = useState<Record<string, string>>({ country: "Ghana" }); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState(""); const update = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await api("/api/tender-submissions", { ...values, submit: true, estimatedValue: null, valueMin: null, valueMax: null, tags: [] }); setDone(true); } catch (e) { setError(e instanceof Error ? e.message : "We could not submit this tender."); } finally { setBusy(false); } }
  if (done) return <section className="cc-page"><div className="cc-empty"><CheckCircle2 size={42}/><h1>Tender submitted for review</h1><p>Thanks. Our team will verify the buyer, dates, source and requirements before it can appear in BidScope.</p></div></section>;
  return <section className="cc-page"><div className="cc-page-heading"><div><p className="cc-eyebrow">CONTRIBUTE TO BIDSCOPE</p><h1>Post a tender</h1><p>Share a public opportunity with the community. Every submission is reviewed before publication.</p></div><div className="cc-page-heading-art"><ShieldCheck size={28}/><span>Human-reviewed<br/>before discovery</span></div></div><form className="cc-form-card" onSubmit={submit}><div className="cc-form-note"><Info size={17}/><span>Only publicly available opportunities that you are permitted to share should be submitted. Do not upload confidential information.</span></div><div className="cc-form-grid">{fields.map(([key, label, placeholder]) => <label key={key}><span>{label}</span><input required={['title','buyerName','country','submissionDeadline'].includes(key)} type={key.toLowerCase().includes('date')||key==='submissionDeadline'?'date':key.endsWith('Url')?'url':'text'} placeholder={placeholder} value={values[key] || ""} onChange={(e) => update(key, e.target.value)}/></label>)}</div>{longFields.map(([key, label, placeholder]) => <label className="cc-form-wide" key={key}><span>{label}</span><textarea required={key==='description'} rows={key==='description'?5:3} placeholder={placeholder} value={values[key] || ""} onChange={(e) => update(key, e.target.value)}/></label>)}<label className="cc-upload-placeholder"><FileUp size={20}/><span><strong>Supporting documents</strong><small>Secure document upload is enabled in the next review phase. Add document names and links above for now.</small></span></label>{error&&<p className="cc-form-error" role="alert">{error}</p>}<button className="cc-button" disabled={busy} type="submit">{busy?"Submitting…":<>Submit for review <Send size={15}/></>}</button></form></section>; }
