"use client";

import {useEffect,useState,type FormEvent} from "react";
import {RefreshCw,ShieldPlus} from "lucide-react";
import {api} from "@/components/customer/data";

type Plan={code:string;name:string;description:string;amount_minor:number|null;provider_plan_code:string|null;activation_status:string;enabled:boolean;payment_kind:string;billing_interval:string;features?:Record<string,unknown>;limits?:Record<string,unknown>};
type Subscription={id:string;organization:{name:string};plan_code:string;status:string;current_period_ends_at:string|null;provider:string};
type Organization={id:string;name:string;region:string|null};
type Data={provider:{configured:boolean;mode:string};productionActivation:string;plans:Plan[];metrics:Record<string,number>;subscriptions:Subscription[];organizations:Organization[]};
const currentPlanCodes=new Set(["pro_launch_monthly","pro_launch_annual","premium_launch_monthly","premium_launch_annual","platinum_launch_monthly","platinum_launch_annual","pro_momo_30","pro_momo_365","premium_momo_30","premium_momo_365","platinum_momo_30","platinum_momo_365"]);
const benefits=(plan:Plan)=>{const name=plan.name.toLowerCase();if(name.includes("pro"))return["Live Ghana and eligible international opportunities","Unlimited keyword search and official source links","Best Match, alerts and deadline reminders","1 workspace seat"];if(name.includes("premium"))return["Everything in Pro","Bid / No-Bid, eligibility and buyer intelligence","AI analysis, readiness scoring and awards history","Up to 3 workspace seats"];return["Everything in Premium Team","Full bid workspace, pipeline and procurement radar","Advanced monitoring and 1,200 AI analyses/month","Up to 5 workspace seats and role-based collaboration"];};
const isoDate=(date:Date)=>date.toISOString().slice(0,10);

export function SubscriptionsRevenue(){
  const[data,setData]=useState<Data|null>(null);
  const[message,setMessage]=useState("Loading subscription operations…");
  const[busy,setBusy]=useState(false);
  const[grantDates]=useState(()=>{const start=new Date();return{start:isoDate(start),end:isoDate(new Date(start.getTime()+30*86400000))};});
  async function load(){const result=await api<{data:Data}>("/api/admin/subscriptions");setData(result.data);setMessage("");}
  useEffect(()=>{void api<{data:Data}>("/api/admin/subscriptions").then(result=>{setData(result.data);setMessage("");}).catch(error=>setMessage(error instanceof Error?error.message:"Subscription operations could not be loaded."));},[]);
  const money=(minor=0)=>new Intl.NumberFormat("en-GH",{style:"currency",currency:"GHS"}).format(minor/100);

  async function savePlan(event:FormEvent<HTMLFormElement>,plan:Plan){
    event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);
    try{await api("/api/admin/subscriptions",{action:"configure_plan",code:plan.code,amountGhs:form.get("amount"),providerPlanCode:form.get("providerPlanCode")||null,activationStatus:form.get("activationStatus"),enabled:form.get("enabled")==="on"},"PATCH");setMessage("Plan configuration saved and recorded in the audit log.");await load();}
    catch(error){setMessage(error instanceof Error?error.message:"Plan could not be saved.");}finally{setBusy(false);}
  }

  async function grantAccess(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);
    try{await api("/api/admin/subscriptions",{action:"manual_grant",organizationId:form.get("organizationId"),reason:form.get("reason"),startsAt:new Date(String(form.get("startsAt"))).toISOString(),expiresAt:new Date(String(form.get("expiresAt"))).toISOString()},"PATCH");setMessage("Temporary full access granted and recorded in the audit log.");event.currentTarget.reset();}
    catch(error){setMessage(error instanceof Error?error.message:"Access could not be granted.");}finally{setBusy(false);}
  }

  async function reconcile(){setBusy(true);try{const result=await api<{data:{processed?:number}}>("/api/admin/subscriptions",{action:"reconcile"},"PATCH");setMessage(`Payment reconciliation completed${result.data.processed===undefined?"":`: ${result.data.processed} processed`}.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"Reconciliation failed.");}finally{setBusy(false);}}

  return <section className="mx-auto max-w-7xl px-5 py-10 lg:px-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#16805e]">Revenue controls</p><h1 className="serif mt-2 text-4xl text-[#17362d] sm:text-5xl">Subscriptions & Revenue</h1><p className="mt-3 text-sm text-[#64766e]">Organisation billing, Paystack health and auditable entitlement operations.</p></div><button type="button" disabled={busy} onClick={()=>void reconcile()} className="inline-flex h-11 items-center justify-center gap-2 rounded-full bg-[#116149] px-5 text-sm font-bold text-white disabled:opacity-50"><RefreshCw size={16}/>Reconcile payments</button></div>
    {message?<p role="status" className="mt-8 rounded-2xl border bg-white p-5 text-sm">{message}</p>:null}
    {data?<>
      <div className="mt-7 rounded-2xl border border-emerald-800/10 bg-emerald-50 p-5"><strong>{data.productionActivation}</strong><p className="mt-1 text-sm text-[#64766e]">Paystack: {data.provider.configured?data.provider.mode:"Not configured"}. Only verified server callbacks activate subscriptions.</p></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.metrics).map(([key,value])=><div className="rounded-2xl border bg-white p-4" key={key}><small className="uppercase tracking-wider text-[#728078]">{key.replaceAll(/([A-Z])/g," $1")}</small><strong className="mt-2 block text-2xl text-[#17362d]">{/mrr|arr|revenue/i.test(key)?money(value):value}</strong></div>)}</div>
      <section className="mt-8 rounded-[22px] border bg-white p-5"><div className="flex items-center gap-2"><ShieldPlus className="text-[#16805e]" size={20}/><h2 className="text-xl font-bold">Grant temporary full access</h2></div><p className="mt-2 text-sm text-[#64766e]">Use for approved trials or support cases. Every grant is time-limited and audited.</p><form className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-5" onSubmit={event=>void grantAccess(event)}><label className="text-xs font-semibold xl:col-span-2">Business<select name="organizationId" required className="mt-1 w-full rounded-xl border p-3"><option value="">Select a business</option>{data.organizations.map(org=><option key={org.id} value={org.id}>{org.name}{org.region?` · ${org.region}`:""}</option>)}</select></label><label className="text-xs font-semibold">Starts<input name="startsAt" type="date" required defaultValue={grantDates.start} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-xs font-semibold">Expires<input name="expiresAt" type="date" required defaultValue={grantDates.end} className="mt-1 w-full rounded-xl border p-3"/></label><label className="text-xs font-semibold xl:col-span-4">Reason<input name="reason" minLength={8} maxLength={500} required placeholder="Approved trial or support reason" className="mt-1 w-full rounded-xl border p-3"/></label><button disabled={busy} className="self-end rounded-full bg-[#17362d] px-5 py-3 text-sm font-bold text-white disabled:opacity-50">Grant access</button></form></section>
      <section className="mt-8 rounded-[22px] border bg-white p-5"><h2 className="text-xl font-bold">Plan configuration</h2><p className="mt-2 text-sm text-[#64766e]">Recurring monthly and annual packages use card subscriptions. Mobile Money packages are one-time access and never auto-renew.</p><div className="mt-5 hidden grid-cols-[1.1fr_.7fr_1.3fr_1fr_1fr_auto] gap-3 border-b pb-2 text-[10px] font-bold uppercase tracking-wider text-[#728078] md:grid"><span>Package</span><span>Price / period</span><span>Included benefits</span><span>Paystack plan code</span><span>Activation</span><span/></div>{data.plans.filter(plan=>currentPlanCodes.has(plan.code)).map(plan=><form key={plan.code} className="mt-4 grid gap-3 border-t pt-4 md:grid-cols-[1.1fr_.7fr_1.3fr_1fr_1fr_auto] md:items-start" onSubmit={event=>void savePlan(event,plan)}><div><strong>{plan.name}</strong><small className="block text-[#728078]">{plan.billing_interval.replaceAll("_"," ")} · {plan.payment_kind==="RECURRING_CARD"?"CARD · AUTO-RENEW":"MOBILE MONEY · ONE-TIME"}</small><p className="mt-2 text-xs text-[#64766e]">{plan.description}</p></div><label className="text-xs">Price (GHS)<input className="mt-1 w-full rounded border p-2" name="amount" defaultValue={plan.amount_minor==null?"":(plan.amount_minor/100).toFixed(2)} required/></label><ul className="space-y-1 text-xs text-[#526a61]">{benefits(plan).map(item=><li key={item}>✓ {item}</li>)}</ul><label className="text-xs">Paystack plan code<input className="mt-1 w-full rounded border p-2" name="providerPlanCode" defaultValue={plan.provider_plan_code||""} disabled={plan.payment_kind!=="RECURRING_CARD"} placeholder={plan.payment_kind!=="RECURRING_CARD"?"Not used for Mobile Money":"PLN_…"}/></label><label className="text-xs">Activation<select className="mt-1 w-full rounded border p-2" name="activationStatus" defaultValue={plan.activation_status}><option>PRICING_CONFIGURATION_REQUIRED</option><option>TEST_READY</option><option>LIVE</option></select><span className="mt-2 flex gap-2"><input type="checkbox" name="enabled" defaultChecked={plan.enabled}/>Enabled</span></label><button disabled={busy} className="h-10 self-center rounded bg-[#185e46] px-4 text-sm font-bold text-white disabled:opacity-50">Save</button></form>)}</section>
      <section className="mt-8 rounded-[22px] border bg-white p-5"><h2 className="text-xl font-bold">Recent subscriptions</h2>{data.subscriptions.length?data.subscriptions.map(subscription=><div className="grid gap-2 border-t py-3 text-sm md:grid-cols-4" key={subscription.id}><strong>{subscription.organization?.name||"Business"}</strong><span>{subscription.plan_code}</span><span>{subscription.status}</span><span>{subscription.provider} · {subscription.current_period_ends_at?new Date(subscription.current_period_ends_at).toLocaleDateString("en-GB"):"No renewal"}</span></div>):<p className="mt-3 text-sm text-[#728078]">No paid subscriptions yet.</p>}</section>
    </>:null}
  </section>;
}
