import type { Metadata } from "next";
import Link from "next/link";
import { ProcurementFooter, ProcurementHeader } from "@/components/procurement/site-shell";
import { LEGAL_CONTACT_EMAIL, TERMS_VERSION } from "@/lib/legal";
import {publicMetadata} from "@/lib/seo/site";

export const metadata: Metadata = publicMetadata({title:"Terms of Service | BidScope Ghana",description:"The terms governing accounts, subscriptions, procurement intelligence and use of BidScope Ghana.",path:"/terms"});

const sections = [
  ["agreement", "Agreement to these terms"], ["service", "The BidScope service"], ["eligibility", "Eligibility and accounts"], ["procurement", "Procurement information"], ["ai", "BidScope AI"], ["subscriptions", "Plans, trials and payments"], ["acceptable-use", "Acceptable use"], ["content", "Your content and licence"], ["intellectual-property", "Our intellectual property"], ["third-parties", "Third-party services and sources"], ["communications", "Service communications"], ["availability", "Availability and changes"], ["termination", "Suspension and termination"], ["warranties", "Disclaimers"], ["liability", "Limitation of liability"], ["indemnity", "Indemnity"], ["law", "Governing law and disputes"], ["changes", "Changes to these terms"], ["contact", "Contact us"],
] as const;

export default function TermsPage() {
  return <main className="min-h-screen bg-[#f7f4eb] text-[#12352a]"><ProcurementHeader/><article className="mx-auto max-w-5xl px-5 py-14 sm:px-6 sm:py-20">
    <header className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#84651f]">BidScope Ghana · Legal</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Terms of Service</h1><p className="mt-5 text-base leading-8 text-[#496159]">Effective and last updated: 16 September 2026 · Version {TERMS_VERSION}</p><p className="mt-6 text-lg leading-8 text-[#334d45]">These Terms of Service form a binding agreement between you and BidScope Ghana (“BidScope”, “we”, “us” or “our”) when you create an account, purchase a plan or use our website, applications, alerts, research tools or procurement-intelligence services.</p></header>
    <div className="mt-10 grid gap-10 lg:grid-cols-[240px_1fr]">
      <nav aria-label="Terms contents" className="h-fit rounded-2xl border border-[#12352a]/10 bg-white/70 p-5 lg:sticky lg:top-24"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#6d7d76]">On this page</p><ol className="mt-4 grid gap-2 text-sm leading-5">{sections.map(([id,label],index)=><li key={id}><a href={`#${id}`} className="text-[#38584e] hover:text-[#116149] hover:underline">{index+1}. {label}</a></li>)}</ol></nav>
      <div className="legal-copy space-y-10 text-base leading-8 text-[#334d45]">
        <LegalSection id="agreement" number="1" title="Agreement to these terms"><p>By selecting the signup acceptance box, creating an account, accessing a paid feature or otherwise using BidScope, you confirm that you have read, understood and agree to these Terms. You also acknowledge our <Link href="/privacy">Privacy Policy</Link> and <Link href="/cookies">Cookie Policy</Link>. If you use BidScope for a company or other organisation, you confirm that you are authorised to accept these Terms for that organisation; “you” then includes both you and that organisation.</p><p>If you do not agree, do not create an account or use the service. Mandatory rights provided by applicable law are not excluded by these Terms.</p></LegalSection>
        <LegalSection id="service" number="2" title="The BidScope service"><p>BidScope is an independent procurement-intelligence platform. Depending on your plan, it may help you discover public-sector and development-funded opportunities, search and filter notices, review buyer and award information, receive alerts, save records, manage a bid pipeline, collaborate with team members, use AI-assisted research and access other procurement tools.</p><p>BidScope is not a government agency, procurement authority, issuing entity, tender portal, law firm, financial adviser or bid-submission agent. We do not award contracts, control procurement processes, submit bids for you or guarantee that you will qualify, win or receive any commercial result.</p></LegalSection>
        <LegalSection id="eligibility" number="3" title="Eligibility and accounts"><ul><li>You must be at least 18 years old and legally capable of entering a contract.</li><li>You must provide accurate, current information and keep it updated.</li><li>You are responsible for your password, authorised users, team seats and all activity under your account.</li><li>You must notify us promptly if you suspect unauthorised access or a security incident.</li><li>You may not create accounts using another person’s identity, misleading information or automated means.</li></ul><p>One person may not share a personal login among multiple users. Where a plan includes team seats, each user must use their own authorised account. We may require reasonable information to verify identity, authority, eligibility or payment.</p></LegalSection>
        <LegalSection id="procurement" number="4" title="Procurement information and your responsibilities"><p>We collect, structure, summarise and link information from identified official, public and licensed sources. Procurement records can be amended, cancelled, delayed, incomplete, mistranslated or published with errors. The issuing authority’s notice and tender documents are always authoritative.</p><p>Before relying on an opportunity, you must independently confirm the official reference, scope, eligibility, mandatory documents, fees, bid security, clarification process, submission method and deadline directly with the issuing authority. You are solely responsible for deciding whether to bid and for the accuracy, legality and timely delivery of any submission.</p><p>Labels such as “live”, “open”, “matched”, “recommended”, “closing soon”, “Ghana eligible” or a match percentage are research aids based on available data; they are not official determinations or guarantees.</p></LegalSection>
        <LegalSection id="ai" number="5" title="BidScope AI and automated features"><p>BidScope AI may generate summaries, questions, comparisons, recommendations or explanations from indexed records and other permitted sources. AI output can be incomplete, inaccurate or outdated and may not capture every clause in the official documents. It does not constitute legal, procurement, accounting, technical or financial advice.</p><p>You must review cited sources and official documents, use qualified professional advice where appropriate and exercise human judgment before acting. Do not enter confidential bid information, trade secrets, personal data you are not authorised to disclose or unlawful content into AI features. We may apply usage limits, safety controls and source restrictions.</p></LegalSection>
        <LegalSection id="subscriptions" number="6" title="Plans, trials, payments and renewal"><ul><li><strong>Plans and limits.</strong> Features, seats, alerts, AI usage, exports and support levels depend on the plan shown at purchase. We may enforce those limits technically.</li><li><strong>Prices and taxes.</strong> Prices are displayed before checkout and may exclude taxes or charges imposed by your bank or payment provider. You authorise our payment provider to process the amount shown.</li><li><strong>Billing period and renewal.</strong> The checkout page will state whether a subscription renews automatically and its billing period. If it renews, you authorise recurring charges until cancellation.</li><li><strong>Trials and promotions.</strong> Trial eligibility, duration and included features are shown when offered. Unless checkout expressly says otherwise, a no-card trial does not automatically become a paid plan.</li><li><strong>Cancellation.</strong> You may cancel a renewing plan through available account controls or by contacting us. Cancellation normally takes effect at the end of the paid billing period unless applicable law requires otherwise.</li><li><strong>Refunds.</strong> Fees already paid are non-refundable except where the checkout terms, our stated refund policy or applicable law provides otherwise. Contact us promptly about duplicate or unauthorised charges.</li><li><strong>Price changes.</strong> We will give reasonable advance notice of changes affecting a future renewal. You may cancel before the changed price takes effect.</li></ul><p>Payments may be processed by Paystack or another disclosed provider. We do not store complete payment-card details on BidScope servers.</p></LegalSection>
        <LegalSection id="acceptable-use" number="7" title="Acceptable use"><p>You must use BidScope lawfully and fairly. You must not:</p><ul><li>circumvent access controls, plan limits, rate limits, authentication or security measures;</li><li>scrape, harvest, bulk-download, mirror, resell or redistribute the service or its organised database except through an expressly permitted feature or written agreement;</li><li>introduce malware, probe vulnerabilities, disrupt infrastructure or attempt unauthorised access;</li><li>use the service for fraud, collusion, bid-rigging, corruption, sanctions evasion, deceptive submissions or infringement of another person’s rights;</li><li>misrepresent BidScope as an official authority or remove source attribution, copyright or proprietary notices;</li><li>use automated output as the sole basis for a decision with legal or similarly significant effects on another person.</li></ul></LegalSection>
        <LegalSection id="content" number="8" title="Your content and licence to operate the service"><p>You retain ownership of information and documents you upload or enter. You grant us a worldwide, non-exclusive, limited licence to host, copy, process, transmit and display that content only as reasonably necessary to provide, secure, support and improve the service and comply with law. You confirm that you have the rights and lawful basis needed to provide the content.</p><p>You are responsible for backups of material important to your business. We may remove content that violates these Terms, infringes rights or creates a security or legal risk.</p></LegalSection>
        <LegalSection id="intellectual-property" number="9" title="Our intellectual property"><p>BidScope and its licensors own the platform, software, design, brand, original research structure, taxonomies and other protected materials, excluding third-party source records and your content. Subject to these Terms, we grant you a limited, revocable, non-exclusive, non-transferable right to use the service for your internal business procurement activities during your account or subscription period.</p><p>No rights are granted by implication. Feedback you voluntarily provide may be used without restriction or payment, provided we do not identify you publicly without permission.</p></LegalSection>
        <LegalSection id="third-parties" number="10" title="Third-party services and official sources"><p>BidScope links to procurement portals, documents, authentication providers, payment services and other third-party websites. Their availability, security, content and terms are controlled by their operators. A link, source label or integration does not imply endorsement or affiliation. You must comply with third-party terms when using those services.</p></LegalSection>
        <LegalSection id="communications" number="11" title="Service communications and alerts"><p>We may send essential account, security, billing, legal and service notices. You cannot opt out of communications strictly necessary to operate your account. Opportunity alerts and marketing communications are optional where required by law and can be managed through available settings or the unsubscribe link. Alerts are a convenience and may be delayed, filtered or unavailable; you remain responsible for monitoring official sources and deadlines.</p></LegalSection>
        <LegalSection id="availability" number="12" title="Availability, maintenance and changes"><p>We aim to provide a reliable service but do not promise uninterrupted or error-free availability. Maintenance, internet failures, source outages, security events and third-party changes may affect access. We may add, modify or retire features and integrations. If a material reduction affects a paid plan, we will provide reasonable notice where practicable.</p></LegalSection>
        <LegalSection id="termination" number="13" title="Suspension and termination"><p>You may stop using BidScope at any time. We may suspend or terminate access where we reasonably believe there is non-payment, misuse, a security threat, a legal requirement or a material breach of these Terms. Where appropriate, we will give notice and an opportunity to remedy the issue. Provisions that by their nature should survive—such as payment obligations, intellectual property, disclaimers, liability and dispute terms—remain effective after termination.</p></LegalSection>
        <LegalSection id="warranties" number="14" title="Disclaimers"><p>To the maximum extent permitted by law, BidScope is provided on an “as available” basis. We do not warrant that every opportunity will be indexed, that source data or AI output will be complete or accurate, that alerts will arrive before a deadline, or that use of the service will produce a successful bid or award. Nothing in these Terms excludes a warranty or consumer right that cannot lawfully be excluded.</p></LegalSection>
        <LegalSection id="liability" number="15" title="Limitation of liability"><p>Nothing in these Terms excludes liability that cannot legally be excluded, including liability for fraud or fraudulent misrepresentation. Subject to that, BidScope will not be liable for indirect, incidental, special, punitive or consequential loss, or for lost profits, revenue, business, opportunity, anticipated savings, goodwill or data arising from use of the service, missed deadlines, source errors, third-party systems or AI output.</p><p>For claims connected with a paid service, our total aggregate liability will not exceed the fees you paid to BidScope for the affected service during the 12 months before the event giving rise to the claim. For a free service, our total aggregate liability will not exceed GHS 500. These limits apply only to the extent permitted by applicable law.</p></LegalSection>
        <LegalSection id="indemnity" number="16" title="Indemnity"><p>If you use BidScope for a business, you will indemnify BidScope against reasonable third-party claims, losses and costs arising from your unlawful use, your content, your bid submissions or your material breach of these Terms, except to the extent caused by BidScope’s own breach or wrongdoing.</p></LegalSection>
        <LegalSection id="law" number="17" title="Governing law and disputes"><p>These Terms are governed by the laws of the Republic of Ghana, without regard to conflict-of-law rules. Before filing a formal claim, each party will give the other written notice and make a good-faith effort for at least 30 days to resolve the dispute. Subject to any mandatory consumer forum or jurisdiction, the courts of Ghana will have jurisdiction.</p></LegalSection>
        <LegalSection id="changes" number="18" title="Changes to these terms"><p>We may update these Terms to reflect service, legal or security changes. We will publish the revised version and effective date. For material changes, we will provide reasonable notice through the service or by email. Continued use after the effective date constitutes acceptance where permitted by law; if you do not agree, you must stop using the service and cancel any renewal before it takes effect.</p></LegalSection>
        <LegalSection id="contact" number="19" title="Contact us"><p>Questions, legal notices or billing concerns may be sent to <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>. Please include your account email and enough information for us to understand the request. Do not send passwords, payment-card numbers or confidential bid documents by email.</p></LegalSection>
      </div>
    </div>
  </article><ProcurementFooter/></main>;
}

function LegalSection({id,number,title,children}:{id:string;number:string;title:string;children:React.ReactNode}) { return <section id={id} className="scroll-mt-24 border-t border-[#12352a]/10 pt-8 first:border-0 first:pt-0"><h2 className="text-2xl font-semibold tracking-tight text-[#12352a]"><span className="mr-2 text-[#9a7429]">{number}.</span>{title}</h2><div className="mt-3 space-y-3">{children}</div></section>; }
