import {randomUUID} from "node:crypto";
import {apiErrorResponse,ApiError} from "@/lib/server/api-error";
import {requireSuperAdmin} from "@/lib/server/auth";
import {supabaseRest} from "@/lib/server/supabase-rest";
import {hashFile} from "@/lib/server/outreach/importer";
import {uploadOutreachFile} from "@/lib/server/outreach/storage";

export const runtime="nodejs";export const maxDuration=300;
export async function GET(request:Request){try{await requireSuperAdmin(request);const{data}=await supabaseRest("prospect_imports?select=*&order=created_at.desc&limit=50");return Response.json({data});}catch(error){return apiErrorResponse(error);}}
export async function POST(request:Request){try{const{user}=await requireSuperAdmin(request);const form=await request.formData();const file=form.get("file");if(!(file instanceof File))throw new ApiError(400,"Choose a CSV file.","missing_file");if(file.size>50*1024*1024)throw new ApiError(413,"Prospect files must be 50 MB or smaller.","file_too_large");const extension=file.name.split(".").pop()?.toLowerCase();if(extension!=="csv")throw new ApiError(400,"Only CSV files are currently supported. Export Excel files as CSV before uploading.","invalid_file_type");const buffer=Buffer.from(await file.arrayBuffer()),hash=hashFile(buffer);const duplicateQuery=new URLSearchParams({select:"id,original_filename,status,created_at",file_hash:`eq.${hash}`,order:"created_at.desc",limit:"1"});const{data:duplicates}=await supabaseRest<Array<{id:string;original_filename:string;status:string;created_at:string}>>(`prospect_imports?${duplicateQuery}`);const id=randomUUID(),safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-120),storagePath=`${id}/${safeName}`;await uploadOutreachFile(storagePath,buffer,file.type||"text/csv");const body={id,original_filename:file.name,storage_path:storagePath,file_hash:hash,file_size_bytes:file.size,file_type:extension,uploaded_by:user.id,status:"uploaded",stage:"reading",warning_message:duplicates[0]?`This exact file was previously uploaded as ${duplicates[0].original_filename} (${duplicates[0].status}).`:null};await supabaseRest("prospect_imports",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(body)});await supabaseRest("audit_log",{method:"POST",body:JSON.stringify({actor_user_id:user.id,action:"outreach.import.uploaded",entity_type:"prospect_import",entity_id:id,metadata:{filename:file.name,file_hash:hash,size:file.size,duplicate_of:duplicates[0]?.id||null}})});return Response.json({data:body},{status:201});}catch(error){return apiErrorResponse(error);}}
