import type { Metadata } from "next";
import { CookieSettingsButton } from "@/components/legal/cookie-consent";
import { ProcurementFooter, ProcurementHeader } from "@/components/procurement/site-shell";
import { COOKIE_POLICY_VERSION, LEGAL_CONTACT_EMAIL } from "@/lib/legal";
import {publicMetadata} from "@/lib/seo/site";

export const metadata: Metadata = publicMetadata({title:"Cookie Policy | BidScope Ghana",description:"The cookies and browser storage BidScope Ghana uses and how to control optional categories.",path:"/cookies"});

export default function CookiePolicyPage() {
  return <main className="min-h-screen bg-[#f7f4eb] text-[#12352a]"><ProcurementHeader/><article className="mx-auto max-w-4xl px-5 py-14 sm:px-6 sm:py-20"><header className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#84651f]">BidScope Ghana · Legal</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Cookie Policy</h1><p className="mt-5 text-base leading-8 text-[#496159]">Effective and last updated: 16 September 2026 · Version {COOKIE_POLICY_VERSION}</p><p className="mt-6 text-lg leading-8 text-[#334d45]">This policy explains how BidScope uses cookies and similar browser storage. Optional categories are off until you choose to allow them.</p><CookieSettingsButton className="mt-6 rounded-full bg-[#116149] px-5 py-3 text-sm font-bold text-white hover:bg-[#0d523e]"/></header>
    <div className="legal-copy mt-12 space-y-9 text-base leading-8 text-[#334d45]"><CookieSection title="1. What cookies and local storage are"><p>Cookies are small text records stored by your browser. Local and session storage are similar browser technologies. They can remember a preference, maintain a secure process, measure use or support a feature. Some expire when you close the browser; others remain for a defined period.</p></CookieSection><CookieSection title="2. Essential storage"><p>Essential storage is required for security, authentication handoffs, session renewal, payment flow integrity, fraud prevention and remembering your privacy choice. BidScope cannot provide core account functions reliably without it, so it cannot be disabled through our banner.</p><p>BidScope currently stores authentication tokens in protected browser storage for the signed-in session. Do not use a shared or public device for sensitive account activity, and sign out when finished.</p></CookieSection><CookieSection title="3. Analytics storage"><p>If you consent, analytics storage may help us understand aggregate visits, feature use, performance and errors so we can improve BidScope. We configure providers to collect only the information reasonably required and do not use optional analytics until consent is recorded.</p></CookieSection><CookieSection title="4. Marketing storage"><p>If you consent, marketing storage may help measure campaigns, remember referral information and make communications more relevant. Rejecting this category does not prevent you from using BidScope or receiving essential account messages.</p></CookieSection><CookieSection title="5. Third-party services"><p>When you choose Google authentication, Paystack checkout, an official procurement link or another external service, that provider may place cookies under its own domain and policy. BidScope does not control cookies placed after you leave our site or interact with a third-party service.</p></CookieSection><CookieSection title="6. Managing your choices"><p>Use the “Cookie settings” button above or in the footer at any time. “Reject optional” leaves essential storage active and switches off analytics and marketing choices. You can also delete site data through your browser. Blocking all storage may prevent sign-in, security or saved preferences from working.</p></CookieSection><CookieSection title="7. Changes and contact"><p>We may update this policy as technology or providers change. If a new version materially changes optional use, we may ask for your choice again. Questions may be sent to <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>.</p></CookieSection></div>
  </article><ProcurementFooter/></main>;
}

function CookieSection({title,children}:{title:string;children:React.ReactNode}) { return <section className="border-t border-[#12352a]/10 pt-8 first:border-0 first:pt-0"><h2 className="text-2xl font-semibold tracking-tight text-[#12352a]">{title}</h2><div className="mt-3 space-y-3">{children}</div></section>; }
