import Image from"next/image";
import Link from"next/link";
import{ArrowRight,BookOpenCheck}from"lucide-react";
import{ProcurementFooter,ProcurementHeader}from"@/components/procurement/site-shell";
import{Breadcrumbs,SeoCta}from"@/components/seo/public-seo";
import{listPublishedSeoContent,type PublishedSeoContent}from"@/lib/server/seo-content";
import{publicMetadata}from"@/lib/seo/site";
export const metadata=publicMetadata({title:"Procurement Insights and Tender Guides | BidScope",description:"Practical Ghana tender guides for suppliers, SMEs and procurement teams: finding opportunities, bidding, alerts, supplier readiness and fair evaluation.",path:"/insights"});
const sections=["Finding tenders","Bidding","For suppliers","For buyers","Procurement"];
function Card({item,featured=false}:{item:PublishedSeoContent;featured?:boolean}){return <article className={`group overflow-hidden rounded-[28px] border border-[#17362d]/10 bg-white shadow-[0_14px_40px_rgba(20,58,46,.06)] ${featured?"md:grid md:grid-cols-[.75fr_1.25fr]":""}`}><div className={`relative overflow-hidden bg-[#dce8df] ${featured?"min-h-64":"h-44"}`}><Image src={item.featured_image_url||"/images/ghana-supplier.webp"} alt="" fill sizes={featured?"(min-width:768px) 38vw, 100vw":"(min-width:768px) 45vw, 100vw"} className="object-cover transition duration-500 group-hover:scale-[1.03]"/><div className="absolute inset-0 bg-gradient-to-t from-[#103f32]/45 to-transparent"/></div><div className="p-6 sm:p-7"><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#8a6a2d]">{item.cluster}</p><h2 className={`${featured?"text-3xl":"text-2xl"} mt-3 font-black leading-tight`}><Link href={`/insights/${item.slug}`}>{item.title}</Link></h2><p className="mt-3 line-clamp-3 leading-7 text-[#61736a]">{item.excerpt}</p><Link href={`/insights/${item.slug}`} className="mt-5 inline-flex items-center gap-2 font-black text-[#116149]">Read guide <ArrowRight size={16}/></Link></div></article>}
export default async function Insights(){const items=await listPublishedSeoContent(100),featured=items[0];return <main className="min-h-screen bg-[#f7f4eb] text-[#17362d]"><ProcurementHeader/><section className="mx-auto max-w-7xl px-5 py-12 sm:px-8"><Breadcrumbs items={[{name:"Home",href:"/"},{name:"Insights",href:"/insights"}]}/><header className="relative mt-8 overflow-hidden rounded-[34px] bg-[#103f32] px-7 py-10 text-white sm:px-11 sm:py-14"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(208,164,75,.28),transparent_38%)]"/><div className="relative max-w-4xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-[#a8e2ca]"><BookOpenCheck size={16}/>BidScope knowledge centre</span><h1 className="serif mt-5 text-4xl leading-tight sm:text-6xl">Practical tender guidance for Ghanaian businesses.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">Learn how to discover opportunities, prepare stronger responses, run fair procurement and build a more dependable bidding process.</p></div></header>{featured?<div className="mt-10"><Card item={featured} featured/></div>:<div className="mt-10 rounded-3xl border border-dashed bg-white p-10 text-center text-[#61736a]">Reviewed articles will appear here after an administrator completes the editorial checks.</div>}{sections.map(section=>{const grouped=items.filter((item,index)=>index>0&&item.cluster.toLowerCase()===section.toLowerCase());return grouped.length?<section key={section} className="mt-14"><div className="flex items-end justify-between gap-4 border-b border-[#17362d]/15 pb-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#116149]">Insights collection</p><h2 className="serif mt-2 text-3xl sm:text-4xl">{section}</h2></div><span className="text-sm text-[#61736a]">{grouped.length} guide{grouped.length===1?"":"s"}</span></div><div className="mt-6 grid gap-5 md:grid-cols-2">{grouped.map(item=><Card key={item.id} item={item}/>)}</div></section>:null})}<div className="mt-14"><SeoCta/></div></section><ProcurementFooter/></main>}
