import {z} from "zod";
import {apiErrorResponse} from "@/lib/server/api-error";
import {requireSuperAdmin} from "@/lib/server/auth";
import {createNotification} from "@/lib/server/notifications";
import {audit} from "@/lib/server/procurement/access";
import {supabaseRest} from "@/lib/server/supabase-rest";

export const dynamic="force-dynamic";
export async function GET(request:Request){try{await requireSuperAdmin(request);const status=new URL(request.url).searchParams.get("status")||"pending";const{data}=await supabaseRest(`buyer_verifications?select=id,organization_id,organization_name,registration_number,official_company_email,contact_person,organization_type,document_paths,status,submitted_by,submitted_at,reviewed_by,reviewed_at,verification_notes&status=eq.${encodeURIComponent(status)}&order=submitted_at.asc.nullslast&limit=200`);return Response.json({data},{headers:{"Cache-Control":"private, no-store"}});}catch(error){return apiErrorResponse(error);}}
export async function POST(request:Request){try{const{user}=await requireSuperAdmin(request);const input=z.object({id:z.string().uuid(),decision:z.enum(["verified","rejected","suspended"]),notes:z.string().trim().max(5000).default("")}).parse(await request.json());const{data}=await supabaseRest<Array<{id:string;organization_id:string;submitted_by:string;status:string}>>(`buyer_verifications?select=id,organization_id,submitted_by,status&id=eq.${input.id}&limit=1`),verification=data[0];if(!verification)return Response.json({error:"Verification request not found."},{status:404});const at=new Date().toISOString();await supabaseRest(`buyer_verifications?id=eq.${input.id}`,{method:"PATCH",body:JSON.stringify({status:input.decision,verification_notes:input.notes||null,reviewed_by:user.id,reviewed_at:at})});if(input.decision==="suspended")await supabaseRest(`organizations?id=eq.${verification.organization_id}`,{method:"PATCH",body:JSON.stringify({can_procure:false})});await createNotification({userId:verification.submitted_by,organizationId:verification.organization_id,type:"system",pushEventKey:"verification",title:input.decision==="verified"?"Buyer verification approved":"Buyer verification updated",message:input.decision==="verified"?"Your organisation can now publish BidScope Tenders.":`Your buyer verification was ${input.decision}. ${input.notes}`.trim(),relatedEntityType:"buyer_verification",relatedEntityId:verification.id,relatedUrl:"/procurement/settings",priority:"high",frequencyOverride:"instant",dedupeKey:`buyer-verification-${verification.id}-${input.decision}-${at.slice(0,10)}`});await audit({organizationId:verification.organization_id,actorUserId:user.id,action:`buyer_verification_${input.decision}`,entityType:"buyer_verification",entityId:verification.id,before:{status:verification.status},after:{status:input.decision,notes:input.notes}});return Response.json({data:{status:input.decision}});}catch(error){return apiErrorResponse(error);}}
