"use client";

import { useEffect, useState } from "react";
import { ArrowRight, Check, Crown, Users } from "lucide-react";

const plans=[
  {name:"Free",description:"Explore current opportunities and verify every notice at its official source.",features:["Live open opportunities","Official source links","Basic search and filters"],cta:"Create free account",href:"/api/auth/google",featured:false},
  {name:"Pro",description:"For Ghanaian businesses that want faster shortlisting and better-informed bid decisions.",features:["Everything in Free","Saved opportunities and bid workspace","Business-fit matching","Priority opportunity alerts","Buyer and award intelligence"],cta:"Upgrade to Pro",href:"mailto:bidscopeghana@gmail.com?subject=BidScope%20Pro%20upgrade",featured:true},
  {name:"Business",description:"For teams managing several sectors, opportunities and bidding responsibilities.",features:["Everything in Pro","Multiple team members","Shared opportunity pipeline","Team alerts and oversight","Priority onboarding"],cta:"Discuss Business",href:"mailto:bidscopeghana@gmail.com?subject=BidScope%20Business%20plan",featured:false},
];

export function PlansClient(){const [signedIn,setSignedIn]=useState(false);useEffect(()=>{void Promise.resolve().then(()=>setSignedIn(Boolean(localStorage.getItem("bidscope_access_token"))));},[]);return <section><div className="bg-[#103f32] px-5 py-12 text-center text-white"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#8ce0bd]">BidScope membership</p><h1 className="serif mx-auto mt-3 max-w-3xl text-4xl tracking-[-.04em] sm:text-6xl">Choose the intelligence your business needs.</h1><p className="mx-auto mt-4 max-w-2xl leading-7 text-white/68">Start free. Move to Pro when you need matching, alerts and a structured bidding workflow.</p></div><div className="mx-auto grid max-w-7xl gap-5 px-5 py-10 sm:px-6 lg:grid-cols-3 lg:px-8">{plans.map(plan=><article key={plan.name} className={`relative flex flex-col rounded-[28px] border p-6 sm:p-8 ${plan.featured?"border-[#c89a43] bg-[#fffdf8] shadow-[0_24px_70px_rgba(19,62,49,.12)]":"border-[#17362d]/10 bg-white"}`}>{plan.featured&&<span className="absolute right-5 top-5 inline-flex items-center gap-1.5 rounded-full bg-[#17362d] px-3 py-1.5 text-xs font-bold text-white"><Crown size={13} className="text-[#d6af5d]"/>Recommended</span>}<div className={`grid size-11 place-items-center rounded-xl ${plan.featured?"bg-[#d6af5d] text-[#17362d]":"bg-[#e4efe8] text-[#116149]"}`}>{plan.name==="Business"?<Users/>:<Crown/>}</div><h2 className="serif mt-5 text-4xl text-[#17362d]">{plan.name}</h2><p className="mt-3 min-h-20 text-sm leading-6 text-[#61736a]">{plan.description}</p><ul className="mt-6 flex-1 space-y-3">{plan.features.map(feature=><li key={feature} className="flex items-start gap-3 text-sm text-[#36564b]"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-[#e3f2e9] text-[#116149]"><Check size={12}/></span>{feature}</li>)}</ul><a href={plan.name==="Free"&&signedIn?"/profile":plan.href} className={`mt-8 inline-flex h-12 items-center justify-center gap-2 rounded-full px-5 text-sm font-bold ${plan.featured?"bg-[#116149] text-white":"border border-[#17362d]/15 text-[#17362d]"}`}>{plan.name==="Free"&&signedIn?"View profile":plan.cta}<ArrowRight size={16}/></a></article>)}</div><p className="mx-auto max-w-3xl px-5 pb-4 text-center text-sm leading-6 text-[#65776f]">Pro and Business upgrades are confirmed personally while secure online billing is being completed. No payment is taken from this page.</p></section>;}
