import {createHmac,timingSafeEqual} from "node:crypto";
import {ApiError} from "../api-error.ts";

export type CampaignState="draft"|"needs_review"|"approved"|"scheduled"|"sending"|"paused"|"completed"|"cancelled";
const transitions:Record<CampaignState,CampaignState[]>={draft:["needs_review","cancelled"],needs_review:["draft","approved","cancelled"],approved:["scheduled","sending","cancelled"],scheduled:["sending","paused","cancelled"],sending:["paused","completed","cancelled"],paused:["sending","cancelled"],completed:[],cancelled:[]};
export function assertCampaignTransition(from:CampaignState,to:CampaignState){if(!transitions[from]?.includes(to))throw new ApiError(409,`Campaign cannot move from ${from} to ${to}.`,"invalid_campaign_transition");}

const allowedVariables=new Set(["company_name","first_name","industry","country","city","tender_count","award_count","latest_activity","relevant_category","bidscope_url","unsubscribe_url","cta_url"]);
export function templateVariables(value:string){return[...value.matchAll(/{{\s*([a-z_]+)\s*}}/g)].map(match=>match[1]);}
export function renderTemplate(value:string,data:Record<string,unknown>){const unknown=templateVariables(value).filter(key=>!allowedVariables.has(key));if(unknown.length)throw new ApiError(400,`Unsupported template variable: ${unknown[0]}.`,"invalid_template_variable");return value.replace(/{{\s*([a-z_]+)\s*}}/g,(_,key)=>String(data[key]??""));}

function secret(){const value=process.env.OUTREACH_TRACKING_SECRET||process.env.BIDSCOPE_INTERNAL_SECRET;if(!value)throw new ApiError(503,"Outreach token security is not configured.","outreach_not_configured");return value;}
export function createSecureToken(payload:Record<string,string>,ttlDays=90){const body=Buffer.from(JSON.stringify({...payload,exp:Date.now()+ttlDays*86400000})).toString("base64url");const sig=createHmac("sha256",secret()).update(body).digest("base64url");return`${body}.${sig}`;}
export function verifySecureToken(token:string){const[body,sig]=token.split(".");if(!body||!sig)throw new ApiError(400,"This link is invalid.","invalid_token");const expected=createHmac("sha256",secret()).update(body).digest("base64url");if(sig.length!==expected.length||!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))throw new ApiError(400,"This link is invalid.","invalid_token");const parsed=JSON.parse(Buffer.from(body,"base64url").toString("utf8")) as Record<string,string|number>;if(Number(parsed.exp)<Date.now())throw new ApiError(410,"This link has expired.","expired_token");return parsed;}

export function outreachEligibility(input:{email?:string|null;doNotContact?:boolean;unsubscribedAt?:string|null;bouncedAt?:string|null;suppressed?:boolean;activeCampaign?:boolean;lastContactedAt?:string|null;minimumGapDays?:number}){if(!input.email)return{eligible:false,reason:"Missing valid email"};if(input.doNotContact)return{eligible:false,reason:"Do not contact"};if(input.unsubscribedAt||input.suppressed)return{eligible:false,reason:"Suppressed"};if(input.bouncedAt)return{eligible:false,reason:"Hard bounced"};if(input.activeCampaign)return{eligible:false,reason:"Already in an active acquisition campaign"};if(input.lastContactedAt&&Date.now()-new Date(input.lastContactedAt).getTime()<(input.minimumGapDays??14)*86400000)return{eligible:false,reason:"Campaign frequency gap"};return{eligible:true,reason:null};}
