import test from "node:test";
import assert from "node:assert/strict";
import{readFileSync}from"node:fs";
import{join}from"node:path";
import{buildSearchOpportunities,SEARCH_OPPORTUNITY_STATES,SEARCH_OPPORTUNITY_TYPES,type SearchMetric}from"../../lib/server/seo-search-opportunity-engine.ts";
const read=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");

test("growth migration extends existing outreach instead of duplicating it",()=>{const sql=read("supabase/migrations/20260921003000_growth_outreach_search_console_engine.sql");assert.match(sql,/alter table public\.seo_outreach_targets/);assert.match(sql,/alter table public\.seo_backlinks/);for(const table of["seo_outreach_activities","seo_partnerships","seo_search_performance_windows","seo_search_opportunities"]){assert.match(sql,new RegExp(`create table if not exists public\\.${table}`));assert.match(sql,new RegExp(`'${table}'`))}});

test("research seed has at least forty individually evidenced organisations and no invented email",()=>{const sql=read("supabase/migrations/20260921003000_growth_outreach_search_console_engine.sql"),rows=(sql.match(/^\('\w/mg)||[]).length;assert.ok(rows>=40,`expected at least 40 researched rows, found ${rows}`);assert.match(sql,/verification_source_url/);assert.match(sql,/Verified from the linked official or credible institutional page/);assert.doesNotMatch(sql,/@(?:gmail|yahoo|hotmail|outlook)\./i)});

test("outreach and partnership writes remain administrator-only and draft-only",()=>{const route=read("app/api/admin/growth/route.ts"),logic=read("lib/server/growth-relationships.ts");assert.match(route,/requireSuperAdmin/);assert.match(logic,/manualReviewRequired:true,autoSend:false/);assert.doesNotMatch(logic,/sendMail|resend\.emails|fetch\([^)]*mail/i);assert.match(logic,/already tracked/)});

test("Search Console opportunity vocabulary and human states are complete",()=>{for(const type of["LOW_CTR","NEAR_PAGE_ONE","DECLINING_TRAFFIC","RISING_QUERY","CONTENT_GAP","QUERY_MISMATCH","CANNIBALISATION","HIGH_IMPRESSIONS_LOW_CONVERSIONS","STRONG_PAGE_EXPANSION","INTERNAL_LINK_OPPORTUNITY"])assert.ok(SEARCH_OPPORTUNITY_TYPES.includes(type as never));for(const state of["NEW","DATA_COLLECTING","WATCH","READY_TO_OPTIMISE","OPTIMISATION_IN_PROGRESS","MEASURING_RESULT","STABLE","NEEDS_REVIEW"])assert.ok(SEARCH_OPPORTUNITY_STATES.includes(state as never))});

test("opportunity engine enforces impression threshold and compares windows",()=>{const current:SearchMetric[]=[{dimensionType:"query",value:"ghana tenders",clicks:4,impressions:500,ctr:.008,position:9.5},{dimensionType:"query",value:"procurement ghana",clicks:5,impressions:500,ctr:.01,position:12},{dimensionType:"query",value:"too small",clicks:0,impressions:40,ctr:0,position:9}],previous:SearchMetric[]=[{dimensionType:"query",value:"ghana tenders",clicks:12,impressions:300,ctr:.04,position:8.8},{dimensionType:"query",value:"procurement ghana",clicks:4,impressions:300,ctr:.013,position:13}],ninetyDay:SearchMetric[]=[{dimensionType:"query",value:"ghana tenders",clicks:25,impressions:1200,ctr:.02,position:10.2},{dimensionType:"query",value:"procurement ghana",clicks:10,impressions:1000,ctr:.01,position:13}];const result=buildSearchOpportunities({current,previous,ninetyDay,minimumImpressions:100});assert.ok(result.some(item=>item.opportunityType==="LOW_CTR"));assert.ok(result.some(item=>item.opportunityType==="NEAR_PAGE_ONE"));assert.ok(result.some(item=>item.opportunityType==="DECLINING_TRAFFIC"));assert.ok(result.some(item=>item.opportunityType==="RISING_QUERY"));assert.ok(result.every(item=>item.query!=="too small"));assert.ok(result.every(item=>item.previousMetrics&&item.ninetyDayMetrics))});

test("growth admin exposes requested relationship tabs and manual SEO actions",()=>{const ui=read("components/admin/growth-relationship-workspace.tsx");for(const tab of["Overview","Organisations","Outreach","Partnerships","Backlinks","Follow-ups"])assert.match(ui,new RegExp(`\\"${tab}\\"`));for(const action of["Approve for work","Snooze 14 days","Mark implemented","Dismiss / review"])assert.match(ui,new RegExp(action));assert.match(ui,/will not send/i)});
