import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {analyseRows,parseProspectFile} from "../../lib/server/outreach/importer.ts";
import {assertCampaignTransition,outreachEligibility,renderTemplate} from "../../lib/server/outreach/campaign.ts";
import {classifyCompany,duplicateConfidence,normalizeCompanyName,normalizeEmail,suggestColumnMappings} from "../../lib/server/outreach/intelligence.ts";

test("outreach migration creates the required private CRM tables and safe queue",()=>{const sql=readFileSync("supabase/migrations/20260916120000_bidscope_outreach.sql","utf8");for(const table of ["prospects","prospect_imports","prospect_import_rows","prospect_segments","campaigns","campaign_steps","campaign_recipients","campaign_messages","email_events","suppression_list","campaign_templates","campaign_attribution","prospect_notes","prospect_tags","outreach_settings"])assert.match(sql,new RegExp(`create table if not exists public\\.${table}`));assert.match(sql,/enable row level security/);assert.match(sql,/emergency_stop boolean not null default true/);assert.match(sql,/sending_enabled boolean not null default false/);assert.match(sql,/state='sending'/);});
test("column aliases map procurement datasets without discarding originals",()=>{const map=suggestColumnMappings(["Organisation","Mail","Sector Description","Telephone"]);assert.equal(map[0].field,"company_name");assert.equal(map[1].field,"email");assert.equal(map[2].field,"industry");assert.equal(map[3].field,"phone");});
test("CSV parser handles quoted commas and import analysis rejects bad email",()=>{const parsed=parseProspectFile(Buffer.from('Organisation,Mail,Sector Description\n"ABC, Ltd",TEAM@EXAMPLE.COM,Construction\nBad,bad-email,IT'),"csv");assert.equal(parsed.rows.length,2);const result=analyseRows(parsed);assert.equal(result.staged[0].cleaned.email,"team@example.com");assert.equal(result.staged[0].classification.primary,"Construction");assert.equal(result.staged[1].status,"rejected");});
test("normalization and duplicate detection stop duplicate emails",()=>{assert.equal(normalizeEmail("  SALES@Example.COM "),"sales@example.com");assert.equal(normalizeCompanyName("A.B.C. Construction Limited"),"a b c construction");assert.equal(duplicateConfidence({email:"A@x.com"},{email:"a@x.com"}).level,"exact");});
test("multi-address source cells select one canonical email without duplicating the prospect",()=>{assert.equal(normalizeEmail("sales@example.com; info@example.com; SALES@example.com"),"sales@example.com");});
test("classification uses deterministic evidence before AI",()=>{const result=classifyCompany({company_name:"Accra Medical and Laboratory Supplies Ltd"});assert.equal(result.primary,"Medical Supplies");assert.equal(result.method,"deterministic_keywords");assert.ok(result.confidence>=.85);});
test("campaign transitions require review then approval then start",()=>{assert.doesNotThrow(()=>assertCampaignTransition("draft","needs_review"));assert.doesNotThrow(()=>assertCampaignTransition("needs_review","approved"));assert.doesNotThrow(()=>assertCampaignTransition("approved","sending"));assert.throws(()=>assertCampaignTransition("draft","sending"));});
test("suppression and overlap always block eligibility",()=>{assert.equal(outreachEligibility({email:"a@example.com",suppressed:true}).eligible,false);assert.equal(outreachEligibility({email:"a@example.com",activeCampaign:true}).eligible,false);assert.equal(outreachEligibility({email:"a@example.com"}).eligible,true);});
test("templates permit only documented variables",()=>{assert.equal(renderTemplate("Hi {{company_name}}",{company_name:"Acme"}),"Hi Acme");assert.throws(()=>renderTemplate("{{secret}}",{}));});
