import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { dedupeCitations,groundedFallback,modelContext,opportunityEvidenceChunk,providerAnalysisHasUnsupportedCompetitionClaim,providerAnalysisHasUnsupportedRequirementClaim,retrieveRelevantChunks,type DocumentChunk,type OpportunityContext } from "../../lib/server/procurement-ai.ts";
import { chunkDocument } from "../../lib/server/documents.ts";
const opportunity:OpportunityContext={id:"00000000-0000-4000-8000-000000000001",title:"Supply of medical equipment",summary:"Equipment for regional hospitals",description:"",buyer_name:"Ghana Health Service",external_reference:"GHS/26/1",bidscope_reference:"BS-1",eligibility_text:null,procurement_method:"Open tender",contract_type:"Goods",estimated_value:null,currency:null,published_at:"2026-09-01T00:00:00Z",deadline_at:"2026-09-24T12:00:00Z",official_source_url:"https://example.gov.gh/tender",official_tender_url:null,documents_url:null,source_name:"Official source",submission_method:null,submission_platform:null};
const chunks:DocumentChunk[]=[{id:"1",document_id:"d1",chunk_index:0,page_number:17,section_label:"4.2",content:"Bidders shall provide a valid Tax Clearance Certificate and bid security.",document:{title:"Tender Document",url:"https://example.gov.gh/tender.pdf"}},{id:"2",document_id:"d1",chunk_index:1,page_number:22,section_label:"7",content:"The evaluation method considers technical responsiveness.",document:{title:"Tender Document",url:"https://example.gov.gh/tender.pdf"}}];
test("retrieval selects tender sections relevant to the question",()=>{const result=retrieveRelevantChunks(chunks,"Which tax clearance document is needed?",1);assert.equal(result[0].page_number,17);});
test("mandatory document analysis cites source text and does not guarantee an outcome",()=>{const result=groundedFallback("mandatory_documents","",opportunity,chunks);assert.match(result.content,/tax clearance/i);assert.doesNotMatch(result.content,/will win|guaranteed/i);assert.equal(result.citations[1].page,17);});
test("unknown questions are explicitly labelled unavailable",()=>{const result=groundedFallback("question","Does the buyer prefer us?",opportunity,[]);assert.match(result.content,/Not stated in the available source documents/i);});
test("AI answers use the safe Markdown renderer instead of exposing formatting characters",()=>{const detail=readFileSync(new URL("../../components/customer/detail.tsx",import.meta.url),"utf8");const renderer=readFileSync(new URL("../../components/ui/safe-markdown.tsx",import.meta.url),"utf8");assert.match(detail,/SafeMarkdown/);for(const element of[/strong/,/h2/,/table/,/hr/])assert.match(renderer,element);assert.doesNotMatch(renderer,/dangerouslySetInnerHTML/);});

test("explanation uses the official title when the source omits a fuller scope",()=>{
  const result=groundedFallback("question","Explain this tender and its key requirements.",{...opportunity,title:"PURCHASE OF ASK SAGE TOKENS",summary:"",description:""},[]);
  assert.match(result.content,/official record identifies the purchase as “PURCHASE OF ASK SAGE TOKENS”/);
  assert.doesNotMatch(result.content,/What is being procured:\*\* Not stated/);
});
test("official structured metadata is available to AI retrieval",()=>{const detailed={...opportunity,source_details:{"Evaluation Mechanism":"Lowest Evaluated Responsive Tenderer (LERT)","Bid Security Amount":"2%"}};const chunk=opportunityEvidenceChunk(detailed);assert.match(chunk.content,/LERT/);assert.match(chunk.content,/2%/);assert.equal(chunk.document?.url,opportunity.official_source_url);});
test("explain questions produce a useful evidence-backed fallback",()=>{const detailed={...opportunity,qualification_requirements:"Postqualification required",bid_security_requirement:"2%",participation_fee_amount:500,participation_fee_currency:"GHS"};const result=groundedFallback("question","Explain this tender and its key requirements.",detailed,[opportunityEvidenceChunk(detailed)]);assert.match(result.content,/Postqualification required/);assert.match(result.content,/GHS 500/);assert.equal(result.groundingStatus,"verified");});
test("duplicate source links are removed even when sections differ",()=>{const citations=dedupeCitations([{label:"Official",url:"https://example.gov.gh/tender",documentId:"a",section:"Metadata"},{label:"Revision",url:"https://example.gov.gh/tender",documentId:"b",section:"Revision"}]);assert.equal(citations.length,1);});
test("explain fallback recovers GHANEPS fee and security from source details",()=>{const detailed={...opportunity,source_details:{"Payment Amount\\s*GHS":"500","Bid Security Amount\\s*GHS":"2","Bid Security Amount Type":"Percentage","Evaluation Mechanism":"LERT"}};const result=groundedFallback("question","Explain this tender and its key requirements.",detailed,[opportunityEvidenceChunk(detailed)]);assert.match(result.content,/Participation fee:\*\* 500/);assert.match(result.content,/2%/);assert.match(result.content,/LERT/);});
test("document chunking preserves long source content without mutating it",()=>{const input="A".repeat(9000);const output=chunkDocument(input);assert.ok(output.length>=3);assert.equal(output[0].chunk_index,0);assert.ok(output.every(chunk=>chunk.content.length<=4000));});
test("model context never exposes the internal opportunity id",()=>{const context=modelContext({action:"summary",question:"Explain",opportunity,chunks});assert.equal("id" in context.opportunity,false);assert.doesNotMatch(JSON.stringify(context),new RegExp(opportunity.id));});
test("unsupported sole-source claims are rejected but cited competition evidence is retained",()=>{const special={...opportunity,contract_type:"Special Notice"};assert.equal(providerAnalysisHasUnsupportedCompetitionClaim("This is a sole-source award without competition.",special),true);assert.equal(providerAnalysisHasUnsupportedCompetitionClaim("This Special Notice is a non‑competitive, sole‑source award. No competitive bidding process is indicated.",special),true);assert.equal(providerAnalysisHasUnsupportedCompetitionClaim("The notice type is Special Notice; competition details are not stated.",special),false);assert.equal(providerAnalysisHasUnsupportedCompetitionClaim("This is a sole-source award.",{...special,description:"Intent to award as a sole-source procurement."}),false);});
test("generic portal guidance cannot become a tender requirement",()=>{const generic={...opportunity,eligibility_text:"A bidder should verify entity registration and exclusions before bidding."};assert.equal(providerAnalysisHasUnsupportedRequirementClaim("Any bidder must be registered in SAM.gov and must not be excluded.",generic),true);assert.equal(providerAnalysisHasUnsupportedRequirementClaim("SAM registration | Must be registered in SAM.gov and not be excluded.",generic),true);assert.equal(providerAnalysisHasUnsupportedRequirementClaim("Most Special Notice solicitations require a technical proposal, price proposal and compliance statements.",generic),true);assert.equal(providerAnalysisHasUnsupportedRequirementClaim("The record advises bidders to verify registration and exclusions.",generic),false);assert.equal(providerAnalysisHasUnsupportedRequirementClaim("Bidders must be registered in SAM.gov.",{...generic,qualification_requirements:"Bidders shall be registered in SAM.gov."}),false);});
