import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{join}from"node:path";
const root=process.cwd();const read=(path:string)=>readFileSync(join(root,path),"utf8");
test("SEO metadata uses the canonical production domain and reusable social tags",()=>{const site=read("lib/seo/site.ts");assert.match(site,/https:\/\/www\.bidscopeghana\.com/);assert.match(site,/alternates:\{canonical\}/);assert.match(site,/openGraph/);assert.match(site,/twitter/)});
test("sitemap includes public acquisition content and excludes account routes",()=>{const sitemap=read("app/sitemap.ts");assert.match(sitemap,/\/tenders/);assert.match(sitemap,/\/for-buyers/);assert.match(sitemap,/\/for-suppliers/);assert.match(sitemap,/\/resources/);assert.doesNotMatch(sitemap,/\/sign-in/);assert.doesNotMatch(sitemap,/\/customer/)});

test("public header keeps core discovery routes reachable below desktop widths",()=>{const shell=read("components/procurement/site-shell.tsx");for(const route of["/tenders/ghana","/for-suppliers","/for-buyers","/plans","/services"])assert.match(shell,new RegExp(`xl:hidden[\\s\\S]*href=\\"${route.replaceAll("/","\\/")}\\"`));});
test("robots excludes private workspaces without blocking public tenders",()=>{const robots=read("app/robots.ts");assert.match(robots,/\/admin\//);assert.match(robots,/\/customer\//);assert.match(robots,/\/procurement\//);assert.match(robots,/\/meetings\//);assert.doesNotMatch(robots,/disallow:[^\n]*\/tenders/)});
test("public tender details are server rendered with safe metadata, related links and schema",()=>{const page=read("app/opportunities/[slug]/page.tsx");assert.match(page,/generateMetadata/);assert.match(page,/getPublicTender/);assert.match(page,/initialItem=\{item\}/);assert.match(page,/Related live tenders/);assert.match(page,/WebPage/);assert.doesNotMatch(page,/buyer_name|official_source_url/)});
test("thin category and location pages are kept out of the index",()=>{const page=read("app/tenders/[[...segments]]/page.tsx");assert.match(page,/result\.total<3/);assert.match(page,/noindex/);assert.match(page,/Faqs/)});
test("private routes explicitly publish noindex directives",()=>{for(const path of["app/customer/[[...section]]/page.tsx","app/procurement/layout.tsx","app/admin/command-centre/layout.tsx","app/profile/layout.tsx","app/notifications/layout.tsx","app/settings/layout.tsx","app/workspace/layout.tsx","app/auth/layout.tsx"]){assert.match(read(path),/index:false/,path)}});
test("homepage names tenders, procurement and Ghana in visible and metadata content",()=>{assert.match(read("app/layout.tsx"),/Tenders, Procurement & Contract Opportunities in Ghana/);const home=read("app/opportunity-dashboard.tsx");assert.match(home,/Find tenders/);assert.match(home,/procurement opportunities in Ghana/)});

test("password reset has a descriptive private page title",()=>{const layout=read("app/auth/reset-password/layout.tsx");assert.match(layout,/Reset your password \| BidScope/);assert.match(layout,/index: false/)});
test("resource pages use article and breadcrumb structured data",()=>{const guide=read("app/resources/[slug]/page.tsx");assert.match(guide,/Article/);assert.match(guide,/Breadcrumbs/);assert.match(guide,/dateModified/)});
