/* eslint-disable react-hooks/exhaustive-deps */
"use client";

import Link from "next/link";
import { Bell, CheckCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useBidScopeSession } from "./auth-nav";

type Notice={id:string;type:string;title:string;message:string;related_url:string|null;priority:string;read_at:string|null;created_at:string};

export function NotificationBell(){const signedIn=useBidScopeSession();const[open,setOpen]=useState(false);const[items,setItems]=useState<Notice[]>([]);const[count,setCount]=useState(0);const[filter,setFilter]=useState("all");
  async function load(){const token=localStorage.getItem("bidscope_access_token");if(!token)return;const response=await fetch(`/api/notifications?type=${filter}&limit=20`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)return;const body=await response.json() as {data:Notice[];unreadCount:number};setItems(body.data);setCount(body.unreadCount);}
  useEffect(()=>{if(signedIn)void Promise.resolve().then(load);},[signedIn,filter]);
  if(!signedIn)return null;
  async function markAll(){const token=localStorage.getItem("bidscope_access_token");if(!token)return;await fetch("/api/notifications",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({markAllRead:true})});void load();}
  async function change(id:string,body:Record<string,boolean>){const token=localStorage.getItem("bidscope_access_token");if(!token)return;await fetch(`/api/notifications/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});void load();}
  return <div className="relative"><button type="button" onClick={()=>setOpen(!open)} aria-label={`${count} unread notifications`} className="relative grid size-9 place-items-center rounded-full border border-[#17362d]/15 bg-white text-[#27493f] hover:bg-[#edf3ee]"><Bell size={16}/>{count>0&&<span className="absolute -right-1 -top-1 grid min-w-4 place-items-center rounded-full bg-[#d65f42] px-1 text-[9px] font-bold leading-4 text-white">{count>99?"99+":count}</span>}</button>{open&&<div className="fixed inset-x-3 top-[68px] z-50 max-h-[72vh] overflow-hidden rounded-2xl border border-[#17362d]/10 bg-[#fffdf8] shadow-2xl sm:absolute sm:-right-12 sm:left-auto sm:top-11 sm:w-[390px]"><div className="flex items-center justify-between border-b px-4 py-3"><div><p className="font-bold text-[#17362d]">Notifications</p><p className="text-[10px] text-[#6d7e76]">Latest 20 alerts · full history in the centre</p></div><button onClick={markAll} className="inline-flex items-center gap-1 text-[11px] font-bold text-[#116149]"><CheckCheck size={14}/>Mark all read</button></div><div className="flex gap-1 overflow-x-auto border-b px-3 py-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{[["all","All"],["opportunity_match","Matches"],["deadline","Deadlines"],["buyer_activity","Buyers"],["award","Awards"],["document_expiry","Documents"],["system","System"]].map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-bold ${filter===value?"bg-[#116149] text-white":"bg-[#edf1eb] text-[#526a61]"}`}>{label}</button>)}</div><div className="max-h-[52vh] overflow-y-auto">{items.length===0?<p className="p-8 text-center text-sm text-[#697a72]">No notifications in this category.</p>:items.map(item=><article key={item.id} className={`relative border-b p-4 last:border-0 ${item.read_at?"bg-transparent":"bg-[#eaf4ee]"}`}><button aria-label="Dismiss" onClick={()=>change(item.id,{dismissed:true})} className="absolute right-3 top-3 text-[#829087]"><X size={14}/></button><span className={`text-[9px] font-bold uppercase tracking-wider ${item.priority==="urgent"?"text-[#c95037]":"text-[#16805e]"}`}>{item.type.replaceAll("_"," ")}</span><Link href={item.related_url||"/notifications"} onClick={()=>{void change(item.id,{read:true});setOpen(false)}} className="mt-1 block pr-5"><strong className="text-sm text-[#17362d]">{item.title}</strong><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#63756d]">{item.message}</p></Link></article>)}</div><Link href="/notifications" onClick={()=>setOpen(false)} className="block border-t px-4 py-3 text-center text-xs font-bold text-[#116149]">Open notification centre</Link></div>}</div>;
}
