"use client";
import {useState,type FormEvent} from "react";
import Link from "next/link";
import {api,invalidate,useData} from "@/components/customer/data";
import {SERVICE_CATALOG,serviceName,type ServiceRequest} from "@/lib/service-catalog";
const field="mt-2 w-full rounded-xl border border-[#17362d]/20 bg-white p-3 text-base";
const button="rounded-full bg-[#116149] px-5 py-3 font-bold text-white disabled:opacity-50";
const TODAY: string = new Date().toISOString().slice(0,10);
const money=(minor:number)=>new Intl.NumberFormat("en-GH",{style:"currency",currency:"GHS"}).format(minor/100);
export function ServiceWorkspace({admin=false,initialService="tender-review"}:{admin?:boolean;initialService?:string}){
 const endpoint=admin?"/api/admin/services":"/api/services";
 const result=useData<{data:ServiceRequest[]}>(endpoint);
 const [selected,setSelected]=useState(initialService);
 const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const service=SERVICE_CATALOG.find(item=>item.code===selected)||SERVICE_CATALOG[0];
 async function mutate(body:unknown,method="PATCH"){setBusy(true);setMessage("");try{await api(endpoint,body,method);invalidate();setMessage("Saved successfully. No payment has been taken.");return true;}catch(error){setMessage(error instanceof Error?error.message:"Unable to save. Please try again.");return false;}finally{setBusy(false);}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const values=new FormData(form);const saved=await mutate({serviceCode:service.code,brief:values.get("brief"),deliverables:values.getAll("deliverable"),quantity:Number(values.get("quantity")),requestedDate:values.get("date")||null},"POST");if(saved)form.reset();}
 async function quote(event:FormEvent<HTMLFormElement>,item:ServiceRequest){event.preventDefault();const values=new FormData(event.currentTarget);await mutate({action:"quote",id:item.id,version:item.version,scope:values.get("scope"),amountMinor:Math.round(Number(values.get("amount"))*100),terms:values.get("terms"),expiresAt:new Date(`${values.get("expiry")}T23:59:59Z`).toISOString(),turnaroundDays:Number(values.get("days"))});}
 return <section className="mx-auto max-w-6xl px-5 py-10 text-[#17362d]"><p className="text-sm font-bold uppercase tracking-widest text-[#116149]">Custom procurement support</p><h1 className="serif mt-3 text-4xl">{admin?"Service requests & quotations":"Your service workspace"}</h1><p className="mt-4 max-w-3xl leading-7 text-[#61736a]">{admin?"Confirm capacity before quoting. Include deliverables, exclusions, revisions, payment arrangements, taxes and cancellation terms. Accepted quotes cannot be silently edited.":"Customise your request and review quotes here. Services are separate purchases, not included subscription benefits. Accepting a quote does not trigger an automatic charge."}</p>
 <div className="mt-4 flex flex-wrap gap-5 font-semibold"><Link href="/services">Service catalogue</Link><Link href="/plans">Subscription plans</Link><Link href="/customer">My workspace</Link></div>
 {message&&<p role="status" className="mt-5 rounded-xl border bg-white p-4">{message}</p>}
 {result.loading?<p className="py-8">Loading requests…</p>:result.error?<div role="alert" className="mt-6 rounded-2xl bg-white p-6"><p>{result.error}</p><Link href="/sign-in?next=%2Fservices%2Frequests" className="mt-4 inline-block font-bold underline">Sign in or create an account</Link></div>:<>
 {!admin&&<form onSubmit={submit} className="mt-8 space-y-5 rounded-3xl border bg-white p-6"><h2 className="text-2xl font-bold">Build your request</h2><label className="block">Service<select className={field} value={service.code} onChange={event=>setSelected(event.target.value)}>{SERVICE_CATALOG.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select></label><fieldset key={service.code}><legend className="font-semibold">Choose deliverables</legend>{service.deliverables.map(label=><label key={label} className="mt-3 flex gap-3"><input name="deliverable" value={label} type="checkbox" defaultChecked/>{label}</label>)}</fieldset><label className="block">Describe your requirements<textarea className={field} name="brief" required minLength={30} maxLength={5000} rows={5} placeholder="Tell us the sector, tender reference if relevant, requested work and exclusions. Do not include passwords, payment details or sensitive personal documents."/></label><div className="grid gap-5 sm:grid-cols-2"><label>Quantity (CVs, profiles, briefs or sessions)<input className={field} name="quantity" type="number" required min={1} max={100} defaultValue={1}/></label><label>Preferred completion date — not guaranteed<input className={field} name="date" type="date" min={TODAY}/></label></div><label className="flex gap-3 text-sm leading-6"><input type="checkbox" required/>I understand this is a request, not a confirmed booking, and I am authorised to share the information supplied.</label><button className={button} disabled={busy}>Request a tailored quote</button></form>}
 <h2 className="mt-10 text-2xl font-bold">{admin?"Requests for review":"Requests and quotes"}</h2>
 {!result.data?.data.length&&<p className="mt-5 rounded-2xl border border-dashed p-8">No service requests yet.</p>}
 <div className="mt-5 space-y-5">{result.data?.data.map(item=><article className="rounded-3xl border bg-white p-6" key={item.id}><div className="flex flex-wrap justify-between gap-3"><h3 className="text-xl font-bold">{serviceName(item.service_code)}</h3><span className="rounded-full bg-[#e8efe9] px-3 py-1 text-sm font-bold">{item.status.replaceAll("_"," ")}</span></div><p className="mt-2 text-xs text-[#61736a]">Request {item.id.slice(0,8)} · Version {item.version} · {new Date(item.created_at).toLocaleDateString("en-GB")}</p><p className="mt-4 whitespace-pre-wrap leading-7">{item.brief}</p><p className="mt-3 text-sm">Quantity: {item.quantity} · Preferred date: {item.requested_date||"Flexible"}</p><ul className="mt-3 list-inside list-disc text-sm">{item.deliverables.map(value=><li key={value}>{value}</li>)}</ul>
 {item.quote_scope&&<section className="mt-5 rounded-2xl bg-[#f3f6f2] p-5"><h4 className="font-bold">Your quotation · {money(item.quote_amount_minor||0)}</h4><p className="mt-3 whitespace-pre-wrap leading-7">{item.quote_scope}</p><p className="mt-3">Turnaround: {item.turnaround_days} days from the agreed start.</p><p>Quote expires: {item.quote_expires_at?new Date(item.quote_expires_at).toLocaleString("en-GB"):"—"}</p><h5 className="mt-4 font-semibold">Payment, delivery and cancellation terms</h5><p className="mt-2 whitespace-pre-wrap leading-7">{item.quote_terms}</p></section>}
 {!admin&&item.status==="QUOTED"&&<form className="mt-5" onSubmit={event=>{event.preventDefault();void mutate({id:item.id,version:item.version,action:"accept",agreed:true});}}><label className="flex gap-3 leading-6"><input required type="checkbox"/>I accept this quote’s scope, total fee and terms. Payment arrangements will be confirmed separately.</label><div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={busy||Date.parse(item.quote_expires_at||"")<=Date.parse(`${TODAY}T00:00:00Z`)}>Accept quote — no charge now</button><button type="button" disabled={busy} className="rounded-full border px-5 py-3" onClick={()=>void mutate({id:item.id,version:item.version,action:"decline"})}>Decline</button></div></form>}
 {admin&&["REQUESTED","QUOTED"].includes(item.status)&&<details className="mt-5 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Prepare / revise quotation</summary><form className="mt-5 space-y-4" onSubmit={event=>void quote(event,item)}><label className="block">Agreed deliverables and exclusions<textarea className={field} name="scope" required minLength={30} maxLength={5000} rows={4} defaultValue={item.quote_scope||""}/></label><div className="grid gap-4 sm:grid-cols-3"><label>Total fee in GHS<input className={field} type="number" name="amount" min={1} max={1000000} step="0.01" required defaultValue={item.quote_amount_minor?item.quote_amount_minor/100:undefined}/></label><label>Turnaround days<input className={field} type="number" name="days" min={1} max={365} required defaultValue={item.turnaround_days||7}/></label><label>Quote expiry (UTC)<input className={field} type="date" name="expiry" required min={TODAY}/></label></div><label className="block">Payment, taxes, revisions and cancellation terms<textarea className={field} name="terms" required minLength={30} maxLength={3000} rows={4} defaultValue={item.quote_terms||""}/></label><button className={button} disabled={busy}>Issue quote to customer workspace</button></form></details>}
 {admin&&<div className="mt-5 flex flex-wrap gap-3">{(item.status==="ACCEPTED"?["start"]:item.status==="IN_PROGRESS"?["complete"]:["REQUESTED","QUOTED"].includes(item.status)?["decline"]:[]).map(action=><button className={button} disabled={busy} key={action} onClick={()=>void mutate({id:item.id,version:item.version,action})}>{action==="start"?"Confirm arrangements & start":action==="complete"?"Mark delivered":"Decline request"}</button>)}</div>}
 </article>)}</div></>}
 </section>;
}
