import { BrandLogo } from "@/components/brand/brand-logo";
import { AuthNav, MemberNavLinks } from "@/components/procurement/auth-nav";
import Link from "next/link";
import { NotificationBell } from "@/components/procurement/notification-bell";
import { CookieSettingsButton } from "@/components/legal/cookie-consent";
import { FloatingHelp } from "@/components/help/floating-help";

export function FloatingHelpButton() {
  return <FloatingHelp />;
}

export function ProcurementHeader() {
  return <header className="sticky top-0 z-40 border-b border-[#084d33]/10 bg-[#fdfbf4]/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:gap-5 sm:px-6 lg:px-8"><Link href="/" aria-label="BidScope home"><BrandLogo priority className="h-auto w-[132px] sm:w-[170px]"/></Link><nav aria-label="Primary navigation" className="ml-auto flex items-center gap-1 text-xs font-semibold text-[#35554a] sm:gap-2 sm:text-sm"><Link className="hidden rounded-full px-3 py-2 hover:bg-[#e9f1e8] xl:inline-flex" href="/tenders/ghana">Tenders</Link><Link className="hidden rounded-full px-3 py-2 hover:bg-[#e9f1e8] xl:inline-flex" href="/for-suppliers">For suppliers</Link><Link className="hidden rounded-full px-3 py-2 hover:bg-[#e9f1e8] xl:inline-flex" href="/for-buyers">For buyers</Link><MemberNavLinks/><Link className="hidden rounded-full px-3 py-2 hover:bg-[#e9f1e8] lg:inline-flex" href="/plans">Plans</Link><Link className="rounded-full px-2 py-2 hover:bg-[#e9f1e8]" href="/blog">Blog</Link><Link className="hidden rounded-full px-2 py-2 hover:bg-[#e9f1e8] sm:inline-flex" href="/services">Services</Link><details className="group relative xl:hidden"><summary className="cursor-pointer list-none rounded-full border border-[#17362d]/12 bg-white px-3 py-2 font-bold text-[#214c3e] hover:bg-[#e9f1e8]">Menu</summary><div className="absolute right-0 top-[calc(100%+.65rem)] z-50 grid min-w-52 gap-1 rounded-2xl border border-[#17362d]/12 bg-[#fffdf8] p-2 shadow-[0_18px_50px_rgba(15,55,43,.18)]"><Link className="rounded-xl px-4 py-3 hover:bg-[#e9f1e8]" href="/tenders/ghana">Tenders</Link><Link className="rounded-xl px-4 py-3 hover:bg-[#e9f1e8]" href="/for-suppliers">For suppliers</Link><Link className="rounded-xl px-4 py-3 hover:bg-[#e9f1e8]" href="/for-buyers">For buyers</Link><Link className="rounded-xl px-4 py-3 hover:bg-[#e9f1e8]" href="/plans">Plans</Link><Link className="rounded-xl px-4 py-3 hover:bg-[#e9f1e8] sm:hidden" href="/services">Services</Link></div></details><NotificationBell/><AuthNav/></nav></div></header>;
}

export function ProcurementFooter() {
  const discovery=[["Tenders","/tenders"],["Public tenders","/public-tenders"],["Private tenders","/private-tenders"],["For suppliers","/for-suppliers"],["For buyers","/for-buyers"],["Blog","/blog"],["Resources","/resources"]];
  const company=[["How it works","/how-it-works"],["About","/about"],["Contact","/contact"],["Privacy","/privacy"],["Terms","/terms"],["Cookies","/cookies"]];
  return <><footer className="mt-16 bg-[#0b3e30] text-white/70"><div className="mx-auto grid max-w-7xl gap-9 px-5 py-11 text-sm leading-6 md:grid-cols-[1.6fr_1fr_1fr] lg:px-8"><div><BrandLogo reversed className="h-auto w-40"/><p className="mt-5 max-w-xl">BidScope is an independent procurement intelligence platform. External notices originate from official and public sources, and formal bids follow the issuing authority&apos;s designated process.</p></div><nav aria-label="Discover BidScope"><p className="font-bold text-white">Discover</p><ul className="mt-3 space-y-2">{discovery.map(([label,href])=><li key={href}><Link href={href} className="hover:text-white hover:underline">{label}</Link></li>)}</ul></nav><nav aria-label="Company and legal"><p className="font-bold text-white">Company</p><ul className="mt-3 space-y-2">{company.map(([label,href])=><li key={href}><Link href={href} className="hover:text-white hover:underline">{label}</Link></li>)}</ul><CookieSettingsButton className="mt-2 hover:text-white"/></nav></div></footer><FloatingHelpButton/></>;
}
