"use client";

import { useEffect, useState } from "react";
import { api } from "@/components/customer/data";
import { GhanepsOcdsCard } from "./ghaneps-ocds-card";

type Source = { id: string; slug: string; name: string; base_url: string; official_source: boolean; reuse_status: string; license_name: string | null; license_url: string | null; permission_evidence: string | null; permission_date: string | null; permission_expiry: string | null; permission_notes: string | null; content_reuse_allowed: boolean; commercial_reuse_allowed: boolean; document_reuse_allowed: boolean; metadata_reuse_allowed: boolean; last_rights_reviewed_at: string | null; discovery_auto_publish_enabled: boolean; discovery_enabled: boolean; crawl_robots_allowed: boolean; crawl_terms_reviewed: boolean; crawl_last_success_at: string | null; crawl_consecutive_failures: number; crawl_next_at: string | null; crawl_max_pages: number };
type Discovery = { id: string; source_id: string; raw_title: string | null; raw_text: string; canonical_url: string; extracted_data: { title?: string; buyer?: string; reference?: string; deadline?: string; description?: string }; processing_status: string; duplicate_status: string; matched_tender_id: string | null; confidence_score: number; duplicate_score: number; error_message: string | null; first_seen_at: string };
type Job = { id: string; status: string; source_id: string; pages_examined: number; discoveries_found: number; started_at: string; error_message: string | null };
type Settings = { enabled: boolean; auto_publish: boolean; max_crawls_per_day: number };
type RightsAudit = { id: string; source_id: string; old_rights: { reuse_status?: string }; new_rights: { reuse_status?: string }; changed_at: string };
type Snapshot = { discoveries: Discovery[]; sources: Source[]; jobs: Job[]; rightsAudit: RightsAudit[]; settings: Settings | null };
const rightsStatuses = ["official_open_data", "explicitly_licensed", "written_permission", "official_api", "public_link_only", "permission_unknown", "prohibited"];

export function DiscoveryCentre() {
  const [data, setData] = useState<Snapshot | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [status, setStatus] = useState("needs_review");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [rightsId, setRightsId] = useState<string | null>(null);
  const [rightsDraft, setRightsDraft] = useState<Source | null>(null);
  async function load() {
    const result = await api<{ data: Snapshot }>(`/api/admin/discovery?status=${encodeURIComponent(status)}`);
    setData(result.data);
  }
  useEffect(() => {
    void api<{ data: Snapshot }>(`/api/admin/discovery?status=${encodeURIComponent(status)}`)
      .then(result => setData(result.data))
      .catch(() => setMessage("Discovery data is unavailable. Check whether the migration has been applied."));
  }, [status]);
  async function act(body: Record<string, unknown>) {
    setBusy(true);
    try { await api("/api/admin/discovery", body, "POST"); await load(); setMessage("Action saved."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Action failed."); }
    finally { setBusy(false); }
  }
  const chosen = data?.discoveries.find(item => item.id === selected);
  function editRights(source: Source) { setRightsId(source.id); setRightsDraft({ ...source }); }
  function updateRights(values: Partial<Source>) { setRightsDraft(current => current ? { ...current, ...values } : current); }
  const rightsSource = data?.sources.find(source => source.id === rightsId);
  async function saveRights() {
    if (!rightsDraft) return;
    await act({ action: "rights", id: rightsDraft.id, reuseStatus: rightsDraft.reuse_status,
      licenseName: rightsDraft.license_name, licenseUrl: rightsDraft.license_url,
      permissionEvidence: rightsDraft.permission_evidence, permissionDate: rightsDraft.permission_date,
      permissionExpiry: rightsDraft.permission_expiry, permissionNotes: rightsDraft.permission_notes,
      contentReuseAllowed: rightsDraft.content_reuse_allowed, commercialReuseAllowed: rightsDraft.commercial_reuse_allowed,
      documentReuseAllowed: rightsDraft.document_reuse_allowed, metadataReuseAllowed: rightsDraft.metadata_reuse_allowed,
      autoPublishEnabled: rightsDraft.discovery_auto_publish_enabled });
  }
  const sourceName = (id: string) => data?.sources.find(source => source.id === id)?.name || "Unknown source";
  return <section className="mx-auto max-w-7xl space-y-6 px-4 py-8 text-[#17362d] sm:px-7">
    <header className="rounded-[28px] bg-gradient-to-r from-[#0b372c] via-[#12644e] to-[#214c3e] p-7 text-white shadow-xl">
      <p className="text-xs font-black uppercase tracking-[.2em] text-[#d9c786]">Procurement intelligence</p>
      <h1 className="mt-2 text-3xl font-bold sm:text-4xl">Opportunity discovery</h1>
      <p className="mt-2 max-w-2xl text-sm leading-6 text-white/75">Private crawler staging, source health and human review. Nothing enters the customer feed until it passes publication checks.</p>
    </header>
    {message && <p role="status" className="rounded-xl border border-[#c5d8cc] bg-white p-3 text-sm">{message}</p>}
    <GhanepsOcdsCard />
    <div className="grid gap-4 lg:grid-cols-3">
      <section className="rounded-2xl bg-white p-5 shadow-sm lg:col-span-1"><h2 className="font-bold">Controls</h2><p className="mt-2 text-xs text-[#61736a]">Global crawl access is off until sources and permissions are reviewed.</p><div className="mt-4 space-y-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(data?.settings?.enabled)} disabled={busy} onChange={event => void act({ action: "settings", enabled: event.target.checked })}/> Scheduled discovery</label><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(data?.settings?.auto_publish)} disabled={busy} onChange={event => void act({ action: "settings", autoPublish: event.target.checked })}/> Automatic publication</label><p>Daily crawl cap: {data?.settings?.max_crawls_per_day ?? "—"}</p><button type="button" disabled={busy} onClick={() => void act({ action: "run" })} className="rounded-full bg-[#116149] px-4 py-2 font-bold text-white disabled:opacity-50">Run next due source</button><button type="button" disabled={busy} onClick={() => void act({ action: "poll" })} className="ml-2 rounded-full border border-[#116149] px-4 py-2 font-bold text-[#116149] disabled:opacity-50">Check jobs</button></div></section>
      <section className="rounded-2xl bg-white p-5 shadow-sm lg:col-span-2">
        <h2 className="font-bold">Source health</h2>
        <p className="mt-1 text-xs text-[#61736a]">Review each site’s crawling rules and reuse terms before enabling it. A source remains blocked until both checks are recorded.</p>
        <div className="mt-3 max-h-72 space-y-2 overflow-auto">{data?.sources.map(source => <div key={source.id} className="rounded-xl border border-[#dce6df] p-3 text-sm">
          <div className="flex flex-wrap items-center justify-between gap-2"><div><b>{source.name}</b><p className="text-xs text-[#61736a]">{source.crawl_consecutive_failures ? `Failing · ${source.crawl_consecutive_failures} errors` : source.crawl_last_success_at ? "Healthy" : "Not tested"} · max {source.crawl_max_pages} pages</p></div><div className="flex flex-wrap gap-2"><button disabled={busy || !["explicitly_licensed", "written_permission", "public_link_only"].includes(source.reuse_status) || source.slug === "ghana-ministry-finance"} onClick={() => void act({ action: "source", id: source.id, enabled: !source.discovery_enabled })} className="rounded-full border px-3 py-1.5 disabled:opacity-40">{source.discovery_enabled ? "Pause" : "Enable"}</button><button disabled={busy || !source.discovery_enabled || !source.crawl_robots_allowed || !source.crawl_terms_reviewed} onClick={() => void act({ action: "run", sourceId: source.id })} className="rounded-full bg-[#e7f4ed] px-3 py-1.5 font-semibold disabled:opacity-40">Run now</button></div></div>
          <div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><a href={source.base_url} target="_blank" rel="noopener noreferrer" className="font-semibold text-[#116149] underline">Source site</a><a href={`${new URL(source.base_url).origin}/robots.txt`} target="_blank" rel="noopener noreferrer" className="font-semibold text-[#116149] underline">Robots rules</a><label className="flex items-center gap-1"><input type="checkbox" checked={source.crawl_robots_allowed} disabled={busy} onChange={event => void act({ action: "source", id: source.id, robotsAllowed: event.target.checked })}/> Robots reviewed</label><label className="flex items-center gap-1"><input type="checkbox" checked={source.crawl_terms_reviewed} disabled={busy} onChange={event => void act({ action: "source", id: source.id, termsReviewed: event.target.checked })}/> Reuse terms reviewed</label></div>
        </div>)}</div>
      </section>
    </div>
    <section className="rounded-2xl bg-white p-5 shadow-sm" aria-labelledby="source-rights-heading">
      <h2 id="source-rights-heading" className="text-lg font-bold">Source Rights</h2>
      <p className="mt-1 text-sm text-[#61736a]">A source being official or technically accessible does not establish content reuse rights. Unknown and prohibited sources cannot be crawled or auto-published. Public-link-only records retain factual metadata and an official link, not copied descriptions or PDFs.</p>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="border-b bg-[#f0f5f1] text-xs uppercase tracking-wide"><tr>{["Source", "Rights status", "Commercial reuse", "Metadata reuse", "Documents reuse", "Evidence", "Last reviewed", "Crawler enabled", "Auto publication enabled", ""].map(label => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{data?.sources.map(source => <tr key={source.id} className="border-b border-[#e0e9e2]"><td className="px-3 py-3 font-semibold">{source.name}{source.official_source && <span className="ml-1 text-xs font-normal">· official</span>}</td><td className="px-3 py-3">{source.reuse_status.replaceAll("_", " ")}</td><td className="px-3 py-3">{source.commercial_reuse_allowed ? "Yes" : "No"}</td><td className="px-3 py-3">{source.metadata_reuse_allowed ? "Yes" : "No"}</td><td className="px-3 py-3">{source.document_reuse_allowed ? "Yes" : "No"}</td><td className="max-w-48 truncate px-3 py-3" title={source.permission_evidence || source.license_url || ""}>{source.permission_evidence || source.license_name || source.license_url || "Not recorded"}</td><td className="px-3 py-3">{source.last_rights_reviewed_at?.slice(0, 10) || "Never"}</td><td className="px-3 py-3">{source.discovery_enabled ? "Yes" : "No"}</td><td className="px-3 py-3">{source.discovery_auto_publish_enabled ? "Yes" : "No"}</td><td className="px-3 py-3"><button type="button" onClick={() => editRights(source)} className="rounded-full border border-[#116149] px-3 py-1 font-semibold text-[#116149]">Review</button></td></tr>)}</tbody></table></div>
      {rightsDraft && rightsSource && <div className="mt-5 rounded-xl border border-[#d2dfd6] bg-[#f8fbf8] p-4"><h3 className="font-bold">Rights review · {rightsSource.name}</h3><p className="mt-1 text-xs text-[#61736a]">Record evidence and exact scope before enabling a crawler. A URL or key alone is not permission.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <label className="text-sm">Rights status<select value={rightsDraft.reuse_status} onChange={event => updateRights({ reuse_status: event.target.value })} className="mt-1 block w-full rounded-lg border p-2">{rightsStatuses.map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>
        {([ ["Licence name", "license_name"], ["Licence URL", "license_url"], ["Permission evidence", "permission_evidence"], ["Permission date", "permission_date"], ["Permission expiry", "permission_expiry"], ["Permission notes", "permission_notes"] ] as const).map(([label, key]) => <label key={key} className="text-sm">{label}<input type={key === "permission_date" || key === "permission_expiry" ? "date" : key === "license_url" ? "url" : "text"} value={rightsDraft[key] || ""} onChange={event => updateRights({ [key]: event.target.value || null })} className="mt-1 block w-full rounded-lg border p-2" /></label>)}
      </div><div className="mt-4 flex flex-wrap gap-4 text-sm">{([ ["Content reuse", "content_reuse_allowed"], ["Commercial reuse", "commercial_reuse_allowed"], ["Document reuse", "document_reuse_allowed"], ["Metadata reuse", "metadata_reuse_allowed"], ["Automatic publication", "discovery_auto_publish_enabled"] ] as const).map(([label, key]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={rightsDraft[key]} onChange={event => updateRights({ [key]: event.target.checked })}/>{label}</label>)}</div><div className="mt-4 flex gap-2"><button type="button" disabled={busy} onClick={() => void saveRights()} className="rounded-full bg-[#116149] px-4 py-2 font-bold text-white disabled:opacity-40">Save rights review</button><button type="button" onClick={() => { setRightsId(null); setRightsDraft(null); }} className="rounded-full border px-4 py-2">Cancel</button></div></div>}
      <h3 className="mt-6 font-bold">Recent rights changes</h3><div className="mt-2 space-y-1 text-sm">{data?.rightsAudit?.map(item => <p key={item.id} className="border-b py-2">{sourceName(item.source_id)} · {item.old_rights.reuse_status || "unknown"} → {item.new_rights.reuse_status || "unknown"} · {new Date(item.changed_at).toLocaleString()}</p>)}{!data?.rightsAudit?.length && <p className="text-[#61736a]">No changes recorded.</p>}</div>
    </section>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-bold">Review queue</h2><select aria-label="Discovery status" value={status} onChange={event => { setStatus(event.target.value); setSelected(null); }} className="rounded-xl border border-[#d0ded5] px-3 py-2 text-sm">{["needs_review", "published", "rejected", "expired", "error"].map(value => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select></div><div className="mt-4 grid gap-3 md:grid-cols-2">{data?.discoveries.map(item => <button type="button" key={item.id} onClick={() => setSelected(item.id)} className={`rounded-xl border p-4 text-left hover:border-[#116149] ${selected === item.id ? "border-[#116149] bg-[#f1faf5]" : "border-[#dce6df]"}`}><p className="text-xs uppercase tracking-wide text-[#64756a]">{sourceName(item.source_id)} · {item.duplicate_status.replaceAll("_", " ")}</p><h3 className="mt-1 font-bold">{item.extracted_data.title || item.raw_title || "Untitled page"}</h3><p className="mt-1 text-xs text-[#61736a]">{item.extracted_data.buyer || "Buyer unknown"} · {item.extracted_data.deadline?.slice(0, 10) || "No deadline"}</p><p className="mt-2 text-xs">Extraction {Math.round(Number(item.confidence_score) * 100)}% · Duplicate {Math.round(Number(item.duplicate_score) * 100)}%</p></button>)}{data?.discoveries.length === 0 && <p className="text-sm text-[#61736a]">No records in this queue.</p>}</div></section>
    {chosen && <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">{chosen.extracted_data.title || chosen.raw_title}</h2><p className="mt-2 text-sm text-[#5b6e62]">{chosen.extracted_data.buyer} · {chosen.extracted_data.reference || "No reference"} · Deadline {chosen.extracted_data.deadline || "not found"}</p><a className="mt-2 inline-block text-sm font-semibold text-[#116149] underline" href={chosen.canonical_url} target="_blank" rel="noopener noreferrer">Open original source</a><p className="mt-3 text-sm text-[#965f32]">{chosen.error_message}</p><pre className="mt-4 max-h-64 overflow-auto whitespace-pre-wrap rounded-xl bg-[#f5f8f5] p-4 text-xs leading-5">{chosen.raw_text.slice(0, 10000)}</pre><div className="mt-4 flex flex-wrap gap-2">{chosen.processing_status !== "published" && <><button disabled={busy} onClick={() => void act({ action: "approve", id: chosen.id })} className="rounded-full bg-[#116149] px-4 py-2 text-sm font-bold text-white">Approve & publish</button><button disabled={busy} onClick={() => void act({ action: "mark_unique", id: chosen.id })} className="rounded-full border px-4 py-2 text-sm">Mark unique</button><button disabled={busy || !chosen.matched_tender_id} onClick={() => void act({ action: "merge", id: chosen.id })} className="rounded-full border px-4 py-2 text-sm">Merge with matched tender</button><button disabled={busy} onClick={() => void act({ action: "reextract", id: chosen.id })} className="rounded-full border px-4 py-2 text-sm">Re-extract</button><button disabled={busy} onClick={() => void act({ action: "reject", id: chosen.id })} className="rounded-full border border-red-200 px-4 py-2 text-sm text-red-700">Reject</button></>}</div></section>}
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold">Recent crawl jobs</h2><div className="mt-3 space-y-2 text-sm">{data?.jobs.map(job => <p key={job.id} className="border-b border-[#e3ebe5] py-2">{sourceName(job.source_id)} · {job.status} · {job.pages_examined} pages · {job.discoveries_found} new/changed{job.error_message ? ` · ${job.error_message}` : ""}</p>)}</div></section>
  </section>;
}
