import { apiErrorResponse } from "@/lib/server/api-error";
import { requireSuperAdmin } from "@/lib/server/auth";
import { configuredProviders } from "@/lib/server/ai/providers";
import { supabaseRest } from "@/lib/server/supabase-rest";

export const dynamic="force-dynamic";
type Log={provider:string|null;task_type:string;user_plan:string|null;input_tokens:number;output_tokens:number;estimated_cost_usd:number;cache_hit:boolean;rule_engine_success:boolean;premium_reasoning:boolean;fallback_count:number;status:string;created_at:string};
export async function GET(request:Request){try{await requireSuperAdmin(request);const month=new Date();month.setUTCDate(1);month.setUTCHours(0,0,0,0);const today=new Date();today.setUTCHours(0,0,0,0);const[{data:logs},{data:providers},{data:budget}]=await Promise.all([supabaseRest<Log[]>(`ai_usage_logs?select=*&created_at=gte.${month.toISOString()}&order=created_at.desc&limit=5000`),supabaseRest<Array<Record<string,unknown>>>("ai_providers?select=*&order=priority.asc"),supabaseRest<Array<Record<string,unknown>>>("ai_budget_settings?select=*&singleton_key=eq.default&limit=1")]);const adapters=new Map(configuredProviders().map(x=>[x.id,x]));const total=(key:keyof Log,filter:Log[]=logs)=>filter.reduce((sum,row)=>sum+Number(row[key]||0),0);const todayLogs=logs.filter(x=>Date.parse(x.created_at)>=today.getTime());const by=(key:keyof Log)=>Object.entries(logs.reduce<Record<string,number>>((a,row)=>{const value=String(row[key]||"unknown");a[value]=(a[value]||0)+1;return a;},{})).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);return Response.json({data:{metrics:{requestsToday:todayLogs.length,requestsMonth:logs.length,ruleResults:logs.filter(x=>x.rule_engine_success).length,cacheHits:logs.filter(x=>x.cache_hit).length,premiumRequests:logs.filter(x=>x.premium_reasoning).length,providerFailures:logs.filter(x=>x.status==="failed").length,fallbackEvents:logs.filter(x=>x.fallback_count>0).length,inputTokens:total("input_tokens"),outputTokens:total("output_tokens"),estimatedCostUsd:total("estimated_cost_usd")},byProvider:by("provider"),byFeature:by("task_type"),byPlan:by("user_plan"),providers:providers.map(p=>({...p,configured:Boolean(adapters.get(String(p.id))?.configured)})),budget:budget[0]||null}});}catch(error){return apiErrorResponse(error);}}
export async function PATCH(request:Request){try{const{user}=await requireSuperAdmin(request);const input=await request.json() as Record<string,unknown>;const keys=["daily_budget_usd","monthly_budget_usd","premium_daily_budget_usd","maximum_tokens_per_task","warning_percent"];const body=Object.fromEntries(keys.filter(key=>Number.isFinite(Number(input[key]))).map(key=>[key,Number(input[key])]));await supabaseRest("ai_budget_settings?singleton_key=eq.default",{method:"PATCH",body:JSON.stringify({...body,updated_at:new Date().toISOString()})});await supabaseRest("audit_log",{method:"POST",body:JSON.stringify({actor_user_id:user.id,action:"ai.budget.updated",entity_type:"ai_budget_settings",entity_id:"default",metadata:{changed:Object.keys(body)}})});return Response.json({data:body});}catch(error){return apiErrorResponse(error);}}
