"use client";

import { useEffect, useState } from "react";
import { BriefcaseBusiness, CircleDot } from "lucide-react";
import { SourceBadge } from "@/components/procurement/source-badge";

type Bid = { id:string; status:string; updated_at:string; notes:string; opportunity:{slug:string;title:string;buyer_name:string;deadline_at:string|null;source_name:string;external_reference:string|null} };
const stages = ["SAVED","REVIEWING","PREPARING","READY_TO_SUBMIT","OFFICIAL_SUBMISSION_OPENED","SUBMITTED","AWARDED","UNSUCCESSFUL","WITHDRAWN"];

export function BidWorkspace() {
  const [bids,setBids]=useState<Bid[]>([]); const [message,setMessage]=useState("Loading your workspace…");
  useEffect(() => { const token=localStorage.getItem("bidscope_access_token"); if(!token){void Promise.resolve().then(()=>setMessage("Sign in to view and track your saved bids."));return;} void fetch("/api/bids",{headers:{Authorization:`Bearer ${token}`}}).then(async response=>{const body=await response.json() as {data:Bid[];error?:string};if(!response.ok)throw new Error(body.error);setBids(body.data);setMessage("");}).catch(()=>setMessage("Your workspace could not be loaded.")); },[]);
  return <section className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#116149]">Bid workspace</p><h1 className="serif mt-3 text-4xl text-[#17362d] sm:text-5xl">From shortlist to outcome.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#667970]">Prepare inside BidScope, submit through the issuing authority, then record the result here. Opening an official portal never counts as a submitted bid.</p><div className="mt-8 flex gap-2 overflow-x-auto pb-2">{stages.map(stage=><span key={stage} className="shrink-0 rounded-full border border-[#17362d]/10 bg-white px-3 py-2 text-[10px] font-bold tracking-wider text-[#4d675d]">{stage.replaceAll("_"," ")}</span>)}</div>{message && <div className="mt-8 rounded-[22px] border border-dashed border-[#17362d]/20 bg-white/60 p-10 text-center"><BriefcaseBusiness className="mx-auto text-[#789087]"/><p className="mt-3 text-sm text-[#61736a]">{message}</p></div>}<div className="mt-8 grid gap-4">{bids.map(bid=><a href={`/opportunities/${bid.opportunity.slug}`} key={bid.id} className="rounded-[22px] border border-[#17362d]/10 bg-[#fffdf8] p-5 shadow-sm"><div className="flex flex-wrap items-center gap-2"><SourceBadge source={bid.opportunity.source_name}/><span className="inline-flex items-center gap-1 rounded-full bg-[#e8efe9] px-2.5 py-1 text-[10px] font-bold text-[#245543]"><CircleDot size={10}/>{bid.status.replaceAll("_"," ")}</span></div><h2 className="mt-4 text-lg font-bold text-[#17362d]">{bid.opportunity.title}</h2><p className="mt-2 text-xs text-[#6a7a73]">{bid.opportunity.buyer_name} · {bid.opportunity.external_reference || "Reference pending"}</p></a>)}</div></section>;
}
