import { createHash } from "node:crypto";
import { ApiError } from "../api-error.ts";
import { supabaseRest } from "../supabase-rest.ts";
import { configuredProviders } from "./providers.ts";
import type { AIComplexity, AIOrchestrationResult, AIPlan, AIProvider, AIProviderResult, AITaskInput } from "./types.ts";

type ModelRow={provider:string;model_id:string;enabled:boolean;task_types:string[];reasoning_level:string;premium_model:boolean;priority:number;input_cost:number;output_cost:number};
type RouteRow={task_type:string;standard_provider_order:string[];premium_provider_order:string[];standard_model_overrides:Record<string,string>;premium_model_overrides:Record<string,string>;max_output_tokens:number;cache_ttl_seconds:number};
type BudgetRow={daily_budget_usd:number;monthly_budget_usd:number;premium_daily_budget_usd:number;maximum_tokens_per_task:number;warning_percent:number};
type ProviderStateRow={id:string;enabled:boolean;allow_sensitive_data:boolean;allow_customer_documents:boolean};
const degradedUntil=new Map<string,number>();
// Workers AI is staged for reviewed, non-sensitive classification only. A database
// route or administrator preset must not silently add it to customer-facing analysis.
export function workersAITaskAllowed(input:AITaskInput):boolean{
  return input.taskType==="public_tender_classification_review"
    && !input.userId && !input.organizationId
    && !input.containsSensitiveData && !input.containsCustomerDocuments
    && !input.requiresLongContext && !input.requiresStructuredOutput;
}
const defaults:Record<string,{complexity:AIComplexity;maxOutputTokens:number;ttl:number}>={company_classification:{complexity:"LOW",maxOutputTokens:500,ttl:31536000},csv_column_mapping:{complexity:"LOW",maxOutputTokens:700,ttl:2592000},campaign_generation:{complexity:"MEDIUM",maxOutputTokens:1800,ttl:604800},email_personalization:{complexity:"LOW",maxOutputTokens:700,ttl:604800},tender_summary:{complexity:"LOW",maxOutputTokens:1800,ttl:86400},tender_extraction:{complexity:"MEDIUM",maxOutputTokens:2200,ttl:86400},deep_tender_analysis:{complexity:"PREMIUM_REASONING",maxOutputTokens:4000,ttl:86400},bid_no_bid:{complexity:"PREMIUM_REASONING",maxOutputTokens:3000,ttl:43200},opportunity_comparison:{complexity:"HIGH",maxOutputTokens:2600,ttl:43200}};

export function inferComplexity(input:AITaskInput):AIComplexity{
  if(input.complexity)return input.complexity;const base=defaults[input.taskType]?.complexity||"MEDIUM";const tokens=input.estimatedInputTokens||estimateTokens(input.messages.map(x=>x.content).join("\n"));
  if(input.requestedMode==="deep"&&["PREMIUM","PLATINUM"].includes(input.plan))return "PREMIUM_REASONING";
  if(input.requestedMode==="standard"&&base==="PREMIUM_REASONING")return "HIGH";
  if((input.documentCount||0)>3||tokens>40000)return base==="PREMIUM_REASONING"?base:"HIGH";
  return base;
}
export function isPremiumEligible(plan:AIPlan){return plan==="PREMIUM"||plan==="PLATINUM";}
export function planFromBillingCode(code:string|undefined|null,adminOverride=false):AIPlan{if(adminOverride)return"PLATINUM";const value=(code||"").toLowerCase();if(value.includes("platinum"))return"PLATINUM";if(value.includes("premium"))return"PREMIUM";if(value.includes("pro")||value.includes("standard"))return"STANDARD";return"FREE";}

export class AIOrchestrator{
  private readonly providers:AIProvider[];
  constructor(providers:AIProvider[]=configuredProviders()){this.providers=providers;}
  async execute(input:AITaskInput):Promise<AIOrchestrationResult>{
    const complexity=inferComplexity(input);const premiumRequested=complexity==="PREMIUM_REASONING";const premiumReasoning=premiumRequested&&isPremiumEligible(input.plan);
    if(input.requestedMode==="deep"&&!isPremiumEligible(input.plan))throw new ApiError(402,"Deep Analysis is available on Premium and Platinum plans. Standard AI remains available.","premium_reasoning_required");
    const normalized={taskType:input.taskType,messages:input.messages,classificationVersion:input.classificationVersion||"v1",mode:premiumReasoning?"premium":"standard",plan:input.plan};const inputHash=hash(JSON.stringify(normalized));const cacheKey=`${input.taskType}:${inputHash}`;
    // The cache table is shared. Never read or persist a user's, organisation's or document's analysis there.
    const cacheAllowed=!input.userId&&!input.organizationId&&!input.containsSensitiveData&&!input.containsCustomerDocuments&&["tender_summary","tender_extraction"].includes(input.taskType);
    if(input.deterministicResult){const result=this.decorate(input.deterministicResult,"rule",complexity,false,0,cacheKey);await this.log(input,result,{ruleEngine:true});return result;}
    const cached=cacheAllowed?await this.cacheGet(cacheKey):null;if(cached){const result=this.decorate(cached,"cache",complexity,premiumReasoning,0,cacheKey);await this.log(input,result,{cacheHit:true});return result;}
    await this.enforceLimits(input,premiumReasoning);
    const [route,models,providerStates]=await Promise.all([this.route(input.taskType),this.models(input.taskType),this.providerStates()]);const order=premiumReasoning?(route?.premium_provider_order?.length?route.premium_provider_order:["openai","gemini","openrouter"]):(route?.standard_provider_order?.length?route.standard_provider_order:["groq","gemini","openrouter","openai"]);let fallbackCount=0;
    for(const providerId of order){const provider=this.providers.find(item=>item.id===providerId);const providerState=providerStates.get(providerId);if(providerState?.enabled===false||!provider?.configured||!this.supports(provider,input,premiumReasoning,providerState)||Date.now()<(degradedUntil.get(providerId)||0))continue;const model=this.pickModel(provider,models,route,premiumReasoning);if(!model)continue;
      try{const maxOutputTokens=Math.min(route?.max_output_tokens||defaults[input.taskType]?.maxOutputTokens||1800,await this.maxTokens());const request={model,messages:input.messages,maxOutputTokens,temperature:premiumReasoning?0.15:0.2,jsonSchema:input.requiresStructuredOutput?{}:undefined,enableWebResearch:input.taskType.includes("tender")};const raw=premiumReasoning?await provider.reason(request):input.requiresStructuredOutput?await provider.generateStructuredOutput(request):await provider.generateText(request);const pricing=models.find(x=>x.provider===provider.id&&x.model_id===model);if(pricing)raw.usage.estimatedCostUsd=(raw.usage.inputTokens*Number(pricing.input_cost||0)+raw.usage.outputTokens*Number(pricing.output_cost||0))/1_000_000;const result=this.decorate(raw,"provider",complexity,premiumReasoning,fallbackCount,cacheKey);if(cacheAllowed)await this.cacheSet(cacheKey,input,result,route?.cache_ttl_seconds||input.cacheTtlSeconds||defaults[input.taskType]?.ttl||86400);await this.log(input,result,{fallbackCount});return result;}catch(error){fallbackCount++;const reason=error instanceof Error?error.message:"provider_failure";if(/429|rate/i.test(reason))degradedUntil.set(providerId,Date.now()+60000);await this.logFailure(input,providerId,model,reason,fallbackCount);}
    }
    throw new ApiError(503,"AI analysis is temporarily unavailable. The tender details remain accessible.","ai_temporarily_unavailable");
  }
  private decorate(result:AIProviderResult,source:AIOrchestrationResult["source"],complexity:AIComplexity,premiumReasoning:boolean,fallbackCount:number,cacheKey:string):AIOrchestrationResult{return{...result,source,complexity,premiumReasoning,fallbackCount,cacheKey};}
  private supports(provider:AIProvider,input:AITaskInput,premium:boolean,state?:ProviderStateRow){if(provider.id==="cloudflare"&&!workersAITaskAllowed(input))return false;if(premium&&!provider.capabilities.reasoning)return false;if(input.requiresStructuredOutput&&!provider.capabilities.structuredOutput)return false;if(input.requiresLongContext&&!provider.capabilities.longContext)return false;if(input.containsSensitiveData&&(!provider.capabilities.sensitiveData||state?.allow_sensitive_data===false))return false;if(input.containsCustomerDocuments&&(!provider.capabilities.customerDocuments||state?.allow_customer_documents===false))return false;return true;}
  private pickModel(provider:AIProvider,models:ModelRow[],route:RouteRow|null,premium:boolean){const override=(premium?route?.premium_model_overrides:route?.standard_model_overrides)?.[provider.id];if(override)return override;const row=models.filter(x=>x.provider===provider.id&&x.enabled&&(!premium||x.premium_model)).sort((a,b)=>a.priority-b.priority)[0];return row?.model_id||(premium?provider.premiumModel:undefined)||provider.defaultModel;}
  private async route(taskType:string){try{const{data}=await supabaseRest<RouteRow[]>(`ai_feature_routes?select=*&task_type=eq.${encodeURIComponent(taskType)}&enabled=eq.true&limit=1`);return data[0]||null;}catch{return null;}}
  private async models(taskType:string){try{const{data}=await supabaseRest<ModelRow[]>(`ai_models?select=provider,model_id,enabled,task_types,reasoning_level,premium_model,priority,input_cost,output_cost&enabled=eq.true`);return data.filter(x=>!x.task_types?.length||x.task_types.includes(taskType));}catch{return[];}}
  private async providerStates(){try{const{data}=await supabaseRest<ProviderStateRow[]>("ai_providers?select=id,enabled,allow_sensitive_data,allow_customer_documents");return new Map(data.map(row=>[row.id,row]));}catch{return new Map<string,ProviderStateRow>();}}
  private async cacheGet(cacheKey:string):Promise<AIProviderResult|null>{try{const{data}=await supabaseRest<Array<{provider:string;model:string;result:AIProviderResult;expires_at:string}>>(`ai_cache?select=provider,model,result,expires_at&cache_key=eq.${encodeURIComponent(cacheKey)}&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&limit=1`);return data[0]?.result||null;}catch{return null;}}
  private async cacheSet(cacheKey:string,input:AITaskInput,result:AIOrchestrationResult,ttl:number){try{await supabaseRest("ai_cache?on_conflict=cache_key",{method:"POST",headers:{Prefer:"resolution=merge-duplicates"},body:JSON.stringify({cache_key:cacheKey,task_type:input.taskType,input_hash:cacheKey.split(":").slice(1).join(":"),provider:result.provider,model:result.model,result,structured_result:result.structured||null,classification_version:input.classificationVersion||"v1",expires_at:new Date(Date.now()+ttl*1000).toISOString()})});}catch{}}
  private async enforceLimits(input:AITaskInput,premium:boolean){const budget=await this.budget();try{const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const{data}=await supabaseRest<Array<{estimated_cost_usd:number;premium_reasoning:boolean;created_at:string}>>(`ai_usage_logs?select=estimated_cost_usd,premium_reasoning,created_at&created_at=gte.${month}-01T00:00:00.000Z`);const daily=data.filter(x=>x.created_at.startsWith(today)).reduce((a,x)=>a+Number(x.estimated_cost_usd||0),0),monthly=data.reduce((a,x)=>a+Number(x.estimated_cost_usd||0),0),premiumDaily=data.filter(x=>x.premium_reasoning&&x.created_at.startsWith(today)).reduce((a,x)=>a+Number(x.estimated_cost_usd||0),0);if(daily>=budget.daily_budget_usd||monthly>=budget.monthly_budget_usd||(premium&&premiumDaily>=budget.premium_daily_budget_usd))throw new ApiError(429,"AI usage is temporarily capped to protect service availability. Standard cached analysis remains available.","ai_budget_reached");if(input.userId){const{response}=await supabaseRest(`ai_usage_logs?select=id&user_id=eq.${input.userId}&created_at=gte.${today}T00:00:00.000Z`,{count:"exact"});const calls=Number(response.headers.get("content-range")?.split("/")[1]||0);const limit={FREE:5,STANDARD:30,PREMIUM:100,PLATINUM:250}[input.plan];if(calls>=limit)throw new ApiError(429,"Your daily AI allowance has been reached. Cached and deterministic tools remain available.","ai_daily_limit_reached");}}catch(error){if(error instanceof ApiError&&["ai_budget_reached","ai_daily_limit_reached"].includes(error.code))throw error;}}
  private async budget():Promise<BudgetRow>{try{const{data}=await supabaseRest<BudgetRow[]>("ai_budget_settings?select=*&singleton_key=eq.default&limit=1");if(data[0])return data[0];}catch{}return{daily_budget_usd:10,monthly_budget_usd:150,premium_daily_budget_usd:5,maximum_tokens_per_task:60000,warning_percent:80};}
  private async maxTokens(){return(await this.budget()).maximum_tokens_per_task;}
  private async log(input:AITaskInput,result:AIOrchestrationResult,extra:Record<string,unknown>){try{await supabaseRest("ai_usage_logs",{method:"POST",body:JSON.stringify({user_id:input.userId||null,organization_id:input.organizationId||null,task_type:input.taskType,feature:String(input.metadata?.feature||input.taskType),provider:result.provider,model:result.model,complexity:result.complexity,user_plan:input.plan,premium_reasoning:result.premiumReasoning,input_tokens:result.usage.inputTokens,output_tokens:result.usage.outputTokens,estimated_cost_usd:result.usage.estimatedCostUsd,cache_hit:result.source==="cache",rule_engine_success:result.source==="rule",fallback_count:result.fallbackCount,status:"succeeded",metadata:extra})});}catch{}}
  private async logFailure(input:AITaskInput,provider:string,model:string,reason:string,fallbackCount:number){try{await supabaseRest("ai_usage_logs",{method:"POST",body:JSON.stringify({user_id:input.userId||null,organization_id:input.organizationId||null,task_type:input.taskType,provider,model,user_plan:input.plan,status:"failed",fallback_count:fallbackCount,fallback_reason:safeReason(reason)})});}catch{}}
}
function estimateTokens(value:string){return Math.ceil(value.length/4);}
function hash(value:string){return createHash("sha256").update(value).digest("hex");}
function safeReason(value:string){return value.replace(/(?:sk-|AIza|gsk_|Bearer\s+)[A-Za-z0-9._-]+/gi,"[redacted]").slice(0,180);}
export const ai=new AIOrchestrator();
